NCBI-TaxID	Kingdom	Phylum	Class	Order	Family	Genus	Species	Number_of_Reads	Relative_Abundance
194	<not present>	<not present>	<not present>	<not present>	<not present>	Campylobacter	<not present>	842	0
482	<not present>	<not present>	<not present>	<not present>	<not present>	Neisseria	<not present>	100	0
836	<not present>	<not present>	<not present>	<not present>	<not present>	Porphyromonas	<not present>	16	0
848	<not present>	<not present>	<not present>	<not present>	<not present>	Fusobacterium	<not present>	4063	0
168808	<not present>	<not present>	<not present>	<not present>	<not present>	Sneathia	<not present>	1019	0
1301	<not present>	<not present>	<not present>	<not present>	<not present>	Streptococcus	<not present>	63	0
1350	<not present>	<not present>	<not present>	<not present>	<not present>	Enterococcus	<not present>	268	0
2050	<not present>	<not present>	<not present>	<not present>	<not present>	Mobiluncus	<not present>	5	0
2093	<not present>	<not present>	<not present>	<not present>	<not present>	Mycoplasma	<not present>	272	0
10375	<not present>	<not present>	<not present>	<not present>	<not present>	Lymphocryptovirus	<not present>	36	0
1653174	<not present>	<not present>	<not present>	<not present>	<not present>	Actinotignum	<not present>	236	0
162289	<not present>	<not present>	<not present>	<not present>	<not present>	Peptoniphilus	<not present>	114	0
43996	<not present>	<not present>	<not present>	<not present>	<not present>	Catonella	<not present>	316	0
76833	<not present>	<not present>	<not present>	<not present>	<not present>	Actinobaculum	<not present>	65	0
216851	<not present>	<not present>	<not present>	<not present>	<not present>	Faecalibacterium	<not present>	78	0
