NCBI-TaxID	Kingdom	Phylum	Class	Order	Family	Genus	Species	Number_of_Reads	Relative_Abundance
157	<not present>	<not present>	<not present>	<not present>	<not present>	Treponema	<not present>	270	0
194	<not present>	<not present>	<not present>	<not present>	<not present>	Campylobacter	<not present>	2	0
123375	<not present>	<not present>	<not present>	<not present>	<not present>	Solobacterium	<not present>	3	0
1257	<not present>	<not present>	<not present>	<not present>	<not present>	Peptostreptococcus	<not present>	7	0
1301	<not present>	<not present>	<not present>	<not present>	<not present>	Streptococcus	<not present>	907	0
34104	<not present>	<not present>	<not present>	<not present>	<not present>	Streptobacillus	<not present>	1924	0
1350	<not present>	<not present>	<not present>	<not present>	<not present>	Enterococcus	<not present>	229	0
1637	<not present>	<not present>	<not present>	<not present>	<not present>	Listeria	<not present>	2070	0
1716	<not present>	<not present>	<not present>	<not present>	<not present>	Corynebacterium	<not present>	123	0
165779	<not present>	<not present>	<not present>	<not present>	<not present>	Anaerococcus	<not present>	1406	0
10375	<not present>	<not present>	<not present>	<not present>	<not present>	Lymphocryptovirus	<not present>	32	0
1273095	<not present>	<not present>	<not present>	<not present>	<not present>	Anaerosphaera	<not present>	2	0
1653174	<not present>	<not present>	<not present>	<not present>	<not present>	Actinotignum	<not present>	31	0
162289	<not present>	<not present>	<not present>	<not present>	<not present>	Peptoniphilus	<not present>	5355	0
39948	<not present>	<not present>	<not present>	<not present>	<not present>	Dialister	<not present>	218	0
572511	<not present>	<not present>	<not present>	<not present>	<not present>	Blautia	<not present>	633	0
