NCBI-TaxID	Kingdom	Phylum	Class	Order	Family	Genus	Species	Number_of_Reads	Relative_Abundance
194	<not present>	<not present>	<not present>	<not present>	<not present>	Campylobacter	<not present>	87063	0
590	<not present>	<not present>	<not present>	<not present>	<not present>	Salmonella	<not present>	21	0
1654	<not present>	<not present>	<not present>	<not present>	<not present>	Actinomyces	<not present>	26	0
10375	<not present>	<not present>	<not present>	<not present>	<not present>	Lymphocryptovirus	<not present>	29	0
75984	<not present>	<not present>	<not present>	<not present>	<not present>	Mannheimia	<not present>	1437	0
572511	<not present>	<not present>	<not present>	<not present>	<not present>	Blautia	<not present>	40	0
