NCBI-TaxID	Kingdom	Phylum	Class	Order	Family	Genus	Species	Number_of_Reads	Relative_Abundance
1000570	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus anginosus	1	0
100225	NA	Actinobacteria	Actinobacteria	Micrococcales	Dermatophilaceae	Austwickia	Austwickia chelonae	1	0
1002804	NA	Proteobacteria	Epsilonproteobacteria	Campylobacterales	Helicobacteraceae	Helicobacter	Helicobacter bizzozeronii	1	0
1006155	NA	Firmicutes	Bacilli	Bacillales	Listeriaceae	Listeria	Listeria weihenstephanensis	1	0
100816	Fungi	Ascomycota	Sordariomycetes	Sordariales	NA	Madurella	Madurella mycetomatis	1	0
101571	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Burkholderiaceae	Burkholderia	Burkholderia ubonensis	2	0
102125	NA	Cyanobacteria	NA	Pleurocapsales	Xenococcaceae	Xenococcus	Xenococcus sp. PCC 7305	2	0
102129	NA	Cyanobacteria	NA	Synechococcales	Leptolyngbyaceae	Leptolyngbya	Leptolyngbya sp. PCC 7375	1	0
1028802	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Haemophilus	Haemophilus haemolyticus	13	0
1028803	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Haemophilus	Haemophilus haemolyticus	12	0
1028804	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Haemophilus	Haemophilus haemolyticus	2	0
1028805	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Haemophilus	Haemophilus haemolyticus	9	0
1028806	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Haemophilus	Haemophilus haemolyticus	15	0
102897	NA	Actinobacteria	Actinobacteria	Frankiales	Frankiaceae	Frankia	Frankia sp. EUN1f	2	0
1028989	NA	Proteobacteria	Gammaproteobacteria	Pseudomonadales	Pseudomonadaceae	Pseudomonas	Pseudomonas sp. StFLB209	1	0
1032069	NA	Proteobacteria	Epsilonproteobacteria	Campylobacterales	Campylobacteraceae	Campylobacter	Campylobacter ureolyticus	60	0
1032480	NA	Actinobacteria	Actinobacteria	Propionibacteriales	Propionibacteriaceae	Microlunatus	Microlunatus phosphovorus	1	0
10325	NA	NA	NA	Herpesvirales	Herpesviridae	Simplexvirus	Macacine alphaherpesvirus 1	1	0
1033741	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	Methylobacteriaceae	Microvirga	Microvirga massiliensis	1	0
103441	NA	Actinobacteria	Actinobacteria	Pseudonocardiales	Pseudonocardiaceae	Pseudonocardia	Pseudonocardia spinosispora	1	0
1036182	NA	Actinobacteria	Actinobacteria	Micromonosporales	Micromonosporaceae	Actinoplanes	Actinoplanes atraurantiacus	3	0
1036612	Fungi	Ascomycota	Eurotiomycetes	Eurotiales	Aspergillaceae	Aspergillus	Aspergillus sydowii	1	0
1036677	NA	Euryarchaeota	Methanomicrobia	Methanosarcinales	Methanosarcinaceae	Methanosarcina	Methanosarcina soligelidi	1	0
1036723	NA	Apicomplexa	Aconoidasida	Haemosporida	Plasmodiidae	Plasmodium	Plasmodium falciparum	1	0
1036725	NA	Apicomplexa	Aconoidasida	Haemosporida	Plasmodiidae	Plasmodium	Plasmodium falciparum	4	0
10370	NA	NA	NA	Herpesvirales	Herpesviridae	Roseolovirus	Human betaherpesvirus 6A	3	0
1037660	Fungi	Basidiomycota	Exobasidiomycetes	Georgefischeriales	Tilletiariaceae	Tilletiaria	Tilletiaria anomala	8	0
10376	NA	NA	NA	Herpesvirales	Herpesviridae	Lymphocryptovirus	Human gammaherpesvirus 4	1	0
1047167	Fungi	Ascomycota	Dothideomycetes	Capnodiales	Mycosphaerellaceae	Zymoseptoria	NA	2	0
1050174	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium epidermidicanis	2	0
10506	NA	NA	NA	NA	Phycodnaviridae	Chlorovirus	Paramecium bursaria Chlorella virus 1	3	0
1052685	Fungi	Basidiomycota	Agaricomycetes	Polyporales	Gelatoporiaceae	Obba	Obba rivulosa	1	0
105422	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptacidiphilus	Streptacidiphilus carbonis	1	0
105487	Fungi	Ascomycota	Sordariomycetes	Diaporthales	Valsaceae	Valsa	Valsa mali	1	0
1055687	NA	NA	NA	Kinetoplastida	Trypanosomatidae	Trypanosoma	Trypanosoma vivax	7	0
105696	Fungi	Ascomycota	Dothideomycetes	Pleosporales	Didymellaceae	Epicoccum	Epicoccum nigrum	1	0
106004	Fungi	Basidiomycota	Microbotryomycetes	Leucosporidiales	Leucosporidiaceae	Leucosporidium	Leucosporidium creatinivorum	1	0
10662	NA	NA	NA	Caudovirales	Myoviridae	NA	NA	1	0
1068625	NA	NA	NA	Kinetoplastida	Trypanosomatidae	Trypanosoma	Trypanosoma congolense	5	0
1069443	Fungi	Mucoromycota	NA	Mortierellales	Mortierellaceae	Mortierella	Mortierella verticillata	12	0
1071378	Fungi	Ascomycota	Saccharomycetes	Saccharomycetales	Saccharomycetaceae	Naumovozyma	Naumovozyma dairenensis	2	0
1071383	Fungi	Ascomycota	Saccharomycetes	Saccharomycetales	Saccharomycetaceae	Kazachstania	Kazachstania naganishii	1	0
1071947	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Pasteurella	Pasteurella oralis	1	0
1073366	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella nigrescens	4	0
1073377	NA	Proteobacteria	Gammaproteobacteria	Aeromonadales	Aeromonadaceae	Aeromonas	Aeromonas hydrophila	1	0
1073571	NA	Firmicutes	Bacilli	Bacillales	Paenibacillaceae	Paenibacillus	Paenibacillus riograndensis	1	0
1074872	NA	Apicomplexa	Coccidia	Eucoccidiorida	Sarcocystidae	Toxoplasma	Toxoplasma gondii	1	0
1074873	NA	Apicomplexa	Coccidia	Eucoccidiorida	Sarcocystidae	Toxoplasma	Toxoplasma gondii	3	0
1075768	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Oxalobacteraceae	Janthinobacterium	Janthinobacterium sp. CG3	1	0
1077284	NA	Apicomplexa	Aconoidasida	Haemosporida	Plasmodiidae	Plasmodium	Plasmodium vivax	1	0
1077348	Fungi	Basidiomycota	Agaricomycetes	Polyporales	Polyporaceae	Ganoderma	Ganoderma sinense	1	0
1078480	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Haemophilus	Haemophilus sputorum	1	0
1078764	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium sp. HFH0082	2	0
1079859	NA	Bacteroidetes	Cytophagia	Cytophagales	Cytophagaceae	Pseudarcicella	Pseudarcicella hirudinis	1	0
1081108	Fungi	Ascomycota	Sordariomycetes	Hypocreales	Cordycipitaceae	Cordyceps	Cordyceps confragosa	3	0
1081904	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella pleuritidis	1	0
108892	Fungi	Basidiomycota	Agaricomycetes	Hymenochaetales	Hymenochaetaceae	Sanghuangporus	Sanghuangporus baumii	2	0
1091495	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Alcaligenaceae	Taylorella	Taylorella asinigenitalis	1	0
109264	Fungi	Ascomycota	Eurotiomycetes	Eurotiales	Aspergillaceae	Aspergillus	Aspergillus bombycis	1	0
1093141	NA	Eustigmatophyceae	NA	Eustigmatales	Monodopsidaceae	Nannochloropsis	Nannochloropsis gaditana	1	0
1094983	Fungi	Ascomycota	Saccharomycetes	Saccharomycetales	Debaryomycetaceae	Candida	Candida albicans	1	0
1095629	Fungi	Basidiomycota	Agaricomycetes	Agaricales	Tricholomataceae	Laccaria	Laccaria amethystina	2	0
1095630	Fungi	Ascomycota	Leotiomycetes	Helotiales	Helotiaceae	Meliniomyces	Meliniomyces bicolor	1	0
1095631	Fungi	Ascomycota	Saccharomycetes	Saccharomycetales	Saccharomycetaceae	Saccharomyces	Saccharomyces cerevisiae x Saccharomyces kudriavzevii	1	0
1095729	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus anginosus	2	0
1095742	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Haemophilus	Haemophilus haemolyticus	8	0
1095743	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Haemophilus	Haemophilus paraphrohaemolyticus	2	0
1095744	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Haemophilus	Haemophilus parahaemolyticus	2	0
1095752	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella sp. oral taxon 306	1	0
109790	NA	Firmicutes	Bacilli	Lactobacillales	Lactobacillaceae	Lactobacillus	Lactobacillus jensenii	1	0
110365	NA	Apicomplexa	Gregarinasina	Eugregarinorida	Gregarinidae	Gregarina	Gregarina niphandrodes	1	0
1108050	Fungi	Basidiomycota	Agaricomycetes	Cantharellales	Ceratobasidiaceae	Rhizoctonia	Rhizoctonia solani	1	0
1109443	Fungi	Basidiomycota	Agaricomycetes	Sebacinales	Serendipitaceae	Serendipita	Serendipita indica	1	0
1110697	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Nocardiaceae	Nocardia	Nocardia asteroides	2	0
1111131	NA	Actinobacteria	Actinobacteria	Propionibacteriales	Propionibacteriaceae	Propionimicrobium	Propionimicrobium sp. BV2F7	634	0
1111133	NA	Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Peptoniphilus	Peptoniphilus sp. BV3AC2	3	0
1111454	NA	Firmicutes	Negativicutes	Veillonellales	Veillonellaceae	Megasphaera	Megasphaera sp. BV3C16-1	1	0
1112244	NA	Chlamydiae	Chlamydiia	Chlamydiales	Chlamydiaceae	Chlamydia	Chlamydia psittaci	1	0
1117322	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Glaesserella	Glaesserella parasuis	3	0
1117	NA	Cyanobacteria	NA	NA	NA	NA	NA	1	0
1120523	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. MJM8645	1	0
1120755	NA	Apicomplexa	Aconoidasida	Haemosporida	Plasmodiidae	Plasmodium	Plasmodium cynomolgi	6	0
112090	NA	NA	Oomycetes	Saprolegniales	Saprolegniaceae	Aphanomyces	Aphanomyces astaci	1	0
1120929	NA	Proteobacteria	Gammaproteobacteria	Pseudomonadales	Moraxellaceae	Acinetobacter	Acinetobacter towneri	2	0
1121001	NA	Proteobacteria	Betaproteobacteria	Neisseriales	Chromobacteriaceae	Andreprevotia	Andreprevotia lacus	1	0
1121276	NA	Proteobacteria	Betaproteobacteria	Neisseriales	Chromobacteriaceae	Chitinilyticum	Chitinilyticum litopenaei	1	0
1122155	NA	Firmicutes	Clostridia	Clostridiales	Clostridiaceae	Lactonifactor	Lactonifactor longoviformis	1	0
1122252	NA	Proteobacteria	Gammaproteobacteria	Oceanospirillales	Oceanospirillaceae	Marinospirillum	Marinospirillum celere	1	0
112413	NA	Actinobacteria	Actinobacteria	Pseudonocardiales	Pseudonocardiaceae	Amycolatopsis	Amycolatopsis rubida	1	0
112498	Fungi	Ascomycota	Dothideomycetes	Capnodiales	Mycosphaerellaceae	Ramularia	Ramularia collo-cygni	1	0
1125694	NA	Proteobacteria	Gammaproteobacteria	Enterobacterales	Morganellaceae	Proteus	Proteus mirabilis	2	0
1129	NA	Cyanobacteria	NA	Synechococcales	Synechococcaceae	Synechococcus	NA	1	0
1130820	NA	Apicomplexa	Coccidia	Eucoccidiorida	Sarcocystidae	Toxoplasma	Toxoplasma gondii	3	0
1130821	NA	Apicomplexa	Coccidia	Eucoccidiorida	Sarcocystidae	Toxoplasma	Toxoplasma gondii	1	0
1131703	NA	Spirochaetes	Spirochaetia	Spirochaetales	Spirochaetaceae	Sphaerochaeta	Sphaerochaeta globosa	1	0
113226	Fungi	Ascomycota	Dothideomycetes	Capnodiales	Mycosphaerellaceae	Pseudocercospora	Pseudocercospora musae	1	0
1134435	NA	Proteobacteria	Betaproteobacteria	Rhodocyclales	Zoogloeaceae	Thauera	Thauera humireducens	1	0
1134827	NA	Firmicutes	Bacilli	Lactobacillales	Enterococcaceae	Enterococcus	Enterococcus faecium	1	0
1136105	NA	Cyanobacteria	NA	Nostocales	Tolypothrichaceae	Tolypothrix	Tolypothrix campylonemoides	1	0
1137138	Fungi	Basidiomycota	Agaricomycetes	Agaricales	Pleurotaceae	Pleurotus	Pleurotus ostreatus	1	0
1141883	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Oxalobacteraceae	Massilia	Massilia putida	1	0
1144310	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	Rhizobiaceae	Rhizobium	Rhizobium sp. CF080	1	0
1144522	NA	NA	NA	Tritrichomonadida	Tritrichomonadidae	Tritrichomonas	Tritrichomonas foetus	2	0
114699	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces rhizosphaericus	1	0
114	NA	Planctomycetes	Planctomycetia	Planctomycetales	Gemmataceae	Gemmata	Gemmata obscuriglobus	1	0
1150469	NA	Proteobacteria	Alphaproteobacteria	Rhodospirillales	Rhodospirillaceae	Pararhodospirillum	Pararhodospirillum photometricum	1	0
1150864	NA	Actinobacteria	Actinobacteria	Micromonosporales	Micromonosporaceae	Micromonospora	Micromonospora lupini	1	0
1155739	NA	Cyanobacteria	NA	Oscillatoriales	Oscillatoriaceae	Moorea	Moorea producens	1	0
115783	NA	Proteobacteria	Deltaproteobacteria	Desulfuromonadales	Geobacteraceae	Geobacter	Geobacter thiogenes	2	0
1157962	Viridiplantae	Chlorophyta	Chlorophyceae	Chlamydomonadales	Chlamydomonadaceae	Chlamydomonas	Chlamydomonas eustigma	2	0
1158050	NA	Actinobacteria	Actinobacteria	Micrococcales	Micrococcaceae	Arthrobacter	Arthrobacter sp. 135MFCol5.1	1	0
1159017	NA	Proteobacteria	Gammaproteobacteria	Alteromonadales	Idiomarinaceae	Idiomarina	Idiomarina indica	2	0
1161902	NA	Firmicutes	Clostridia	Clostridiales	Clostridiales Family XIII. Incertae Sedis	NA	[Eubacterium] nodatum	1	0
1165852	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Comamonadaceae	Melaminivora	Melaminivora alkalimesophila	1	0
1167634	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Alcaligenaceae	Achromobacter	Achromobacter xylosoxidans	1	0
1169145	NA	Actinobacteria	Actinobacteria	Micrococcales	Microbacteriaceae	Cryocola	Cryocola sp. 340MFSha3.1	2	0
1169158	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. CNS615	1	0
1169673	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus sp. GMD4S	1	0
117008	NA	Apicomplexa	Coccidia	Eucoccidiorida	Cryptosporidiidae	Cryptosporidium	Cryptosporidium andersoni	1	0
117179	Fungi	Basidiomycota	Exobasidiomycetes	Tilletiales	Tilletiaceae	Tilletia	Tilletia walkeri	2	0
117207	NA	Proteobacteria	Alphaproteobacteria	Sphingomonadales	Sphingomonadaceae	Sphingopyxis	Sphingopyxis alaskensis	2	0
1177574	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella jejuni	1	0
1177594	NA	Actinobacteria	Actinobacteria	Micrococcales	Microbacteriaceae	Microbacterium	Microbacterium sp. C448	1	0
1182542	Fungi	Ascomycota	Eurotiomycetes	Chaetothyriales	Herpotrichiellaceae	Capronia	Capronia epimyces	3	0
1182544	Fungi	Ascomycota	Eurotiomycetes	Chaetothyriales	Herpotrichiellaceae	Cladophialophora	Cladophialophora yegresii	1	0
1182545	Fungi	Ascomycota	Eurotiomycetes	Chaetothyriales	Herpotrichiellaceae	Exophiala	Exophiala aquamarina	2	0
118322	NA	Cyanobacteria	NA	Oscillatoriales	Oscillatoriaceae	Lyngbya	Lyngbya aestuarii	1	0
118323	NA	Cyanobacteria	NA	Oscillatoriales	Oscillatoriaceae	Oscillatoria	Oscillatoria acuminata	2	0
1183411	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	Rhizobiaceae	Agrobacterium	Agrobacterium genomosp. 6	1	0
1184151	NA	Verrucomicrobia	Opitutae	Opitutales	Opitutaceae	NA	Opitutaceae bacterium TSB47	1	0
1185650	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Mycobacteriaceae	Mycobacterium	Mycobacterium abscessus	22	0
119060	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Burkholderiaceae	NA	NA	3	0
1190620	NA	Actinobacteria	Coriobacteriia	Coriobacteriales	Atopobiaceae	Atopobium	Atopobium sp. ICM42b	1	0
1193181	NA	Actinobacteria	Actinobacteria	Micrococcales	Intrasporangiaceae	Tetrasphaera	Tetrasphaera elongata	1	0
1193518	NA	Actinobacteria	Actinobacteria	Micrococcales	Intrasporangiaceae	Tetrasphaera	Tetrasphaera jenkinsii	1	0
1193682	NA	Actinobacteria	Actinobacteria	Pseudonocardiales	Pseudonocardiaceae	Actinokineospora	Actinokineospora bangkokensis	1	0
1194083	NA	Actinobacteria	Actinobacteria	Micrococcales	Intrasporangiaceae	Tetrasphaera	Tetrasphaera japonica	2	0
1195612	NA	NA	Cryptophyta	Pyrenomonadales	Chroomonadaceae	Chroomonas	Chroomonas mesostigmatica	1	0
1196095	NA	Proteobacteria	Gammaproteobacteria	Orbales	Orbaceae	Gilliamella	Gilliamella apicola	3	0
1198029	Fungi	Ascomycota	Neolectomycetes	Neolectales	Neolectaceae	Neolecta	Neolecta irregularis	1	0
1202716	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	Hyphomicrobiaceae	Rhodomicrobium	Rhodomicrobium udaipurense	1	0
1203560	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium sp. KPL1821	1	0
1203561	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium sp. KPL1824	1	0
1203563	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium sp. KPL1856	1	0
1203564	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium sp. KPL1857	1	0
1203605	NA	Actinobacteria	Actinobacteria	Propionibacteriales	Propionibacteriaceae	Propionibacterium	Propionibacterium sp. oral taxon 192	1	0
1204738	NA	Proteobacteria	Gammaproteobacteria	Oceanospirillales	Halomonadaceae	Halomonas	Halomonas titanicae	7	0
1209926	Fungi	Ascomycota	Sordariomycetes	Glomerellales	Glomerellaceae	Colletotrichum	Colletotrichum orchidophilum	1	0
1210046	NA	Actinobacteria	Actinobacteria	Micrococcales	Intrasporangiaceae	Janibacter	Janibacter hoylei	1	0
1213189	Fungi	Zoopagomycota	NA	Harpellales	Legeriomycetaceae	Zancudomyces	Zancudomyces culisetae	1	0
1213857	Fungi	Ascomycota	Sordariomycetes	Glomerellales	Glomerellaceae	Colletotrichum	Colletotrichum orbiculare	2	0
1213859	Fungi	Ascomycota	Sordariomycetes	Glomerellales	Glomerellaceae	Colletotrichum	Colletotrichum gloeosporioides	1	0
1214787	NA	Proteobacteria	Alphaproteobacteria	Rhodobacterales	Rhodobacteraceae	Paracoccus	Paracoccus sediminis	1	0
121759	Fungi	Ascomycota	Eurotiomycetes	Onygenales	NA	Paracoccidioides	Paracoccidioides brasiliensis	1	0
1217657	NA	Proteobacteria	Gammaproteobacteria	Pseudomonadales	Moraxellaceae	Acinetobacter	Acinetobacter gyllenbergii	2	0
1219585	NA	Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Arcanobacterium	Arcanobacterium sp. S3PF19	2	0
1219626	NA	Firmicutes	Clostridia	Clostridiales	Peptostreptococcaceae	Peptostreptococcus	Peptostreptococcus sp. MV1	1	0
1219	NA	Cyanobacteria	NA	Synechococcales	Prochloraceae	Prochlorococcus	Prochlorococcus marinus	1	0
122368	Fungi	Ascomycota	Dothideomycetes	Capnodiales	Mycosphaerellaceae	Cercospora	Cercospora beticola	1	0
1223802	NA	Proteobacteria	Betaproteobacteria	Nitrosomonadales	Sterolibacteriaceae	Sulfuritalea	Sulfuritalea hydrogenivorans	1	0
1224162	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium marinum	1	0
1224	NA	Proteobacteria	NA	NA	NA	NA	NA	151	0
122706	NA	Proteobacteria	Deltaproteobacteria	NA	NA	NA	NA	1	0
1227077	NA	Bacteroidetes	Cytophagia	Cytophagales	Hymenobacteraceae	Siccationidurans	Siccationidurans arizonensis	1	0
1227269	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Porphyromonadaceae	Porphyromonas	Porphyromonas gingivalis	1	0
1229172	NA	Cyanobacteria	NA	Synechococcales	Leptolyngbyaceae	Leptolyngbya	Leptolyngbya sp. KIOST-1	2	0
1229664	Fungi	Ascomycota	Sordariomycetes	Hypocreales	Nectriaceae	Fusarium	Fusarium oxysporum	4	0
1230075	Fungi	Basidiomycota	Tremellomycetes	Tremellales	Cryptococcaceae	Cryptococcus	Cryptococcus neoformans	4	0
1230078	Fungi	Basidiomycota	Tremellomycetes	Tremellales	Cryptococcaceae	Cryptococcus	Cryptococcus neoformans	1	0
1230730	NA	Firmicutes	Tissierellia	NA	NA	NA	Tissierellia bacterium S5-A11	1	0
1231623	NA	Proteobacteria	Alphaproteobacteria	Rhodospirillales	Acetobacteraceae	Tanticharoenia	Tanticharoenia sakaeratensis	1	0
1234382	NA	Proteobacteria	Betaproteobacteria	Rhodocyclales	Zoogloeaceae	Thauera	Thauera phenylacetica	30	0
1234606	NA	Proteobacteria	Gammaproteobacteria	Alteromonadales	Alteromonadaceae	Gayadomonas	Gayadomonas joobiniege	1	0
1234679	NA	Firmicutes	Bacilli	Lactobacillales	Carnobacteriaceae	Carnobacterium	Carnobacterium maltaromaticum	1	0
1235797	NA	Firmicutes	Clostridia	Clostridiales	Oscillospiraceae	Oscillibacter	Oscillibacter sp. 1-3	1	0
1235811	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella disiens	245	0
1236220	NA	Firmicutes	Bacilli	Bacillales	Thermoactinomycetaceae	Melghirimyces	Melghirimyces thermohalophilus	1	0
1236	NA	Proteobacteria	Gammaproteobacteria	NA	NA	NA	NA	282	0
1237896	Fungi	Ascomycota	Sordariomycetes	Glomerellales	Glomerellaceae	Colletotrichum	Colletotrichum gloeosporioides	1	0
123822	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	NA	[Haemophilus] felis	2	0
1239	NA	Firmicutes	NA	NA	NA	NA	NA	945	0
124252	NA	Actinobacteria	Actinobacteria	Streptosporangiales	Nocardiopsaceae	Nocardiopsis	Nocardiopsis halotolerans	1	0
1244108	NA	Proteobacteria	Alphaproteobacteria	Rhodobacterales	Rhodobacteraceae	Jannaschia	Jannaschia faecimaris	7	0
1246581	Fungi	Cryptomycota	NA	NA	NA	Paramicrosporidium	Paramicrosporidium saccamoebae	26	0
1246981	NA	Cyanobacteria	NA	Nostocales	Tolypothrichaceae	Tolypothrix	Tolypothrix bouteillei	1	0
1255043	NA	Proteobacteria	Gammaproteobacteria	Chromatiales	Ectothiorhodospiraceae	Thioalkalivibrio	Thioalkalivibrio nitratireducens	1	0
1256570	NA	NA	NA	NA	NA	NA	uncultured bacterium A1Q1_fos_291	2	0
1257118	NA	NA	NA	Longamoebia	Acanthamoebidae	Acanthamoeba	Acanthamoeba castellanii	2	0
1260356	NA	Firmicutes	Bacilli	Lactobacillales	Enterococcaceae	Enterococcus	Enterococcus faecalis	103	0
1260	NA	Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Finegoldia	Finegoldia magna	7	0
1261633	NA	Proteobacteria	Gammaproteobacteria	Pseudomonadales	Pseudomonadaceae	Pseudomonas	Pseudomonas sp. URIL14HWK12:I9	1	0
1261658	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Bibersteinia	Bibersteinia trehalosi	4	0
1262695	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Rikenellaceae	Alistipes	Alistipes sp. CAG:435	1	0
1262736	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Bacteroidaceae	Bacteroides	Bacteroides sp. CAG:144	2	0
1262740	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Bacteroidaceae	Bacteroides	Bacteroides sp. CAG:462	1	0
1262827	NA	Firmicutes	Clostridia	Clostridiales	Clostridiaceae	Clostridium	Clostridium sp. CAG:609	2	0
1262832	NA	Firmicutes	Clostridia	Clostridiales	Clostridiaceae	Clostridium	Clostridium sp. CAG:7	1	0
1262845	NA	Firmicutes	Clostridia	Clostridiales	Clostridiaceae	Clostridium	Clostridium sp. CAG:91	1	0
1262886	NA	Firmicutes	Clostridia	Clostridiales	Eubacteriaceae	Eubacterium	Eubacterium sp. CAG:251	1	0
1262890	NA	Firmicutes	Clostridia	Clostridiales	Eubacteriaceae	Eubacterium	Eubacterium sp. CAG:581	1	0
1262910	NA	Firmicutes	Clostridia	Clostridiales	Oscillospiraceae	Oscillibacter	Oscillibacter sp. CAG:155	1	0
1262913	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Tannerellaceae	Parabacteroides	Parabacteroides sp. CAG:409	2	0
1262916	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Porphyromonadaceae	Porphyromonas	Porphyromonas sp. CAG:1061	154	0
1262917	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella sp. CAG:1031	1	0
1262927	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella sp. CAG:485	1	0
1262928	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella sp. CAG:487	1	0
1262934	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella sp. CAG:732	2	0
1262938	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella sp. CAG:924	1	0
1263022	NA	Firmicutes	NA	NA	NA	NA	Firmicutes bacterium CAG:424	1	0
1263058	NA	Actinobacteria	Actinobacteria	Bifidobacteriales	Bifidobacteriaceae	Bifidobacterium	Bifidobacterium bifidum CAG:234	1	0
1263082	Fungi	Mucoromycota	NA	Mucorales	Lichtheimiaceae	Lichtheimia	Lichtheimia corymbifera	1	0
1263090	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Odoribacteraceae	Odoribacter	Odoribacter splanchnicus CAG:14	2	0
1263415	Fungi	Ascomycota	Eurotiomycetes	Verrucariales	Verrucariaceae	Endocarpon	Endocarpon pusillum	1	0
1268	NA	Actinobacteria	Actinobacteria	Micrococcales	Micrococcaceae	NA	NA	1	0
1276135	Fungi	Ascomycota	Sordariomycetes	Hypocreales	Clavicipitaceae	Metarhizium	Metarhizium anisopliae	1	0
1278258	NA	NA	NA	NA	Phycodnaviridae	Chlorovirus	Paramecium bursaria Chlorella virus KS1B	1	0
1279	NA	Firmicutes	Bacilli	Bacillales	Staphylococcaceae	Staphylococcus	NA	4	0
1280390	NA	Firmicutes	Bacilli	Bacillales	Paenibacillaceae	Gorillibacterium	Gorillibacterium massiliense	1	0
1280	NA	Firmicutes	Bacilli	Bacillales	Staphylococcaceae	Staphylococcus	Staphylococcus aureus	4	0
1283301	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces afghaniensis	1	0
1284686	NA	Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Anaerococcus	Anaerococcus lactolyticus	8	0
1284775	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella sp. S7-1-8	2	0
1286822	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. WMMB 714	1	0
1288121	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Rikenellaceae	Alistipes	Alistipes senegalensis	1	0
1288971	NA	Firmicutes	Tissierellia	Tissierellales	Tissierellaceae	NA	[Clostridium] ultunense	3	0
1292020	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Dietziaceae	Dietzia	Dietzia sp. UCD-THP	6	0
1292037	NA	Actinobacteria	Actinobacteria	Pseudonocardiales	Pseudonocardiaceae	Amycolatopsis	Amycolatopsis vancoresmycina	1	0
129394	NA	Proteobacteria	Gammaproteobacteria	Xanthomonadales	Xanthomonadaceae	Xanthomonas	Xanthomonas oryzae	1	0
1294348	Fungi	Ascomycota	Saccharomycetes	Saccharomycetales	Saccharomycetaceae	Saccharomyces	Saccharomyces cerevisiae	1	0
1295140	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Haemophilus	Haemophilus influenzae	6	0
1295531	Fungi	Basidiomycota	Tremellomycetes	Tremellales	Cryptococcaceae	Cryptococcus	Cryptococcus depauperatus	1	0
1296100	Fungi	Basidiomycota	Tremellomycetes	Tremellales	Cryptococcaceae	Kwoniella	Kwoniella bestiolae	3	0
1296105	Fungi	Basidiomycota	Tremellomycetes	Tremellales	Cryptococcaceae	Cryptococcus	Cryptococcus gattii VGIV	1	0
1296121	Fungi	Basidiomycota	Tremellomycetes	Tremellales	Cryptococcaceae	Kwoniella	Kwoniella dejecticola	3	0
1296	NA	Firmicutes	Bacilli	Bacillales	Staphylococcaceae	Staphylococcus	Staphylococcus sciuri	1	0
1297750	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Bacteroidaceae	Bacteroides	Bacteroides luti	2	0
1298881	NA	Proteobacteria	Gammaproteobacteria	Alteromonadales	Idiomarinaceae	NA	Idiomarinaceae bacterium HL-53	1	0
1300150	NA	Firmicutes	Bacilli	Lactobacillales	Enterococcaceae	Enterococcus	Enterococcus mundtii	1	0
1300267	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces zhaozhouensis	2	0
130081	NA	NA	Bangiophyceae	Cyanidiales	Cyanidiaceae	Galdieria	Galdieria sulphuraria	4	0
1300	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	NA	NA	1	0
1301	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	NA	2	0
1302243	NA	Actinobacteria	Actinobacteria	Propionibacteriales	Propionibacteriaceae	Cutibacterium	Cutibacterium acnes	1	0
1304833	NA	Cyanobacteria	NA	Nostocales	Tolypothrichaceae	Hassallia	Hassallia byssoidea	1	0
1304865	NA	Actinobacteria	Actinobacteria	Micrococcales	Cellulomonadaceae	Cellulomonas	Cellulomonas sp. KRMCY2	1	0
1304866	NA	Firmicutes	Clostridia	Clostridiales	Clostridiaceae	Clostridium	Clostridium sp. ASBs410	2	0
1305826	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. Amel2xC10	1	0
1306787	NA	Proteobacteria	Gammaproteobacteria	Oceanospirillales	Alcanivoracaceae	Alcanivorax	Alcanivorax pacificus	2	0
1307437	NA	Proteobacteria	Gammaproteobacteria	Alteromonadales	Pseudoalteromonadaceae	Pseudoalteromonas	Pseudoalteromonas agarivorans	1	0
13076	NA	Firmicutes	Bacilli	Lactobacillales	Aerococcaceae	Globicatella	Globicatella sanguinis	1	0
1310627	NA	Proteobacteria	Gammaproteobacteria	Pseudomonadales	Moraxellaceae	Acinetobacter	Acinetobacter baumannii	2	0
1310866	NA	Proteobacteria	Gammaproteobacteria	Pseudomonadales	Moraxellaceae	Acinetobacter	Acinetobacter baumannii	1	0
1311	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus agalactiae	6	0
1313	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus pneumoniae	17	0
1314670	Fungi	Ascomycota	Dothideomycetes	Mytilinidiales	Argynnaceae	Lepidopterella	Lepidopterella palustris	1	0
1314672	Fungi	Basidiomycota	Agaricomycetes	Russulales	Peniophoraceae	Peniophora	Peniophora sp. CONT	2	0
1314674	Fungi	Basidiomycota	Agaricomycetes	Agaricales	Physalacriaceae	Cylindrobasidium	Cylindrobasidium torrendii	1	0
1314771	Fungi	Mucoromycota	NA	Mortierellales	Mortierellaceae	Mortierella	Mortierella elongata	1	0
1314776	Fungi	Basidiomycota	Agaricomycetes	Trechisporales	Hydnodontaceae	Sistotremastrum	Sistotremastrum suecicum	1	0
1314781	Fungi	Basidiomycota	Agaricomycetes	Auriculariales	Exidiaceae	Exidia	Exidia glandulosa	1	0
1314782	Fungi	Basidiomycota	Agaricomycetes	Gloeophyllales	Gloeophyllaceae	Neolentinus	Neolentinus lepideus	1	0
1314962	NA	NA	NA	Kinetoplastida	NA	Perkinsela	Perkinsela sp. CCAP 1560/4	1	0
1314	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus pyogenes	4	0
131567	NA	NA	NA	NA	NA	NA	NA	113	0
1316194	Fungi	Ascomycota	Eurotiomycetes	Eurotiales	Aspergillaceae	Penicillium	Penicillium subrubescens	1	0
1321772	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Aggregatibacter	Aggregatibacter sp. oral taxon 458	2	0
1322346	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Glaesserella	Glaesserella parasuis	1	0
1322	NA	Firmicutes	Clostridia	Clostridiales	Lachnospiraceae	Blautia	Blautia hansenii	29	0
1323249	NA	Apicomplexa	Aconoidasida	Haemosporida	Plasmodiidae	Plasmodium	Plasmodium yoelii	1	0
1324934	NA	Bacteroidetes	Flavobacteriia	Flavobacteriales	Flavobacteriaceae	Myroides	Myroides xuanwuensis	1	0
1328760	Fungi	Ascomycota	Xylonomycetes	Xylonomycetales	Xylonomycetaceae	Xylona	Xylona heveae	2	0
13289	Fungi	Basidiomycota	Exobasidiomycetes	Tilletiales	Tilletiaceae	Tilletia	NA	2	0
1328	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus anginosus	1	0
1330534	NA	Firmicutes	Clostridia	Clostridiales	Ruminococcaceae	Ruminiclostridium	[Clostridium] papyrosolvens	1	0
1331043	NA	Proteobacteria	Gammaproteobacteria	Enterobacterales	Enterobacteriaceae	Salmonella	Salmonella enterica	12	0
1331668	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sparsogenes	1	0
1332264	NA	Actinobacteria	Actinobacteria	Propionibacteriales	Propionibacteriaceae	Tessaracoccus	Tessaracoccus aquimaris	1	0
13335	NA	Proteobacteria	Gammaproteobacteria	Aeromonadales	Succinivibrionaceae	Anaerobiospirillum	Anaerobiospirillum succiniciproducens	1	0
1333667	NA	Actinobacteria	Actinobacteria	Geodermatophilales	Geodermatophilaceae	Geodermatophilus	Geodermatophilus poikilotrophus	1	0
133412	Fungi	Zoopagomycota	NA	Harpellales	Legeriomycetaceae	Smittium	Smittium culicis	1	0
1334187	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Haemophilus	Haemophilus influenzae	35	0
133448	NA	Proteobacteria	Gammaproteobacteria	Enterobacterales	Enterobacteriaceae	Citrobacter	Citrobacter youngae	1	0
1337886	NA	Firmicutes	Negativicutes	Selenomonadales	Sporomusaceae	Sporomusa	Sporomusa sphaeroides	1	0
1338	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus intermedius	1	0
1339242	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Comamonadaceae	Delftia	Delftia sp. ZNC0008	1	0
1339277	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Bacteroidaceae	Bacteroides	Bacteroides fragilis	1	0
1339307	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Bacteroidaceae	Bacteroides	Bacteroides fragilis	1	0
1339316	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Bacteroidaceae	Bacteroides	Bacteroides fragilis	2	0
1339329	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Bacteroidaceae	Bacteroides	Bacteroides fragilis	1	0
134006	NA	NA	NA	Kinetoplastida	Trypanosomatidae	Phytomonas	Phytomonas sp. isolate EM1	1	0
1341119	NA	Proteobacteria	Gammaproteobacteria	Cellvibrionales	Halieaceae	Luminiphilus	Luminiphilus syltensis	1	0
1344416	Fungi	Chytridiomycota	Monoblepharidomycetes	Monoblepharidales	Gonapodyaceae	Gonapodya	Gonapodya prolifera	1	0
134821	NA	Tenericutes	Mollicutes	Mycoplasmatales	Mycoplasmataceae	Ureaplasma	Ureaplasma parvum	6	0
134959	NA	Actinobacteria	Actinobacteria	Streptosporangiales	Thermomonosporaceae	Actinomadura	Actinomadura mexicana	2	0
134962	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Nocardiaceae	Nocardia	Nocardia soli	1	0
134964	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Nocardiaceae	Nocardia	Nocardia africana	1	0
1350	NA	Firmicutes	Bacilli	Lactobacillales	Enterococcaceae	Enterococcus	NA	86	0
1351754	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Avibacterium	Avibacterium paragallinarum	2	0
1351	NA	Firmicutes	Bacilli	Lactobacillales	Enterococcaceae	Enterococcus	Enterococcus faecalis	1354	0
1352	NA	Firmicutes	Bacilli	Lactobacillales	Enterococcaceae	Enterococcus	Enterococcus faecium	4	0
1353009	Fungi	Basidiomycota	Agaricomycetes	Polyporales	Polyporaceae	Trametes	Trametes coccinea	1	0
1353536	NA	Proteobacteria	Gammaproteobacteria	Alteromonadales	Shewanellaceae	Shewanella	Shewanella decolorationis	2	0
1353952	Fungi	Basidiomycota	Dacrymycetes	Dacrymycetales	Dacrymycetaceae	Calocera	Calocera cornea	7	0
1353977	NA	Chlamydiae	Chlamydiia	Parachlamydiales	Parachlamydiaceae	Candidatus Protochlamydia	Candidatus Protochlamydia sp. R18	1	0
1355477	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	Bradyrhizobiaceae	Bradyrhizobium	Bradyrhizobium diazoefficiens	2	0
1355	NA	Firmicutes	Bacilli	Lactobacillales	Enterococcaceae	Enterococcus	Enterococcus columbae	1	0
135614	NA	Proteobacteria	Gammaproteobacteria	Xanthomonadales	NA	NA	NA	1	0
135622	NA	Proteobacteria	Gammaproteobacteria	Alteromonadales	NA	NA	NA	1	0
135623	NA	Proteobacteria	Gammaproteobacteria	Vibrionales	NA	NA	NA	1	0
135625	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	NA	NA	NA	3	0
135719	NA	Proteobacteria	Alphaproteobacteria	Sphingomonadales	Sphingomonadaceae	Sphingobium	Sphingobium amiense	1	0
1357716	Fungi	Chytridiomycota	Chytridiomycetes	Rhizophydiales	NA	Batrachochytrium	Batrachochytrium salamandrivorans	4	0
1358418	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	Rhizobiaceae	Sinorhizobium	Sinorhizobium sp. GL28	3	0
1359208	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. TP-A0356	2	0
136370	Fungi	Ascomycota	Lecanoromycetes	Umbilicariales	Umbilicariaceae	Umbilicaria	Umbilicaria pustulata	1	0
136849	NA	Proteobacteria	Gammaproteobacteria	Pseudomonadales	Pseudomonadaceae	Pseudomonas	NA	5	0
13687	NA	Proteobacteria	Alphaproteobacteria	Sphingomonadales	Sphingomonadaceae	Sphingomonas	NA	1	0
13706	Fungi	Mucoromycota	NA	Mucorales	Syncephalastraceae	Syncephalastrum	Syncephalastrum racemosum	1	0
137071	NA	Apicomplexa	Aconoidasida	Haemosporida	Plasmodiidae	Plasmodium	Plasmodium falciparum	1	0
13769	NA	Euryarchaeota	Halobacteria	Natrialbales	Natrialbaceae	Natrialba	Natrialba magadii	1	0
1380356	NA	Actinobacteria	Actinobacteria	Geodermatophilales	Geodermatophilaceae	Blastococcus	Blastococcus sp. URHD0036	1	0
1380390	NA	Actinobacteria	Thermoleophilia	Solirubrobacterales	NA	NA	Solirubrobacterales bacterium URHD0059	1	0
138074	NA	Proteobacteria	Gammaproteobacteria	Enterobacterales	Yersiniaceae	Serratia	Serratia symbiotica	1	0
1381753	Fungi	Basidiomycota	Agaricomycetes	Agaricales	Marasmiaceae	Moniliophthora	Moniliophthora roreri	1	0
1381	NA	Actinobacteria	Coriobacteriia	Coriobacteriales	Atopobiaceae	Atopobium	Atopobium minutum	1	0
1382345	NA	Bacteroidetes	Cytophagia	Cytophagales	Flammeovirgaceae	Flammeovirga	Flammeovirga sp. OC4	1	0
138336	NA	Actinobacteria	Actinobacteria	Geodermatophilales	Geodermatophilaceae	Blastococcus	Blastococcus saxobsidens	2	0
1384078	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella sp. DNF00663	1	0
1384082	NA	Firmicutes	Negativicutes	Veillonellales	Veillonellaceae	NA	Veillonellaceae bacterium DNF00751	1	0
1385625	NA	Proteobacteria	Gammaproteobacteria	Chromatiales	Chromatiaceae	Thiohalocapsa	uncultured Thiohalocapsa sp. PB-PSB1	2	0
1385935	NA	Cyanobacteria	NA	Synechococcales	Leptolyngbyaceae	Leptolyngbya	Leptolyngbya sp. Heron Island J	1	0
1385	NA	Firmicutes	Bacilli	Bacillales	NA	NA	NA	1	0
1388766	Fungi	Ascomycota	Eurotiomycetes	Eurotiales	Aspergillaceae	Aspergillus	Aspergillus ruber	1	0
139043	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Bacteroidaceae	Bacteroides	NA	4	0
1390	NA	Firmicutes	Bacilli	Bacillales	Bacillaceae	Bacillus	Bacillus amyloliquefaciens	1	0
1391654	NA	Proteobacteria	Deltaproteobacteria	Myxococcales	Labilitrichaceae	Labilithrix	Labilithrix luteola	2	0
1392248	Fungi	Ascomycota	Eurotiomycetes	Eurotiales	Aspergillaceae	Aspergillus	Aspergillus campestris	1	0
1392256	Fungi	Ascomycota	Eurotiomycetes	Eurotiales	Aspergillaceae	Aspergillus	Aspergillus ochraceoroseus	1	0
1395125	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella salivae	1	0
1396141	NA	Verrucomicrobia	Verrucomicrobiae	Verrucomicrobiales	Verrucomicrobiaceae	Haloferula	Haloferula sp. BvORR071	1	0
1396	NA	Firmicutes	Bacilli	Bacillales	Bacillaceae	Bacillus	Bacillus cereus	2	0
1397851	NA	Proteobacteria	Gammaproteobacteria	Enterobacterales	Morganellaceae	Xenorhabdus	Xenorhabdus bovienii	1	0
1398559	Fungi	Basidiomycota	Ustilaginomycetes	Ustilaginales	Ustilaginaceae	Melanopsichium	Melanopsichium pennsylvanicum	1	0
1399860	Fungi	Ascomycota	Sordariomycetes	Hypocreales	Ophiocordycipitaceae	Ophiocordyceps	Ophiocordyceps australis	2	0
1401068	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella bivia	2	0
1401075	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella disiens	6	0
1401325	NA	Bacteroidetes	Flavobacteriia	Flavobacteriales	Flavobacteriaceae	Ornithobacterium	Ornithobacterium rhinotracheale	2	0
1402135	NA	Proteobacteria	Alphaproteobacteria	Rhodobacterales	Rhodobacteraceae	Sulfitobacter	Sulfitobacter pseudonitzschiae	2	0
1403939	NA	Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Actinomyces	Actinomyces urogenitalis	5	0
1403948	NA	Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Varibaculum	Varibaculum cambriense	3	0
1407017	NA	Firmicutes	Clostridia	Clostridiales	Clostridiaceae	Clostridium	Clostridium botulinum	1	0
1410327	NA	NA	NA	Acytosteliales	Acytosteliaceae	Acytostelium	Acytostelium subglobosum	1	0
1410623	NA	Firmicutes	Clostridia	Clostridiales	Lachnospiraceae	NA	Lachnospiraceae bacterium FD2005	1	0
1411022	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Tannerellaceae	Tannerella	Tannerella sp. oral taxon HOT-286	1	0
1411681	NA	NA	NA	NA	Partitiviridae	NA	Rhizoctonia solani dsRNA virus 2	1	0
1415557	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. WM6378	2	0
1416333	NA	NA	NA	Kinetoplastida	Trypanosomatidae	Trypanosoma	Trypanosoma cruzi	18	0
1420915	Fungi	Ascomycota	Leotiomycetes	NA	Pseudeurotiaceae	Pseudogymnoascus	Pseudogymnoascus sp. VKM F-4520 (FW-2644)	1	0
1427391	NA	Actinobacteria	Actinobacteria	Pseudonocardiales	Pseudonocardiaceae	Saccharothrix	Saccharothrix sp. ST-888	1	0
1428644	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces gilvigriseus	1	0
142864	NA	Cyanobacteria	NA	Nostocales	Nostocaceae	Cylindrospermum	Cylindrospermum stagnale	1	0
1429438	NA	Candidatus Tectomicrobia	NA	NA	NA	Candidatus Entotheonella	Candidatus Entotheonella factor	1	0
1432056	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Mannheimia	Mannheimia sp. USDA-ARS-USMARC-1261	1	0
1432141	Fungi	Mucoromycota	Glomeromycetes	Glomerales	Glomeraceae	Rhizophagus	Rhizophagus irregularis	1	0
1432307	Fungi	Ascomycota	Leotiomycetes	Helotiales	Sclerotiniaceae	Sclerotinia	Sclerotinia borealis	1	0
1433844	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella sp. HJM029	1	0
143387	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Fusobacterium	Fusobacterium necrophorum	2	0
1434195	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Burkholderiaceae	Burkholderia	Burkholderia pseudomallei	1	0
1434831	NA	Proteobacteria	Gammaproteobacteria	Oceanospirillales	Halomonadaceae	Halomonas	Halomonas sp. JB380	1	0
1434930	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Burkholderiaceae	Burkholderia	Burkholderia pseudomallei	1	0
1437824	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Alcaligenaceae	Castellaniella	Castellaniella defragrans	1	0
143813	NA	Proteobacteria	Gammaproteobacteria	Pseudomonadales	Pseudomonadaceae	Pseudomonas	Pseudomonas sp. LAB-08	3	0
1441469	Fungi	Ascomycota	Eurotiomycetes	Eurotiales	Trichocomaceae	Talaromyces	Talaromyces atroroseus	2	0
144185	NA	Actinobacteria	Actinobacteria	Micrococcales	Microbacteriaceae	Leifsonia	Leifsonia aquatica	1	0
1445513	NA	Proteobacteria	Gammaproteobacteria	Orbales	Orbaceae	Gilliamella	Gilliamella apicola	1	0
1447782	NA	Proteobacteria	Alphaproteobacteria	Rhodobacterales	Rhodobacteraceae	Wenxinia	Wenxinia saemankumensis	1	0
1447875	Fungi	Ascomycota	Eurotiomycetes	Onygenales	Ajellomycetaceae	Helicocarpus	Helicocarpus griseus	1	0
1447883	Fungi	Ascomycota	Eurotiomycetes	Onygenales	Ajellomycetaceae	Polytolypa	Polytolypa hystricis	1	0
1449049	NA	Proteobacteria	Alphaproteobacteria	Caulobacterales	Caulobacteraceae	Caulobacter	Caulobacter sp. UNC358MFTsu5.1	2	0
1450521	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium diphtheriae	1	0
1453352	NA	Bacteroidetes	Flavobacteriia	Flavobacteriales	Flavobacteriaceae	Sediminicola	Sediminicola sp. YIK13	1	0
1454202	NA	Proteobacteria	Gammaproteobacteria	Vibrionales	Vibrionaceae	Photobacterium	Photobacterium phosphoreum	8	0
145458	NA	Actinobacteria	Actinobacteria	Micrococcales	Microbacteriaceae	Rathayibacter	Rathayibacter toxicus	1	0
1455909	NA	Thaumarchaeota	NA	NA	NA	NA	uncultured marine thaumarchaeote AD1000_33_G09	1	0
145854	NA	Actinobacteria	Actinobacteria	Micromonosporales	Micromonosporaceae	Micromonospora	Micromonospora pallida	1	0
146018	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Mycobacteriaceae	Mycobacterium	Mycobacterium neworleansense	1	0
146021	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Mycobacteriaceae	Mycobacterium	Mycobacterium houstonense	1	0
1461579	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Haemophilus	Haemophilus massiliensis	1	0
1461583	NA	Firmicutes	Bacilli	Bacillales	Bacillaceae	Lysinibacillus	Lysinibacillus saudimassiliensis	2	0
1462733	NA	Proteobacteria	Alphaproteobacteria	Rickettsiales	Rickettsiaceae	Rickettsia	Rickettsia endosymbiont of Proechinophthirus fluctus	1	0
1463825	NA	Actinobacteria	Actinobacteria	Pseudonocardiales	Pseudonocardiaceae	Saccharothrix	Saccharothrix sp. NRRL B-16314	1	0
1463833	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. NRRL B-24484	2	0
1463846	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. NRRL F-3213	1	0
1463858	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. NRRL F-5135	1	0
1463880	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. NRRL S-1022	1	0
1463888	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. NRRL S-1813	1	0
1464038	NA	Firmicutes	Tissierellia	NA	NA	Ezakiella	Ezakiella peruensis	2	0
1464122	NA	Firmicutes	Bacilli	Bacillales	Bacillaceae	Bacillus	Bacillus lonarensis	1	0
146537	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces azureus	1	0
1465756	NA	Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Peptoniphilus	Peptoniphilus grossensis	3	0
146923	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces parvulus	1	0
146938	NA	Proteobacteria	Betaproteobacteria	Rhodocyclales	Rhodocyclaceae	Azovibrio	Azovibrio restrictus	1	0
1470345	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Bacteroidaceae	Bacteroides	Bacteroides timonensis	1	0
147467	NA	Firmicutes	Bacilli	Bacillales	Staphylococcaceae	Staphylococcus	Staphylococcus sciuri	1	0
1477000	NA	Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Peptoniphilus	Peptoniphilus sp. DNF00840	11	0
1485	NA	Firmicutes	Clostridia	Clostridiales	Clostridiaceae	Clostridium	NA	2	0
1486991	NA	Proteobacteria	Gammaproteobacteria	Enterobacterales	Pectobacteriaceae	Sodalis	Candidatus Sodalis pierantonius	1	0
1487953	NA	Cyanobacteria	NA	Synechococcales	Leptolyngbyaceae	Leptolyngbya	Leptolyngbya sp. JSC-1	4	0
149040	Fungi	Ascomycota	Leotiomycetes	Helotiales	NA	Phialocephala	Phialocephala scopiformis	2	0
1491	NA	Firmicutes	Clostridia	Clostridiales	Clostridiaceae	Clostridium	Clostridium botulinum	2	0
1494	NA	Firmicutes	Clostridia	Clostridiales	Clostridiaceae	Clostridium	Clostridium cochlearium	1	0
1495638	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. M56	1	0
1496690	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	Rhizobiaceae	Rhizobium	Rhizobium marinum	1	0
1496	NA	Firmicutes	Clostridia	Clostridiales	Peptostreptococcaceae	Clostridioides	Clostridioides difficile	3	0
1497953	NA	Bacteroidetes	Bacteroidia	Bacteroidales	NA	NA	Bacteroidales bacterium KA00251	4	0
1497954	NA	Bacteroidetes	Bacteroidia	Bacteroidales	NA	NA	Bacteroidales bacterium KA00344	4	0
1497955	NA	Firmicutes	Clostridia	Clostridiales	NA	NA	Clostridiales bacterium KA00274	1	0
1497	NA	Firmicutes	Clostridia	Clostridiales	Clostridiaceae	Clostridium	Clostridium formicaceticum	1	0
1501329	NA	Firmicutes	Clostridia	Clostridiales	Lachnospiraceae	Oribacterium	Oribacterium parvum	1	0
150247	NA	Firmicutes	Bacilli	Bacillales	Bacillaceae	Anoxybacillus	NA	1	0
1502734	NA	Actinobacteria	Actinobacteria	Frankiales	Frankiaceae	Frankia	Frankia sp. CpI1-P	1	0
1504320	NA	Actinobacteria	Actinobacteria	NA	NA	NA	actinobacterium acAcidi	1	0
1505932	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	Phyllobacteriaceae	Mesorhizobium	Mesorhizobium sp. ORS3324	1	0
1506553	NA	Firmicutes	Clostridia	Clostridiales	Lachnospiraceae	Lachnoclostridium	NA	2	0
1507806	NA	Proteobacteria	Epsilonproteobacteria	Campylobacterales	Campylobacteraceae	Campylobacter	Campylobacter fetus	2	0
1507870	Fungi	Ascomycota	Dothideomycetes	Capnodiales	Cladosporiaceae	Rachicladosporium	Rachicladosporium antarcticum	1	0
1507979	NA	Proteobacteria	Gammaproteobacteria	Vibrionales	Vibrionaceae	Vibrio	Vibrio sp. J2-29	10	0
1517936	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Nocardiaceae	Rhodococcus	Rhodococcus sp. CUA-806	1	0
1519475	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. NRRL F-5755	1	0
1520806	NA	Firmicutes	Clostridia	Clostridiales	Lachnospiraceae	Butyrivibrio	Butyrivibrio sp. INlla18	1	0
1522368	NA	Actinobacteria	Actinobacteria	Geodermatophilales	Geodermatophilaceae	Modestobacter	Modestobacter caceresii	1	0
1523428	NA	Proteobacteria	Betaproteobacteria	NA	NA	NA	beta proteobacterium AAP99	1	0
152794	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium efficiens	2	0
1532555	NA	Proteobacteria	Alphaproteobacteria	Caulobacterales	Caulobacteraceae	Brevundimonas	Brevundimonas sp. DS20	1	0
1533	NA	Firmicutes	Clostridia	Clostridiales	Clostridiaceae	Clostridium	Clostridium fallax	1	0
1538294	NA	Actinobacteria	Actinobacteria	Micromonosporales	Micromonosporaceae	Micromonospora	Micromonospora sp. HK10	1	0
1546107	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. NBRC 110027	1	0
1547283	NA	Firmicutes	Bacilli	Bacillales	Bacillaceae	Bacillus	Bacillus weihaiensis	1	0
1547922	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	NA	Ideonella	Ideonella sakaiensis	2	0
1548	NA	Firmicutes	Clostridia	Clostridiales	Clostridiaceae	Clostridium	Clostridium scatologenes	1	0
155322	NA	Firmicutes	Bacilli	Bacillales	Bacillaceae	Bacillus	Bacillus toyonensis	2	0
155892	NA	Proteobacteria	Alphaproteobacteria	Caulobacterales	Caulobacteraceae	Caulobacter	Caulobacter vibrioides	1	0
1564113	NA	Proteobacteria	Alphaproteobacteria	Sphingomonadales	Sphingomonadaceae	Sphingomonas	Sphingomonas sp. Ant H11	2	0
156453	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces yunnanensis	1	0
156578	NA	Proteobacteria	Gammaproteobacteria	Alteromonadales	NA	NA	Alteromonadales bacterium TW-7	1	0
1565991	NA	Firmicutes	Bacilli	Bacillales	Bacillaceae	Bacillus	Bacillus sp. X1(2014)	1	0
1566283	NA	Proteobacteria	Alphaproteobacteria	Sphingomonadales	Sphingomonadaceae	Sphingomonas	Sphingomonas sp. NFR04	1	0
1566285	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	Bradyrhizobiaceae	Bradyrhizobium	Bradyrhizobium sp. NFR13	1	0
1566295	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	Rhizobiaceae	Sinorhizobium	Sinorhizobium sp. NFACC03	1	0
156980	NA	Actinobacteria	Actinobacteria	Micrococcales	Micrococcaceae	Arthrobacter	Arthrobacter woluwensis	1	0
1570339	NA	Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	NA	NA	289	0
1573173	Fungi	Ascomycota	Sordariomycetes	Glomerellales	Glomerellaceae	Colletotrichum	Colletotrichum incanum	1	0
157538	NA	NA	NA	Kinetoplastida	Trypanosomatidae	Leptomonas	Leptomonas pyrrhocoris	1	0
1578	NA	Firmicutes	Bacilli	Lactobacillales	Lactobacillaceae	Lactobacillus	NA	2	0
1581050	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium sp. HMSC04H06	2	0
1581069	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium sp. HMSC29G08	1	0
1581089	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium sp. HMSC11E11	1	0
1581123	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium sp. HMSC06D04	1	0
1581131	NA	Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Actinomyces	Actinomyces sp. HMSC08A01	3	0
1581137	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium sp. HMSC08C04	1	0
158607	Fungi	Ascomycota	Sordariomycetes	Diaporthales	Diaporthaceae	Diaporthe	Diaporthe helianthi	9	0
1588750	NA	Firmicutes	Clostridia	Clostridiales	NA	NA	Clostridiales bacterium KA00134	4	0
1588751	NA	Firmicutes	Tissierellia	NA	NA	NA	Tissierellia bacterium KA00581	2	0
1588755	NA	Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Parvimonas	Parvimonas sp. KA00067	1	0
158	NA	Spirochaetes	Spirochaetia	Spirochaetales	Spirochaetaceae	Treponema	Treponema denticola	2	0
1592328	NA	Actinobacteria	Actinobacteria	NA	NA	NA	Actinobacteria bacterium OV450	1	0
1592897	NA	Proteobacteria	Gammaproteobacteria	Legionellales	Coxiellaceae	NA	Coxiella-like endosymbiont	2	0
159291	NA	Spirochaetes	Spirochaetia	Spirochaetales	Spirochaetaceae	Alkalispirochaeta	Alkalispirochaeta americana	1	0
159449	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces scabrisporus	2	0
159749	NA	Bacillariophyta	Coscinodiscophyceae	Thalassiosirales	Thalassiosiraceae	Thalassiosira	Thalassiosira oceanica	10	0
159	NA	Spirochaetes	Spirochaetia	Brachyspirales	Brachyspiraceae	Brachyspira	Brachyspira hyodysenteriae	2	0
1603295	Fungi	NA	NA	NA	NA	NA	fungal sp. No.11243	1	0
160386	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium casei	3	0
1608898	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Haemophilus	Haemophilus sp. HMSC71H05	1	0
1609095	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. NRRL F-4489	1	0
161358	NA	Actinobacteria	Actinobacteria	Streptosporangiales	Streptosporangiaceae	Microtetraspora	Microtetraspora malaysiensis	1	0
1615590	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces rubellomurinus	1	0
1618356	NA	Candidatus Amesbacteria	NA	NA	NA	NA	Candidatus Amesbacteria bacterium GW2011_GWA2_42_12	1	0
1618669	NA	Candidatus Kaiserbacteria	NA	NA	NA	NA	Candidatus Kaiserbacteria bacterium GW2011_GWA2_49_19	1	0
161895	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium phocae	2	0
161896	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium camporealensis	4	0
161920	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Dietziaceae	Dietzia	Dietzia natronolimnaea	14	0
1619308	NA	Actinobacteria	Actinobacteria	Micrococcales	Microbacteriaceae	Cnuibacter	Cnuibacter physcomitrellae	1	0
1619947	NA	Actinobacteria	Actinobacteria	Micrococcales	Intrasporangiaceae	Terrabacter	Terrabacter sp. 28	1	0
1621260	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. NBRC 110028	1	0
162156	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Bacteroidaceae	Bacteroides	uncultured Bacteroides sp.	1	0
162289	NA	Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Peptoniphilus	NA	1883	0
1624	NA	Firmicutes	Bacilli	Lactobacillales	Lactobacillaceae	Lactobacillus	Lactobacillus salivarius	4	0
162	NA	Spirochaetes	Spirochaetia	Spirochaetales	Spirochaetaceae	Treponema	Treponema phagedenis	1	0
1630135	NA	Actinobacteria	Actinobacteria	Micrococcales	Dermabacteraceae	Dermabacter	Dermabacter vaginalis	2	0
1630172	NA	Actinobacteria	Actinobacteria	Bifidobacteriales	Bifidobacteriaceae	Bifidobacterium	Bifidobacterium hapali	4	0
1631249	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	Phyllobacteriaceae	Mesorhizobium	Mesorhizobium prunaredense	1	0
1635280	NA	Candidatus Marinimicrobia	NA	NA	NA	NA	Marinimicrobia bacterium 46_43	1	0
1636606	NA	Proteobacteria	Gammaproteobacteria	Aeromonadales	Aeromonadaceae	Aeromonas	Aeromonas sp. ASNIH1	1	0
1637841	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Burkholderiaceae	Burkholderia	Burkholderia sp. MSMB0852	1	0
1637844	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Burkholderiaceae	Burkholderia	Burkholderia sp. RF2-non_BP3	1	0
1637	NA	Firmicutes	Bacilli	Bacillales	Listeriaceae	Listeria	NA	1	0
1639	NA	Firmicutes	Bacilli	Bacillales	Listeriaceae	Listeria	Listeria monocytogenes	1	0
1650662	NA	Firmicutes	Clostridia	Clostridiales	Clostridiaceae	Desnuesiella	Desnuesiella massiliensis	1	0
165179	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella copri	5	0
1653174	NA	Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Actinotignum	NA	1896	0
1653	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	NA	NA	389	0
1654	NA	Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Actinomyces	NA	165	0
165695	NA	Proteobacteria	Alphaproteobacteria	Sphingomonadales	Sphingomonadaceae	Sphingobium	NA	1	0
165779	NA	Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Anaerococcus	NA	121	0
1657	NA	Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Actinobaculum	Actinobaculum suis	6	0
1658172	Fungi	Ascomycota	Eurotiomycetes	Onygenales	Ajellomycetaceae	Emmonsia	Emmonsia sp. CAC-2015a	1	0
1660093	NA	Bacteroidetes	Flavobacteriia	Flavobacteriales	Flavobacteriaceae	Chryseobacterium	Chryseobacterium sp. SCN 40-13	1	0
1660156	NA	NA	NA	NA	NA	NA	bacterium SCN 62-11	1	0
1660158	NA	Proteobacteria	Betaproteobacteria	Nitrosomonadales	NA	NA	NA	1	0
1661388	NA	Actinobacteria	Actinobacteria	Streptosporangiales	Nocardiopsaceae	Nocardiopsis	Nocardiopsis sp. RV163	1	0
1661745	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Haemophilus	Haemophilus sp. C1	3	0
1661	NA	Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Trueperella	Trueperella pyogenes	2	0
166939	NA	Firmicutes	Bacilli	Lactobacillales	Carnobacteriaceae	Allofustis	Allofustis seminis	1	0
1673719	NA	Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Anaerococcus	Anaerococcus sp. SB3	2	0
1673721	NA	Firmicutes	Clostridia	Clostridiales	NA	Intestinimonas	Intestinimonas massiliensis	1	0
1678012	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. MUSC 1	2	0
1678	NA	Actinobacteria	Actinobacteria	Bifidobacteriales	Bifidobacteriaceae	Bifidobacterium	NA	1	0
1679001	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	NA	Pasteurellaceae bacterium NI1060	3	0
1679444	NA	Verrucomicrobia	Verrucomicrobiae	Verrucomicrobiales	Akkermansiaceae	Akkermansia	Akkermansia glycaniphila	2	0
167968	NA	Proteobacteria	Deltaproteobacteria	Desulfovibrionales	Desulfovibrionaceae	Desulfovibrio	uncultured Desulfovibrio sp.	2	0
1680763	NA	Bacteroidetes	Flavobacteriia	Flavobacteriales	Flavobacteriaceae	Tenacibaculum	Tenacibaculum finnmarkense	1	0
1680	NA	Actinobacteria	Actinobacteria	Bifidobacteriales	Bifidobacteriaceae	Bifidobacterium	Bifidobacterium adolescentis	1	0
1682113	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Mycobacteriaceae	Mycobacterium	Mycobacterium sp. YC-RL4	1	0
1684	NA	Actinobacteria	Actinobacteria	Bifidobacteriales	Bifidobacteriaceae	Bifidobacterium	Bifidobacterium asteroides	1	0
1689272	NA	Proteobacteria	Betaproteobacteria	Neisseriales	Neisseriaceae	Vitreoscilla	Vitreoscilla sp. SN6	1	0
1689303	NA	Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Lagierella	Lagierella massiliensis	2	0
168934	NA	Proteobacteria	Alphaproteobacteria	Rhodospirillales	Rhodospirillaceae	Thalassospira	NA	1	0
1690244	NA	Firmicutes	Bacilli	Lactobacillales	Enterococcaceae	Enterococcus	Enterococcus sp. RIT-PI-f	2	0
169292	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium aurimucosum	13	0
1697	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium ammoniagenes	1	0
1698	NA	Actinobacteria	Actinobacteria	Micrococcales	Brevibacteriaceae	Brevibacterium	Brevibacterium epidermidis	1	0
1701325	NA	NA	NA	NA	NA	NA	uncultured bacterium 5G12	1	0
1703339	NA	Proteobacteria	Alphaproteobacteria	Sphingomonadales	Erythrobacteraceae	Croceicoccus	Croceicoccus mobilis	2	0
1703398	NA	Proteobacteria	Deltaproteobacteria	NA	NA	NA	Deltaproteobacteria bacterium SG8_13	1	0
1703771	NA	NA	NA	NA	NA	NA	candidate division TA06 bacterium DG_26	1	0
1703920	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. CB02488	1	0
1703930	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Kitasatospora	Kitasatospora sp. CB01950	1	0
1703932	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. CB00316	1	0
1706375	NA	Proteobacteria	Gammaproteobacteria	Cellvibrionales	Spongiibacteraceae	NA	NA	2	0
1707	NA	Actinobacteria	Actinobacteria	Micrococcales	Cellulomonadaceae	Cellulomonas	NA	2	0
1708715	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	Rhizobiaceae	Ensifer	Ensifer aridi	1	0
1709476	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. NRRL B-24085	3	0
170994	NA	Actinobacteria	Actinobacteria	Micrococcales	Brevibacteriaceae	Brevibacterium	Brevibacterium paucivorans	3	0
1710	NA	Actinobacteria	Actinobacteria	Micrococcales	Promicromonosporaceae	Cellulosimicrobium	Cellulosimicrobium cellulans	3	0
171292	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Mycobacteriaceae	Mycobacterium	uncultured Mycobacterium sp.	2	0
1715034	NA	Actinobacteria	Actinobacteria	Micrococcales	Micrococcaceae	Rothia	Rothia sp. HMSC071F11	1	0
1715123	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Haemophilus	Haemophilus sp. HMSC071C11	2	0
171549	NA	Bacteroidetes	Bacteroidia	Bacteroidales	NA	NA	NA	605	0
171551	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Porphyromonadaceae	NA	NA	68	0
171552	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	NA	NA	117	0
1715989	NA	Nitrospirae	Nitrospira	Nitrospirales	Nitrospiraceae	Nitrospira	Candidatus Nitrospira inopinata	1	0
1716	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	NA	6089	0
1717	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium diphtheriae	9	0
1719	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium pseudotuberculosis	1	0
1720317	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Porphyromonadaceae	NA	Porphyromonadaceae bacterium FC4	5	0
172042	NA	Actinobacteria	Actinobacteria	Micrococcales	Micrococcaceae	Rothia	Rothia aeria	1	0
1727216	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. H-KF8	1	0
172733	NA	Firmicutes	Clostridia	Clostridiales	NA	NA	uncultured Clostridiales bacterium	1	0
1729688	NA	Firmicutes	Bacilli	Bacillales	Bacillaceae	Bacillus	Bacillus sp. FJAT-29814	3	0
1735688	NA	Actinobacteria	Actinobacteria	Micrococcales	Microbacteriaceae	Agromyces	Agromyces sp. Leaf222	1	0
1735693	NA	Proteobacteria	Alphaproteobacteria	Sphingomonadales	Sphingomonadaceae	Sphingobium	Sphingobium sp. Leaf26	1	0
1736244	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	Methylobacteriaceae	Methylobacterium	Methylobacterium sp. Leaf88	1	0
1736314	NA	Actinobacteria	Actinobacteria	Micrococcales	Microbacteriaceae	Leifsonia	Leifsonia sp. Leaf264	1	0
1736337	NA	Actinobacteria	Actinobacteria	Micrococcales	Microbacteriaceae	Leifsonia	Leifsonia sp. Leaf325	1	0
1736354	NA	Actinobacteria	Actinobacteria	Geodermatophilales	Geodermatophilaceae	Geodermatophilus	Geodermatophilus sp. Leaf369	1	0
1736489	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Oxalobacteraceae	Duganella	Duganella sp. Root198D2	1	0
1736555	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	Phyllobacteriaceae	Mesorhizobium	Mesorhizobium sp. Root552	1	0
1736558	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	Rhizobiaceae	Ensifer	Ensifer sp. Root558	1	0
1737404	NA	Firmicutes	Tissierellia	NA	NA	NA	NA	81	0
1737405	NA	Firmicutes	Tissierellia	Tissierellales	NA	NA	NA	7	0
1739305	NA	Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Peptoniphilus	Peptoniphilus sp. HMSC062D09	1	0
1739311	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Turicella	Turicella sp. HMSC074A09	1	0
1739317	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Haemophilus	Haemophilus sp. HMSC066A11	2	0
1739356	NA	Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Anaerococcus	Anaerococcus sp. HMSC065G05	1	0
1739390	NA	Proteobacteria	Gammaproteobacteria	Pseudomonadales	Pseudomonadaceae	Pseudomonas	Pseudomonas sp. HMSC066A08	1	0
1739394	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Porphyromonadaceae	Porphyromonas	Porphyromonas sp. HMSC065F10	10	0
1739400	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium sp. HMSC069E04	2	0
1739416	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium sp. HMSC056E09	1	0
1739446	NA	Actinobacteria	Actinobacteria	Micrococcales	Micrococcaceae	Rothia	Rothia sp. HMSC071C12	1	0
1739462	NA	Actinobacteria	Actinobacteria	Micrococcales	Micrococcaceae	Rothia	Rothia sp. HMSC036D11	1	0
1739525	NA	Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Peptoniphilus	Peptoniphilus sp. HMSC075B08	2	0
1739529	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Porphyromonadaceae	Porphyromonas	Porphyromonas sp. HMSC077F02	100	0
1739536	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium sp. HMSC073D01	2	0
1739537	NA	Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Anaerococcus	Anaerococcus sp. HMSC075B03	3	0
1744	NA	Actinobacteria	Actinobacteria	Propionibacteriales	Propionibacteriaceae	Propionibacterium	Propionibacterium freudenreichii	4	0
1747	NA	Actinobacteria	Actinobacteria	Propionibacteriales	Propionibacteriaceae	Cutibacterium	Cutibacterium acnes	6	0
1752188	NA	Actinobacteria	NA	NA	NA	NA	NA	5	0
1752733	NA	Candidatus Yanofskybacteria	NA	NA	NA	NA	NA	1	0
1752737	NA	Candidatus Moranbacteria	NA	NA	NA	NA	NA	1	0
1754190	Fungi	Chytridiomycota	Neocallimastigomycetes	Neocallimastigales	Neocallimastigaceae	Neocallimastix	Neocallimastix californiae	5	0
1754191	Fungi	Chytridiomycota	Neocallimastigomycetes	Neocallimastigales	Neocallimastigaceae	Piromyces	Piromyces finnis	24	0
1754192	Fungi	Chytridiomycota	Neocallimastigomycetes	Neocallimastigales	Neocallimastigaceae	Anaeromyces	Anaeromyces robustus	2	0
1755991	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Burkholderiaceae	Burkholderia	Burkholderia sp. A27	1	0
1756034	NA	NA	NA	NA	Orthomyxoviridae	Influenzavirus A	Influenza A virus	2	0
1756150	NA	Bacteroidetes	Flavobacteriia	Flavobacteriales	Flavobacteriaceae	Elizabethkingia	Elizabethkingia genomosp. 4	1	0
1756987	NA	Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Peptoniphilus	Peptoniphilus sp. KHD2	2	0
1760	NA	Actinobacteria	Actinobacteria	NA	NA	NA	NA	856	0
1761772	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	Bradyrhizobiaceae	Bradyrhizobium	Bradyrhizobium sp. err11	1	0
1761887	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella sp. ne3005	1	0
1761903	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. cf124	1	0
1763536	NA	Proteobacteria	Gammaproteobacteria	Alteromonadales	Colwelliaceae	Thalassotalea	Thalassotalea crassostreae	1	0
1763	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Mycobacteriaceae	Mycobacterium	NA	8	0
1765722	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces silvensis	1	0
1768112	NA	NA	NA	NA	NA	NA	bacterium P201	1	0
1768	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Mycobacteriaceae	Mycobacterium	Mycobacterium kansasii	1	0
1772284	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Mycobacteriaceae	Mycobacterium	Mycobacterium sp. IS-1496	1	0
1773	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Mycobacteriaceae	Mycobacterium	Mycobacterium tuberculosis	5	0
177413	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	Xanthobacteraceae	Ancylobacter	Ancylobacter rudongensis	2	0
1776081	NA	Firmicutes	Negativicutes	Veillonellales	Veillonellaceae	Megasphaera	Megasphaera sp. DISK 18	1	0
1776381	NA	Actinobacteria	Coriobacteriia	Coriobacteriales	Coriobacteriaceae	Olegusella	Olegusella massiliensis	1	0
1776387	NA	Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Peptoniphilus	Peptoniphilus sp. KHD4	1	0
1776390	NA	Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Peptoniphilus	Peptoniphilus sp. KHD5	1	0
1778	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Mycobacteriaceae	Mycobacterium	Mycobacterium gordonae	1	0
177971	NA	Firmicutes	Clostridia	Clostridiales	Lachnospiraceae	Shuttleworthia	NA	1	0
1783270	NA	NA	NA	NA	NA	NA	NA	1	0
1783272	NA	NA	NA	NA	NA	NA	NA	209	0
1786003	NA	Proteobacteria	Alphaproteobacteria	Rhodobacterales	Rhodobacteraceae	Rhodobacter	Rhodobacter sp. CCB-MM2	1	0
178876	Fungi	Basidiomycota	Tremellomycetes	Tremellales	Cryptococcaceae	Cryptococcus	Cryptococcus neoformans	5	0
1789683	Fungi	Ascomycota	Saccharomycetes	Saccharomycetales	Saccharomycetaceae	Kazachstania	Kazachstania saulgeensis	1	0
1794810	NA	NA	NA	NA	NA	NA	NA	1	0
1794811	NA	NA	NA	NA	NA	NA	NA	1	0
1797336	NA	Bacteroidetes	NA	NA	NA	NA	Bacteroidetes bacterium GWE2_41_25	1	0
1797546	NA	Candidatus Buchananbacteria	NA	NA	NA	NA	Candidatus Buchananbacteria bacterium RIFCSPLOWO2_01_FULL_46_12	1	0
1797605	NA	Chlamydiae	NA	NA	NA	NA	Chlamydiae bacterium RIFCSPHIGHO2_12_FULL_49_9	1	0
1797697	NA	Proteobacteria	Gammaproteobacteria	Legionellales	Coxiellaceae	Coxiella	Coxiella sp. RIFCSPHIGHO2_12_FULL_44_14	1	0
1797770	NA	Candidatus Daviesbacteria	NA	NA	NA	NA	Candidatus Daviesbacteria bacterium RIFCSPHIGHO2_02_FULL_39_12	1	0
1797906	NA	Proteobacteria	Deltaproteobacteria	NA	NA	NA	Deltaproteobacteria bacterium RIFOXYD12_FULL_57_12	1	0
1797913	NA	Proteobacteria	Deltaproteobacteria	Desulfobacterales	NA	NA	Desulfobacterales bacterium GWB2_56_26	1	0
1797914	NA	Proteobacteria	Deltaproteobacteria	Desulfobacterales	NA	NA	Desulfobacterales bacterium RIFOXYA12_FULL_46_15	1	0
1797952	NA	Elusimicrobia	NA	NA	NA	NA	Elusimicrobia bacterium RIFCSPLOWO2_12_FULL_59_9	1	0
1797	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Mycobacteriaceae	Mycobacterium	Mycobacterium thermoresistibile	1	0
1798190	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. GP55	1	0
1798277	NA	Proteobacteria	Gammaproteobacteria	NA	NA	NA	Gammaproteobacteria bacterium RIFCSPHIGHO2_12_FULL_37_34	1	0
1798375	NA	Candidatus Gottesmanbacteria	NA	NA	NA	NA	Candidatus Gottesmanbacteria bacterium RIFCSPHIGHO2_01_FULL_39_10	1	0
1798382	NA	Candidatus Gottesmanbacteria	NA	NA	NA	NA	Candidatus Gottesmanbacteria bacterium RIFCSPHIGHO2_02_FULL_39_11	1	0
1798413	NA	Proteobacteria	Hydrogenophilalia	Hydrogenophilales	NA	NA	NA	1	0
1798491	NA	Candidatus Kaiserbacteria	NA	NA	NA	NA	Candidatus Kaiserbacteria bacterium RIFCSPHIGHO2_02_FULL_49_34	1	0
1798532	NA	Candidatus Kaiserbacteria	NA	NA	NA	NA	Candidatus Kaiserbacteria bacterium RIFOXYD1_FULL_42_15	1	0
1799655	NA	Proteobacteria	Alphaproteobacteria	Micropepsales	Micropepsaceae	Rhizomicrobium	Rhizomicrobium sp. SCGC AG-212-E05	1	0
180088	Fungi	Basidiomycota	Agaricomycetes	Boletales	Rhizopogonaceae	Rhizopogon	Rhizopogon vesiculosus	4	0
1801639	NA	Candidatus Moranbacteria	NA	NA	NA	NA	Candidatus Moranbacteria bacterium RIFCSPHIGHO2_02_FULL_40_12b	2	0
1801952	NA	Planctomycetes	NA	NA	NA	NA	Planctomycetes bacterium GWC2_45_44	2	0
1801957	NA	Planctomycetes	NA	NA	NA	NA	Planctomycetes bacterium GWF2_41_51	2	0
180197	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Comamonadaceae	Giesbergeria	Giesbergeria anulus	3	0
1802030	NA	Candidatus Roizmanbacteria	NA	NA	NA	NA	Candidatus Roizmanbacteria bacterium RIFCSPHIGHO2_01_FULL_39_12b	1	0
1802176	NA	Spirochaetes	NA	NA	NA	NA	Spirochaetes bacterium GWB1_59_5	1	0
1802368	NA	Candidatus Terrybacteria	NA	NA	NA	NA	Candidatus Terrybacteria bacterium RIFCSPLOWO2_01_FULL_48_14	1	0
1804758	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. CB03911	1	0
1804984	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Burkholderiaceae	Burkholderia	Burkholderia sp. OLGA172	1	0
1805075	NA	Chloroflexi	NA	NA	NA	NA	Chloroflexi bacterium 13_1_40CM_4_65_16	1	0
1805265	NA	Nitrospirae	NA	NA	NA	NA	Nitrospirae bacterium 13_1_40CM_2_62_10	1	0
1805496	NA	NA	NA	NA	NA	Moramonas	Moramonas marocensis	1	0
1806505	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Alcaligenaceae	Achromobacter	Achromobacter sp. 2789STDY5608618	1	0
1806885	NA	Proteobacteria	Alphaproteobacteria	Sphingomonadales	Sphingomonadaceae	Sphingorhabdus	Sphingorhabdus sp. M41	1	0
1813822	Fungi	NA	NA	NA	NA	NA	fungal sp. No.14919	1	0
1817	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Nocardiaceae	Nocardia	NA	2	0
1822464	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Burkholderiaceae	Paraburkholderia	NA	1	0
182411	NA	Firmicutes	Clostridia	Clostridiales	Proteinivoraceae	Anaerobranca	Anaerobranca californiensis	1	0
1827	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Nocardiaceae	Rhodococcus	NA	2	0
182899	NA	Aquificae	Aquificae	Aquificales	Hydrogenothermaceae	Persephonella	NA	1	0
1830	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Nocardiaceae	Rhodococcus	Rhodococcus ruber	1	0
1839759	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. DvalAA-14	1	0
1839780	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. MnatMP-M17	1	0
1839	NA	Actinobacteria	Actinobacteria	Propionibacteriales	Nocardioidaceae	Nocardioides	NA	1	0
1842532	NA	Proteobacteria	Deltaproteobacteria	Desulfuromonadales	Desulfuromonadaceae	Pelobacter	Pelobacter sp. SFB93	1	0
184870	NA	Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Varibaculum	Varibaculum cambriense	2	0
1848	NA	Actinobacteria	Actinobacteria	Pseudonocardiales	Pseudonocardiaceae	Pseudonocardia	Pseudonocardia thermophila	1	0
1849176	NA	Firmicutes	Clostridia	Clostridiales	Clostridiaceae	Clostridium	Clostridium sp. W14A	1	0
185291	NA	Bacteroidetes	Bacteroidia	Bacteroidales	NA	NA	NA	1	0
185431	NA	NA	NA	Kinetoplastida	Trypanosomatidae	Trypanosoma	Trypanosoma brucei	3	0
1854	NA	Actinobacteria	Actinobacteria	Frankiales	Frankiaceae	Frankia	NA	5	0
1855300	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Comamonadaceae	Polaromonas	Polaromonas sp. OV174	1	0
1855319	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	Bradyrhizobiaceae	Bradyrhizobium	Bradyrhizobium sp. Ghvi	1	0
1855325	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella sp. KH2C16	1	0
1855343	NA	Firmicutes	Clostridia	Clostridiales	Lachnospiraceae	Oribacterium	Oribacterium sp. WCC10	1	0
1855662	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Mycobacteriaceae	Mycobacterium	Mycobacterium sp. D16R12	2	0
1855728	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Comamonadaceae	Variovorax	Variovorax sp. KK3	1	0
185642	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Mycobacteriaceae	Mycobacterium	Mycobacterium parmense	1	0
185761	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium spheniscorum	1	0
1858794	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Mycobacteriaceae	Mycobacterium	Mycobacterium talmoniae	1	0
1858805	Fungi	Basidiomycota	Dacrymycetes	Dacrymycetales	Dacrymycetaceae	Dacryopinax	Dacryopinax primogenitus	4	0
1859694	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Haemophilus	Haemophilus sp. CCUG 66565	2	0
1862701	NA	NA	NA	Caudovirales	Myoviridae	Phikzvirus	Pseudomonas virus phiKZ	1	0
1865	NA	Actinobacteria	Actinobacteria	Micromonosporales	Micromonosporaceae	Actinoplanes	NA	1	0
186801	NA	Firmicutes	Clostridia	NA	NA	NA	NA	1	0
186802	NA	Firmicutes	Clostridia	Clostridiales	NA	NA	NA	15	0
186803	NA	Firmicutes	Clostridia	Clostridiales	Lachnospiraceae	NA	NA	135	0
186822	NA	Firmicutes	Bacilli	Bacillales	Paenibacillaceae	NA	NA	1	0
186826	NA	Firmicutes	Bacilli	Lactobacillales	NA	NA	NA	14	0
1869	NA	Actinobacteria	Actinobacteria	Micromonosporales	Micromonosporaceae	Actinoplanes	Actinoplanes utahensis	1	0
1870995	NA	Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Actinotignum	Actinotignum timonense	30	0
1871012	NA	Firmicutes	Clostridia	Clostridiales	Clostridiales Family XIII. Incertae Sedis	Mobilibacterium	Mobilibacterium timonense	1	0
1871017	NA	Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Peptoniphilus	Peptoniphilus urinimassiliensis	2	0
1871034	NA	Actinobacteria	Actinobacteria	Propionibacteriales	Propionibacteriaceae	Propionimicrobium	Propionimicrobium sp. Marseille-P3275	3	0
1871037	NA	Bacteroidetes	Flavobacteriia	Flavobacteriales	Flavobacteriaceae	NA	Flavobacteriaceae bacterium	1	0
1872629	NA	Proteobacteria	Epsilonproteobacteria	Campylobacterales	Campylobacteraceae	Arcobacter	Arcobacter sp.	1	0
1873	NA	Actinobacteria	Actinobacteria	Micromonosporales	Micromonosporaceae	Micromonospora	NA	2	0
1877	NA	Actinobacteria	Actinobacteria	Micromonosporales	Micromonosporaceae	Micromonospora	Micromonospora echinospora	1	0
1879031	NA	Proteobacteria	Gammaproteobacteria	Alteromonadales	Alteromonadaceae	Marinobacter	Marinobacter sp. AC-23	1	0
1881057	NA	Actinobacteria	Actinobacteria	Kineosporiales	Kineosporiaceae	Quadrisphaera	Quadrisphaera sp. DSM 44207	1	0
1883	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	NA	32	0
1884352	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	NA	NA	Rhizobiales bacterium GAS113	1	0
1884358	NA	Firmicutes	Bacilli	Bacillales	Bacillaceae	Psychrobacillus	Psychrobacillus sp. OK032	1	0
1884633	Fungi	Basidiomycota	Tremellomycetes	Tremellales	Cryptococcaceae	NA	NA	2	0
1885573	NA	Actinobacteria	Actinobacteria	Pseudonocardiales	Pseudonocardiaceae	Pseudonocardia	Pseudonocardia sp. Ae717_Ps2	1	0
1888890	NA	Bacteroidetes	Flavobacteriia	Flavobacteriales	Flavobacteriaceae	Cellulophaga	Cellulophaga sp. W5C	1	0
1888	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces albus	1	0
1889	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces ambofaciens	1	0
1890286	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. LUP47B	1	0
1890302	NA	Firmicutes	Bacilli	Bacillales	Bacillaceae	Bacillus	Bacillus wiedmannii	3	0
1891184	NA	Proteobacteria	Gammaproteobacteria	Vibrionales	Vibrionaceae	Thaumasiovibrio	Thaumasiovibrio occultus	1	0
1891207	NA	Proteobacteria	Gammaproteobacteria	Vibrionales	Vibrionaceae	Thaumasiovibrio	Thaumasiovibrio subtropicus	1	0
1891920	NA	Actinobacteria	Actinobacteria	Micrococcales	Microbacteriaceae	Curtobacterium	Curtobacterium sp. ER1/6	1	0
189426	NA	Firmicutes	Bacilli	Bacillales	Paenibacillaceae	Paenibacillus	Paenibacillus odorifer	11	0
1895746	NA	Firmicutes	Clostridia	Clostridiales	NA	NA	Clostridiales bacterium 38-18	1	0
1895792	NA	Actinobacteria	Actinobacteria	Micrococcales	NA	NA	Micrococcales bacterium 73-15	2	0
1895826	NA	Proteobacteria	Alphaproteobacteria	Rhodospirillales	NA	NA	Rhodospirillales bacterium 70-18	1	0
1895839	NA	Bacteroidetes	Sphingobacteriia	Sphingobacteriales	NA	NA	Sphingobacteriales bacterium 46-32	1	0
189622	NA	Apicomplexa	Aconoidasida	NA	Babesiidae	Babesia	Babesia ovata	10	0
1896965	NA	Proteobacteria	Alphaproteobacteria	Rhodospirillales	Acetobacteraceae	Acetobacter	Acetobacter sp. 46_36	1	0
1896974	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Bacteroidaceae	Bacteroides	Bacteroides sp. 43_108	1	0
1896989	NA	Firmicutes	Clostridia	Clostridiales	Clostridiaceae	Clostridium	Clostridium sp. CAG:354_28_25	1	0
1897043	NA	Firmicutes	Clostridia	Clostridiales	NA	NA	Clostridiales bacterium 41_12_two_minus	1	0
189722	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella marshii	1	0
189723	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella micans	1	0
1898112	NA	Proteobacteria	Alphaproteobacteria	Rhodospirillales	Rhodospirillaceae	NA	Rhodospirillaceae bacterium	1	0
190146	NA	Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Actinotignum	Actinotignum urinale	2	0
1903186	NA	Actinobacteria	Actinobacteria	Micrococcales	Dermabacteraceae	Brachybacterium	Brachybacterium sp. P6-10-X1	1	0
1903	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces corchorusii	1	0
1904961	NA	Actinobacteria	Actinobacteria	Streptosporangiales	Thermomonosporaceae	Actinomadura	Actinomadura sp. CNU-125	1	0
1904965	NA	Actinobacteria	Actinobacteria	Streptosporangiales	Nocardiopsaceae	Nocardiopsis	Nocardiopsis sp. CNR-923	1	0
1906744	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Rodentibacter	Rodentibacter heylii	2	0
1906745	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Rodentibacter	Rodentibacter ratti	1	0
1906	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces fradiae	1	0
1907391	NA	Actinobacteria	Actinobacteria	Micrococcales	Microbacteriaceae	Microbacterium	Microbacterium sp. RURRCA19A	1	0
1908257	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Rodentibacter	Rodentibacter mrazii	1	0
1908260	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Rodentibacter	Rodentibacter rarus	1	0
1908264	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Rodentibacter	Rodentibacter genomosp. 1	3	0
1908266	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Rodentibacter	Rodentibacter genomosp. 2	1	0
1908690	NA	Planctomycetes	Planctomycetia	Planctomycetales	Gemmataceae	Fimbriiglobus	Fimbriiglobus ruber	2	0
1911079	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	Methylocystaceae	Methylocystis	Methylocystis sp.	1	0
1911	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces griseus	1	0
1912795	NA	Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Actinomyces	Actinomyces sp. VUL4_3	1	0
1912856	NA	Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Peptoniphilus	Peptoniphilus sp. ING2-D1G	1	0
1913988	NA	Proteobacteria	Alphaproteobacteria	NA	NA	NA	Alphaproteobacteria bacterium	1	0
1913989	NA	Proteobacteria	Gammaproteobacteria	NA	NA	NA	Gammaproteobacteria bacterium	3	0
191610	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium atypicum	1	0
1917019	NA	Firmicutes	Bacilli	Bacillales	Bacillaceae	Bacillus	Bacillus sp. VT-16-64	1	0
1917481	NA	Proteobacteria	Gammaproteobacteria	Methylococcales	Methylococcaceae	NA	Methylococcaceae bacterium NSP1-2	1	0
1917878	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella ihumii	4	0
1919	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces microflavus	1	0
1920113	NA	Proteobacteria	Gammaproteobacteria	Aeromonadales	Aeromonadaceae	Aeromonas	Aeromonas sp. ASNIH8	3	0
192073	NA	Proteobacteria	Gammaproteobacteria	Alteromonadales	Shewanellaceae	Shewanella	Shewanella denitrificans	1	0
1924934	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	NA	Pasteurellaceae bacterium 15-036681	1	0
192584	NA	NA	NA	NA	Baculoviridae	Betabaculovirus	Phthorimaea operculella granulovirus	1	0
1928334	NA	Proteobacteria	Alphaproteobacteria	Rhodobacterales	Rhodobacteraceae	NA	Rhodobacteraceae bacterium WFHF2C18	1	0
192	NA	Proteobacteria	Alphaproteobacteria	Rhodospirillales	Rhodospirillaceae	Azospirillum	Azospirillum brasilense	1	0
1933029	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. ZL-24	1	0
1934250	NA	Proteobacteria	Deltaproteobacteria	Desulfobacterales	Desulfobulbaceae	NA	Desulfobulbaceae bacterium A2	1	0
193462	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces niveus	2	0
1938600	NA	Proteobacteria	Gammaproteobacteria	Alteromonadales	Pseudoalteromonadaceae	Pseudoalteromonas	Pseudoalteromonas sp. TB64	1	0
1938847	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. 4121.5	2	0
1938849	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. Ag109_G2-1	1	0
1938954	Fungi	Mucoromycota	NA	Endogonales	NA	Bifiguratus	Bifiguratus adelaidae	1	0
1938	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces viridochromogenes	1	0
194326	NA	Firmicutes	Bacilli	Lactobacillales	Lactobacillaceae	Lactobacillus	Lactobacillus versmoldensis	1	0
1943582	NA	Cyanobacteria	NA	Synechococcales	Synechococcaceae	Synechococcus	Candidatus Synechococcus spongiarum	2	0
194	NA	Proteobacteria	Epsilonproteobacteria	Campylobacterales	Campylobacteraceae	Campylobacter	NA	203	0
1960084	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Rodentibacter	NA	6	0
196109	Fungi	Ascomycota	Sordariomycetes	Xylariales	Microdochiaceae	Microdochium	Microdochium bolleyi	3	0
1962290	NA	Cyanobacteria	NA	Synechococcales	Leptolyngbyaceae	Leptolyngbya	Leptolyngbya ohadii	3	0
1964395	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Mycobacteriaceae	Mycobacterium	Mycobacterium sp. AFP003	2	0
1965562	NA	Firmicutes	Clostridia	Clostridiales	Lachnospiraceae	Lachnoclostridium	Lachnoclostridium sp. An14	1	0
1965564	NA	Firmicutes	Erysipelotrichia	Erysipelotrichales	Erysipelotrichaceae	Massiliomicrobiota	Massiliomicrobiota sp. An142	1	0
1965632	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Bacteroidaceae	Bacteroides	Bacteroides sp. An322	1	0
1969111	NA	Firmicutes	Bacilli	Bacillales	Paenibacillaceae	Paenibacillus	Paenibacillus sp. 32352	1	0
196914	NA	Actinobacteria	Actinobacteria	Micromonosporales	Micromonosporaceae	Actinoplanes	Actinoplanes friuliensis	1	0
1969835	NA	Firmicutes	Clostridia	Clostridiales	Peptococcaceae	Desulfosporosinus	Desulfosporosinus sp. FKB	1	0
196	NA	Proteobacteria	Epsilonproteobacteria	Campylobacterales	Campylobacteraceae	Campylobacter	Campylobacter fetus	3	0
1970199	NA	Proteobacteria	Deltaproteobacteria	Myxococcales	NA	NA	Sorangiineae bacterium NIC37A_2	1	0
1970550	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	NA	NA	Rhizobiales bacterium 32-66-8	1	0
1970778	NA	Bacteroidetes	NA	NA	NA	NA	Bacteroidetes bacterium 4484_249	1	0
1973486	NA	Cyanobacteria	NA	Nostocales	Rivulariaceae	Calothrix	Calothrix parasitica	1	0
1973896	NA	Proteobacteria	Alphaproteobacteria	NA	NA	NA	Alphaproteobacteria bacterium CG_4_10_14_0_2_um_filter_63_37	1	0
1973905	NA	Chloroflexi	Anaerolineae	NA	NA	NA	Anaerolineae bacterium CG03_land_8_20_14_0_80_58_20	1	0
1973927	NA	Proteobacteria	Oligoflexia	Bdellovibrionales	NA	NA	Bdellovibrionales bacterium CG10_big_fil_rev_8_21_14_0_10_45_34	1	0
1974566	NA	Candidatus Falkowbacteria	NA	NA	NA	NA	Candidatus Falkowbacteria bacterium CG10_big_fil_rev_8_21_14_0_10_39_9	1	0
1974858	NA	Candidatus Roizmanbacteria	NA	NA	NA	NA	Candidatus Roizmanbacteria bacterium CG17_big_fil_post_rev_8_21_14_2_50_39_7	1	0
1975524	NA	Candidatus Marinimicrobia	NA	NA	NA	NA	Candidatus Marinimicrobia bacterium CG08_land_8_20_14_0_20_45_22	1	0
197575	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Haemophilus	Haemophilus aegyptius	5	0
1977277	NA	Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Anaerococcus	Anaerococcus sp. Marseille-P3625	2	0
1977882	NA	Proteobacteria	Gammaproteobacteria	Pseudomonadales	Moraxellaceae	Acinetobacter	Acinetobacter sp. ANC 4999	1	0
1979527	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium kefirresidentii	3	0
1982044	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	Phyllobacteriaceae	NA	Phyllobacteriaceae bacterium X9-2-2	1	0
198252	NA	Proteobacteria	Alphaproteobacteria	Pelagibacterales	Pelagibacteraceae	Candidatus Pelagibacter	Candidatus Pelagibacter ubique	1	0
1983803	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. SM13	1	0
1985876	NA	Proteobacteria	Gammaproteobacteria	Enterobacterales	Enterobacteriaceae	Escherichia	Escherichia sp. ESNIH1	1	0
1986670	NA	Bacteroidetes	Saprospiria	Saprospirales	NA	NA	Saprospirales bacterium TMED214	1	0
1986681	NA	Bacteroidetes	Cytophagia	Cytophagales	Flammeovirgaceae	NA	Flammeovirgaceae bacterium TMED32	1	0
1986840	NA	Proteobacteria	Gammaproteobacteria	Cellvibrionales	NA	NA	Cellvibrionales bacterium TMED148	1	0
198730	Fungi	Ascomycota	Eurotiomycetes	Eurotiales	Trichocomaceae	Talaromyces	Talaromyces verruculosus	1	0
1	NA	NA	NA	NA	NA	NA	NA	10	0
2002	NA	Actinobacteria	Actinobacteria	Streptosporangiales	Streptosporangiaceae	Streptosporangium	Streptosporangium amethystogenes	2	0
200324	Fungi	Basidiomycota	Pucciniomycetes	Pucciniales	Pucciniaceae	Puccinia	Puccinia coronata	1	0
2003629	NA	Bacteroidetes	Sphingobacteriia	Sphingobacteriales	Sphingobacteriaceae	Pedobacter	Pedobacter sp. AJM	1	0
200378	NA	Actinobacteria	Actinobacteria	Pseudonocardiales	Pseudonocardiaceae	Lechevalieria	Lechevalieria fradiae	1	0
2004951	Fungi	Ascomycota	Sordariomycetes	Hypocreales	Cordycipitaceae	Cordyceps	Cordyceps sp. RAO-2017	2	0
2004952	Fungi	Ascomycota	Sordariomycetes	Hypocreales	Ophiocordycipitaceae	Ophiocordyceps	Ophiocordyceps camponoti-rufipedis	1	0
2005464	NA	Cyanobacteria	NA	Nostocales	Scytonemataceae	Scytonema	Scytonema sp. NIES-4073	1	0
200643	NA	Bacteroidetes	Bacteroidia	NA	NA	NA	NA	8	0
200795	NA	Chloroflexi	NA	NA	NA	NA	NA	1	0
2009329	NA	Proteobacteria	Alphaproteobacteria	Rhodobacterales	Rhodobacteraceae	Sagittula	Sagittula sp. P11	1	0
201089	NA	Proteobacteria	Deltaproteobacteria	Desulfobacterales	Desulfobacteraceae	Desulfobacterium	uncultured Desulfobacterium sp.	1	0
201174	NA	Actinobacteria	NA	NA	NA	NA	NA	19	0
2013686	NA	Bacteroidetes	NA	NA	NA	NA	Bacteroidetes bacterium HGW-Bacteroidetes-18	1	0
2013701	NA	Proteobacteria	Betaproteobacteria	NA	NA	NA	Betaproteobacteria bacterium HGW-Betaproteobacteria-10	1	0
2013718	NA	Proteobacteria	Betaproteobacteria	NA	NA	NA	Betaproteobacteria bacterium HGW-Betaproteobacteria-6	1	0
2013723	NA	Chloroflexi	NA	NA	NA	NA	Chloroflexi bacterium HGW-Chloroflexi-1	1	0
2013851	NA	Tenericutes	NA	NA	NA	NA	Tenericutes bacterium HGW-Tenericutes-8	1	0
2013866	NA	Proteobacteria	Gammaproteobacteria	Alteromonadales	Ferrimonadaceae	Paraferrimonas	Paraferrimonas haliotis	1	0
2014065	NA	Planctomycetes	Planctomycetia	Planctomycetales	Planctomycetaceae	Rhodopirellula	Rhodopirellula bahusiensis	1	0
2014310	NA	Elusimicrobia	NA	NA	NA	NA	Elusimicrobia bacterium CG08_land_8_20_14_0_20_59_10	2	0
2014528	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium sp. Marseille-P4122	1	0
2015568	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	NA	NA	Burkholderiales bacterium PBB6	1	0
2017	NA	Actinobacteria	Actinobacteria	Pseudonocardiales	Pseudonocardiaceae	Streptoalloteichus	Streptoalloteichus hindustanus	1	0
2018025	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Kitasatospora	Kitasatospora sp. MMS16-BH015	1	0
2019	NA	Actinobacteria	Actinobacteria	Streptosporangiales	Thermomonosporaceae	Thermomonospora	NA	1	0
2024223	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella sp. P3-122	1	0
2024580	NA	Actinobacteria	Actinobacteria	Micromonosporales	Micromonosporaceae	Plantactinospora	Plantactinospora sp. KBS50	3	0
2025039	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Lactococcus	Lactococcus reticulitermitis	1	0
2026724	NA	Chloroflexi	NA	NA	NA	NA	Chloroflexi bacterium	3	0
2026785	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	Rhodobiaceae	NA	Rhodobiaceae bacterium	1	0
202789	NA	Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Actinobaculum	Actinobaculum massiliense	13786	0
202956	NA	Proteobacteria	Gammaproteobacteria	Pseudomonadales	Moraxellaceae	Acinetobacter	Acinetobacter towneri	1	0
2030880	NA	Proteobacteria	Gammaproteobacteria	NA	NA	NA	SAR86 cluster bacterium	2	0
2030	NA	Actinobacteria	Actinobacteria	Pseudonocardiales	Pseudonocardiaceae	Kibdelosporangium	Kibdelosporangium aridum	1	0
203133	NA	Actinobacteria	Actinobacteria	Propionibacteriales	Propionibacteriaceae	Propionimicrobium	NA	2725	0
203267	NA	Actinobacteria	Actinobacteria	Micrococcales	NA	Tropheryma	Tropheryma whipplei	1	0
2033435	NA	Proteobacteria	Alphaproteobacteria	Rhodobacterales	Rhodobacteraceae	NA	Rhodobacteraceae bacterium QY30	1	0
2033654	NA	Actinobacteria	Actinobacteria	Micrococcales	Microbacteriaceae	Curtobacterium	Curtobacterium sp. 'Ferrero'	2	0
2033	NA	Actinobacteria	Actinobacteria	Micrococcales	Microbacteriaceae	Microbacterium	Microbacterium testaceum	2	0
2035218	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. 94	1	0
2035219	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. 93	1	0
2035249	NA	Actinobacteria	Actinobacteria	Micromonosporales	Micromonosporaceae	Verrucosispora	Verrucosispora sp. CNZ293	1	0
2036	NA	Actinobacteria	Actinobacteria	Micrococcales	Microbacteriaceae	Curtobacterium	Curtobacterium citreum	1	0
2037	NA	Actinobacteria	Actinobacteria	Actinomycetales	NA	NA	NA	1	0
2038116	NA	Cyanobacteria	NA	Nostocales	Nostocaceae	Nostoc	Nostoc flagelliforme	1	0
204429	NA	Chlamydiae	Chlamydiia	NA	NA	NA	NA	1	0
2044729	NA	Bacteroidetes	Cytophagia	Cytophagales	Cytophagaceae	Candidatus Nephrothrix	Candidatus Nephrothrix sp. EaCA	1	0
2047	NA	Actinobacteria	Actinobacteria	Micrococcales	Micrococcaceae	Rothia	Rothia dentocariosa	43	0
2049	NA	Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	NA	NA	2114	0
2051	NA	Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Mobiluncus	Mobiluncus curtisii	1	0
2053305	NA	Bacteroidetes	Bacteroidia	Marinilabiliales	Salinivirgaceae	NA	Salinivirgaceae bacterium	1	0
2053	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Gordoniaceae	Gordonia	NA	1	0
2054903	NA	Deinococcus-Thermus	Deinococci	Deinococcales	Deinococcaceae	Deinococcus	Deinococcus sp. SJW1-2	1	0
2054913	NA	Firmicutes	Bacilli	Bacillales	Bacillaceae	Bacillus	Bacillus sp. mrc49	1	0
205914	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Histophilus	Histophilus somni	2	0
206096	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Dysgonamonadaceae	Dysgonomonas	uncultured Dysgonomonas sp.	1	0
2062	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	NA	NA	1	0
2066054	NA	Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Actinomyces	Actinomyces sp. UMB0138	3	0
2066	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Kitasatospora	Kitasatospora setae	1	0
2069309	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus sp. UMB1385	2	0
2069311	NA	Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Actinomyces	Actinomyces sp. UMB0918	2	0
206	NA	Proteobacteria	Epsilonproteobacteria	Campylobacterales	Campylobacteraceae	Campylobacter	Campylobacter sputorum	4	0
2070341	NA	Firmicutes	Bacilli	Bacillales	Bacillaceae	Bacillus	Bacillus sp. UFRGS-B20	1	0
2070	NA	Actinobacteria	Actinobacteria	Pseudonocardiales	Pseudonocardiaceae	NA	NA	4	0
2071	NA	Actinobacteria	Actinobacteria	Pseudonocardiales	Pseudonocardiaceae	Saccharothrix	NA	1	0
2072509	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. DH-12	1	0
2074	NA	Actinobacteria	Actinobacteria	Pseudonocardiales	Pseudonocardiaceae	Pseudonocardia	Pseudonocardia autotrophica	2	0
2080747	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. Ru72	2	0
208479	NA	Firmicutes	Clostridia	Clostridiales	Lachnospiraceae	Lachnoclostridium	[Clostridium] bolteae	1	0
208962	NA	Proteobacteria	Gammaproteobacteria	Enterobacterales	Enterobacteriaceae	Escherichia	Escherichia albertii	1	0
2092	NA	Tenericutes	Mollicutes	Mycoplasmatales	Mycoplasmataceae	NA	NA	2	0
210408	NA	Proteobacteria	Gammaproteobacteria	Chromatiales	Chromatiaceae	Thiorhodococcus	Thiorhodococcus drewsii	1	0
210	NA	Proteobacteria	Epsilonproteobacteria	Campylobacterales	Helicobacteraceae	Helicobacter	Helicobacter pylori	5	0
211114	NA	Actinobacteria	Actinobacteria	Pseudonocardiales	Pseudonocardiaceae	Allokutzneria	Allokutzneria albata	2	0
212774	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. EN23	1	0
2129	NA	Tenericutes	Mollicutes	Mycoplasmatales	Mycoplasmataceae	Ureaplasma	NA	608	0
2130	NA	Tenericutes	Mollicutes	Mycoplasmatales	Mycoplasmataceae	Ureaplasma	Ureaplasma urealyticum	2043	0
213223	NA	Proteobacteria	Deltaproteobacteria	Desulfuromonadales	Geobacteraceae	Geothermobacter	NA	1	0
213849	NA	Proteobacteria	Epsilonproteobacteria	Campylobacterales	NA	NA	NA	15	0
215243	Fungi	Ascomycota	Eurotiomycetes	Chaetothyriales	Herpotrichiellaceae	Exophiala	Exophiala oligosperma	1	0
2157	NA	NA	NA	NA	NA	NA	NA	1	0
220687	NA	Firmicutes	Bacilli	Bacillales	Bacillaceae	Bacillus	Bacillus novalis	1	0
221103	Fungi	Basidiomycota	Agaricomycetes	Agaricales	Marasmiaceae	Moniliophthora	Moniliophthora roreri	2	0
221822	NA	Proteobacteria	Alphaproteobacteria	Rhodobacterales	Rhodobacteraceae	Phaeobacter	Phaeobacter inhibens	1	0
221988	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Basfia	[Mannheimia] succiniciproducens	7	0
222	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Alcaligenaceae	Achromobacter	NA	1	0
223184	NA	Actinobacteria	Actinobacteria	Micrococcales	Micrococcaceae	Kocuria	Kocuria marina	1	0
224013	NA	Cyanobacteria	NA	Nostocales	Nostocaceae	Nostoc	Nostoc piscinale	1	0
2248	NA	Euryarchaeota	Halobacteria	Haloferacales	Halorubraceae	Halorubrum	Halorubrum saccharovorum	15	0
225359	Fungi	Ascomycota	Leotiomycetes	Erysiphales	Erysiphaceae	Erysiphe	Erysiphe pulchra	2	0
225849	NA	Proteobacteria	Gammaproteobacteria	Alteromonadales	Shewanellaceae	Shewanella	Shewanella piezotolerans	1	0
227290	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	Rhizobiaceae	NA	NA	1	0
227321	Fungi	Ascomycota	Eurotiomycetes	Eurotiales	Aspergillaceae	Aspergillus	Aspergillus nidulans	1	0
228603	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella shahii	1	0
233412	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Haemophilus	[Haemophilus] ducreyi	2	0
234	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	Brucellaceae	Brucella	NA	1	0
235	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	Brucellaceae	Brucella	Brucella abortus	1	0
2371	NA	Proteobacteria	Gammaproteobacteria	Xanthomonadales	Xanthomonadaceae	Xylella	Xylella fastidiosa	2	0
240427	NA	Firmicutes	Bacilli	Lactobacillales	Lactobacillaceae	Lactobacillus	Lactobacillus paracollinoides	1	0
2422	NA	Thermotogae	Thermotogae	Thermotogales	Fervidobacteriaceae	Fervidobacterium	NA	1	0
242750	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella bergensis	2	0
245562	Fungi	Ascomycota	Dothideomycetes	NA	NA	Acidomyces	Acidomyces richmondensis	5	0
246196	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Mycobacteriaceae	Mycobacterium	Mycobacterium smegmatis	1	0
247490	NA	Planctomycetes	Planctomycetia	Candidatus Brocadiales	Candidatus Brocadiaceae	Candidatus Jettenia	Candidatus Jettenia caeni	2	0
247634	NA	Proteobacteria	Gammaproteobacteria	Cellvibrionales	Halieaceae	NA	marine gamma proteobacterium HTCC2148	1	0
249350	Viridiplantae	Chlorophyta	Trebouxiophyceae	NA	NA	Paradoxia	Paradoxia multiseta	1	0
253244	NA	Bacteroidetes	Flavobacteriia	Flavobacteriales	Cryomorphaceae	NA	NA	1	0
253628	Fungi	Ascomycota	Dothideomycetes	Venturiales	Sympoventuriaceae	Verruconis	Verruconis gallopava	1	0
260936	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Nocardiaceae	Rhodococcus	Rhodococcus sp. RD6.2	7	0
261292	NA	Proteobacteria	Betaproteobacteria	Nitrosomonadales	Nitrosomonadaceae	Nitrosomonas	Nitrosomonas sp. Is79A3	1	0
261658	NA	NA	NA	Acytosteliales	Cavenderiaceae	Cavenderia	Cavenderia fasciculata	3	0
262727	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Haemophilus	Haemophilus influenzae	3	0
263910	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Nocardiaceae	Nocardia	Nocardia anaemiae	1	0
265948	NA	Firmicutes	Bacilli	Bacillales	Bacillaceae	Anoxybacillus	Anoxybacillus tepidamans	1	0
266762	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Porphyromonadaceae	Porphyromonas	Porphyromonas gingivicanis	5	0
267410	NA	Firmicutes	Bacilli	Bacillales	Listeriaceae	Listeria	Listeria monocytogenes	1	0
269800	NA	Actinobacteria	Actinobacteria	Streptosporangiales	Nocardiopsaceae	Thermobifida	Thermobifida fusca	1	0
2702	NA	Actinobacteria	Actinobacteria	Bifidobacteriales	Bifidobacteriaceae	Gardnerella	Gardnerella vaginalis	4	0
271	NA	Deinococcus-Thermus	Deinococci	Thermales	Thermaceae	Thermus	Thermus aquaticus	1	0
272239	NA	Actinobacteria	Actinobacteria	Micrococcales	Microbacteriaceae	Pseudoclavibacter	Pseudoclavibacter bifida	1	0
272556	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Aggregatibacter	Aggregatibacter actinomycetemcomitans	2	0
272629	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Mannheimia	Mannheimia haemolytica	12	0
272843	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Pasteurella	Pasteurella multocida	2	0
273119	NA	Tenericutes	Mollicutes	Mycoplasmatales	Mycoplasmataceae	Ureaplasma	Ureaplasma parvum	3	0
27349	Fungi	Basidiomycota	Pucciniomycetes	Pucciniales	Pucciniaceae	Puccinia	Puccinia sorghi	4	0
2734	NA	Firmicutes	Clostridia	Clostridiales	Symbiobacteriaceae	Symbiobacterium	Symbiobacterium thermophilum	10	0
2736	NA	Verrucomicrobia	Verrucomicrobiae	Verrucomicrobiales	Verrucomicrobiaceae	Verrucomicrobium	Verrucomicrobium spinosum	1	0
2745	NA	Proteobacteria	Gammaproteobacteria	Oceanospirillales	Halomonadaceae	Halomonas	NA	1	0
2759	NA	NA	NA	NA	NA	NA	NA	48	0
2786	NA	NA	Bangiophyceae	Bangiales	Bangiaceae	Porphyra	Porphyra umbilicalis	6	0
278961	NA	Acidobacteria	Acidobacteriia	Acidobacteriales	Acidobacteriaceae	Terriglobus	Terriglobus sp. TAA 43	1	0
279215	NA	Firmicutes	Bacilli	Bacillales	Bacillaceae	Bacillus	Bacillus alveayuensis	1	0
279832	NA	Proteobacteria	Gammaproteobacteria	Cardiobacteriales	Cardiobacteriaceae	Suttonella	Suttonella ornithocola	2	0
28005	NA	NA	NA	Kinetoplastida	Trypanosomatidae	Strigomonas	Strigomonas culicis	2	0
28028	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium flavescens	3	0
280463	NA	NA	NA	Isochrysidales	Noelaerhabdaceae	Emiliania	Emiliania huxleyi	3	0
28051	NA	Firmicutes	Clostridia	Clostridiales	Lachnospiraceae	Lachnospira	Lachnospira multipara	1	0
280772	NA	Proteobacteria	Gammaproteobacteria	NA	NA	NA	methanotrophic bacterial endosymbiont of Bathymodiolus sp.	3	0
28092	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Burkholderiaceae	Robbsia	Robbsia andropogonis	1	0
28112	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Tannerellaceae	Tannerella	Tannerella forsythia	5	0
28123	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Porphyromonadaceae	Porphyromonas	Porphyromonas asaccharolytica	6	0
28124	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Porphyromonadaceae	Porphyromonas	Porphyromonas endodontalis	1	0
28125	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella bivia	10	0
28127	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella buccalis	2	0
28128	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella corporis	18	0
28129	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella denticola	1	0
28130	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella disiens	4060	0
281310	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Haemophilus	Haemophilus influenzae	2	0
28131	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella intermedia	5	0
28133	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella nigrescens	6	0
28134	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella oralis	2	0
28136	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella oulorum	3	0
28137	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella veroralis	1	0
28151	NA	Proteobacteria	Gammaproteobacteria	Enterobacterales	Yersiniaceae	Serratia	Serratia proteamaculans	1	0
28183	NA	Spirochaetes	Spirochaetia	NA	Leptospiraceae	Leptospira	Leptospira santarosai	1	0
28184	NA	Spirochaetes	Spirochaetia	NA	Leptospiraceae	Leptospira	Leptospira weilii	1	0
28188	NA	Bacteroidetes	Flavobacteriia	Flavobacteriales	Flavobacteriaceae	Capnocytophaga	Capnocytophaga canimorsus	1	0
281920	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Porphyromonadaceae	Porphyromonas	Porphyromonas uenonis	11	0
28211	NA	Proteobacteria	Alphaproteobacteria	NA	NA	NA	NA	3	0
28216	NA	Proteobacteria	Betaproteobacteria	NA	NA	NA	NA	3	0
282402	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella multiformis	1	0
28264	NA	Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Arcanobacterium	Arcanobacterium haemolyticum	4	0
28447	NA	Actinobacteria	Actinobacteria	Micrococcales	Microbacteriaceae	Clavibacter	Clavibacter michiganensis	1	0
28450	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Burkholderiaceae	Burkholderia	Burkholderia pseudomallei	12	0
28453	NA	Bacteroidetes	Sphingobacteriia	Sphingobacteriales	Sphingobacteriaceae	Sphingobacterium	NA	1	0
285473	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces rubrolavendulae	3	0
285514	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces xylophagus	1	0
285568	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces bungoensis	1	0
285679	NA	Actinobacteria	Actinobacteria	Micromonosporales	Micromonosporaceae	Micromonospora	Micromonospora lupini	2	0
286	NA	Proteobacteria	Gammaproteobacteria	Pseudomonadales	Pseudomonadaceae	Pseudomonas	NA	12	0
2880	NA	Phaeophyceae	NA	Ectocarpales	Ectocarpaceae	Ectocarpus	Ectocarpus siliculosus	1	0
28901	NA	Proteobacteria	Gammaproteobacteria	Enterobacterales	Enterobacteriaceae	Salmonella	Salmonella enterica	2	0
290052	NA	Firmicutes	Clostridia	Clostridiales	Ruminococcaceae	Acetivibrio	Acetivibrio ethanolgignens	1	0
292462	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Mycobacteriaceae	Mycobacterium	Mycobacterium florentinum	1	0
29290	NA	Nitrospirae	Nitrospira	Nitrospirales	Nitrospiraceae	Candidatus Magnetobacterium	Candidatus Magnetobacterium bavaricum	1	0
292	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Burkholderiaceae	Burkholderia	Burkholderia cepacia	1	0
293091	NA	Euryarchaeota	Halobacteria	Haloferacales	Haloferacaceae	Haloquadratum	Haloquadratum walsbyi	1	0
29367	NA	Firmicutes	Clostridia	Clostridiales	Clostridiaceae	Clostridium	Clostridium puniceum	1	0
29448	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	Bradyrhizobiaceae	Bradyrhizobium	Bradyrhizobium elkanii	1	0
29497	NA	Proteobacteria	Gammaproteobacteria	Vibrionales	Vibrionaceae	Vibrio	Vibrio splendidus	4	0
2951	NA	NA	Dinophyceae	Suessiales	Symbiodiniaceae	Symbiodinium	Symbiodinium microadriaticum	606	0
29529	NA	Bacteroidetes	Chitinophagia	Chitinophagales	Chitinophagaceae	Chitinophaga	Chitinophaga arvensicola	1	0
29542	NA	Proteobacteria	Deltaproteobacteria	Desulfuromonadales	Desulfuromonadaceae	Pelobacter	Pelobacter acetylenicus	1	0
29547	NA	Proteobacteria	Epsilonproteobacteria	NA	NA	NA	NA	13	0
29833	Fungi	Ascomycota	Saccharomycetes	Saccharomycetales	Saccharomycodaceae	Hanseniaspora	Hanseniaspora uvarum	1	0
29845	Fungi	Ascomycota	Eurotiomycetes	Eurotiales	Aspergillaceae	Penicillium	Penicillium vulpinum	1	0
29907	Fungi	Ascomycota	Sordariomycetes	Ophiostomatales	Ophiostomataceae	Sporothrix	NA	2	0
2	NA	NA	NA	NA	NA	NA	NA	16935	0
300876	NA	Proteobacteria	Gammaproteobacteria	Vibrionales	Vibrionaceae	Vibrio	Vibrio europaeus	1	0
303	NA	Proteobacteria	Gammaproteobacteria	Pseudomonadales	Pseudomonadaceae	Pseudomonas	Pseudomonas putida	2	0
3055	Viridiplantae	Chlorophyta	Chlorophyceae	Chlamydomonadales	Chlamydomonadaceae	Chlamydomonas	Chlamydomonas reinhardtii	10	0
306263	NA	Proteobacteria	Epsilonproteobacteria	Campylobacterales	Campylobacteraceae	Campylobacter	Campylobacter lari	2	0
3068	Viridiplantae	Chlorophyta	Chlorophyceae	Chlamydomonadales	Volvocaceae	Volvox	Volvox carteri	105	0
307249	NA	Firmicutes	Negativicutes	Selenomonadales	Sporomusaceae	Sporomusa	uncultured Sporomusa sp.	1	0
3075	Viridiplantae	Chlorophyta	Trebouxiophyceae	Chlorellales	Chlorellaceae	Auxenochlorella	Auxenochlorella protothecoides	1	0
309801	NA	Chloroflexi	Thermomicrobia	Thermomicrobiales	Thermomicrobiaceae	Thermomicrobium	Thermomicrobium roseum	1	0
310298	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Bacteroidaceae	Bacteroides	Bacteroides coprocola	2	0
310514	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella multisaccharivorax	2	0
310779	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces yanglinensis	1	0
312017	NA	NA	Oligohymenophorea	Hymenostomatida	Tetrahymenidae	Tetrahymena	Tetrahymena thermophila	1	0
312540	NA	Euryarchaeota	Thermoplasmata	Thermoplasmatales	Ferroplasmaceae	Acidiplasma	Acidiplasma cupricumulans	1	0
31271	NA	Apicomplexa	Aconoidasida	Haemosporida	Plasmodiidae	Plasmodium	Plasmodium chabaudi	25	0
314275	NA	Proteobacteria	Gammaproteobacteria	Alteromonadales	Alteromonadaceae	Alteromonas	Alteromonas mediterranea	1	0
314276	NA	Proteobacteria	Gammaproteobacteria	Alteromonadales	Idiomarinaceae	Idiomarina	Idiomarina baltica	1	0
316330	NA	Actinobacteria	Actinobacteria	Streptosporangiales	Streptosporangiaceae	Microbispora	Microbispora sp. ATCC PTA-5024	1	0
317013	NA	Proteobacteria	Gammaproteobacteria	Xanthomonadales	Xanthomonadaceae	Xanthomonas	Xanthomonas phaseoli	1	0
31957	NA	Actinobacteria	Actinobacteria	Propionibacteriales	Propionibacteriaceae	NA	NA	18	0
31962	NA	Actinobacteria	Actinobacteria	Streptosporangiales	Thermomonosporaceae	Actinomadura	Actinomadura rifamycini	1	0
319705	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Mycobacteriaceae	Mycobacterium	Mycobacterium abscessus	1	0
319	NA	Proteobacteria	Gammaproteobacteria	Pseudomonadales	Pseudomonadaceae	Pseudomonas	Pseudomonas savastanoi	4	0
32008	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Burkholderiaceae	Burkholderia	NA	3	0
32022	NA	Proteobacteria	Epsilonproteobacteria	Campylobacterales	Campylobacteraceae	Campylobacter	Campylobacter jejuni	3	0
321314	NA	Proteobacteria	Gammaproteobacteria	Enterobacterales	Enterobacteriaceae	Salmonella	Salmonella enterica	2	0
321318	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Dietziaceae	Dietzia	Dietzia cinnamea	43	0
321339	NA	Proteobacteria	Alphaproteobacteria	Rhodobacterales	Rhodobacteraceae	Citreimonas	Citreimonas salinaria	1	0
321763	NA	Firmicutes	Clostridia	Halanaerobiales	Halanaerobiaceae	Halarsenatibacter	Halarsenatibacter silvermanii	1	0
32207	NA	Actinobacteria	Actinobacteria	Micrococcales	Micrococcaceae	Rothia	NA	339	0
322095	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Porphyromonadaceae	Porphyromonas	Porphyromonas somerae	4699	0
322865	NA	Cyanobacteria	NA	Synechococcales	Leptolyngbyaceae	Leptolyngbya	Leptolyngbya valderiana	1	0
329046	Fungi	Chytridiomycota	Chytridiomycetes	Chytridiales	Chytriomycetaceae	Rhizoclosmatium	Rhizoclosmatium globosum	1	0
33007	NA	Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Actinomyces	Actinomyces neuii	25	0
330084	NA	Actinobacteria	Actinobacteria	Pseudonocardiales	Pseudonocardiaceae	Amycolatopsis	Amycolatopsis jejuensis	1	0
33012	NA	Actinobacteria	Actinobacteria	Propionibacteriales	Propionibacteriaceae	Propionimicrobium	Propionimicrobium lymphophilum	16	0
33029	NA	Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Anaerococcus	Anaerococcus hydrogenalis	1	0
33032	NA	Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Anaerococcus	Anaerococcus lactolyticus	2319	0
33034	NA	Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Anaerococcus	Anaerococcus prevotii	1	0
33036	NA	Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Anaerococcus	Anaerococcus tetradius	1	0
33037	NA	Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Anaerococcus	Anaerococcus vaginalis	1	0
33060	NA	Proteobacteria	Gammaproteobacteria	Enterobacterales	Yersiniaceae	Yersinia	Yersinia mollaretii	1	0
33074	NA	Proteobacteria	Gammaproteobacteria	Oceanospirillales	Halomonadaceae	Zymobacter	Zymobacter palmae	1	0
33194	Fungi	Ascomycota	Dothideomycetes	Pleosporales	Pleosporaceae	Bipolaris	NA	2	0
33203	Fungi	Ascomycota	Sordariomycetes	Hypocreales	Ophiocordycipitaceae	Purpureocillium	Purpureocillium lilacinum	1	0
332648	Fungi	Ascomycota	Leotiomycetes	Helotiales	Sclerotiniaceae	Botrytis	Botrytis cinerea	1	0
337	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Burkholderiaceae	Burkholderia	Burkholderia glumae	1	0
33876	NA	Actinobacteria	Actinobacteria	Micromonosporales	Micromonosporaceae	Catenuloplanes	Catenuloplanes japonicus	1	0
33882	NA	Actinobacteria	Actinobacteria	Micrococcales	Microbacteriaceae	Microbacterium	NA	16	0
33910	NA	Actinobacteria	Actinobacteria	Pseudonocardiales	Pseudonocardiaceae	Amycolatopsis	Amycolatopsis mediterranei	1	0
33934	NA	Firmicutes	Bacilli	Bacillales	Bacillaceae	Anoxybacillus	Anoxybacillus flavithermus	1	0
33958	NA	Firmicutes	Bacilli	Lactobacillales	Lactobacillaceae	NA	NA	1	0
34018	NA	Proteobacteria	Alphaproteobacteria	Rhodospirillales	Rhodospirillaceae	Rhodospirillum	Rhodospirillum centenum	1	0
340486	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella conceptionensis	1	0
34085	NA	Bacteroidetes	Flavobacteriia	Flavobacteriales	Flavobacteriaceae	Riemerella	Riemerella anatipestifer	1	0
341189	Fungi	Basidiomycota	Agaricomycetes	Boletales	Serpulaceae	Serpula	Serpula lacrymans	2	0
341663	Fungi	Ascomycota	Eurotiomycetes	Eurotiales	Aspergillaceae	Aspergillus	Aspergillus terreus	29	0
34384	Fungi	Ascomycota	Eurotiomycetes	Onygenales	Arthrodermataceae	NA	NA	1	0
345341	NA	Actinobacteria	Actinobacteria	Pseudonocardiales	Pseudonocardiaceae	Kutzneria	Kutzneria sp. 744	2	0
347515	NA	NA	NA	Kinetoplastida	Trypanosomatidae	Leishmania	Leishmania major	1	0
348802	Fungi	Ascomycota	Eurotiomycetes	Chaetothyriales	Herpotrichiellaceae	Exophiala	Exophiala xenobiotica	1	0
349102	NA	Proteobacteria	Alphaproteobacteria	Rhodobacterales	Rhodobacteraceae	Rhodobacter	Rhodobacter sphaeroides	5	0
349751	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium marinum	2	0
351187	NA	Actinobacteria	Actinobacteria	Micromonosporales	Micromonosporaceae	Salinispora	Salinispora pacifica	2	0
352472	NA	NA	NA	Dictyosteliales	Dictyosteliaceae	Dictyostelium	Dictyostelium discoideum	1	0
35250	NA	NA	NA	Herpesvirales	Herpesviridae	Mardivirus	Gallid alphaherpesvirus 3	1	0
354276	NA	Proteobacteria	Gammaproteobacteria	Enterobacterales	Enterobacteriaceae	Enterobacter	NA	2	0
35619	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces griseoflavus	1	0
356660	NA	Proteobacteria	Alphaproteobacteria	Rhodobacterales	Rhodobacteraceae	Albimonas	Albimonas donghaensis	1	0
356852	NA	Actinobacteria	Actinobacteria	Micromonosporales	Micromonosporaceae	Micromonospora	Micromonospora coxensis	2	0
356	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	NA	NA	NA	3	0
35717	Fungi	Ascomycota	Sordariomycetes	Hypocreales	Clavicipitaceae	Epichloe	Epichloe festucae	1	0
35762	NA	Actinobacteria	Actinobacteria	Streptosporangiales	Streptosporangiaceae	Planobispora	Planobispora rosea	2	0
35806	NA	Proteobacteria	Alphaproteobacteria	Rhodobacterales	Rhodobacteraceae	Rhodovulum	Rhodovulum sulfidophilum	1	0
35817	NA	Proteobacteria	Epsilonproteobacteria	Campylobacterales	Helicobacteraceae	Helicobacter	Helicobacter heilmannii	1	0
35837	NA	Proteobacteria	Deltaproteobacteria	Syntrophobacterales	Syntrophobacteraceae	Desulfacinum	Desulfacinum infernum	1	0
358823	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces olindensis	1	0
360054	NA	Acidobacteria	Solibacteres	Solibacterales	Bryobacteraceae	Bryobacter	Bryobacter aggregatus	1	0
360107	NA	Proteobacteria	Epsilonproteobacteria	Campylobacterales	Campylobacteraceae	Campylobacter	Campylobacter hominis	2	0
360316	NA	Proteobacteria	Gammaproteobacteria	Methylococcales	Crenotrichaceae	Crenothrix	Crenothrix polyspora	1	0
36050	Fungi	Ascomycota	Sordariomycetes	Hypocreales	Nectriaceae	Fusarium	Fusarium poae	1	0
363253	NA	Proteobacteria	Deltaproteobacteria	Desulfovibrionales	Desulfovibrionaceae	Lawsonia	Lawsonia intracellularis	1	0
36330	NA	Apicomplexa	Aconoidasida	Haemosporida	Plasmodiidae	Plasmodium	Plasmodium ovale	5	0
363858	NA	Firmicutes	Bacilli	Bacillales	Paenibacillaceae	Paenibacillus	Paenibacillus panacisoli	3	0
364410	NA	Proteobacteria	Alphaproteobacteria	Rhodospirillales	Acetobacteraceae	Granulibacter	Granulibacter bethesdensis	3	0
365528	NA	Actinobacteria	Actinobacteria	Frankiales	Frankiaceae	Frankia	Frankia discariae	1	0
365533	NA	Proteobacteria	Alphaproteobacteria	Rhodospirillales	Acetobacteraceae	Belnapia	Belnapia moabensis	1	0
366602	NA	Proteobacteria	Alphaproteobacteria	Caulobacterales	Caulobacteraceae	Caulobacter	Caulobacter sp. K31	2	0
366649	NA	Proteobacteria	Gammaproteobacteria	Xanthomonadales	Xanthomonadaceae	Xanthomonas	Xanthomonas fuscans	3	0
367298	NA	Actinobacteria	Actinobacteria	Micrococcales	Intrasporangiaceae	Phycicoccus	NA	1	0
367791	NA	Bacteroidetes	Cytophagia	Cytophagales	Flammeovirgaceae	Flammeovirga	Flammeovirga yaeyamensis	1	0
36809	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Mycobacteriaceae	Mycobacterium	Mycobacterium abscessus	5	0
36814	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Mycobacteriaceae	Mycobacterium	Mycobacterium rhodesiae	1	0
36874	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Porphyromonadaceae	Porphyromonas	Porphyromonas cangingivalis	1	0
370354	NA	NA	NA	NA	Entamoebidae	Entamoeba	Entamoeba dispar	5	0
370355	NA	NA	NA	NA	Entamoebidae	Entamoeba	Entamoeba invadens	1	0
370974	NA	Bacteroidetes	Flavobacteriia	Flavobacteriales	Flavobacteriaceae	Flavobacterium	Flavobacterium filum	1	0
371036	NA	Firmicutes	Bacilli	Bacillales	Bacillaceae	Bacillus	Bacillus acidiceler	1	0
371601	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Bacteroidaceae	Bacteroides	Bacteroides xylanisolvens	6	0
371720	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces monomycini	1	0
372443	NA	NA	NA	NA	Phycodnaviridae	Coccolithovirus	NA	1	0
372663	NA	Actinobacteria	Actinobacteria	Micrococcales	Promicromonosporaceae	Isoptericola	Isoptericola dokdonensis	1	0
372787	NA	Cyanobacteria	NA	Nostocales	Hapalosiphonaceae	Fischerella	Fischerella thermalis	1	0
37452	NA	Bacteroidetes	NA	NA	NA	NA	NA	2	0
374927	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Haemophilus	Haemophilus influenzae	36	0
374928	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Haemophilus	Haemophilus influenzae	7	0
374930	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Haemophilus	Haemophilus influenzae	11	0
374931	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Haemophilus	Haemophilus influenzae	10	0
374932	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Haemophilus	Haemophilus influenzae	23	0
374933	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Haemophilus	Haemophilus influenzae	14	0
374	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	Bradyrhizobiaceae	Bradyrhizobium	NA	1	0
375063	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Haemophilus	Haemophilus influenzae	23	0
375177	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Haemophilus	Haemophilus influenzae	6	0
375432	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Haemophilus	Haemophilus influenzae	11	0
376806	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Bacteroidaceae	Bacteroides	Bacteroides gallinarum	1	0
376815	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Comamonadaceae	Variovorax	Variovorax soli	1	0
378806	NA	Proteobacteria	Deltaproteobacteria	Myxococcales	Archangiaceae	Stigmatella	Stigmatella aurantiaca	1	0
37914	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Dietziaceae	Dietzia	NA	2	0
37919	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Nocardiaceae	Rhodococcus	Rhodococcus opacus	1	0
379508	Fungi	Ascomycota	Saccharomycetes	Saccharomycetales	Debaryomycetaceae	Lodderomyces	Lodderomyces elongisporus	12	0
379	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	Rhizobiaceae	Rhizobium	NA	1	0
380244	NA	Actinobacteria	Actinobacteria	Glycomycetales	Glycomycetaceae	Glycomyces	Glycomyces sambucus	3	0
38038	Fungi	Ascomycota	Leotiomycetes	Helotiales	NA	Rhynchosporium	Rhynchosporium secalis	2	0
380	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	Rhizobiaceae	Sinorhizobium	Sinorhizobium fredii	1	0
38284	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium accolens	5	0
38289	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium jeikeium	11	0
38294	NA	Proteobacteria	Gammaproteobacteria	Vibrionales	Vibrionaceae	Photobacterium	Photobacterium damselae	6	0
38300	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces pristinaespiralis	1	0
38302	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium mycetoides	1	0
38303	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium pseudogenitalium	1674	0
38304	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium tuberculostearicum	8	0
38305	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium vitaeruminis	1	0
38311	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Nocardiaceae	Rhodococcus	Rhodococcus marinonascens	1	0
383855	Fungi	Ascomycota	Dothideomycetes	Capnodiales	Mycosphaerellaceae	Pseudocercospora	Pseudocercospora fijiensis	7	0
384677	NA	Actinobacteria	Actinobacteria	Micrococcales	Intrasporangiaceae	Ornithinimicrobium	Ornithinimicrobium pekingense	1	0
38504	NA	Tenericutes	Mollicutes	Mycoplasmatales	Mycoplasmataceae	Ureaplasma	Ureaplasma parvum	2	0
386414	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella timonensis	4	0
388400	NA	Firmicutes	Bacilli	Bacillales	Bacillaceae	Bacillus	Bacillus sp. B14905	2	0
391593	NA	Proteobacteria	Alphaproteobacteria	Rhodobacterales	Rhodobacteraceae	Roseobacter	Roseobacter sp. CCS2	1	0
392613	Fungi	Ascomycota	Eurotiomycetes	Onygenales	Ascosphaeraceae	Ascosphaera	Ascosphaera apis	1	0
393310	NA	Proteobacteria	Alphaproteobacteria	Rhodospirillales	Rhodospirillaceae	Skermanella	Skermanella aerolata	3	0
393480	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Fusobacterium	Fusobacterium nucleatum	2	0
393921	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Porphyromonadaceae	Porphyromonas	Porphyromonas crevioricanis	1	0
39416	Fungi	Ascomycota	Pezizomycetes	Pezizales	Tuberaceae	Tuber	Tuber melanosporum	1	0
394734	NA	Actinobacteria	Actinobacteria	Propionibacteriales	Nocardioidaceae	Nocardioides	Nocardioides insulae	2	0
39478	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces laurentii	1	0
396716	NA	Firmicutes	Bacilli	Lactobacillales	Lactobacillaceae	Lactobacillus	Lactobacillus hayakitensis	5	0
396	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	Rhizobiaceae	Rhizobium	Rhizobium phaseoli	2	0
39700	NA	NA	NA	Kinetoplastida	Trypanosomatidae	Trypanosoma	NA	1	0
397278	NA	Actinobacteria	Actinobacteria	Propionibacteriales	Nocardioidaceae	Marmoricola	Marmoricola aequoreus	23	0
397291	NA	Firmicutes	Clostridia	Clostridiales	Lachnospiraceae	NA	Lachnospiraceae bacterium A4	1	0
39779	NA	Firmicutes	Clostridia	Clostridiales	NA	NA	NA	1	0
39791	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium glucuronolyticum	326	0
399548	NA	Proteobacteria	Deltaproteobacteria	Desulfovibrionales	Desulfovibrionaceae	Desulfocurvus	Desulfocurvus vexinensis	2	0
39966	Fungi	Basidiomycota	Agaricomycetes	Agaricales	Lyophyllaceae	Hypsizygus	Hypsizygus marmoreus	3	0
402229	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. SM1	2	0
402676	Fungi	Ascomycota	Schizosaccharomycetes	Schizosaccharomycetales	Schizosaccharomycetaceae	Schizosaccharomyces	Schizosaccharomyces japonicus	1	0
40324	NA	Proteobacteria	Gammaproteobacteria	Xanthomonadales	Xanthomonadaceae	Stenotrophomonas	Stenotrophomonas maltophilia	1	0
404386	NA	Actinobacteria	Actinobacteria	Streptosporangiales	Streptosporangiaceae	Nonomuraea	Nonomuraea coxensis	1	0
404433	NA	Proteobacteria	Gammaproteobacteria	Oceanospirillales	Halomonadaceae	Salinicola	Salinicola socius	1	0
404692	Fungi	Ascomycota	Eurotiomycetes	Onygenales	NA	Coccidioides	Coccidioides immitis	1	0
40576	NA	Proteobacteria	Gammaproteobacteria	Enterobacterales	Morganellaceae	Xenorhabdus	Xenorhabdus bovienii	1	0
405782	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptacidiphilus	Streptacidiphilus anmyonensis	2	0
406341	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	Bradyrhizobiaceae	Bosea	Bosea sp. WAO	1	0
408	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	Methylobacteriaceae	Methylobacterium	Methylobacterium extorquens	1	0
411459	NA	Firmicutes	Clostridia	Clostridiales	Lachnospiraceae	Blautia	Blautia obeum	1	0
411465	NA	Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Parvimonas	Parvimonas micra	1	0
411466	NA	Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Actinomyces	Actinomyces odontolyticus	4	0
411470	NA	Firmicutes	Clostridia	Clostridiales	Lachnospiraceae	Blautia	[Ruminococcus] gnavus	3	0
411474	NA	Firmicutes	Clostridia	Clostridiales	Lachnospiraceae	Coprococcus	Coprococcus eutactus	1	0
411477	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Tannerellaceae	Parabacteroides	Parabacteroides merdae	6	0
411479	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Bacteroidaceae	Bacteroides	Bacteroides uniformis	1	0
411486	NA	Firmicutes	Clostridia	Clostridiales	Clostridiaceae	Clostridium	Clostridium sp. M62/1	2	0
41292	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	NA	NA	NA	1	0
413479	NA	Proteobacteria	Gammaproteobacteria	Nevskiales	Sinobacteraceae	Solimonas	Solimonas soli	1	0
413497	NA	Proteobacteria	Gammaproteobacteria	Enterobacterales	Enterobacteriaceae	Cronobacter	Cronobacter dublinensis	1	0
414682	NA	Firmicutes	Bacilli	Lactobacillales	Lactobacillaceae	Lactobacillus	Lactobacillus similis	1	0
414771	NA	Firmicutes	Bacilli	Bacillales	Paenibacillaceae	Paenibacillus	Paenibacillus donghaensis	1	0
41688	Fungi	Ascomycota	Sordariomycetes	Microascales	Microascaceae	Lomentospora	Lomentospora prolificans	1	0
416916	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Aggregatibacter	NA	2	0
418459	Fungi	Basidiomycota	Pucciniomycetes	Pucciniales	Pucciniaceae	Puccinia	Puccinia graminis	1	0
41875	Viridiplantae	Chlorophyta	Mamiellophyceae	Mamiellales	Bathycoccaceae	Bathycoccus	Bathycoccus prasinos	1	0
418867	Fungi	Basidiomycota	Agaricomycetes	Hymenochaetales	Hymenochaetaceae	Phellinus	Phellinus noxius	1	0
418	NA	Proteobacteria	Gammaproteobacteria	Methylococcales	Methylococcaceae	Methylomonas	Methylomonas sp.	1	0
419005	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella amnii	7	0
419435	NA	NA	NA	NA	Polydnaviridae	Ichnovirus	Glypta fumiferanae ichnovirus	2	0
41997	NA	Firmicutes	Bacilli	Lactobacillales	Enterococcaceae	Enterococcus	Enterococcus saccharolyticus	1	0
420245	NA	NA	NA	Kinetoplastida	Trypanosomatidae	Leishmania	Leishmania braziliensis	2	0
420778	Fungi	Ascomycota	Dothideomycetes	Botryosphaeriales	Botryosphaeriaceae	Diplodia	Diplodia seriata	3	0
42234	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces acidiscabies	2	0
425265	Fungi	Basidiomycota	Malasseziomycetes	Malasseziales	Malasseziaceae	Malassezia	Malassezia globosa	1	0
426129	NA	Firmicutes	Clostridia	Clostridiales	Clostridiaceae	Alkaliphilus	Alkaliphilus peptidifermentans	1	0
428127	NA	Firmicutes	Erysipelotrichia	Erysipelotrichales	Erysipelotrichaceae	Absiella	Absiella dolichum	2	0
429131	NA	NA	NA	Kinetoplastida	Trypanosomatidae	Trypanosoma	Trypanosoma rangeli	1	0
43049	Fungi	Basidiomycota	Exobasidiomycetes	Tilletiales	Tilletiaceae	Tilletia	Tilletia indica	1	0
431895	NA	NA	NA	Choanoflagellida	Salpingoecidae	Monosiga	Monosiga brevicollis	22	0
432331	NA	Aquificae	Aquificae	Aquificales	Hydrogenothermaceae	Sulfurihydrogenibium	Sulfurihydrogenibium yellowstonense	1	0
432359	NA	Apicomplexa	Coccidia	Eucoccidiorida	Sarcocystidae	Toxoplasma	Toxoplasma gondii	1	0
43263	NA	Proteobacteria	Gammaproteobacteria	Pseudomonadales	Pseudomonadaceae	Pseudomonas	Pseudomonas alcaligenes	1	0
43305	NA	Firmicutes	Clostridia	Clostridiales	Lachnospiraceae	Butyrivibrio	Butyrivibrio proteoclasticus	1	0
43357	NA	Actinobacteria	Actinobacteria	Pseudonocardiales	Pseudonocardiaceae	Kutzneria	Kutzneria albida	1	0
433660	NA	Actinobacteria	Actinobacteria	Propionibacteriales	Nocardioidaceae	Nocardioides	Nocardioides halotolerans	1	0
433924	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Comamonadaceae	Pseudacidovorax	Pseudacidovorax intermedius	2	0
433	NA	Proteobacteria	Alphaproteobacteria	Rhodospirillales	Acetobacteraceae	NA	NA	1	0
434	NA	Proteobacteria	Alphaproteobacteria	Rhodospirillales	Acetobacteraceae	Acetobacter	NA	1	0
435289	NA	Proteobacteria	Gammaproteobacteria	Xanthomonadales	Xanthomonadaceae	Lysobacter	Lysobacter spongiicola	1	0
435830	NA	Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Actinomyces	Actinomyces graevenitzii	1	0
435998	NA	Proteobacteria	Gammaproteobacteria	Enterobacterales	Yersiniaceae	Serratia	Serratia marcescens	1	0
436010	Fungi	Basidiomycota	Agaricomycetes	Atheliales	Atheliaceae	Fibularhizoctonia	Fibularhizoctonia sp. CBS 109695	2	0
43657	NA	Proteobacteria	Gammaproteobacteria	Alteromonadales	Pseudoalteromonadaceae	Pseudoalteromonas	Pseudoalteromonas luteoviolacea	2	0
43663	NA	Actinobacteria	Actinobacteria	Micrococcales	Micrococcaceae	Paenarthrobacter	Paenarthrobacter aurescens	1	0
43678	NA	Actinobacteria	Actinobacteria	Micrococcales	Cellulomonadaceae	Oerskovia	Oerskovia enterophila	1	0
43770	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium striatum	11	0
43997	NA	Firmicutes	Clostridia	Clostridiales	Lachnospiraceae	Catonella	Catonella morbi	801	0
44056	NA	NA	Pelagophyceae	Pelagomonadales	NA	Aureococcus	Aureococcus anophagefferens	1	0
44249	NA	Firmicutes	Bacilli	Bacillales	Paenibacillaceae	Paenibacillus	NA	7	0
44283	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Pasteurella	Pasteurella multocida	5	0
44415	NA	Apicomplexa	Coccidia	Eucoccidiorida	Eimeriidae	Eimeria	Eimeria mitis	9	0
444	NA	Proteobacteria	Gammaproteobacteria	Legionellales	Legionellaceae	NA	NA	2	0
445576	NA	Actinobacteria	Actinobacteria	Pseudonocardiales	Pseudonocardiaceae	Pseudonocardia	Pseudonocardia sp. AL041005-10	1	0
445960	NA	Bacteroidetes	Flavobacteriia	Flavobacteriales	Flavobacteriaceae	Chryseobacterium	Chryseobacterium jejuense	1	0
445	NA	Proteobacteria	Gammaproteobacteria	Legionellales	Legionellaceae	Legionella	NA	1	0
44689	NA	NA	NA	Dictyosteliales	Dictyosteliaceae	Dictyostelium	Dictyostelium discoideum	6	0
446	NA	Proteobacteria	Gammaproteobacteria	Legionellales	Legionellaceae	Legionella	Legionella pneumophila	1	0
447095	Fungi	Ascomycota	Eurotiomycetes	Onygenales	Ajellomycetaceae	Blastomyces	Blastomyces dermatitidis	1	0
448	NA	Proteobacteria	Gammaproteobacteria	Legionellales	Legionellaceae	Legionella	Legionella erythra	1	0
45067	NA	Proteobacteria	Gammaproteobacteria	Legionellales	Legionellaceae	Legionella	Legionella lansingensis	1	0
450746	NA	Firmicutes	Erysipelotrichia	Erysipelotrichales	Erysipelotrichaceae	Coprobacillus	Coprobacillus sp. 8_1_38FAA	1	0
451435	Fungi	Chytridiomycota	Chytridiomycetes	NA	NA	NA	NA	1	0
451514	NA	NA	NA	NA	NA	NA	magneto-ovoid bacterium MO-1	2	0
452529	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces scopuliridis	1	0
452589	Fungi	Ascomycota	Sordariomycetes	Hypocreales	Hypocreaceae	Trichoderma	Trichoderma atroviride	3	0
454130	Fungi	Ascomycota	Eurotiomycetes	Eurotiales	Aspergillaceae	Aspergillus	Aspergillus calidoustus	1	0
454	NA	Proteobacteria	Gammaproteobacteria	Legionellales	Legionellaceae	Legionella	Legionella israelensis	1	0
456298	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Glaesserella	Glaesserella parasuis	7	0
456482	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Haemophilus	Haemophilus influenzae	84	0
456493	NA	Firmicutes	Bacilli	Bacillales	Paenibacillaceae	Saccharibacillus	Saccharibacillus sacchari	2	0
457390	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Bacteroidaceae	Bacteroides	Bacteroides sp. 3_1_23	1	0
457427	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces himastatinicus	1	0
457944	NA	Cyanobacteria	NA	Nostocales	Nostocaceae	Nostoc	Nostoc sp. KVJ20	1	0
460086	NA	Actinobacteria	Actinobacteria	Propionibacteriales	Nocardioidaceae	Kribbella	Kribbella catacumbae	1	0
461836	NA	NA	NA	NA	Apusomonadidae	Thecamonas	Thecamonas trahens	2	0
463191	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sviceus	1	0
46433	NA	NA	NA	NA	Reticulomyxidae	Reticulomyxa	Reticulomyxa filosa	76	0
465541	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. Mg1	4	0
469371	NA	Actinobacteria	Actinobacteria	NA	NA	Thermobispora	Thermobispora bispora	2	0
469383	NA	Actinobacteria	Thermoleophilia	Solirubrobacterales	Conexibacteraceae	Conexibacter	Conexibacter woesei	1	0
469590	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Bacteroidaceae	Bacteroides	Bacteroides sp. 2_2_4	2	0
469591	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Tannerellaceae	Parabacteroides	Parabacteroides sp. 20_3	2	0
469	NA	Proteobacteria	Gammaproteobacteria	Pseudomonadales	Moraxellaceae	Acinetobacter	NA	4	0
470145	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Bacteroidaceae	Bacteroides	Bacteroides coprocola	3	0
470	NA	Proteobacteria	Gammaproteobacteria	Pseudomonadales	Moraxellaceae	Acinetobacter	Acinetobacter baumannii	3	0
471514	NA	Firmicutes	Bacilli	Bacillales	Alicyclobacillaceae	Alicyclobacillus	Alicyclobacillus ferrooxydans	1	0
471874	NA	Proteobacteria	Gammaproteobacteria	Enterobacterales	Morganellaceae	Providencia	Providencia stuartii	2	0
472569	NA	Actinobacteria	Actinobacteria	Micrococcales	Dermabacteraceae	Devriesea	Devriesea agamarum	1	0
472963	NA	Firmicutes	Bacilli	Bacillales	Bacillaceae	Anaerobacillus	Anaerobacillus alkalidiazotrophicus	1	0
47312	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Tsukamurellaceae	Tsukamurella	Tsukamurella pulmonis	1	0
474995	Fungi	Ascomycota	Sordariomycetes	Hypocreales	Ophiocordycipitaceae	Ophiocordyceps	NA	2	0
4751	Fungi	NA	NA	NA	NA	NA	NA	1	0
475254	NA	Bacteroidetes	Sphingobacteriia	Sphingobacteriales	Sphingobacteriaceae	Pedobacter	Pedobacter borealis	2	0
475	NA	Proteobacteria	Gammaproteobacteria	Pseudomonadales	Moraxellaceae	Moraxella	NA	1	0
47715	NA	Firmicutes	Bacilli	Lactobacillales	Lactobacillaceae	Lactobacillus	Lactobacillus rhamnosus	1	0
47735	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Bibersteinia	Bibersteinia trehalosi	2	0
47760	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces aurantiacus	3	0
47790	Viridiplantae	Chlorophyta	Chlorophyceae	Chlamydomonadales	Tetrabaenaceae	Tetrabaena	Tetrabaena socialis	1	0
4781	NA	NA	Oomycetes	Peronosporales	Peronosporaceae	Plasmopara	Plasmopara halstedii	1	0
47839	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Mycobacteriaceae	Mycobacterium	Mycobacterium triplex	2	0
47858	NA	Actinobacteria	Actinobacteria	Micromonosporales	Micromonosporaceae	Micromonospora	Micromonospora echinofusca	1	0
47877	NA	Proteobacteria	Gammaproteobacteria	Pseudomonadales	Pseudomonadaceae	Pseudomonas	Pseudomonas amygdali	1	0
4792	NA	NA	Oomycetes	Peronosporales	NA	Phytophthora	Phytophthora parasitica	3	0
4795	NA	NA	Oomycetes	Peronosporales	NA	Phytophthora	Phytophthora megakarya	2	0
482145	Fungi	Ascomycota	Eurotiomycetes	Eurotiales	Aspergillaceae	Aspergillus	Aspergillus taichungensis	1	0
482561	Fungi	Ascomycota	Eurotiomycetes	Onygenales	NA	Paracoccidioides	Paracoccidioides brasiliensis	1	0
482628	NA	Proteobacteria	Epsilonproteobacteria	Campylobacterales	Campylobacteraceae	Campylobacter	Campylobacter jejuni	3	0
482957	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Burkholderiaceae	Burkholderia	Burkholderia lata	1	0
4829	Fungi	Mucoromycota	NA	Mucorales	Cunninghamellaceae	Absidia	Absidia glauca	1	0
4830	Fungi	Mucoromycota	NA	Mucorales	Mucoraceae	Mucor	NA	1	0
483139	NA	Apicomplexa	Coccidia	Eucoccidiorida	Sarcocystidae	Cystoisospora	Cystoisospora suis	5	0
486041	Fungi	Basidiomycota	Agaricomycetes	Agaricales	Tricholomataceae	Laccaria	Laccaria bicolor	2	0
486410	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus dysgalactiae	1	0
486698	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Mycobacteriaceae	Mycobacterium	Mycobacterium riyadhense	1	0
487173	NA	Firmicutes	Negativicutes	Veillonellales	Veillonellaceae	Dialister	Dialister succinatiphilus	1	0
487796	NA	Bacteroidetes	Flavobacteriia	NA	NA	NA	Flavobacteria bacterium MS024-2A	1	0
48782	NA	Spirochaetes	Spirochaetia	NA	Leptospiraceae	Leptospira	Leptospira fainei	1	0
487	NA	Proteobacteria	Betaproteobacteria	Neisseriales	Neisseriaceae	Neisseria	Neisseria meningitidis	2	0
4911	Fungi	Ascomycota	Saccharomycetes	Saccharomycetales	Saccharomycetaceae	Kluyveromyces	Kluyveromyces marxianus	1	0
4932	Fungi	Ascomycota	Saccharomycetes	Saccharomycetales	Saccharomycetaceae	Saccharomyces	Saccharomyces cerevisiae	4	0
49546	NA	Bacteroidetes	Flavobacteriia	Flavobacteriales	Flavobacteriaceae	NA	NA	1	0
4956	Fungi	Ascomycota	Saccharomycetes	Saccharomycetales	Saccharomycetaceae	Zygosaccharomyces	Zygosaccharomyces rouxii	1	0
500638	NA	Proteobacteria	Gammaproteobacteria	Enterobacterales	Hafniaceae	Edwardsiella	Edwardsiella tarda	1	0
501497	NA	Thermodesulfobacteria	Thermodesulfobacteria	Thermodesulfobacteriales	Thermodesulfobacteriaceae	Thermodesulfatator	Thermodesulfatator atlanticus	1	0
502393	NA	Firmicutes	Bacilli	Bacillales	NA	Gemella	Gemella asaccharolytica	1	0
503106	Fungi	Ascomycota	Leotiomycetes	Helotiales	Dermateaceae	Marssonina	Marssonina coronariae	2	0
5042	Fungi	Ascomycota	Eurotiomycetes	Eurotiales	NA	NA	NA	1	0
504474	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium urealyticum	1	0
504805	NA	Actinobacteria	Actinobacteria	Streptosporangiales	Streptosporangiaceae	Sinosporangium	Sinosporangium album	1	0
5052	Fungi	Ascomycota	Eurotiomycetes	Eurotiales	Aspergillaceae	Aspergillus	NA	8	0
505317	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Chelonobacter	Chelonobacter oris	1	0
5057	Fungi	Ascomycota	Eurotiomycetes	Eurotiales	Aspergillaceae	Aspergillus	Aspergillus clavatus	1	0
5061	Fungi	Ascomycota	Eurotiomycetes	Eurotiales	Aspergillaceae	Aspergillus	Aspergillus niger	3	0
5073	Fungi	Ascomycota	Eurotiomycetes	Eurotiales	Aspergillaceae	Penicillium	NA	2	0
507601	NA	Apicomplexa	Coccidia	Eucoccidiorida	Sarcocystidae	Toxoplasma	Toxoplasma gondii	2	0
5078	Fungi	Ascomycota	Eurotiomycetes	Eurotiales	Aspergillaceae	Penicillium	Penicillium griseofulvum	1	0
508770	NA	Actinobacteria	Actinobacteria	Pseudonocardiales	Pseudonocardiaceae	Sciscionella	Sciscionella marina	1	0
508771	NA	Apicomplexa	Coccidia	Eucoccidiorida	Sarcocystidae	Toxoplasma	Toxoplasma gondii	3	0
511	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Alcaligenaceae	Alcaligenes	Alcaligenes faecalis	1	0
51314	NA	Apicomplexa	Coccidia	Eucoccidiorida	Eimeriidae	Eimeria	Eimeria brunetti	1	0
51315	NA	Apicomplexa	Coccidia	Eucoccidiorida	Eimeriidae	Eimeria	Eimeria necatrix	8	0
51316	NA	Apicomplexa	Coccidia	Eucoccidiorida	Eimeriidae	Eimeria	Eimeria praecox	2	0
5141	Fungi	Ascomycota	Sordariomycetes	Sordariales	Sordariaceae	Neurospora	Neurospora crassa	1	0
515414	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella falsenii	1	0
515608	NA	Tenericutes	Mollicutes	Mycoplasmatales	Mycoplasmataceae	Ureaplasma	Ureaplasma parvum	3	0
515611	NA	Tenericutes	Mollicutes	Mycoplasmatales	Mycoplasmataceae	Ureaplasma	Ureaplasma urealyticum	2	0
5157	Fungi	Ascomycota	Sordariomycetes	Microascales	Ceratocystidaceae	Ceratocystis	NA	1	0
515849	Fungi	Ascomycota	Sordariomycetes	Sordariales	Lasiosphaeriaceae	Podospora	Podospora anserina	1	0
517722	NA	Proteobacteria	Alphaproteobacteria	Sphingomonadales	Sphingomonadaceae	Citromicrobium	Citromicrobium sp. JLT1363	1	0
5178	Fungi	Ascomycota	Leotiomycetes	Helotiales	NA	NA	NA	1	0
518603	NA	Tenericutes	Mollicutes	Mycoplasmatales	Mycoplasmataceae	Ureaplasma	Ureaplasma urealyticum	8	0
520141	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Mycobacteriaceae	Mycobacterium	Mycobacterium tuberculosis	2	0
521004	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Haemophilus	Haemophilus influenzae	1	0
521005	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Haemophilus	Haemophilus influenzae	5	0
525254	NA	Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Anaerococcus	Anaerococcus lactolyticus	26	0
525255	NA	Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Anaerococcus	Anaerococcus tetradius	5	0
525260	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium accolens	1	0
525264	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium pseudogenitalium	167	0
525268	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium striatum	2	0
52584	NA	Spirochaetes	Spirochaetia	Brachyspirales	Brachyspiraceae	Brachyspira	Brachyspira pilosicoli	1	0
530584	NA	Actinobacteria	Actinobacteria	Pseudonocardiales	Pseudonocardiaceae	Prauserella	Prauserella marina	1	0
53335	NA	Proteobacteria	Gammaproteobacteria	Enterobacterales	Erwiniaceae	Pantoea	NA	1	0
53346	NA	Firmicutes	Bacilli	Lactobacillales	Enterococcaceae	Enterococcus	Enterococcus mundtii	1	0
53355	NA	Actinobacteria	Actinobacteria	Micrococcales	Intrasporangiaceae	Terrabacter	NA	1	0
53368	NA	Actinobacteria	Actinobacteria	Micromonosporales	Micromonosporaceae	Hamadaea	Hamadaea tsunoensis	1	0
53409	NA	Proteobacteria	Gammaproteobacteria	Pseudomonadales	Pseudomonadaceae	Pseudomonas	Pseudomonas coronafaciens	1	0
5341	Fungi	Basidiomycota	Agaricomycetes	Agaricales	Agaricaceae	Agaricus	Agaricus bisporus	1	0
5353	Fungi	Basidiomycota	Agaricomycetes	Agaricales	Omphalotaceae	Lentinula	Lentinula edodes	1	0
537006	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Tannerellaceae	Parabacteroides	Parabacteroides johnsonii	1	0
537007	NA	Firmicutes	Clostridia	Clostridiales	Lachnospiraceae	Blautia	Blautia hansenii	8	0
5375	Fungi	Basidiomycota	Agaricomycetes	Boletales	Rhizopogonaceae	Rhizopogon	NA	1	0
537971	NA	Proteobacteria	Epsilonproteobacteria	Campylobacterales	Helicobacteraceae	Helicobacter	Helicobacter cinaedi	1	0
538381	NA	Proteobacteria	Alphaproteobacteria	Rhodobacterales	Rhodobacteraceae	Stappia	Stappia indica	1	0
54005	NA	Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Peptoniphilus	Peptoniphilus harei	1865	0
541000	NA	Firmicutes	Clostridia	Clostridiales	Ruminococcaceae	NA	NA	1	0
543791	Fungi	Ascomycota	Arthoniomycetes	Arthoniales	Opegraphaceae	Opegrapha	Opegrapha vulgata	1	0
543	NA	Proteobacteria	Gammaproteobacteria	Enterobacterales	Enterobacteriaceae	NA	NA	10	0
544580	NA	Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Actinomyces	Actinomyces oris	1	0
5454	Fungi	Ascomycota	Dothideomycetes	Pleosporales	Didymellaceae	Ascochyta	Ascochyta rabiei	5	0
546364	NA	Actinobacteria	Actinobacteria	Pseudonocardiales	Pseudonocardiaceae	Amycolatopsis	Amycolatopsis australiensis	2	0
546871	NA	Actinobacteria	Actinobacteria	Propionibacteriales	Nocardioidaceae	Friedmanniella	Friedmanniella luteola	1	0
547334	NA	Actinobacteria	Actinobacteria	Micrococcales	Micrococcaceae	Arthrobacter	Arthrobacter pityocampae	1	0
548476	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium aurimucosum	3	0
548477	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium glucuronolyticum	22	0
548478	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium glucuronolyticum	11	0
548	NA	Proteobacteria	Gammaproteobacteria	Enterobacterales	Enterobacteriaceae	Klebsiella	Klebsiella aerogenes	1	0
550773	NA	Tenericutes	Mollicutes	Mycoplasmatales	Mycoplasmataceae	Ureaplasma	Ureaplasma urealyticum	2	0
550	NA	Proteobacteria	Gammaproteobacteria	Enterobacterales	Enterobacteriaceae	Enterobacter	Enterobacter cloacae	4	0
5518	Fungi	Ascomycota	Sordariomycetes	Hypocreales	Nectriaceae	Fusarium	Fusarium graminearum	1	0
55211	NA	Proteobacteria	Gammaproteobacteria	Enterobacterales	Erwiniaceae	Erwinia	Erwinia persicina	2	0
552	NA	Proteobacteria	Gammaproteobacteria	Enterobacterales	Erwiniaceae	Erwinia	Erwinia amylovora	1	0
553171	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella bivia	2	0
553174	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella melaninogenica	1	0
553175	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Porphyromonadaceae	Porphyromonas	Porphyromonas endodontalis	1	0
553206	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium tuberculostearicum	23	0
553510	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces gilvosporeus	1	0
553	NA	Proteobacteria	Gammaproteobacteria	Enterobacterales	Erwiniaceae	Pantoea	Pantoea ananatis	8	0
554065	Viridiplantae	Chlorophyta	Trebouxiophyceae	Chlorellales	Chlorellaceae	Chlorella	Chlorella variabilis	1	0
554155	Fungi	Ascomycota	Eurotiomycetes	Onygenales	Arthrodermataceae	Microsporum	Microsporum canis	1	0
5544	Fungi	Ascomycota	Sordariomycetes	Hypocreales	Hypocreaceae	Trichoderma	Trichoderma harzianum	3	0
556484	NA	Bacillariophyta	Bacillariophyceae	Naviculales	Phaeodactylaceae	Phaeodactylum	Phaeodactylum tricornutum	1	0
556499	NA	Actinobacteria	Actinobacteria	Propionibacteriales	Propionibacteriaceae	Propionibacterium	Propionibacterium acidifaciens	1	0
558152	NA	Bacteroidetes	Flavobacteriia	Flavobacteriales	Flavobacteriaceae	Chryseobacterium	Chryseobacterium piperi	1	0
5599	Fungi	Ascomycota	Dothideomycetes	Pleosporales	Pleosporaceae	Alternaria	Alternaria alternata	1	0
5627	Fungi	Basidiomycota	Agaricomycetes	Polyporales	Grifolaceae	Grifola	Grifola frondosa	1	0
562	NA	Proteobacteria	Gammaproteobacteria	Enterobacterales	Enterobacteriaceae	Escherichia	Escherichia coli	15	0
563008	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella oris	2	0
563031	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella sp. C561	2	0
563032	NA	Actinobacteria	Actinobacteria	Micrococcales	Micrococcaceae	Rothia	Rothia dentocariosa	7	0
563193	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Tannerellaceae	Parabacteroides	Parabacteroides sp. D13	1	0
5643	Fungi	Basidiomycota	Agaricomycetes	Polyporales	Polyporaceae	Trametes	Trametes cinnabarina	1	0
565575	NA	Tenericutes	Mollicutes	Mycoplasmatales	Mycoplasmataceae	Ureaplasma	Ureaplasma urealyticum	6	0
5661	NA	NA	NA	Kinetoplastida	Trypanosomatidae	Leishmania	Leishmania donovani	1	0
56698	NA	Proteobacteria	Epsilonproteobacteria	Campylobacterales	Campylobacteraceae	Sulfurospirillum	Sulfurospirillum arsenophilum	1	0
5671	NA	NA	NA	Kinetoplastida	Trypanosomatidae	Leishmania	Leishmania infantum	1	0
5684	NA	NA	NA	Kinetoplastida	Trypanosomatidae	Leptomonas	Leptomonas seymouri	3	0
568899	NA	Firmicutes	Bacilli	Bacillales	Bacillaceae	Alteribacillus	Alteribacillus persepolensis	1	0
5691	NA	NA	NA	Kinetoplastida	Trypanosomatidae	Trypanosoma	Trypanosoma brucei	4	0
5693	NA	NA	NA	Kinetoplastida	Trypanosomatidae	Trypanosoma	Trypanosoma cruzi	9	0
570	NA	Proteobacteria	Gammaproteobacteria	Enterobacterales	Enterobacteriaceae	Klebsiella	NA	1	0
572307	NA	Apicomplexa	Coccidia	Eucoccidiorida	Sarcocystidae	Neospora	Neospora caninum	2	0
572511	NA	Firmicutes	Clostridia	Clostridiales	Lachnospiraceae	Blautia	NA	6	0
57266	NA	Apicomplexa	Aconoidasida	Haemosporida	Plasmodiidae	Plasmodium	Plasmodium falciparum	1	0
57267	NA	Apicomplexa	Aconoidasida	Haemosporida	Plasmodiidae	Plasmodium	Plasmodium falciparum	2	0
57270	NA	Apicomplexa	Aconoidasida	Haemosporida	Plasmodiidae	Plasmodium	Plasmodium falciparum	1	0
573569	NA	Proteobacteria	Gammaproteobacteria	Thiotrichales	Francisellaceae	Francisella	Francisella sp. TX077308	1	0
573570	NA	Proteobacteria	Gammaproteobacteria	Thiotrichales	Francisellaceae	Francisella	Francisella sp. TX077310	1	0
573729	Fungi	Ascomycota	Sordariomycetes	Sordariales	Chaetomiaceae	Thermothelomyces	Thermothelomyces thermophila	2	0
573	NA	Proteobacteria	Gammaproteobacteria	Enterobacterales	Enterobacteriaceae	Klebsiella	Klebsiella pneumoniae	2	0
5741	NA	NA	NA	NA	Hexamitidae	Giardia	Giardia intestinalis	1	0
574697	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Odoribacteraceae	Butyricimonas	NA	1	0
574774	Fungi	Ascomycota	Dothideomycetes	NA	Gloniaceae	Glonium	Glonium stellatum	9	0
575540	NA	Planctomycetes	Planctomycetia	Planctomycetales	Isosphaeraceae	Isosphaera	Isosphaera pallida	1	0
575611	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella buccae	1	0
575615	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella sp. oral taxon 317	2	0
57665	NA	Proteobacteria	Epsilonproteobacteria	Campylobacterales	Campylobacteraceae	Sulfurospirillum	NA	2	0
577470	NA	Actinobacteria	Actinobacteria	Micrococcales	Demequinaceae	Demequina	Demequina salsinemoris	1	0
578462	Fungi	Blastocladiomycota	Blastocladiomycetes	Blastocladiales	Blastocladiaceae	Allomyces	Allomyces macrogynus	2	0
5794	NA	Apicomplexa	NA	NA	NA	NA	NA	1	0
580026	NA	Actinobacteria	Coriobacteriia	Eggerthellales	Eggerthellaceae	Enterorhabdus	Enterorhabdus mucosicola	1	0
580058	NA	Apicomplexa	Aconoidasida	Haemosporida	Plasmodiidae	Plasmodium	Plasmodium falciparum	2	0
5800	NA	Apicomplexa	Coccidia	Eucoccidiorida	Eimeriidae	Eimeria	NA	1	0
5801	NA	Apicomplexa	Coccidia	Eucoccidiorida	Eimeriidae	Eimeria	Eimeria acervulina	2	0
5802	NA	Apicomplexa	Coccidia	Eucoccidiorida	Eimeriidae	Eimeria	Eimeria tenella	5	0
58117	NA	Actinobacteria	Actinobacteria	Streptosporangiales	Streptosporangiaceae	Microbispora	Microbispora rosea	2	0
5811	NA	Apicomplexa	Coccidia	Eucoccidiorida	Sarcocystidae	Toxoplasma	Toxoplasma gondii	4	0
5820	NA	Apicomplexa	Aconoidasida	Haemosporida	Plasmodiidae	Plasmodium	NA	1	0
5821	NA	Apicomplexa	Aconoidasida	Haemosporida	Plasmodiidae	Plasmodium	Plasmodium berghei	15	0
582419	NA	Euryarchaeota	Thermococci	Thermococcales	Thermococcaceae	Thermococcus	Thermococcus paralvinellae	1	0
582472	NA	Proteobacteria	Gammaproteobacteria	NA	NA	Wohlfahrtiimonas	NA	1	0
5833	NA	Apicomplexa	Aconoidasida	Haemosporida	Plasmodiidae	Plasmodium	Plasmodium falciparum	4	0
584	NA	Proteobacteria	Gammaproteobacteria	Enterobacterales	Morganellaceae	Proteus	Proteus mirabilis	17	0
5850	NA	Apicomplexa	Aconoidasida	Haemosporida	Plasmodiidae	Plasmodium	Plasmodium knowlesi	13	0
585198	NA	Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Mobiluncus	Mobiluncus curtisii	1	0
5851	NA	Apicomplexa	Aconoidasida	Haemosporida	Plasmodiidae	Plasmodium	Plasmodium knowlesi	37	0
5854	NA	Apicomplexa	Aconoidasida	Haemosporida	Plasmodiidae	Plasmodium	Plasmodium reichenowi	6	0
585543	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Bacteroidaceae	Bacteroides	Bacteroides sp. D20	2	0
5855	NA	Apicomplexa	Aconoidasida	Haemosporida	Plasmodiidae	Plasmodium	Plasmodium vivax	3	0
5858	NA	Apicomplexa	Aconoidasida	Haemosporida	Plasmodiidae	Plasmodium	Plasmodium malariae	17	0
585	NA	Proteobacteria	Gammaproteobacteria	Enterobacterales	Morganellaceae	Proteus	Proteus vulgaris	1	0
588596	Fungi	Mucoromycota	Glomeromycetes	Glomerales	Glomeraceae	Rhizophagus	Rhizophagus irregularis	3	0
590646	Fungi	Ascomycota	Saccharomycetes	Saccharomycetales	Debaryomycetaceae	Yamadazyma	[Candida] tenuis	1	0
591157	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. SPB78	1	0
592026	NA	Firmicutes	Clostridia	Clostridiales	Lachnospiraceae	Catonella	Catonella morbi	39	0
5932	NA	NA	Oligohymenophorea	Hymenostomatida	NA	Ichthyophthirius	Ichthyophthirius multifiliis	7	0
59505	NA	Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Actinotignum	Actinotignum schaalii	1357	0
595468	NA	Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Actinomyces	Actinomyces hominis	1	0
59557	Fungi	Ascomycota	Pezizomycetes	Pezizales	Tuberaceae	Tuber	Tuber aestivum	1	0
59561	NA	Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Trueperella	Trueperella bernardiae	1	0
596085	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella aurantiaca	1	0
59620	NA	Firmicutes	Clostridia	Clostridiales	Clostridiaceae	Clostridium	uncultured Clostridium sp.	2	0
596327	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Porphyromonadaceae	Porphyromonas	Porphyromonas uenonis	1	0
59799	NA	NA	NA	Kinetoplastida	Trypanosomatidae	Angomonas	Angomonas deanei	1	0
59813	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Mycobacteriaceae	Mycobacterium	Mycobacterium novocastrense	2	0
59930	NA	Cyanobacteria	NA	Synechococcales	Synechococcaceae	Cyanobium	Cyanobium gracile	1	0
60136	NA	Proteobacteria	Alphaproteobacteria	Rhodobacterales	Rhodobacteraceae	Sulfitobacter	NA	1	0
61598	NA	Proteobacteria	Gammaproteobacteria	Chromatiales	Chromatiaceae	Lamprocystis	Lamprocystis purpurea	1	0
615	NA	Proteobacteria	Gammaproteobacteria	Enterobacterales	Yersiniaceae	Serratia	Serratia marcescens	10	0
62322	NA	Proteobacteria	Gammaproteobacteria	Alteromonadales	Shewanellaceae	Shewanella	Shewanella baltica	4	0
624	NA	Proteobacteria	Gammaproteobacteria	Enterobacterales	Enterobacteriaceae	Shigella	Shigella sonnei	5	0
626095	NA	Tenericutes	Mollicutes	Mycoplasmatales	Mycoplasmataceae	Ureaplasma	Ureaplasma urealyticum	2	0
626096	NA	Tenericutes	Mollicutes	Mycoplasmatales	Mycoplasmataceae	Ureaplasma	Ureaplasma urealyticum	2	0
626522	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Alloprevotella	Alloprevotella tannerae	2	0
626	NA	Proteobacteria	Gammaproteobacteria	Enterobacterales	Morganellaceae	Xenorhabdus	NA	1	0
62805	NA	NA	NA	NA	Retroviridae	NA	Human endogenous retrovirus W	1	0
630390	Fungi	Basidiomycota	Pucciniomycetes	Pucciniales	Pucciniaceae	Puccinia	Puccinia triticina	1	0
630515	NA	Actinobacteria	Actinobacteria	Propionibacteriales	Propionibacteriaceae	Microlunatus	Microlunatus soli	6	0
630	NA	Proteobacteria	Gammaproteobacteria	Enterobacterales	Yersiniaceae	Yersinia	Yersinia enterocolitica	1	0
632955	NA	Proteobacteria	Gammaproteobacteria	Pseudomonadales	Moraxellaceae	Acinetobacter	Acinetobacter rudis	1	0
632	NA	Proteobacteria	Gammaproteobacteria	Enterobacterales	Yersiniaceae	Yersinia	Yersinia pestis	1	0
633701	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella saccharolytica	1	0
634994	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Leptotrichiaceae	Leptotrichia	Leptotrichia hofstadii	3	0
635003	NA	Bacillariophyta	Bacillariophyceae	Bacillariales	Bacillariaceae	Fragilariopsis	Fragilariopsis cylindrus	6	0
636	NA	Proteobacteria	Gammaproteobacteria	Enterobacterales	Hafniaceae	Edwardsiella	Edwardsiella tarda	1	0
641	NA	Proteobacteria	Gammaproteobacteria	Vibrionales	Vibrionaceae	NA	NA	8	0
642	NA	Proteobacteria	Gammaproteobacteria	Aeromonadales	Aeromonadaceae	Aeromonas	NA	2	0
643680	Fungi	Ascomycota	Saccharomycetes	Saccharomycetales	Saccharomycetaceae	Saccharomyces	Saccharomyces cerevisiae	2	0
644352	Fungi	Ascomycota	Sordariomycetes	Magnaporthales	Magnaporthaceae	Gaeumannomyces	Gaeumannomyces tritici	1	0
644358	Fungi	Ascomycota	Sordariomycetes	Magnaporthales	Magnaporthaceae	Magnaporthiopsis	Magnaporthiopsis poae	6	0
645133	Fungi	Ascomycota	Sordariomycetes	Glomerellales	Glomerellaceae	Colletotrichum	Colletotrichum graminicola	2	0
645465	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. e14	3	0
646526	Fungi	Microsporidia	NA	NA	Enterocytozoonidae	Enterocytozoon	Enterocytozoon hepatopenaei	1	0
648	NA	Proteobacteria	Gammaproteobacteria	Aeromonadales	Aeromonadaceae	Aeromonas	Aeromonas caviae	2	0
649349	NA	Bacteroidetes	Cytophagia	Cytophagales	Cytophagaceae	Leadbetterella	Leadbetterella byssophila	1	0
649462	NA	Balneolaeota	Balneolia	Balneolales	Balneolaceae	Gracilimonas	NA	1	0
64969	NA	Proteobacteria	Gammaproteobacteria	Oceanospirillales	Oceanospirillaceae	Oceanospirillum	Oceanospirillum multiglobuliferum	1	0
649724	NA	Firmicutes	Clostridia	Clostridiales	Clostridiaceae	Clostridium	Clostridium sp. ATCC BAA-442	2	0
64972	NA	Proteobacteria	Gammaproteobacteria	Oceanospirillales	Oceanospirillaceae	Oceanobacter	Oceanobacter kriegii	1	0
649758	NA	Firmicutes	Bacilli	Lactobacillales	Lactobacillaceae	Lactobacillus	Lactobacillus brevis	1	0
649760	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella oris	1	0
649761	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella veroralis	1	0
650164	Fungi	Basidiomycota	Agaricomycetes	Polyporales	Phanerochaetaceae	Phanerochaete	Phanerochaete carnosa	1	0
65058	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium ulcerans	1	0
653386	NA	Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Actinomyces	Actinomyces sp. oral taxon 849	6	0
65393	NA	Cyanobacteria	NA	Oscillatoriales	Cyanothecaceae	Cyanothece	Cyanothece sp. PCC 7424	1	0
65496	NA	Actinobacteria	Actinobacteria	Pseudonocardiales	Pseudonocardiaceae	Actinoalloteichus	NA	1	0
65499	NA	Actinobacteria	Actinobacteria	Pseudonocardiales	Pseudonocardiaceae	Lentzea	Lentzea albida	1	0
654	NA	Proteobacteria	Gammaproteobacteria	Aeromonadales	Aeromonadaceae	Aeromonas	Aeromonas veronii	1	0
65552	NA	Deinococcus-Thermus	Deinococci	Thermales	Thermaceae	Meiothermus	Meiothermus cerbereus	1	0
655981	Fungi	Ascomycota	Leotiomycetes	NA	Pseudeurotiaceae	Pseudogymnoascus	Pseudogymnoascus destructans	5	0
656024	NA	Actinobacteria	Actinobacteria	Frankiales	Frankiaceae	Frankia	Frankia symbiont of Datisca glomerata	1	0
656179	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Burkholderiaceae	Pandoraea	Pandoraea faecigallinarum	1	0
656912	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Haemophilus	Haemophilus influenzae	44	0
656913	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Haemophilus	Haemophilus influenzae	17	0
656916	Fungi	Ascomycota	Eurotiomycetes	Eurotiales	Aspergillaceae	Aspergillus	Aspergillus arachidicola	1	0
657	NA	Proteobacteria	Gammaproteobacteria	Vibrionales	Vibrionaceae	Photobacterium	NA	1	0
658445	NA	Proteobacteria	Gammaproteobacteria	Vibrionales	Vibrionaceae	Photobacterium	Photobacterium gaetbulicola	4	0
658665	NA	Firmicutes	Clostridia	Clostridiales	Lachnospiraceae	Dorea	Dorea sp. D27	1	0
658858	NA	NA	NA	NA	Hexamitidae	Giardia	Giardia intestinalis	1	0
65959	NA	Proteobacteria	Alphaproteobacteria	Rhodospirillales	Acetobacteraceae	Acetobacter	Acetobacter pomorum	1	0
660122	Fungi	Ascomycota	Sordariomycetes	Hypocreales	Nectriaceae	Fusarium	[Nectria] haematococca	1	0
662755	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium resistens	9	0
663202	Fungi	Ascomycota	Eurotiomycetes	Onygenales	Arthrodermataceae	Trichophyton	Trichophyton verrucosum	1	0
66369	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces carpinensis	1	0
66378	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces yerevanensis	2	0
66423	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces eurocidicus	3	0
66430	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces roseus	1	0
665912	Fungi	Ascomycota	Dothideomycetes	Pleosporales	Pleosporaceae	Bipolaris	Bipolaris sorokiniana	2	0
666	NA	Proteobacteria	Gammaproteobacteria	Vibrionales	Vibrionaceae	Vibrio	Vibrio cholerae	5	0
667019	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Comamonadaceae	Curvibacter	Curvibacter putative symbiont of Hydra magnipapillata	4	0
66869	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces atroolivaceus	1	0
66875	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces catenulae	1	0
669260	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Mannheimia	Mannheimia haemolytica	1	0
669359	NA	Cyanobacteria	NA	Chroococcales	Chroococcaceae	Geminocystis	Geminocystis herdmanii	1	0
67003	NA	NA	NA	Kinetoplastida	Trypanosomatidae	Trypanosoma	Trypanosoma theileri	1	0
670483	Fungi	Basidiomycota	Agaricomycetes	Gloeophyllales	Gloeophyllaceae	Gloeophyllum	Gloeophyllum trabeum	3	0
670905	NA	Proteobacteria	Gammaproteobacteria	Enterobacterales	Enterobacteriaceae	Escherichia	Escherichia coli	1	0
670	NA	Proteobacteria	Gammaproteobacteria	Vibrionales	Vibrionaceae	Vibrio	Vibrio parahaemolyticus	4	0
671216	NA	Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Peptoniphilus	Peptoniphilus sp. oral taxon 836	2	0
671987	Fungi	Ascomycota	Dothideomycetes	Pleosporales	Pleosporaceae	Setosphaeria	Setosphaeria turcica	1	0
672	NA	Proteobacteria	Gammaproteobacteria	Vibrionales	Vibrionaceae	Vibrio	Vibrio vulnificus	1	0
67365	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sparsogenes	2	0
67386	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces yokosukanensis	2	0
674977	NA	Proteobacteria	Gammaproteobacteria	Vibrionales	Vibrionaceae	Vibrio	Vibrio alginolyticus	1	0
67854	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Actinobacillus	Actinobacillus succinogenes	3	0
679190	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella buccalis	1	0
679191	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella amnii	1	0
679200	NA	Firmicutes	Clostridia	Clostridiales	Lachnospiraceae	Johnsonella	Johnsonella ignava	1	0
679716	NA	NA	NA	Kinetoplastida	Trypanosomatidae	Trypanosoma	Trypanosoma brucei	49	0
680	NA	Proteobacteria	Gammaproteobacteria	Vibrionales	Vibrionaceae	Vibrio	Vibrio campbellii	4	0
682148	NA	Actinobacteria	Actinobacteria	Bifidobacteriales	Bifidobacteriaceae	Gardnerella	Gardnerella vaginalis	2	0
68231	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces longwoodensis	1	0
683082	NA	Proteobacteria	Epsilonproteobacteria	Campylobacterales	Campylobacteraceae	Campylobacter	Campylobacter jejuni	4	0
683260	NA	Actinobacteria	Actinobacteria	Streptosporangiales	Streptosporangiaceae	Nonomuraea	Nonomuraea maritima	1	0
683316	NA	Actinobacteria	Actinobacteria	Frankiales	Frankiaceae	Frankia	Frankia sp. EI5c	1	0
68336	NA	NA	NA	NA	NA	NA	NA	1	0
68525	NA	Proteobacteria	NA	NA	NA	NA	NA	3	0
685588	Fungi	Basidiomycota	Agaricomycetes	Agaricales	Strophariaceae	Galerina	Galerina marginata	1	0
68565	NA	Actinobacteria	Actinobacteria	Streptosporangiales	Thermomonosporaceae	Actinomadura	Actinomadura hibisca	2	0
686832	Fungi	Basidiomycota	Agaricomycetes	Agaricales	Cortinariaceae	Hebeloma	Hebeloma cylindrosporum	1	0
687861	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	Bartonellaceae	Bartonella	Bartonella schoenbuchensis	1	0
692275	Fungi	Ascomycota	Dothideomycetes	Capnodiales	Mycosphaerellaceae	Sphaerulina	Sphaerulina musiva	13	0
694068	Fungi	Basidiomycota	Agaricomycetes	Hymenochaetales	Hymenochaetaceae	Fomitiporia	Fomitiporia mediterranea	1	0
69578	NA	Actinobacteria	Actinobacteria	Micrococcales	Microbacteriaceae	Cryobacterium	NA	1	0
695850	NA	NA	Oomycetes	Saprolegniales	Saprolegniaceae	Saprolegnia	Saprolegnia parasitica	11	0
697331	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Basfia	NA	1	0
702438	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella oulorum	3	0
702443	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Bacteroidaceae	Bacteroides	Bacteroides ovatus	1	0
702444	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Bacteroidaceae	Bacteroides	Bacteroides xylanisolvens	4	0
702446	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Bacteroidaceae	Bacteroides	Bacteroides vulgatus	3	0
702447	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Bacteroidaceae	Bacteroides	Bacteroides xylanisolvens	5	0
702957	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium sp. NML92-0415	1	0
703135	Fungi	Basidiomycota	Agaricomycetes	Agaricales	Amanitaceae	Amanita	Amanita thiersii	1	0
703756	Fungi	Ascomycota	Sordariomycetes	Glomerellales	Glomerellaceae	Colletotrichum	Colletotrichum simmondsii	1	0
706438	NA	Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Actinomyces	Actinomyces sp. oral taxon 171	1	0
708187	Fungi	Ascomycota	Sordariomycetes	Glomerellales	Glomerellaceae	Colletotrichum	Colletotrichum chlorophyti	1	0
710731	NA	Acidobacteria	NA	NA	NA	NA	uncultured Acidobacteria bacterium HF4000_26D02	1	0
712148	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Aggregatibacter	Aggregatibacter sp. oral taxon 458	1	0
712	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	NA	NA	1065	0
71421	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Haemophilus	Haemophilus influenzae	99	0
714	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Aggregatibacter	Aggregatibacter actinomycetemcomitans	6	0
715989	Fungi	Ascomycota	NA	NA	NA	NA	NA	2	0
715	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Actinobacillus	Actinobacillus pleuropneumoniae	1	0
716545	Fungi	Ascomycota	NA	NA	NA	NA	NA	2	0
716546	Fungi	Ascomycota	NA	NA	NA	NA	NA	1	0
717605	NA	Firmicutes	Bacilli	Bacillales	Paenibacillaceae	Thermobacillus	Thermobacillus composti	1	0
717610	NA	Proteobacteria	Gammaproteobacteria	Vibrionales	Vibrionaceae	Vibrio	NA	1	0
717646	Fungi	Ascomycota	Dothideomycetes	Capnodiales	Teratosphaeriaceae	Baudoinia	Baudoinia panamericana	1	0
71784	Fungi	Basidiomycota	Tremellomycetes	Tremellales	Naemateliaceae	Naematelia	Naematelia encephala	4	0
717944	Fungi	Basidiomycota	Agaricomycetes	Polyporales	Polyporaceae	Trametes	Trametes versicolor	1	0
717962	NA	Firmicutes	Clostridia	Clostridiales	Lachnospiraceae	Coprococcus	Coprococcus catus	1	0
718014	NA	Actinobacteria	Actinobacteria	Streptosporangiales	Streptosporangiaceae	Microbispora	Microbispora sp. GMKU363	1	0
71804	NA	NA	NA	Kinetoplastida	Trypanosomatidae	Trypanosoma	Trypanosoma grayi	3	0
721885	Fungi	Basidiomycota	Agaricomycetes	Russulales	Stereaceae	Stereum	Stereum hirsutum	1	0
72275	NA	Proteobacteria	Gammaproteobacteria	Alteromonadales	Alteromonadaceae	NA	NA	1	0
72294	NA	Proteobacteria	Epsilonproteobacteria	Campylobacterales	Campylobacteraceae	NA	NA	10	0
723601	NA	Actinobacteria	Actinobacteria	NA	NA	NA	uncultured actinobacterium HF0130_15N16	1	0
724	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Haemophilus	NA	3610	0
72520	NA	Eustigmatophyceae	NA	Eustigmatales	Monodopsidaceae	Nannochloropsis	Nannochloropsis gaditana	2	0
726	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Haemophilus	Haemophilus haemolyticus	17	0
727	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Haemophilus	Haemophilus influenzae	4009	0
728	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Avibacterium	Avibacterium paragallinarum	2	0
729	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Haemophilus	Haemophilus parainfluenzae	7	0
731	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Histophilus	Histophilus somni	2	0
73230	Fungi	Ascomycota	Eurotiomycetes	Onygenales	Ajellomycetaceae	Emmonsia	Emmonsia crescens	1	0
73239	NA	Apicomplexa	Aconoidasida	Haemosporida	Plasmodiidae	Plasmodium	Plasmodium yoelii	1	0
732	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Aggregatibacter	Aggregatibacter aphrophilus	8	0
733	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Haemophilus	Haemophilus haemoglobinophilus	4	0
735	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Haemophilus	Haemophilus parahaemolyticus	1	0
738	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Glaesserella	Glaesserella parasuis	1	0
739	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Aggregatibacter	Aggregatibacter segnis	1	0
741275	Fungi	Basidiomycota	Agaricomycetes	Corticiales	Punctulariaceae	Punctularia	Punctularia strigosozonata	1	0
741276	Fungi	Basidiomycota	Microbotryomycetes	Sporidiobolales	Sporidiobolaceae	Rhodotorula	Rhodotorula taiwanensis	2	0
741705	Fungi	Basidiomycota	Agaricomycetes	Boletales	Coniophoraceae	Coniophora	Coniophora puteana	1	0
742152	Fungi	Basidiomycota	Agaricomycetes	Polyporales	Laetiporaceae	Wolfiporia	Wolfiporia cocos	1	0
742723	NA	Firmicutes	Clostridia	Clostridiales	Lachnospiraceae	NA	Lachnospiraceae bacterium 2_1_46FAA	1	0
743788	Fungi	Basidiomycota	Agaricomycetes	Polyporales	Fomitopsidaceae	Fomitopsis	Fomitopsis pinicola	1	0
744980	NA	Proteobacteria	Alphaproteobacteria	Rhodobacterales	Rhodobacteraceae	Roseibium	Roseibium sp. TrichSKD4	1	0
745531	Fungi	Basidiomycota	Agaricomycetes	Polyporales	Phanerochaetaceae	Phlebiopsis	Phlebiopsis gigantea	1	0
745	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Pasteurella	NA	1	0
74700	NA	Tenericutes	Mollicutes	Entomoplasmatales	Entomoplasmataceae	Entomoplasma	Entomoplasma freundtii	1	0
747089	Fungi	Mucoromycota	Glomeromycetes	Glomerales	Glomeraceae	Rhizophagus	Rhizophagus irregularis	3	0
747377	NA	Firmicutes	Clostridia	Clostridiales	Clostridiaceae	Clostridium	Clostridium sp. DMHC 10	1	0
747	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Pasteurella	Pasteurella multocida	29	0
755172	NA	Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Peptoniphilus	Peptoniphilus coxii	8964	0
755272	NA	NA	NA	NA	NA	NA	Micromonas pusilla virus 12T	1	0
755	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Avibacterium	Avibacterium gallinarum	1	0
75654	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Oxalobacteraceae	Duganella	NA	1	0
756982	Fungi	Ascomycota	Orbiliomycetes	Orbiliales	Orbiliaceae	Arthrobotrys	Arthrobotrys oligospora	1	0
758	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Rodentibacter	Rodentibacter pneumotropicus	6	0
75984	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Mannheimia	NA	1	0
761	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Pasteurella	Pasteurella testudinis	1	0
762948	NA	Actinobacteria	Actinobacteria	Micrococcales	Micrococcaceae	Rothia	Rothia dentocariosa	4	0
762964	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Haemophilus	Haemophilus sp. oral taxon 851	1	0
762965	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Haemophilus	Haemophilus sp. oral taxon 851	15	0
762968	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Paraprevotella	Paraprevotella clara	1	0
762982	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Paraprevotella	Paraprevotella xylaniphila	4	0
763407	Fungi	Mucoromycota	NA	Mucorales	Phycomycetaceae	Phycomyces	Phycomyces blakesleeanus	41	0
765067	NA	Actinobacteria	Actinobacteria	Propionibacteriales	Propionibacteriaceae	Cutibacterium	Cutibacterium acnes	3	0
765076	NA	Actinobacteria	Actinobacteria	Propionibacteriales	Propionibacteriaceae	Cutibacterium	Cutibacterium acnes	4	0
76517	NA	Proteobacteria	Epsilonproteobacteria	Campylobacterales	Campylobacteraceae	Campylobacter	Campylobacter hominis	1	0
765257	Fungi	Basidiomycota	Agaricomycetes	Boletales	Pisolithaceae	Pisolithus	Pisolithus microcarpus	3	0
765868	Fungi	Ascomycota	Dothideomycetes	Pleosporales	Massarinaceae	Stagonospora	Stagonospora sp. SRC1lsM3a	2	0
765915	Fungi	Blastocladiomycota	Blastocladiomycetes	Blastocladiales	Catenariaceae	Catenaria	Catenaria anguillulae	2	0
766039	Fungi	Ascomycota	Dothideomycetes	NA	NA	Acidomyces	Acidomyces richmondensis	1	0
76833	NA	Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Actinobaculum	NA	232	0
77044	Fungi	Ascomycota	Sordariomycetes	Xylariales	Xylariaceae	Rosellinia	Rosellinia necatrix	3	0
77133	NA	NA	NA	NA	NA	NA	uncultured bacterium	12	0
77519	NA	Apicomplexa	Aconoidasida	Haemosporida	Plasmodiidae	Plasmodium	Plasmodium gonderi	2	0
780	NA	Proteobacteria	Alphaproteobacteria	Rickettsiales	Rickettsiaceae	Rickettsia	NA	5	0
78156	Fungi	Ascomycota	Leotiomycetes	NA	Pseudeurotiaceae	Pseudogymnoascus	NA	2	0
80816	NA	Proteobacteria	Deltaproteobacteria	Myxococcales	Kofleriaceae	Haliangium	Haliangium ochraceum	1	0
80854	NA	Proteobacteria	Gammaproteobacteria	Alteromonadales	Moritellaceae	Moritella	Moritella viscosa	1	0
80864	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Comamonadaceae	NA	NA	1	0
813	NA	Chlamydiae	Chlamydiia	Chlamydiales	Chlamydiaceae	Chlamydia	Chlamydia trachomatis	115	0
81529	NA	NA	NA	Choanoflagellida	Salpingoecidae	NA	NA	1	0
816	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Bacteroidaceae	Bacteroides	NA	32	0
817	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Bacteroidaceae	Bacteroides	Bacteroides fragilis	13	0
81852	NA	Firmicutes	Bacilli	Lactobacillales	Enterococcaceae	NA	NA	4	0
818	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Bacteroidaceae	Bacteroides	Bacteroides thetaiotaomicron	7	0
820	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Bacteroidaceae	Bacteroides	Bacteroides uniformis	1	0
821	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Bacteroidaceae	Bacteroides	Bacteroides vulgatus	4	0
827	NA	Proteobacteria	Epsilonproteobacteria	Campylobacterales	Campylobacteraceae	Campylobacter	Campylobacter ureolyticus	6085	0
830	NA	Firmicutes	Clostridia	Clostridiales	Lachnospiraceae	Butyrivibrio	NA	1	0
83231	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella brevis	1	0
832	NA	Fibrobacteres	Fibrobacteria	Fibrobacterales	Fibrobacteraceae	Fibrobacter	NA	1	0
83451	NA	Proteobacteria	Deltaproteobacteria	Myxococcales	Archangiaceae	Archangium	Archangium violaceum	1	0
83555	NA	Chlamydiae	Chlamydiia	Chlamydiales	Chlamydiaceae	Chlamydia	Chlamydia abortus	3	0
83656	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces tsukubensis	1	0
836	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Porphyromonadaceae	Porphyromonas	NA	10751	0
837	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Porphyromonadaceae	Porphyromonas	Porphyromonas gingivalis	6	0
838	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	NA	1281	0
839	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella ruminicola	2	0
84999	NA	Actinobacteria	Coriobacteriia	Coriobacteriales	NA	NA	NA	1	0
85006	NA	Actinobacteria	Actinobacteria	Micrococcales	NA	NA	NA	1	0
85007	NA	Actinobacteria	Actinobacteria	Corynebacteriales	NA	NA	NA	29	0
85009	NA	Actinobacteria	Actinobacteria	Propionibacteriales	NA	NA	NA	7	0
85023	NA	Actinobacteria	Actinobacteria	Micrococcales	Microbacteriaceae	NA	NA	1	0
85025	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Nocardiaceae	NA	NA	1	0
85056	NA	NA	NA	Kinetoplastida	Trypanosomatidae	Trypanosoma	Trypanosoma cruzi	7	0
85057	NA	NA	NA	Kinetoplastida	Trypanosomatidae	Trypanosoma	Trypanosoma cruzi	5	0
851	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Fusobacterium	Fusobacterium nucleatum	1	0
85404	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Mannheimia	Mannheimia varigena	1	0
857291	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella histicola	1	0
858619	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium variabile	1	0
858893	Fungi	Ascomycota	Eurotiomycetes	Chaetothyriales	Herpotrichiellaceae	Exophiala	Exophiala dermatitidis	2	0
859	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Fusobacterium	Fusobacterium necrophorum	1	0
86049	Fungi	Ascomycota	Eurotiomycetes	Chaetothyriales	Herpotrichiellaceae	Cladophialophora	Cladophialophora carrionii	3	0
86182	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Comamonadaceae	Curvibacter	Curvibacter lanceolatus	1	0
862422	NA	Actinobacteria	Actinobacteria	Micrococcales	Cellulomonadaceae	Actinotalea	Actinotalea fermentans	2	0
862512	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium accolens	6	0
862515	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella marshii	1	0
862964	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Haemophilus	Haemophilus influenzae	16	0
862965	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Haemophilus	Haemophilus parainfluenzae	2	0
864141	NA	Apicomplexa	Aconoidasida	Haemosporida	Plasmodiidae	Plasmodium	Plasmodium ovale	1	0
864142	NA	Apicomplexa	Aconoidasida	Haemosporida	Plasmodiidae	Plasmodium	Plasmodium ovale	23	0
86661	NA	Firmicutes	Bacilli	Bacillales	Bacillaceae	Bacillus	NA	1	0
866771	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella disiens	29	0
866779	NA	Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Finegoldia	Finegoldia magna	1	0
868129	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella bivia	2	0
872	NA	Proteobacteria	Deltaproteobacteria	Desulfovibrionales	Desulfovibrionaceae	Desulfovibrio	NA	1	0
873513	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella buccae	1	0
875932	NA	Proteobacteria	Gammaproteobacteria	Vibrionales	Vibrionaceae	Photobacterium	Photobacterium sanguinicancri	1	0
87626	NA	Proteobacteria	Gammaproteobacteria	Alteromonadales	Pseudoalteromonadaceae	Pseudoalteromonas	Pseudoalteromonas tunicata	5	0
879305	NA	Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Anaerococcus	Anaerococcus prevotii	2	0
879308	NA	Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Peptoniphilus	Peptoniphilus sp. oral taxon 375	5	0
883066	NA	Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Actinobaculum	Actinobaculum massiliense	255	0
883067	NA	Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Actinotignum	Actinotignum schaalii	13	0
883077	NA	Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Actinomyces	Actinomyces turicensis	3	0
883158	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella micans	1	0
883161	NA	Actinobacteria	Actinobacteria	Propionibacteriales	Propionibacteriaceae	Propionimicrobium	Propionimicrobium lymphophilum	3	0
883165	NA	Proteobacteria	Epsilonproteobacteria	Campylobacterales	Campylobacteraceae	Campylobacter	Campylobacter ureolyticus	8	0
88382	NA	Actinobacteria	Actinobacteria	Micrococcales	Promicromonosporaceae	Promicromonospora	Promicromonospora sukumoe	3	0
88456	NA	Apicomplexa	Coccidia	Eucoccidiorida	Eimeriidae	Cyclospora	Cyclospora cayetanensis	1	0
887324	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Actinobacillus	Actinobacillus ureae	1	0
887929	NA	Firmicutes	Clostridia	Clostridiales	Eubacteriaceae	Pseudoramibacter	Pseudoramibacter alactolyticus	4	0
888019	NA	Actinobacteria	Actinobacteria	Micrococcales	Micrococcaceae	Rothia	Rothia aeria	1	0
888050	NA	Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Actinomyces	Actinomyces cardiffensis	1	0
888054	NA	Bacteroidetes	NA	NA	NA	NA	Bacteroidetes bacterium oral taxon 272	1	0
888056	NA	Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Actinomyces	Actinomyces sp. oral taxon 448	1	0
888057	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Aggregatibacter	Aggregatibacter segnis	7	0
888439	NA	Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Actinomyces	Actinomyces neuii	19	0
888728	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Haemophilus	Haemophilus aegyptius	30	0
888828	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Haemophilus	Haemophilus parainfluenzae	10	0
888832	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella salivae	4	0
89373	NA	Bacteroidetes	Cytophagia	Cytophagales	Cytophagaceae	NA	NA	1	0
89382	NA	NA	NA	NA	Retroviridae	NA	Human endogenous retrovirus W	1	0
90370	NA	Proteobacteria	Gammaproteobacteria	Enterobacterales	Enterobacteriaceae	Salmonella	Salmonella enterica	3	0
905079	NA	NA	Cryptophyta	Pyrenomonadales	Geminigeraceae	Guillardia	Guillardia theta	1	0
908125	NA	NA	NA	NA	Geminiviridae	Begomovirus	Okra enation leaf curl virus	1	0
908285	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Necropsobacter	Necropsobacter rosorum	2	0
908338	NA	Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Peptoniphilus	Peptoniphilus harei	59	0
910312	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Porphyromonadaceae	Porphyromonas	Porphyromonas asaccharolytica	2	0
91061	NA	Firmicutes	Bacilli	NA	NA	NA	NA	23	0
911162	Fungi	Ascomycota	Sordariomycetes	Hypocreales	Ophiocordycipitaceae	Ophiocordyceps	Ophiocordyceps sinensis	1	0
913028	NA	Proteobacteria	Gammaproteobacteria	Enterobacterales	Yersiniaceae	Yersinia	Yersinia enterocolitica	1	0
91347	NA	Proteobacteria	Gammaproteobacteria	Enterobacterales	NA	NA	NA	27	0
92644	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces malaysiensis	1	0
926570	NA	Proteobacteria	Alphaproteobacteria	Rhodospirillales	Acetobacteraceae	Acidiphilium	Acidiphilium multivorum	1	0
92938	NA	Cyanobacteria	NA	Nostocales	Hapalosiphonaceae	Fischerella	Fischerella muscicola	1	0
929439	NA	NA	NA	Kinetoplastida	Trypanosomatidae	Leishmania	Leishmania mexicana	2	0
930090	Fungi	Ascomycota	Dothideomycetes	Pleosporales	Pleosporaceae	Bipolaris	Bipolaris oryzae	1	0
93064	NA	Proteobacteria	Alphaproteobacteria	Sphingomonadales	Sphingomonadaceae	Sphingomonas	Sphingomonas koreensis	1	0
930991	Fungi	Basidiomycota	Agaricomycetes	Boletales	Paxillaceae	Paxillus	Paxillus rubicundulus	1	0
931089	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium deserti	2	0
931537	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Nocardiaceae	Nocardia	Nocardia grenadensis	1	0
931890	Fungi	Ascomycota	Saccharomycetes	Saccharomycetales	Saccharomycetaceae	Eremothecium	Eremothecium cymbalariae	1	0
93217	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Burkholderiaceae	Pandoraea	NA	1	0
935652	NA	Apicomplexa	Coccidia	Eucoccidiorida	Sarcocystidae	Toxoplasma	Toxoplasma gondii	7	0
935866	NA	Actinobacteria	Actinobacteria	Propionibacteriales	Nocardioidaceae	Nocardioides	Nocardioides sp. J54	1	0
936155	NA	Proteobacteria	Epsilonproteobacteria	Campylobacterales	Helicobacteraceae	Helicobacter	Helicobacter felis	2	0
936554	NA	Proteobacteria	Epsilonproteobacteria	Campylobacterales	Campylobacteraceae	Campylobacter	Campylobacter sp. FOBRC14	1	0
936562	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Fusobacterium	Fusobacterium sp. CM21	1	0
93681	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	NA	Roseateles	NA	1	0
941280	NA	Proteobacteria	Gammaproteobacteria	Enterobacterales	Enterobacteriaceae	Escherichia	Escherichia coli	6	0
941824	NA	Firmicutes	Clostridia	Clostridiales	Clostridiaceae	Thermobrachium	Thermobrachium celere	2	0
941907	NA	Proteobacteria	Alphaproteobacteria	Sphingomonadales	Sphingomonadaceae	Sphingomonas	Sphingomonas indica	1	0
94254	NA	Bacteroidetes	Cytophagia	Cytophagales	Cytophagaceae	Dyadobacter	Dyadobacter fermentans	1	0
943118	NA	Apicomplexa	Coccidia	Eucoccidiorida	Sarcocystidae	Toxoplasma	Toxoplasma gondii	3	0
944288	Fungi	Basidiomycota	Agaricomycetes	Amylocorticiales	Amylocorticiaceae	Plicaturopsis	Plicaturopsis crispa	1	0
945553	Fungi	Basidiomycota	Agaricomycetes	Agaricales	Strophariaceae	Hypholoma	Hypholoma sublateritium	1	0
946362	NA	NA	NA	Choanoflagellida	Salpingoecidae	Salpingoeca	Salpingoeca rosetta	17	0
94643	NA	Apicomplexa	Coccidia	Eucoccidiorida	Sarcocystidae	Besnoitia	Besnoitia besnoiti	3	0
946678	NA	Bacteroidetes	Flavobacteriia	Flavobacteriales	Flavobacteriaceae	Flavobacterium	Flavobacterium araucananum	1	0
948	NA	Proteobacteria	Alphaproteobacteria	Rickettsiales	Anaplasmataceae	Anaplasma	Anaplasma phagocytophilum	2	0
958	NA	Proteobacteria	Oligoflexia	Bdellovibrionales	Bdellovibrionaceae	Bdellovibrio	NA	1	0
96344	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Burkholderiaceae	Cupriavidus	Cupriavidus oxalaticus	1	0
97195	NA	NA	NA	NA	Phycodnaviridae	Raphidovirus	Heterosigma akashiwo virus 01	2	0
976	NA	Bacteroidetes	NA	NA	NA	NA	NA	104	0
98228	NA	Firmicutes	Bacilli	Bacillales	Bacillaceae	Bacillus	Bacillus sp. OxB-1	1	0
983506	Fungi	Basidiomycota	Agaricomycetes	Cantharellales	Ceratobasidiaceae	Rhizoctonia	Rhizoctonia solani	2	0
98403	Fungi	Ascomycota	Sordariomycetes	Hypocreales	Ophiocordycipitaceae	Drechmeria	Drechmeria coniospora	265	0
984307	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Burkholderiaceae	Paraburkholderia	Paraburkholderia kururiensis	1	0
985895	Fungi	Ascomycota	Dothideomycetes	Pleosporales	Leptosphaeriaceae	Leptosphaeria	Leptosphaeria maculans	1	0
98671	NA	Actinobacteria	Actinobacteria	Micrococcales	Micrococcaceae	Pseudoglutamicibacter	Pseudoglutamicibacter albus	1	0
98765	Fungi	Basidiomycota	Agaricomycetes	Polyporales	Meruliaceae	Phlebia	Phlebia centrifuga	2	0
988821	NA	Actinobacteria	Actinobacteria	Micrococcales	Cellulomonadaceae	Cellulomonas	Cellulomonas marina	2	0
990650	Fungi	Basidiomycota	Agaricomycetes	Geastrales	Sphaerobolaceae	Sphaerobolus	Sphaerobolus stellatus	1	0
991929	NA	Proteobacteria	Gammaproteobacteria	Vibrionales	Vibrionaceae	Vibrio	Vibrio cholerae	4	0
993689	NA	Proteobacteria	Gammaproteobacteria	Xanthomonadales	Rhodanobacteraceae	Metallibacterium	Metallibacterium scheffleri	1	0
994086	Fungi	Basidiomycota	Agaricomycetes	Boletales	Paxillaceae	Hydnomerulius	Hydnomerulius pinastri	3	0
997353	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella pallens	2	0
999422	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella maculosa	1	0
999810	Fungi	Ascomycota	Leotiomycetes	Helotiales	Sclerotiniaceae	Botrytis	Botrytis cinerea	1	0
999898	NA	Firmicutes	Clostridia	Clostridiales	Peptococcaceae	NA	Peptococcaceae bacterium CEB3	1	0
