NCBI-TaxID	Kingdom	Phylum	Class	Order	Family	Genus	Species	Number_of_Reads	Relative_Abundance
1000569	NA	Firmicutes	Negativicutes	Veillonellales	Veillonellaceae	Megasphaera	Megasphaera sp. UPII 135-E	5	0
1001832	Fungi	Ascomycota	Sordariomycetes	Xylariales	Hypoxylaceae	Daldinia	Daldinia sp. EC12	1	0
1003181	NA	Proteobacteria	Gammaproteobacteria	Thiotrichales	Thiotrichaceae	Thiomargarita	Candidatus Thiomargarita nelsonii	1	0
1005945	NA	Actinobacteria	Actinobacteria	Propionibacteriales	Nocardioidaceae	Nocardioides	Nocardioides psychrotolerans	1	0
1006155	NA	Firmicutes	Bacilli	Bacillales	Listeriaceae	Listeria	Listeria weihenstephanensis	1	0
100716	NA	Chlorobi	Chlorobia	Chlorobiales	Chlorobiaceae	Chloroherpeton	Chloroherpeton thalassium	1	0
100787	Fungi	Ascomycota	Sordariomycetes	Glomerellales	Plectosphaerellaceae	Verticillium	Verticillium longisporum	2	0
1008153	NA	Euryarchaeota	Halobacteria	Halobacteriales	Halobacteriaceae	Halalkalicoccus	Halalkalicoccus paucihalophilus	1	0
100816	Fungi	Ascomycota	Sordariomycetes	Sordariales	NA	Madurella	Madurella mycetomatis	1	0
100860	NA	NA	Oomycetes	Saprolegniales	Saprolegniaceae	Aphanomyces	NA	1	0
101510	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Nocardiaceae	Rhodococcus	Rhodococcus jostii	2	0
101571	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Burkholderiaceae	Burkholderia	Burkholderia ubonensis	1	0
102106	NA	Actinobacteria	Coriobacteriia	Coriobacteriales	Coriobacteriaceae	Collinsella	NA	1	0
102127	NA	Cyanobacteria	NA	Oscillatoriales	Coleofasciculaceae	Geitlerinema	Geitlerinema sp. PCC 7105	1	0
1022	NA	Proteobacteria	Gammaproteobacteria	Thiotrichales	Thiotrichaceae	Beggiatoa	Beggiatoa alba	2	0
102684	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus infantarius	1	0
102891	NA	Actinobacteria	Actinobacteria	Frankiales	Frankiaceae	Frankia	Frankia sp. ACN1ag	1	0
1032069	NA	Proteobacteria	Epsilonproteobacteria	Campylobacterales	Campylobacteraceae	Campylobacter	Campylobacter ureolyticus	189	0
1032505	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Fusobacterium	Fusobacterium sp. OBRC1	15	0
1032526	NA	Verrucomicrobia	Verrucomicrobiae	Verrucomicrobiales	Verrucomicrobia subdivision 3	Pedosphaera	NA	1	0
1032851	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium nuruki	3	0
1035190	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus oralis	1	0
1035195	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium durum	2	0
1036612	Fungi	Ascomycota	Eurotiomycetes	Eurotiales	Aspergillaceae	Aspergillus	Aspergillus sydowii	1	0
1036719	Fungi	Ascomycota	Sordariomycetes	Glomerellales	Plectosphaerellaceae	Verticillium	NA	2	0
1036723	NA	Apicomplexa	Aconoidasida	Haemosporida	Plasmodiidae	Plasmodium	Plasmodium falciparum	1	0
1036724	NA	Apicomplexa	Aconoidasida	Haemosporida	Plasmodiidae	Plasmodium	Plasmodium falciparum	1	0
1036808	Fungi	Basidiomycota	Agaricomycetes	Boletales	Sclerodermataceae	Scleroderma	Scleroderma citrinum	2	0
10370	NA	NA	NA	Herpesvirales	Herpesviridae	Roseolovirus	Human betaherpesvirus 6A	1	0
1037362	NA	Proteobacteria	Alphaproteobacteria	Rhodobacterales	Rhodobacteraceae	Tropicibacter	Tropicibacter phthalicicus	1	0
1037660	Fungi	Basidiomycota	Exobasidiomycetes	Georgefischeriales	Tilletiariaceae	Tilletiaria	Tilletiaria anomala	7	0
103817	NA	Actinobacteria	Actinobacteria	Micrococcales	Intrasporangiaceae	Janibacter	Janibacter terrae	1	0
1042404	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus thermophilus	39	0
1043003	Fungi	Ascomycota	Dothideomycetes	Dothideales	Saccotheciaceae	Aureobasidium	Aureobasidium melanogenum	1	0
1043004	Fungi	Ascomycota	Dothideomycetes	Dothideales	Saccotheciaceae	Aureobasidium	Aureobasidium namibiae	4	0
1043005	Fungi	Ascomycota	Dothideomycetes	Dothideales	Saccotheciaceae	Aureobasidium	Aureobasidium subglaciale	1	0
1046629	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus salivarius	1	0
104669	Fungi	Basidiomycota	Tremellomycetes	Tremellales	Cryptococcaceae	Cryptococcus	Cryptococcus amylolentus	2	0
1047049	NA	Candidatus Atribacteria	NA	NA	NA	NA	NA	1	0
1048332	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus salivarius	1	0
1050174	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium epidermidicanis	2	0
1051072	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus equi	1	0
1051074	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus thermophilus	167	0
105487	Fungi	Ascomycota	Sordariomycetes	Diaporthales	Valsaceae	Valsa	Valsa mali	1	0
1055687	NA	NA	NA	Kinetoplastida	Trypanosomatidae	Trypanosoma	Trypanosoma vivax	9	0
105696	Fungi	Ascomycota	Dothideomycetes	Pleosporales	Didymellaceae	Epicoccum	Epicoccum nigrum	1	0
1057002	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	Rhizobiaceae	Ensifer	Ensifer sp. BR816	2	0
106004	Fungi	Basidiomycota	Microbotryomycetes	Leucosporidiales	Leucosporidiaceae	Leucosporidium	Leucosporidium creatinivorum	2	0
106589	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Burkholderiaceae	Cupriavidus	NA	1	0
1068625	NA	NA	NA	Kinetoplastida	Trypanosomatidae	Trypanosoma	Trypanosoma congolense	9	0
1069073	NA	Actinobacteria	Actinobacteria	Pseudonocardiales	Pseudonocardiaceae	Amycolatopsis	Amycolatopsis halophila	1	0
1069443	Fungi	Mucoromycota	NA	Mortierellales	Mortierellaceae	Mortierella	Mortierella verticillata	10	0
1071378	Fungi	Ascomycota	Saccharomycetes	Saccharomycetales	Saccharomycetaceae	Naumovozyma	Naumovozyma dairenensis	1	0
1072256	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium uterequi	1	0
1072389	Fungi	Ascomycota	Leotiomycetes	Helotiales	Dermateaceae	Marssonina	Marssonina brunnea	4	0
1073569	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus thermophilus	2	0
1073570	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus thermophilus	8	0
1073571	NA	Firmicutes	Bacilli	Bacillales	Paenibacillaceae	Paenibacillus	Paenibacillus riograndensis	1	0
1074494	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus salivarius	2	0
1075402	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces oceani	3	0
1076523	NA	Proteobacteria	Gammaproteobacteria	Xanthomonadales	Rhodanobacteraceae	Rhodanobacter	Rhodanobacter sp. OR87	2	0
1077348	Fungi	Basidiomycota	Agaricomycetes	Polyporales	Polyporaceae	Ganoderma	Ganoderma sinense	1	0
1077972	NA	Actinobacteria	Actinobacteria	Micrococcales	Micrococcaceae	Arthrobacter	Arthrobacter globiformis	4	0
1080071	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus orisasini	2	0
108007	NA	Synergistetes	Synergistia	Synergistales	Synergistaceae	Thermanaerovibrio	Thermanaerovibrio velox	1	0
1081109	Fungi	Ascomycota	Sordariomycetes	Hypocreales	Clavicipitaceae	Moelleriella	Moelleriella libera	1	0
1085	NA	Proteobacteria	Alphaproteobacteria	Rhodospirillales	Rhodospirillaceae	Rhodospirillum	Rhodospirillum rubrum	1	0
108892	Fungi	Basidiomycota	Agaricomycetes	Hymenochaetales	Hymenochaetaceae	Sanghuangporus	Sanghuangporus baumii	2	0
1089449	Fungi	Ascomycota	Sordariomycetes	Hypocreales	Nectriaceae	Fusarium	Fusarium oxysporum	1	0
1091495	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Alcaligenaceae	Taylorella	Taylorella asinigenitalis	3	0
109328	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Leptotrichiaceae	Leptotrichia	Leptotrichia trevisanii	3	0
109329	NA	Actinobacteria	Actinobacteria	Streptosporangiales	Nocardiopsaceae	Nocardiopsis	Nocardiopsis trehalosi	2	0
1094469	NA	Proteobacteria	Gammaproteobacteria	Pseudomonadales	Moraxellaceae	Acinetobacter	Acinetobacter baumannii	3	0
1095629	Fungi	Basidiomycota	Agaricomycetes	Agaricales	Tricholomataceae	Laccaria	Laccaria amethystina	3	0
1095630	Fungi	Ascomycota	Leotiomycetes	Helotiales	Helotiaceae	Meliniomyces	Meliniomyces bicolor	1	0
1097670	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus agalactiae	1	0
109790	NA	Firmicutes	Bacilli	Lactobacillales	Lactobacillaceae	Lactobacillus	Lactobacillus jensenii	3	0
1097	NA	Chlorobi	Chlorobia	Chlorobiales	Chlorobiaceae	Chlorobaculum	Chlorobaculum tepidum	1	0
1100824	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. SceaMP-e96	1	0
1101373	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	NA	Tepidimonas	Tepidimonas fonticaldi	1	0
110319	NA	Actinobacteria	Actinobacteria	Propionibacteriales	Nocardioidaceae	Nocardioides	Nocardioides sp. CF8	1	0
110365	NA	Apicomplexa	Gregarinasina	Eugregarinorida	Gregarinidae	Gregarina	Gregarina niphandrodes	3	0
1108050	Fungi	Basidiomycota	Agaricomycetes	Cantharellales	Ceratobasidiaceae	Rhizoctonia	Rhizoctonia solani	2	0
110932	NA	Actinobacteria	Actinobacteria	Micrococcales	Microbacteriaceae	Leifsonia	NA	1	0
1111077	Fungi	Ascomycota	Sordariomycetes	Hypocreales	Clavicipitaceae	Claviceps	Claviceps purpurea	1	0
1111454	NA	Firmicutes	Negativicutes	Veillonellales	Veillonellaceae	Megasphaera	Megasphaera sp. BV3C16-1	2	0
1111760	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus troglodytae	2	0
1112253	NA	Chlamydiae	Chlamydiia	Chlamydiales	Chlamydiaceae	Chlamydia	Chlamydia psittaci	1	0
1114965	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus parasanguinis	3	0
111527	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Burkholderiaceae	Burkholderia	NA	1	0
1120755	NA	Apicomplexa	Aconoidasida	Haemosporida	Plasmodiidae	Plasmodium	Plasmodium cynomolgi	4	0
112090	NA	NA	Oomycetes	Saprolegniales	Saprolegniaceae	Aphanomyces	Aphanomyces astaci	1	0
1121310	NA	Firmicutes	Clostridia	Clostridiales	Clostridiaceae	Clostridium	Clostridium felsineum	1	0
1121321	NA	Firmicutes	Clostridia	Clostridiales	Peptostreptococcaceae	Asaccharospora	Asaccharospora irregularis	1	0
1122169	NA	Proteobacteria	Gammaproteobacteria	Legionellales	Legionellaceae	Legionella	Legionella shakespearei	1	0
1124188	NA	Bacteroidetes	Flavobacteriia	Flavobacteriales	Flavobacteriaceae	Flavobacterium	Flavobacterium fontis	1	0
1125693	NA	Proteobacteria	Gammaproteobacteria	Enterobacterales	Morganellaceae	Proteus	Proteus mirabilis	2	0
1125694	NA	Proteobacteria	Gammaproteobacteria	Enterobacterales	Morganellaceae	Proteus	Proteus mirabilis	3	0
1125779	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium pyruviciproducens	2120	0
1126	NA	Cyanobacteria	NA	Chroococcales	Microcystaceae	Microcystis	Microcystis aeruginosa	1	0
1127134	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Nocardiaceae	Nocardia	Nocardia cyriacigeorgica	7	0
1129771	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Leptotrichiaceae	NA	NA	489	0
1130380	NA	Spirochaetes	NA	NA	NA	NA	NA	1	0
1130820	NA	Apicomplexa	Coccidia	Eucoccidiorida	Sarcocystidae	Toxoplasma	Toxoplasma gondii	2	0
1130821	NA	Apicomplexa	Coccidia	Eucoccidiorida	Sarcocystidae	Toxoplasma	Toxoplasma gondii	1	0
1133968	NA	Apicomplexa	Aconoidasida	NA	Babesiidae	Babesia	Babesia microti	1	0
1136105	NA	Cyanobacteria	NA	Nostocales	Tolypothrichaceae	Tolypothrix	Tolypothrix campylonemoides	1	0
1137130	NA	Firmicutes	Bacilli	Bacillales	Staphylococcaceae	Staphylococcus	Staphylococcus aureus	1	0
1140001	NA	Firmicutes	Bacilli	Lactobacillales	Enterococcaceae	Enterococcus	Enterococcus durans	3	0
1144522	NA	NA	NA	Tritrichomonadida	Tritrichomonadidae	Tritrichomonas	Tritrichomonas foetus	2	0
114628	NA	Firmicutes	Clostridia	Clostridiales	Clostridiaceae	Alkaliphilus	Alkaliphilus transvaalensis	1	0
114652	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus orisratti	1	0
1149755	Fungi	Ascomycota	Leotiomycetes	Helotiales	Helotiaceae	Meliniomyces	Meliniomyces variabilis	2	0
114	NA	Planctomycetes	Planctomycetia	Planctomycetales	Gemmataceae	Gemmata	Gemmata obscuriglobus	1	0
1150469	NA	Proteobacteria	Alphaproteobacteria	Rhodospirillales	Rhodospirillaceae	Pararhodospirillum	Pararhodospirillum photometricum	1	0
1150475	NA	Firmicutes	Bacilli	Bacillales	Bacillaceae	Bacillus	Bacillus velezensis	1	0
1150864	NA	Actinobacteria	Actinobacteria	Micromonosporales	Micromonosporaceae	Micromonospora	Micromonospora lupini	1	0
1151754	Fungi	Basidiomycota	Ustilaginomycetes	Ustilaginales	Ustilaginaceae	Moesziomyces	Moesziomyces antarcticus	1	0
115335	NA	Actinobacteria	Actinobacteria	Streptosporangiales	Thermomonosporaceae	Actinomadura	Actinomadura rubrobrunea	1	0
1155714	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. LaPpAH-108	1	0
1157479	NA	Firmicutes	Bacilli	Lactobacillales	Enterococcaceae	Enterococcus	Enterococcus faecium	1	0
1157630	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. LamerLS-316	1	0
115778	NA	Firmicutes	Bacilli	Lactobacillales	Leuconostocaceae	Leuconostoc	Leuconostoc gelidum	1	0
115783	NA	Proteobacteria	Deltaproteobacteria	Desulfuromonadales	Geobacteraceae	Geobacter	Geobacter thiogenes	1	0
1157946	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus salivarius	2	0
1157962	Viridiplantae	Chlorophyta	Chlorophyceae	Chlamydomonadales	Chlamydomonadaceae	Chlamydomonas	Chlamydomonas eustigma	1	0
1158294	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella sp. 10(H)	1	0
1160091	NA	Actinobacteria	Actinobacteria	Bifidobacteriales	Bifidobacteriaceae	Alloscardovia	Alloscardovia macacae	1	0
1161417	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus sp. SR4	7	0
1161427	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus agalactiae	1	0
1161	NA	Cyanobacteria	NA	Nostocales	NA	NA	NA	1	0
1162717	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Leptotrichiaceae	Streptobacillus	Streptobacillus hongkongensis	1	0
1164594	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Oxalobacteraceae	Massilia	Massilia yuzhufengensis	1	0
1165852	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Comamonadaceae	Melaminivora	Melaminivora alkalimesophila	1	0
1166015	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium diphtheriae	6	0
1169540	NA	Chromerida	NA	NA	NA	Vitrella	Vitrella brassicaformis	3	0
117179	Fungi	Basidiomycota	Exobasidiomycetes	Tilletiales	Tilletiaceae	Tilletia	Tilletia walkeri	3	0
1172189	NA	NA	Spirotrichea	Sporadotrichida	Oxytrichidae	Oxytricha	Oxytricha trifallax	2	0
1173027	NA	Cyanobacteria	NA	Oscillatoriales	Microcoleaceae	Microcoleus	Microcoleus sp. PCC 7113	1	0
1173701	Fungi	Ascomycota	Sordariomycetes	Glomerellales	Glomerellaceae	Colletotrichum	Colletotrichum sublineola	1	0
1174528	NA	Cyanobacteria	NA	Nostocales	Hapalosiphonaceae	Fischerella	Fischerella sp. PCC 9339	1	0
1179773	NA	Actinobacteria	Actinobacteria	Pseudonocardiales	Pseudonocardiaceae	Saccharothrix	Saccharothrix espanaensis	1	0
1182542	Fungi	Ascomycota	Eurotiomycetes	Chaetothyriales	Herpotrichiellaceae	Capronia	Capronia epimyces	1	0
1182544	Fungi	Ascomycota	Eurotiomycetes	Chaetothyriales	Herpotrichiellaceae	Cladophialophora	Cladophialophora yegresii	1	0
118322	NA	Cyanobacteria	NA	Oscillatoriales	Oscillatoriaceae	Lyngbya	Lyngbya aestuarii	1	0
1185650	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Mycobacteriaceae	Mycobacterium	Mycobacterium abscessus	27	0
1187956	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus thermophilus	9	0
119044	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	Hyphomicrobiaceae	Filomicrobium	NA	1	0
1193518	NA	Actinobacteria	Actinobacteria	Micrococcales	Intrasporangiaceae	Tetrasphaera	Tetrasphaera jenkinsii	3	0
119602	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus dysgalactiae	1	0
1196095	NA	Proteobacteria	Gammaproteobacteria	Orbales	Orbaceae	Gilliamella	Gilliamella apicola	2	0
1196653	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Fusobacterium	Fusobacterium nucleatum	1	0
1198676	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus mutans	1	0
119978	NA	Proteobacteria	Acidithiobacillia	Acidithiobacillales	Acidithiobacillaceae	Acidithiobacillus	Acidithiobacillus albertensis	1	0
1200749	NA	Firmicutes	Clostridia	Clostridiales	Lachnospiraceae	NA	Lachnospiraceae bacterium G41	1	0
1200793	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus salivarius	45	0
1203622	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium sp. KPL1989	1	0
1204475	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Fusobacterium	Fusobacterium nucleatum	51	0
121039	NA	Actinobacteria	Acidimicrobiia	Acidimicrobiales	Acidimicrobiaceae	Ferrimicrobium	Ferrimicrobium acidiphilum	1	0
1212764	NA	Firmicutes	Bacilli	Bacillales	Paenibacillaceae	Paenibacillus	Paenibacillus popilliae	10	0
1213189	Fungi	Zoopagomycota	NA	Harpellales	Legeriomycetaceae	Zancudomyces	Zancudomyces culisetae	2	0
1213857	Fungi	Ascomycota	Sordariomycetes	Glomerellales	Glomerellaceae	Colletotrichum	Colletotrichum orbiculare	1	0
1214573	Fungi	Ascomycota	Sordariomycetes	Diaporthales	Diaporthaceae	Diaporthe	Diaporthe ampelina	1	0
1215331	Fungi	Ascomycota	Eurotiomycetes	Onygenales	Arthrodermataceae	Trichophyton	Trichophyton soudanense	1	0
1215914	NA	Firmicutes	Bacilli	Lactobacillales	Lactobacillaceae	Lactobacillus	Lactobacillus casei	1	0
1216362	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Fusobacterium	Fusobacterium hwasookii	14	0
121723	NA	Proteobacteria	Gammaproteobacteria	Vibrionales	Vibrionaceae	Photobacterium	Photobacterium sp. SKA34	3	0
1217657	NA	Proteobacteria	Gammaproteobacteria	Pseudomonadales	Moraxellaceae	Acinetobacter	Acinetobacter gyllenbergii	1	0
1218	NA	Cyanobacteria	NA	Synechococcales	Prochloraceae	Prochlorococcus	NA	1	0
1219382	NA	Proteobacteria	Gammaproteobacteria	Pseudomonadales	Moraxellaceae	Acinetobacter	Acinetobacter nectaris	1	0
1220162	Fungi	Basidiomycota	Tremellomycetes	Trichosporonales	Trichosporonaceae	Trichosporon	Trichosporon asahii	1	0
1220924	Fungi	Ascomycota	Eurotiomycetes	Chaetothyriales	Cyphellophoraceae	Cyphellophora	Cyphellophora europaea	1	0
122368	Fungi	Ascomycota	Dothideomycetes	Capnodiales	Mycosphaerellaceae	Cercospora	Cercospora beticola	1	0
1224162	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium marinum	1	0
1224749	NA	Firmicutes	Bacilli	Bacillales	NA	Exiguobacterium	Exiguobacterium sp. ZWU0009	1	0
1224	NA	Proteobacteria	NA	NA	NA	NA	NA	41	0
1225564	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	Methylobacteriaceae	Microvirga	Microvirga vignae	1	0
1226748	NA	Actinobacteria	Actinobacteria	Propionibacteriales	Propionibacteriaceae	Cutibacterium	Cutibacterium acnes	1	0
1227275	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus sobrinus	2	0
1229172	NA	Cyanobacteria	NA	Synechococcales	Leptolyngbyaceae	Leptolyngbya	Leptolyngbya sp. KIOST-1	2	0
1229521	NA	Proteobacteria	Gammaproteobacteria	Oceanospirillales	Oceanospirillaceae	Nitrincola	Nitrincola nitratireducens	1	0
1230067	Fungi	Basidiomycota	Tremellomycetes	Tremellales	Cryptococcaceae	Cryptococcus	Cryptococcus neoformans	1	0
1230070	Fungi	Basidiomycota	Tremellomycetes	Tremellales	Cryptococcaceae	Cryptococcus	Cryptococcus neoformans	1	0
1230075	Fungi	Basidiomycota	Tremellomycetes	Tremellales	Cryptococcaceae	Cryptococcus	Cryptococcus neoformans	2	0
1230078	Fungi	Basidiomycota	Tremellomycetes	Tremellales	Cryptococcaceae	Cryptococcus	Cryptococcus neoformans	3	0
1230383	Fungi	Basidiomycota	Malasseziomycetes	Malasseziales	Malasseziaceae	Malassezia	Malassezia sympodialis	1	0
1230998	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium frankenforstense	1	0
1231000	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium lactis	3	0
1232429	NA	Actinobacteria	Actinobacteria	Micrococcales	Micrococcaceae	Nesterenkonia	Nesterenkonia massiliensis	1	0
1234382	NA	Proteobacteria	Betaproteobacteria	Rhodocyclales	Zoogloeaceae	Thauera	Thauera phenylacetica	37	0
1235797	NA	Firmicutes	Clostridia	Clostridiales	Oscillospiraceae	Oscillibacter	Oscillibacter sp. 1-3	1	0
1236	NA	Proteobacteria	Gammaproteobacteria	NA	NA	NA	NA	5	0
1237896	Fungi	Ascomycota	Sordariomycetes	Glomerellales	Glomerellaceae	Colletotrichum	Colletotrichum gloeosporioides	1	0
1239	NA	Firmicutes	NA	NA	NA	NA	NA	1712	0
1242866	NA	Euryarchaeota	Thermoplasmata	Thermoplasmatales	NA	NA	Thermoplasmatales archaeon SCGC AB-540-F20	1	0
1243	NA	Firmicutes	Bacilli	Lactobacillales	Leuconostocaceae	Leuconostoc	NA	2	0
1244108	NA	Proteobacteria	Alphaproteobacteria	Rhodobacterales	Rhodobacteraceae	Jannaschia	Jannaschia faecimaris	3	0
1244513	NA	Proteobacteria	Gammaproteobacteria	Xanthomonadales	Xanthomonadaceae	Luteimonas	Luteimonas huabeiensis	1	0
1244531	NA	Proteobacteria	Epsilonproteobacteria	Campylobacterales	Campylobacteraceae	Campylobacter	Campylobacter iguaniorum	1	0
1246581	Fungi	Cryptomycota	NA	NA	NA	Paramicrosporidium	Paramicrosporidium saccamoebae	26	0
1246595	Fungi	Ascomycota	Saccharomycetes	Saccharomycetales	Saccharomycodaceae	Hanseniaspora	Hanseniaspora uvarum	1	0
1247	NA	Firmicutes	Bacilli	Lactobacillales	Leuconostocaceae	Oenococcus	Oenococcus oeni	1	0
1248420	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus intermedius	8	0
1249665	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Burkholderiaceae	Burkholderia	Burkholderia thailandensis	1	0
1256570	NA	NA	NA	NA	NA	NA	uncultured bacterium A1Q1_fos_291	5	0
1257118	NA	NA	NA	Longamoebia	Acanthamoebidae	Acanthamoeba	Acanthamoeba castellanii	2	0
1260356	NA	Firmicutes	Bacilli	Lactobacillales	Enterococcaceae	Enterococcus	Enterococcus faecalis	66	0
1260	NA	Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Finegoldia	Finegoldia magna	7	0
1261061	NA	Actinobacteria	Actinobacteria	Bifidobacteriales	Bifidobacteriaceae	Gardnerella	Gardnerella vaginalis	2	0
126156	NA	Firmicutes	Bacilli	Bacillales	Bacillaceae	Psychrobacillus	Psychrobacillus psychrotolerans	1	0
1261658	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Bibersteinia	Bibersteinia trehalosi	5	0
1262450	Fungi	Ascomycota	Sordariomycetes	Ophiostomatales	Ophiostomataceae	Ophiostoma	Ophiostoma piceae	1	0
1262699	NA	Firmicutes	Clostridia	Clostridiales	Lachnospiraceae	Anaerostipes	Anaerostipes sp. CAG:276	5	0
1262747	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Bacteroidaceae	Bacteroides	Bacteroides sp. CAG:702	4	0
1262770	NA	Firmicutes	Clostridia	Clostridiales	Clostridiaceae	Clostridium	Clostridium sp. CAG:1024	1	0
1262794	NA	Firmicutes	Clostridia	Clostridiales	Clostridiaceae	Clostridium	Clostridium sp. CAG:306	2	0
1262900	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Fusobacterium	Fusobacterium sp. CAG:649	5	0
1262944	NA	Firmicutes	Clostridia	Clostridiales	Lachnospiraceae	Roseburia	Roseburia sp. CAG:303	1	0
1262987	NA	Proteobacteria	NA	NA	NA	NA	Proteobacteria bacterium CAG:495	2	0
1263110	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus thermophilus CAG:236	5	0
1263415	Fungi	Ascomycota	Eurotiomycetes	Verrucariales	Verrucariaceae	Endocarpon	Endocarpon pusillum	1	0
1263550	NA	Proteobacteria	Gammaproteobacteria	Enterobacterales	Hafniaceae	Edwardsiella	Edwardsiella piscicida	1	0
1265492	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. FxanaA7	1	0
1268239	NA	Proteobacteria	Gammaproteobacteria	Alteromonadales	Pseudoalteromonadaceae	Pseudoalteromonas	Pseudoalteromonas luteoviolacea	3	0
1268	NA	Actinobacteria	Actinobacteria	Micrococcales	Micrococcaceae	NA	NA	6	0
1270	NA	Actinobacteria	Actinobacteria	Micrococcales	Micrococcaceae	Micrococcus	Micrococcus luteus	1	0
1271860	NA	Actinobacteria	Actinobacteria	Pseudonocardiales	Pseudonocardiaceae	Alloactinosynnema	Alloactinosynnema iranicum	5	0
1272	NA	Actinobacteria	Actinobacteria	Micrococcales	Micrococcaceae	Kocuria	Kocuria varians	1	0
1273125	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Nocardiaceae	Rhodococcus	Rhodococcus rhodnii	1	0
1278268	NA	NA	NA	NA	Phycodnaviridae	Chlorovirus	Acanthocystis turfacea Chlorella virus Br0604L	1	0
1279	NA	Firmicutes	Bacilli	Bacillales	Staphylococcaceae	Staphylococcus	NA	6	0
1280523	Fungi	Ascomycota	Sordariomycetes	Hypocreales	Stachybotryaceae	Stachybotrys	Stachybotrys chartarum	1	0
1280669	NA	Firmicutes	Clostridia	Clostridiales	Lachnospiraceae	Dorea	Dorea sp. AGR2135	1	0
1280674	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella sp. AGR2160	1	0
1280681	NA	Firmicutes	Clostridia	Clostridiales	Lachnospiraceae	Butyrivibrio	Butyrivibrio sp. WCD2001	1	0
1280946	NA	Proteobacteria	Alphaproteobacteria	Rhodobacterales	Hyphomonadaceae	Hyphomonas	Hyphomonas beringensis	1	0
1280	NA	Firmicutes	Bacilli	Bacillales	Staphylococcaceae	Staphylococcus	Staphylococcus aureus	10	0
1283286	NA	Bacteroidetes	Flavobacteriia	Flavobacteriales	Flavobacteriaceae	Gillisia	Gillisia sp. JM1	1	0
1284664	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces gancidicus	1	0
1284708	NA	Firmicutes	Tissierellia	NA	NA	NA	Tissierellia bacterium S7-1-4	1	0
1287182	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	Phyllobacteriaceae	Mesorhizobium	Mesorhizobium sp. L48C026A00	2	0
1288080	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. CNT360	1	0
1288971	NA	Firmicutes	Tissierellia	Tissierellales	Tissierellaceae	NA	[Clostridium] ultunense	9	0
1289387	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. TAA204	1	0
1291522	Viridiplantae	Chlorophyta	Trebouxiophyceae	Chlorellales	Chlorellaceae	Helicosporidium	Helicosporidium sp. ATCC 50920	1	0
1291764	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Lactococcus	Lactococcus fujiensis	2	0
1292020	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Dietziaceae	Dietzia	Dietzia sp. UCD-THP	7	0
1294274	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus equinus	1	0
1294348	Fungi	Ascomycota	Saccharomycetes	Saccharomycetales	Saccharomycetaceae	Saccharomyces	Saccharomyces cerevisiae	2	0
1295528	Fungi	Basidiomycota	Tremellomycetes	Tremellales	Cryptococcaceae	Tsuchiyaea	Tsuchiyaea wingfieldii	1	0
1296096	Fungi	Basidiomycota	Tremellomycetes	Tremellales	Cryptococcaceae	Kwoniella	Kwoniella pini	1	0
1296100	Fungi	Basidiomycota	Tremellomycetes	Tremellales	Cryptococcaceae	Kwoniella	Kwoniella bestiolae	1	0
1296105	Fungi	Basidiomycota	Tremellomycetes	Tremellales	Cryptococcaceae	Cryptococcus	Cryptococcus gattii VGIV	1	0
1296121	Fungi	Basidiomycota	Tremellomycetes	Tremellales	Cryptococcaceae	Kwoniella	Kwoniella dejecticola	1	0
12968	NA	NA	NA	NA	NA	Blastocystis	Blastocystis hominis	1	0
1296	NA	Firmicutes	Bacilli	Bacillales	Staphylococcaceae	Staphylococcus	Staphylococcus sciuri	2	0
1297579	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Fusobacterium	Fusobacterium nucleatum	24	0
1297742	NA	Proteobacteria	Deltaproteobacteria	Myxococcales	Myxococcaceae	Myxococcus	Myxococcus hansupus	1	0
1298860	NA	Actinobacteria	Actinobacteria	Micrococcales	Microbacteriaceae	Microbacterium	Microbacterium sp. URHA0036	1	0
1298915	NA	Nitrospirae	NA	NA	NA	NA	NA	1	0
1299328	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Mycobacteriaceae	Mycobacterium	Mycobacterium kansasii	1	0
1299332	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Mycobacteriaceae	Mycobacterium	Mycobacterium ulcerans	3	0
1299334	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Mycobacteriaceae	Mycobacterium	Mycobacterium xenopi	1	0
1300267	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces zhaozhouensis	1	0
1300	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	NA	NA	216	0
1301279	NA	NA	NA	NA	Iridoviridae	Iridovirus	Invertebrate iridovirus 22	1	0
1301915	NA	Euryarchaeota	Methanococci	Methanococcales	Methanocaldococcaceae	Methanocaldococcus	Methanocaldococcus bathoardescens	1	0
1301	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	NA	11534	0
1302626	NA	Firmicutes	Bacilli	Bacillales	Listeriaceae	Listeria	Listeria monocytogenes	1	0
1302629	NA	Firmicutes	Bacilli	Bacillales	Listeriaceae	Listeria	Listeria monocytogenes	1	0
1302863	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus cristatus	1	0
1302	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus gordonii	2	0
1303	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus oralis	9	0
1304833	NA	Cyanobacteria	NA	Nostocales	Tolypothrichaceae	Hassallia	Hassallia byssoidea	2	0
1304866	NA	Firmicutes	Clostridia	Clostridiales	Clostridiaceae	Clostridium	Clostridium sp. ASBs410	3	0
1304	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus salivarius	64	0
1305675	NA	Firmicutes	Bacilli	Bacillales	Bacillaceae	Bacillus	Bacillus solimangrovi	2	0
1305764	Fungi	Basidiomycota	Ustilaginomycetes	Ustilaginales	Ustilaginaceae	Pseudozyma	Pseudozyma hubeiensis	2	0
1307428	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Fusobacterium	Fusobacterium nucleatum	35	0
1307437	NA	Proteobacteria	Gammaproteobacteria	Alteromonadales	Pseudoalteromonadaceae	Pseudoalteromonas	Pseudoalteromonas agarivorans	1	0
1307442	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Fusobacterium	Fusobacterium hwasookii	7	0
1307443	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Fusobacterium	Fusobacterium hwasookii	3	0
1307	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus suis	25	0
1308	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus thermophilus	4445	0
1309	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus mutans	7	0
131081	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium capitovis	10	0
1310	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus sobrinus	1	0
1311	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus agalactiae	18	0
1313	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus pneumoniae	108	0
1314670	Fungi	Ascomycota	Dothideomycetes	Mytilinidiales	Argynnaceae	Lepidopterella	Lepidopterella palustris	1	0
1314672	Fungi	Basidiomycota	Agaricomycetes	Russulales	Peniophoraceae	Peniophora	Peniophora sp. CONT	1	0
1314777	Fungi	Basidiomycota	Agaricomycetes	Trechisporales	Hydnodontaceae	Sistotremastrum	Sistotremastrum niveocremeum	1	0
1314781	Fungi	Basidiomycota	Agaricomycetes	Auriculariales	Exidiaceae	Exidia	Exidia glandulosa	1	0
1314783	Fungi	Basidiomycota	Agaricomycetes	Polyporales	Fomitopsidaceae	Daedalea	Daedalea quercina	1	0
1314785	Fungi	Basidiomycota	Agaricomycetes	Polyporales	Laetiporaceae	Laetiporus	Laetiporus sulphureus	1	0
1314	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus pyogenes	16	0
131567	NA	NA	NA	NA	NA	NA	NA	132	0
131568	NA	Actinobacteria	Actinobacteria	Kineosporiales	Kineosporiaceae	Kineococcus	Kineococcus radiotolerans	1	0
1316409	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus sp. HSISB1	1	0
1316410	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus sp. HSISS1	2	0
1316411	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus sp. HSISS2	6	0
1316412	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus sp. HSISS3	1	0
1316586	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Fusobacterium	Fusobacterium nucleatum	6	0
1316587	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Fusobacterium	Fusobacterium nucleatum	2	0
1316588	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Fusobacterium	Fusobacterium nucleatum	2	0
1317065	NA	NA	Oomycetes	Peronosporales	NA	Phytophthora	Phytophthora parasitica	1	0
1318460	Fungi	Ascomycota	Sordariomycetes	Hypocreales	Nectriaceae	Fusarium	Fusarium sp. FIESC_5	3	0
1318	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus parasanguinis	6	0
1319815	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Cetobacterium	Cetobacterium somerae	1	0
1321779	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Leptotrichiaceae	Leptotrichia	Leptotrichia sp. oral taxon 215	5	0
132249	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Nocardiaceae	Nocardia	Nocardia veterana	1	0
1323249	NA	Apicomplexa	Aconoidasida	Haemosporida	Plasmodiidae	Plasmodium	Plasmodium yoelii	1	0
132605	NA	Cyanobacteria	NA	Synechococcales	Pseudanabaenaceae	Limnothrix	NA	1	0
1328	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus anginosus	1	0
132919	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Nocardiaceae	Rhodococcus	Rhodococcus jostii	1	0
1329	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus canis	1	0
1333998	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	Rhodobiaceae	Tepidicaulis	Tepidicaulis marinus	7	0
133412	Fungi	Zoopagomycota	NA	Harpellales	Legeriomycetaceae	Smittium	Smittium culicis	1	0
1334	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus dysgalactiae	4	0
1335309	NA	Bacteroidetes	Chitinophagia	Chitinophagales	Chitinophagaceae	Chitinophaga	Chitinophaga costaii	1	0
1335419	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Mycobacteriaceae	Mycobacterium	Mycobacterium avium	1	0
1335	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus equinus	2	0
1336	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus equi	8	0
1338	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus intermedius	1	0
1339	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus macacae	1	0
1340	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus porcinus	1	0
1343841	NA	NA	NA	NA	NA	NA	uncultured bacterium 405006-B04	1	0
1343	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus vestibularis	12	0
1344416	Fungi	Chytridiomycota	Monoblepharidomycetes	Monoblepharidales	Gonapodyaceae	Gonapodya	Gonapodya prolifera	1	0
134605	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Fusobacterium	Fusobacterium equinum	2	0
1348	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus parauberis	4	0
134959	NA	Actinobacteria	Actinobacteria	Streptosporangiales	Thermomonosporaceae	Actinomadura	Actinomadura mexicana	1	0
1349	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus uberis	1	0
1350	NA	Firmicutes	Bacilli	Lactobacillales	Enterococcaceae	Enterococcus	NA	54	0
1351	NA	Firmicutes	Bacilli	Lactobacillales	Enterococcaceae	Enterococcus	Enterococcus faecalis	981	0
1352	NA	Firmicutes	Bacilli	Lactobacillales	Enterococcaceae	Enterococcus	Enterococcus faecium	9	0
1353260	NA	Thaumarchaeota	Nitrososphaeria	Nitrososphaerales	Nitrososphaeraceae	Candidatus Nitrosocosmicus	Candidatus Nitrocosmicus oleophilus	1	0
1353952	Fungi	Basidiomycota	Dacrymycetes	Dacrymycetales	Dacrymycetaceae	Calocera	Calocera cornea	9	0
1353977	NA	Chlamydiae	Chlamydiia	Parachlamydiales	Parachlamydiaceae	Candidatus Protochlamydia	Candidatus Protochlamydia sp. R18	1	0
1354	NA	Firmicutes	Bacilli	Lactobacillales	Enterococcaceae	Enterococcus	Enterococcus hirae	1	0
1355477	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	Bradyrhizobiaceae	Bradyrhizobium	Bradyrhizobium diazoefficiens	1	0
1355	NA	Firmicutes	Bacilli	Lactobacillales	Enterococcaceae	Enterococcus	Enterococcus columbae	1	0
135623	NA	Proteobacteria	Gammaproteobacteria	Vibrionales	NA	NA	NA	2	0
1357398	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Fusobacterium	Fusobacterium nucleatum	6	0
1358	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Lactococcus	Lactococcus lactis	8	0
1359208	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. TP-A0356	1	0
1359	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Lactococcus	Lactococcus lactis	3	0
136370	Fungi	Ascomycota	Lecanoromycetes	Umbilicariales	Umbilicariaceae	Umbilicaria	Umbilicaria pustulata	2	0
1363	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Lactococcus	Lactococcus garvieae	1	0
1365108	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Burkholderiaceae	Burkholderia	Burkholderia sp. A9	2	0
1365824	Fungi	Basidiomycota	Ustilaginomycetes	Ustilaginales	Ustilaginaceae	Kalmanozyma	Kalmanozyma brasiliensis	1	0
136845	NA	Proteobacteria	Gammaproteobacteria	Pseudomonadales	Pseudomonadaceae	Pseudomonas	NA	1	0
136857	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium testudinoris	1	0
13687	NA	Proteobacteria	Alphaproteobacteria	Sphingomonadales	Sphingomonadaceae	Sphingomonas	NA	1	0
137071	NA	Apicomplexa	Aconoidasida	Haemosporida	Plasmodiidae	Plasmodium	Plasmodium falciparum	1	0
1376	NA	Firmicutes	Bacilli	Lactobacillales	Aerococcaceae	Aerococcus	Aerococcus urinae	4	0
1378168	NA	Firmicutes	NA	NA	NA	NA	Firmicutes bacterium ASF500	1	0
1379909	NA	Bacteroidetes	Cytophagia	Cytophagales	Hymenobacteraceae	Rufibacter	Rufibacter sp. DG15C	1	0
1380370	NA	Actinobacteria	Actinobacteria	Micrococcales	Intrasporangiaceae	NA	Intrasporangiaceae bacterium URHB0013	1	0
1380	NA	Actinobacteria	Coriobacteriia	Coriobacteriales	Atopobiaceae	Atopobium	NA	1	0
138298	NA	Apicomplexa	Aconoidasida	Haemosporida	Plasmodiidae	Plasmodium	Plasmodium vinckei	1	0
138336	NA	Actinobacteria	Actinobacteria	Geodermatophilales	Geodermatophilaceae	Blastococcus	Blastococcus saxobsidens	1	0
1384082	NA	Firmicutes	Negativicutes	Veillonellales	Veillonellaceae	NA	Veillonellaceae bacterium DNF00751	3	0
1384509	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Leptotrichiaceae	Streptobacillus	Streptobacillus felis	1	0
1385521	NA	Actinobacteria	Actinobacteria	Micrococcales	Intrasporangiaceae	Knoellia	Knoellia subterranea	3	0
1385	NA	Firmicutes	Bacilli	Bacillales	NA	NA	NA	3	0
1386	NA	Firmicutes	Bacilli	Bacillales	Bacillaceae	Bacillus	NA	2	0
1388004	NA	Firmicutes	Bacilli	Bacillales	Staphylococcaceae	Staphylococcus	Staphylococcus aureus	1	0
1392248	Fungi	Ascomycota	Eurotiomycetes	Eurotiales	Aspergillaceae	Aspergillus	Aspergillus campestris	3	0
1392250	Fungi	Ascomycota	Eurotiomycetes	Eurotiales	Aspergillaceae	Aspergillus	Aspergillus steynii	2	0
1392	NA	Firmicutes	Bacilli	Bacillales	Bacillaceae	Bacillus	Bacillus anthracis	1	0
1396	NA	Firmicutes	Bacilli	Bacillales	Bacillaceae	Bacillus	Bacillus cereus	3	0
1398154	Fungi	Ascomycota	Sordariomycetes	Ophiostomatales	Ophiostomataceae	Sporothrix	Sporothrix brasiliensis	1	0
1398559	Fungi	Basidiomycota	Ustilaginomycetes	Ustilaginales	Ustilaginaceae	Melanopsichium	Melanopsichium pennsylvanicum	2	0
1399419	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	Bradyrhizobiaceae	Bradyrhizobium	Bradyrhizobium sp. BR10280	1	0
1399860	Fungi	Ascomycota	Sordariomycetes	Hypocreales	Ophiocordycipitaceae	Ophiocordyceps	Ophiocordyceps australis	3	0
1400862	NA	Proteobacteria	Gammaproteobacteria	NA	Competibacteraceae	Candidatus Competibacter	Candidatus Competibacter denitrificans	1	0
1402135	NA	Proteobacteria	Alphaproteobacteria	Rhodobacterales	Rhodobacteraceae	Sulfitobacter	Sulfitobacter pseudonitzschiae	2	0
1402163	NA	Proteobacteria	Alphaproteobacteria	Rickettsiales	Anaplasmataceae	Wolbachia	Wolbachia endosymbiont of Culex molestus	2	0
1403829	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus mutans	3	0
1403933	NA	Firmicutes	Negativicutes	Veillonellales	Veillonellaceae	Veillonella	Veillonella sp. DORA_B_18_19_23	3	0
1403937	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus sp. DORA_10	1	0
1403940	NA	Firmicutes	Clostridia	Clostridiales	Peptostreptococcaceae	Intestinibacter	Intestinibacter bartlettii	12	0
1403946	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus anginosus	8	0
1403947	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus parasanguinis	4	0
1403948	NA	Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Varibaculum	Varibaculum cambriense	14	0
1405	NA	Firmicutes	Bacilli	Bacillales	Bacillaceae	Bacillus	Bacillus mycoides	1	0
1408178	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus thermophilus	3	0
1408	NA	Firmicutes	Bacilli	Bacillales	Bacillaceae	Bacillus	Bacillus pumilus	1	0
1410327	NA	NA	NA	Acytosteliales	Acytosteliaceae	Acytostelium	Acytostelium subglobosum	1	0
1413492	NA	Firmicutes	Bacilli	Bacillales	Staphylococcaceae	Staphylococcus	Staphylococcus aureus	1	0
1415541	NA	Actinobacteria	Actinobacteria	Micromonosporales	Micromonosporaceae	Micromonospora	Micromonospora sp. NRRL B-16802	1	0
1415546	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. MMG1533	1	0
1415557	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. WM6378	1	0
1415776	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus thermophilus	7	0
1416333	NA	NA	NA	Kinetoplastida	Trypanosomatidae	Trypanosoma	Trypanosoma cruzi	20	0
1417980	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces odonnellii	1	0
1420902	Fungi	Ascomycota	Leotiomycetes	NA	Pseudeurotiaceae	Pseudogymnoascus	Pseudogymnoascus sp. VKM F-4246	1	0
1420909	Fungi	Ascomycota	Leotiomycetes	NA	Pseudeurotiaceae	Pseudogymnoascus	Pseudogymnoascus sp. VKM F-4515 (FW-2607)	1	0
1420915	Fungi	Ascomycota	Leotiomycetes	NA	Pseudeurotiaceae	Pseudogymnoascus	Pseudogymnoascus sp. VKM F-4520 (FW-2644)	1	0
1423145	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus thermophilus	10	0
1423	NA	Firmicutes	Bacilli	Bacillales	Bacillaceae	Bacillus	Bacillus subtilis	1	0
1428620	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces humi	1	0
1428	NA	Firmicutes	Bacilli	Bacillales	Bacillaceae	Bacillus	Bacillus thuringiensis	5	0
1431688	NA	Proteobacteria	Gammaproteobacteria	Chromatiales	Chromatiaceae	Thiohalocapsa	Thiohalocapsa sp. ML1	1	0
143223	NA	Bacteroidetes	Flavobacteriia	Flavobacteriales	Flavobacteriaceae	Salegentibacter	Salegentibacter salegens	1	0
1432307	Fungi	Ascomycota	Leotiomycetes	Helotiales	Sclerotiniaceae	Sclerotinia	Sclerotinia borealis	1	0
1433288	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus thermophilus	2	0
1433289	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus thermophilus	14	0
143387	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Fusobacterium	Fusobacterium necrophorum	4	0
1434011	NA	Proteobacteria	Alphaproteobacteria	Rhodospirillales	Acetobacteraceae	Komagataeibacter	NA	1	0
1434099	NA	Euryarchaeota	Methanomicrobia	Methanosarcinales	Methanosarcinaceae	Methanosarcina	Methanosarcina sp. Kolksee	1	0
1434215	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Mannheimia	Mannheimia varigena	1	0
1434700	NA	Bacteroidetes	Flavobacteriia	Flavobacteriales	Flavobacteriaceae	Moheibacter	Moheibacter sediminis	1	0
1435972	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus thermophilus	1	0
1435974	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus thermophilus	11	0
1435981	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus thermophilus	12	0
1436725	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus thermophilus	10	0
1437360	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	Bradyrhizobiaceae	Bradyrhizobium	Bradyrhizobium erythrophlei	3	0
1439139	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus pyogenes	3	0
1441469	Fungi	Ascomycota	Eurotiomycetes	Eurotiales	Trichocomaceae	Talaromyces	Talaromyces atroroseus	2	0
1441733	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Fusobacterium	Fusobacterium necrophorum	1	0
1441735	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Fusobacterium	Fusobacterium necrophorum	8	0
1441931	NA	Proteobacteria	Gammaproteobacteria	Pseudomonadales	Pseudomonadaceae	Pseudomonas	Pseudomonas aeruginosa	1	0
1442368	Fungi	Ascomycota	Eurotiomycetes	Chaetothyriales	Herpotrichiellaceae	Fonsecaea	Fonsecaea pedrosoi	1	0
1447875	Fungi	Ascomycota	Eurotiomycetes	Onygenales	Ajellomycetaceae	Helicocarpus	Helicocarpus griseus	2	0
1448857	NA	Proteobacteria	Epsilonproteobacteria	Campylobacterales	Campylobacteraceae	Campylobacter	Campylobacter corcagiensis	2	0
1450648	NA	Firmicutes	Clostridia	Clostridiales	Clostridiaceae	Clostridium	Clostridium oryzae	1	0
1454202	NA	Proteobacteria	Gammaproteobacteria	Vibrionales	Vibrionaceae	Photobacterium	Photobacterium phosphoreum	1	0
146015	NA	NA	NA	Herpesvirales	Herpesviridae	Proboscivirus	Elephantid betaherpesvirus 1	1	0
146021	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Mycobacteriaceae	Mycobacterium	Mycobacterium houstonense	1	0
1460289	NA	NA	NA	Prymnesiales	Chrysochromulinaceae	Chrysochromulina	Chrysochromulina sp. CCMP291	2	0
1460649	NA	Firmicutes	Bacilli	Bacillales	NA	NA	Geomicrobium sp. JCM 19055	1	0
1463820	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Actinosporangium sp. NRRL B-3428	1	0
1463858	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. NRRL F-5135	1	0
1463864	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. NRRL F-5630	1	0
1463889	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. NRRL S-1824	1	0
1463900	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. NRRL S-337	1	0
1465756	NA	Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Peptoniphilus	Peptoniphilus grossensis	2	0
1465811	NA	Actinobacteria	Actinobacteria	Micrococcales	Cellulomonadaceae	Cellulomonas	Cellulomonas massiliensis	1	0
146819	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces europaeiscabiei	1	0
146821	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces reticuliscabiei	1	0
146827	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium simulans	1	0
146938	NA	Proteobacteria	Betaproteobacteria	Rhodocyclales	Rhodocyclaceae	Azovibrio	Azovibrio restrictus	1	0
147467	NA	Firmicutes	Bacilli	Bacillales	Staphylococcaceae	Staphylococcus	Staphylococcus sciuri	3	0
1477000	NA	Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Peptoniphilus	Peptoniphilus sp. DNF00840	3	0
147802	NA	Firmicutes	Bacilli	Lactobacillales	Lactobacillaceae	Lactobacillus	Lactobacillus iners	11	0
1479237	NA	Proteobacteria	Gammaproteobacteria	Alteromonadales	Alteromonadaceae	Marinobacter	Marinobacter sp. HL-58	1	0
1482	NA	Firmicutes	Bacilli	Bacillales	Bacillaceae	Virgibacillus	Virgibacillus halodenitrificans	1	0
1484116	NA	Bacteroidetes	Cytophagia	Cytophagales	Hymenobacteraceae	Hymenobacter	Hymenobacter sp. PAMC 26554	1	0
1485543	NA	Firmicutes	Negativicutes	Selenomonadales	Selenomonadaceae	Selenomonas	Selenomonas sp. AE3005	2	0
1485	NA	Firmicutes	Clostridia	Clostridiales	Clostridiaceae	Clostridium	NA	5	0
1487921	NA	Firmicutes	Clostridia	Clostridiales	Clostridiaceae	Clostridium	Clostridium sp. HMP27	1	0
1487953	NA	Cyanobacteria	NA	Synechococcales	Leptolyngbyaceae	Leptolyngbya	Leptolyngbya sp. JSC-1	5	0
148814	NA	Firmicutes	Bacilli	Lactobacillales	Lactobacillaceae	Lactobacillus	Lactobacillus kunkeei	3	0
1488406	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. MBT76	1	0
1488	NA	Firmicutes	Clostridia	Clostridiales	Clostridiaceae	Clostridium	Clostridium acetobutylicum	1	0
149040	Fungi	Ascomycota	Leotiomycetes	Helotiales	NA	Phialocephala	Phialocephala scopiformis	4	0
1491	NA	Firmicutes	Clostridia	Clostridiales	Clostridiaceae	Clostridium	Clostridium botulinum	1	0
1492898	NA	Bacteroidetes	Chitinophagia	Chitinophagales	Chitinophagaceae	Flavisolibacter	Flavisolibacter tropicus	1	0
1492	NA	Firmicutes	Clostridia	Clostridiales	Clostridiaceae	Clostridium	Clostridium butyricum	1	0
1495650	NA	Chloroflexi	Thermoflexia	Thermoflexales	Thermoflexaceae	Thermoflexus	Thermoflexus hugenholtzii	1	0
1496	NA	Firmicutes	Clostridia	Clostridiales	Peptostreptococcaceae	Clostridioides	Clostridioides difficile	37	0
1500283	NA	Bacteroidetes	Flavobacteriia	Flavobacteriales	Flavobacteriaceae	Chryseobacterium	Chryseobacterium sp. CF356	1	0
150055	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus lutetiensis	1	0
1501	NA	Firmicutes	Clostridia	Clostridiales	Clostridiaceae	Clostridium	Clostridium pasteurianum	1	0
150240	NA	Firmicutes	Bacilli	Bacillales	NA	Gemella	Gemella cuniculi	1	0
1503470	NA	Cyanobacteria	NA	NA	NA	NA	cyanobacterium TDX16	1	0
1504320	NA	Actinobacteria	Actinobacteria	NA	NA	NA	actinobacterium acAcidi	1	0
1505232	NA	Fibrobacteres	Chitinivibrionia	Chitinivibrionales	Chitinivibrionaceae	Chitinivibrio	Chitinivibrio alkaliphilus	1	0
1505530	NA	NA	NA	NA	Caulimoviridae	Badnavirus	Pagoda yellow mosaic associated virus	1	0
1505933	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	Phyllobacteriaceae	Mesorhizobium	Mesorhizobium sp. ORS3359	1	0
1506553	NA	Firmicutes	Clostridia	Clostridiales	Lachnospiraceae	Lachnoclostridium	NA	1	0
1507806	NA	Proteobacteria	Epsilonproteobacteria	Campylobacterales	Campylobacteraceae	Campylobacter	Campylobacter fetus	1	0
1507870	Fungi	Ascomycota	Dothideomycetes	Capnodiales	Cladosporiaceae	Rachicladosporium	Rachicladosporium antarcticum	3	0
1507979	NA	Proteobacteria	Gammaproteobacteria	Vibrionales	Vibrionaceae	Vibrio	Vibrio sp. J2-29	4	0
1509	NA	Firmicutes	Clostridia	Clostridiales	Clostridiaceae	Clostridium	Clostridium sporogenes	2	0
1515610	NA	Actinobacteria	Actinobacteria	Pseudonocardiales	Pseudonocardiaceae	Prauserella	Prauserella sp. Am3	1	0
1519475	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. NRRL F-5755	1	0
1519	NA	Firmicutes	Clostridia	Clostridiales	Clostridiaceae	Clostridium	Clostridium tyrobutyricum	2	0
1520802	NA	Firmicutes	Clostridia	Clostridiales	Lachnospiraceae	Pseudobutyrivibrio	Pseudobutyrivibrio sp. YE44	1	0
1520	NA	Firmicutes	Clostridia	Clostridiales	Clostridiaceae	Clostridium	Clostridium beijerinckii	3	0
1522002	NA	Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Actinomyces	Actinomyces succiniciruminis	1	0
1524337	NA	Tenericutes	Mollicutes	Mycoplasmatales	Mycoplasmataceae	NA	Mycoplasmataceae bacterium RC_NB112A	7	0
1524831	Fungi	Ascomycota	Leotiomycetes	NA	Pseudeurotiaceae	Pseudogymnoascus	Pseudogymnoascus sp. 23342-1-I1	1	0
152794	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium efficiens	1	0
1528099	NA	Actinobacteria	Actinobacteria	Corynebacteriales	NA	Lawsonella	Lawsonella clevelandensis	1	0
1529006	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	Phyllobacteriaceae	Mesorhizobium	Mesorhizobium sp. 1M-11	2	0
1533	NA	Firmicutes	Clostridia	Clostridiales	Clostridiaceae	Clostridium	Clostridium fallax	1	0
1546107	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. NBRC 110027	3	0
1549812	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Oxalobacteraceae	Massilia	Massilia sp. BSC265	1	0
1549	NA	Firmicutes	Clostridia	Clostridiales	Ruminococcaceae	Ruminiclostridium	[Clostridium] sporosphaeroides	1	0
155085	NA	Firmicutes	Bacilli	Bacillales	Staphylococcaceae	Staphylococcus	Staphylococcus lutrae	1	0
1552662	NA	NA	NA	NA	NA	Negevirus	Brejeira virus	1	0
155615	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Fusobacterium	Fusobacterium nucleatum	2	0
155892	NA	Proteobacteria	Alphaproteobacteria	Caulobacterales	Caulobacteraceae	Caulobacter	Caulobacter vibrioides	2	0
1561004	NA	NA	NA	NA	NA	NA	bacterium 2013Ark19i	2	0
1561	NA	Firmicutes	Clostridia	Clostridiales	Clostridiaceae	Clostridium	Clostridium baratii	1	0
1564506	NA	Proteobacteria	Alphaproteobacteria	Rhodobacterales	Rhodobacteraceae	Rhodovulum	Rhodovulum sp. P5	1	0
156456	NA	Firmicutes	Negativicutes	Veillonellales	Veillonellaceae	Anaeroglobus	Anaeroglobus geminatus	6	0
156978	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium imitans	3	0
1570339	NA	Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	NA	NA	5	0
1570345	NA	Actinobacteria	Actinobacteria	Micrococcales	Demequinaceae	Demequina	Demequina sp. NBRC 110056	2	0
157076	NA	Firmicutes	Bacilli	Lactobacillales	Carnobacteriaceae	Trichococcus	Trichococcus collinsii	1	0
1574409	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	Phyllobacteriaceae	Mesorhizobium	Mesorhizobium sp. F7	1	0
157538	NA	NA	NA	Kinetoplastida	Trypanosomatidae	Leptomonas	Leptomonas pyrrhocoris	1	0
1575	NA	Actinobacteria	Actinobacteria	Micrococcales	Microbacteriaceae	Leifsonia	Leifsonia xyli	1	0
1576605	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. 150FB	1	0
157687	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Leptotrichiaceae	Leptotrichia	Leptotrichia wadei	3	0
157692	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Leptotrichiaceae	Leptotrichia	Leptotrichia goodfellowii	1	0
1578	NA	Firmicutes	Bacilli	Lactobacillales	Lactobacillaceae	Lactobacillus	NA	16	0
1579339	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus sp. 449_SSPC	1	0
1579348	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus sp. 1171_SSPC	2	0
157	NA	Spirochaetes	Spirochaetia	Spirochaetales	Spirochaetaceae	Treponema	NA	1	0
1580	NA	Firmicutes	Bacilli	Lactobacillales	Lactobacillaceae	Lactobacillus	Lactobacillus brevis	1	0
1581061	NA	Firmicutes	Bacilli	Lactobacillales	Aerococcaceae	Abiotrophia	Abiotrophia sp. HMSC24B09	1	0
1581069	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium sp. HMSC29G08	1	0
1581080	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus sp. HMSC10E12	1	0
1581135	NA	Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Trueperella	Trueperella sp. HMSC08B05	2	0
1581144	NA	Actinobacteria	Actinobacteria	Micrococcales	Dermabacteraceae	Dermabacter	Dermabacter sp. HMSC08H10	2	0
1581	NA	Firmicutes	Bacilli	Lactobacillales	Lactobacillaceae	Lactobacillus	Lactobacillus buchneri	2	0
1582224	NA	Thermotogae	Thermotogae	Kosmotogales	Kosmotogaceae	Mesotoga	Mesotoga sp. B105.6.4	1	0
1582879	NA	Firmicutes	Tissierellia	NA	NA	Ezakiella	NA	1	0
1583098	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Fusobacterium	Fusobacterium hwasookii	42	0
1585	NA	Firmicutes	Bacilli	Lactobacillales	Lactobacillaceae	Lactobacillus	Lactobacillus delbrueckii	1	0
158607	Fungi	Ascomycota	Sordariomycetes	Diaporthales	Diaporthaceae	Diaporthe	Diaporthe helianthi	2	0
1588023	NA	Actinobacteria	Actinobacteria	Micrococcales	Micrococcaceae	Arthrobacter	Arthrobacter sp. Hiyo8	8	0
1588750	NA	Firmicutes	Clostridia	Clostridiales	NA	NA	Clostridiales bacterium KA00134	5	0
158	NA	Spirochaetes	Spirochaetia	Spirochaetales	Spirochaetaceae	Treponema	Treponema denticola	1	0
1590596	NA	Bacteroidetes	Sphingobacteriia	Sphingobacteriales	Sphingobacteriaceae	Sphingobacterium	Sphingobacterium sp. T2	1	0
159291	NA	Spirochaetes	Spirochaetia	Spirochaetales	Spirochaetaceae	Alkalispirochaeta	Alkalispirochaeta americana	2	0
159449	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces scabrisporus	2	0
159749	NA	Bacillariophyta	Coscinodiscophyceae	Thalassiosirales	Thalassiosiraceae	Thalassiosira	Thalassiosira oceanica	15	0
1597	NA	Firmicutes	Bacilli	Lactobacillales	Lactobacillaceae	Lactobacillus	Lactobacillus paracasei	1	0
1598	NA	Firmicutes	Bacilli	Lactobacillales	Lactobacillaceae	Lactobacillus	Lactobacillus reuteri	1	0
1603887	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium sp. CMW7794	3	0
1605721	NA	NA	NA	NA	NA	Pandoravirus	Pandoravirus inopinatum	2	0
1609095	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. NRRL F-4489	1	0
1609969	NA	Candidatus Omnitrophica	NA	NA	NA	Candidatus Omnitrophus	Candidatus Omnitrophus magneticus	1	0
1616823	NA	Proteobacteria	Alphaproteobacteria	Rhodospirillales	Rhodospirillaceae	Thalassospira	Thalassospira sp. HJ	1	0
1618359	NA	Candidatus Amesbacteria	NA	NA	NA	NA	Candidatus Amesbacteria bacterium GW2011_GWA2_47_70	1	0
1618553	NA	Candidatus Woesebacteria	NA	NA	NA	NA	Candidatus Woesebacteria bacterium GW2011_GWA1_40_43	6	0
1618669	NA	Candidatus Kaiserbacteria	NA	NA	NA	NA	Candidatus Kaiserbacteria bacterium GW2011_GWA2_49_19	3	0
1618715	NA	Candidatus Moranbacteria	NA	NA	NA	NA	Candidatus Moranbacteria bacterium GW2011_GWF1_34_10	1	0
161879	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium kroppenstedtii	2	0
1618941	NA	NA	NA	NA	NA	NA	Parcubacteria group bacterium GW2011_GWD2_38_11	4	0
161899	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium singulare	1	0
161920	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Dietziaceae	Dietzia	Dietzia natronolimnaea	13	0
1619308	NA	Actinobacteria	Actinobacteria	Micrococcales	Microbacteriaceae	Cnuibacter	Cnuibacter physcomitrellae	2	0
1622149	Fungi	Ascomycota	Leotiomycetes	NA	Pseudeurotiaceae	Pseudogymnoascus	Pseudogymnoascus sp. 05NY08	1	0
162289	NA	Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Peptoniphilus	NA	1	0
1624	NA	Firmicutes	Bacilli	Lactobacillales	Lactobacillaceae	Lactobacillus	Lactobacillus salivarius	1	0
1629124	NA	Bacteroidetes	Cytophagia	Cytophagales	Hymenobacteraceae	Hymenobacter	Hymenobacter terrenus	1	0
1630135	NA	Actinobacteria	Actinobacteria	Micrococcales	Dermabacteraceae	Dermabacter	Dermabacter vaginalis	1	0
1630141	NA	Proteobacteria	Gammaproteobacteria	Chromatiales	Chromatiaceae	Candidatus Nitrosoglobus	Candidatus Nitrosoglobus terrae	6	0
1630172	NA	Actinobacteria	Actinobacteria	Bifidobacteriales	Bifidobacteriaceae	Bifidobacterium	Bifidobacterium hapali	3	0
1635258	NA	Proteobacteria	Deltaproteobacteria	Desulfovibrionales	Desulfohalobiaceae	Desulfonauticus	Desulfonauticus sp. 38_4375	2	0
1635288	NA	Firmicutes	Clostridia	Thermoanaerobacterales	NA	NA	Thermoanaerobacterales bacterium 50_218	3	0
1636152	NA	Planctomycetes	Planctomycetia	Planctomycetales	Planctomycetaceae	Planctomyces	Planctomyces sp. SH-PL62	1	0
1638985	NA	Actinobacteria	Actinobacteria	Micrococcales	Demequinaceae	Lysinimicrobium	Lysinimicrobium rhizosphaerae	1	0
1639	NA	Firmicutes	Bacilli	Bacillales	Listeriaceae	Listeria	Listeria monocytogenes	3	0
1640685	NA	Firmicutes	Bacilli	Lactobacillales	Enterococcaceae	Enterococcus	Enterococcus massiliensis	1	0
1641377	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Dysgonamonadaceae	Proteiniphilum	Proteiniphilum sp. 51_7	1	0
1642949	NA	Proteobacteria	Alphaproteobacteria	Sphingomonadales	Sphingomonadaceae	Sphingomonas	Sphingomonas sp. Ag1	1	0
164348	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces puniciscabiei	1	0
1652495	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium crudilactis	3	0
1653207	NA	Actinobacteria	Actinobacteria	Bifidobacteriales	Bifidobacteriaceae	Bifidobacterium	Bifidobacterium aquikefiri	1	0
1653831	NA	Bacteroidetes	Flavobacteriia	Flavobacteriales	Blattabacteriaceae	Blattabacterium	Blattabacterium cuenoti	1	0
1653	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	NA	NA	167	0
1655	NA	Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Actinomyces	Actinomyces naeslundii	2	0
165697	NA	Proteobacteria	Alphaproteobacteria	Sphingomonadales	Sphingomonadaceae	Sphingopyxis	NA	1	0
165779	NA	Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Anaerococcus	NA	1	0
1658008	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Dysgonamonadaceae	Dysgonomonas	Dysgonomonas sp. BGC7	1	0
1660160	NA	Acidobacteria	NA	NA	NA	NA	Acidobacteria bacterium SCN 69-37	1	0
1663591	NA	Proteobacteria	Alphaproteobacteria	Rhodospirillales	Rhodospirillaceae	Magnetospirillum	Magnetospirillum sp. XM-1	4	0
1673723	NA	Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Murdochiella	Murdochiella massiliensis	1	0
1673726	NA	Firmicutes	Clostridia	Clostridiales	NA	NA	Clostridiales bacterium SIT11	1	0
167642	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Ilyobacter	Ilyobacter polytropus	1	0
1678	NA	Actinobacteria	Actinobacteria	Bifidobacteriales	Bifidobacteriaceae	Bifidobacterium	NA	5	0
1679753	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. NBRC 110468	2	0
1680	NA	Actinobacteria	Actinobacteria	Bifidobacteriales	Bifidobacteriaceae	Bifidobacterium	Bifidobacterium adolescentis	1	0
168697	NA	Actinobacteria	Actinobacteria	Micromonosporales	Micromonosporaceae	Salinispora	Salinispora arenicola	1	0
168808	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Leptotrichiaceae	Sneathia	NA	1485	0
1688	NA	Actinobacteria	Actinobacteria	Bifidobacteriales	Bifidobacteriaceae	Bifidobacterium	Bifidobacterium cuniculi	1	0
1689271	NA	Actinobacteria	Actinobacteria	Micrococcales	Cellulomonadaceae	Cellulomonas	Cellulomonas sp. SN7	1	0
1689303	NA	Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Lagierella	Lagierella massiliensis	2	0
1690244	NA	Firmicutes	Bacilli	Lactobacillales	Enterococcaceae	Enterococcus	Enterococcus sp. RIT-PI-f	1	0
1691891	NA	Actinobacteria	Actinobacteria	Streptosporangiales	Streptosporangiaceae	Nonomuraea	Nonomuraea sp. NBRC 110462	1	0
169435	NA	Firmicutes	Clostridia	Clostridiales	Ruminococcaceae	Anaerotruncus	Anaerotruncus colihominis	2	0
1696	NA	Actinobacteria	Actinobacteria	Micrococcales	Brevibacteriaceae	Brevibacterium	NA	3	0
1701324	NA	NA	NA	NA	NA	NA	uncultured bacterium 5E7	1	0
1701325	NA	NA	NA	NA	NA	NA	uncultured bacterium 5G12	2	0
1701326	NA	NA	NA	NA	NA	NA	uncultured bacterium 5G4	25	0
1703755	NA	candidate division WOR-3	NA	NA	NA	NA	NA	1	0
1703770	NA	NA	NA	NA	NA	NA	candidate division TA06 bacterium DG_24	1	0
1703926	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. MJM1172	1	0
1703940	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. CB02261	1	0
1705388	NA	Cyanobacteria	NA	Oscillatoriales	Microcoleaceae	Planktothricoides	Planktothricoides sp. SR001	1	0
1705	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium stationis	1	0
1706375	NA	Proteobacteria	Gammaproteobacteria	Cellvibrionales	Spongiibacteraceae	NA	NA	1	0
1707	NA	Actinobacteria	Actinobacteria	Micrococcales	Cellulomonadaceae	Cellulomonas	NA	1	0
1709476	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. NRRL B-24085	2	0
1711	NA	Actinobacteria	Actinobacteria	Micrococcales	Cellulomonadaceae	Cellulomonas	Cellulomonas flavigena	1	0
171437	NA	Proteobacteria	Alphaproteobacteria	Rhodospirillales	Rhodospirillaceae	Tistrella	Tistrella mobilis	1	0
1714833	Fungi	Basidiomycota	Agaricomycetes	Agaricales	Agaricaceae	Leucoagaricus	Leucoagaricus sp. SymC.cos	1	0
1715051	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus sp. HMSC068F04	1	0
1715116	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus sp. HMSC065H07	2	0
171549	NA	Bacteroidetes	Bacteroidia	Bacteroidales	NA	NA	NA	4	0
171550	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Rikenellaceae	NA	NA	1	0
171674	NA	Proteobacteria	Alphaproteobacteria	Rhodospirillales	Rhodospirillaceae	Inquilinus	Inquilinus limosus	1	0
171693	NA	Firmicutes	Bacilli	Bacillales	Bacillaceae	Oceanobacillus	Oceanobacillus picturae	1	0
1716	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	NA	9338	0
1717	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium diphtheriae	7	0
1718951	NA	Actinobacteria	Actinobacteria	Streptosporangiales	Nocardiopsaceae	Nocardiopsis	Nocardiopsis sp. TSRI0078	1	0
1718985	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. CB02923	1	0
1718	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium glutamicum	7	0
1719	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium pseudotuberculosis	2	0
171	NA	Spirochaetes	Spirochaetia	NA	Leptospiraceae	Leptospira	NA	1	0
1720192	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium bouchesdurhonense	1	0
1720199	NA	Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Anaerococcus	Anaerococcus rubeinfantis	1	0
1720349	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium diphtheriae	6	0
1723384	NA	Firmicutes	Clostridia	Clostridiales	NA	Fenollaria	Fenollaria timonensis	1	0
1724	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium renale	1	0
1725	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium xerosis	1	0
1727216	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. H-KF8	1	0
172733	NA	Firmicutes	Clostridia	Clostridiales	NA	NA	uncultured Clostridiales bacterium	3	0
1736252	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	Methylobacteriaceae	Methylobacterium	Methylobacterium sp. Leaf100	1	0
1736255	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	Methylobacteriaceae	Methylobacterium	Methylobacterium sp. Leaf106	2	0
1736322	NA	Actinobacteria	Actinobacteria	Propionibacteriales	Nocardioidaceae	Nocardioides	Nocardioides sp. Leaf285	1	0
1736328	NA	Actinobacteria	Actinobacteria	Micrococcales	Microbacteriaceae	Rathayibacter	Rathayibacter sp. Leaf299	1	0
1736331	NA	Actinobacteria	Actinobacteria	Propionibacteriales	Nocardioidaceae	Nocardioides	Nocardioides sp. Leaf307	1	0
1736354	NA	Actinobacteria	Actinobacteria	Geodermatophilales	Geodermatophilaceae	Geodermatophilus	Geodermatophilus sp. Leaf369	3	0
1736356	NA	Actinobacteria	Actinobacteria	Geodermatophilales	Geodermatophilaceae	Modestobacter	Modestobacter sp. Leaf380	2	0
1736379	NA	Actinobacteria	Actinobacteria	Propionibacteriales	Nocardioidaceae	Marmoricola	Marmoricola sp. Leaf446	1	0
1736409	NA	Actinobacteria	Actinobacteria	Propionibacteriales	Nocardioidaceae	Nocardioides	Nocardioides sp. Soil777	1	0
1736433	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	NA	Rhizobacter	Rhizobacter sp. Root1221	1	0
1736459	NA	Actinobacteria	Actinobacteria	Micrococcales	Cellulomonadaceae	Cellulomonas	Cellulomonas sp. Root137	1	0
1736528	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	NA	Rhizobacter	Rhizobacter sp. Root404	1	0
1737404	NA	Firmicutes	Tissierellia	NA	NA	NA	NA	1	0
1739279	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Fusobacterium	Fusobacterium sp. HMSC064B12	4	0
1739312	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium sp. HMSC078A10	1	0
1739371	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus sp. HMSC064H09	3	0
1739381	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus sp. HMSC072D03	1	0
1739435	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Fusobacterium	Fusobacterium sp. HMSC065F01	6	0
1739447	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium sp. HMSC072D12	2	0
1739483	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus sp. HMSC078H12	1	0
1739536	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium sp. HMSC073D01	20	0
1739540	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium sp. HMSC075D04	6	0
1739543	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Fusobacterium	Fusobacterium sp. HMSC064B11	2	0
1740263	NA	Bacteroidetes	Flavobacteriia	Flavobacteriales	Crocinitomicaceae	Crocinitomix	Crocinitomix algicola	1	0
1742262	NA	Actinobacteria	Actinobacteria	Frankiales	Frankiaceae	Frankia	Frankia sp. CgIM4	1	0
1742973	NA	Nitrospirae	Nitrospira	Nitrospirales	Nitrospiraceae	Nitrospira	Candidatus Nitrospira nitrificans	1	0
1744	NA	Actinobacteria	Actinobacteria	Propionibacteriales	Propionibacteriaceae	Propionibacterium	Propionibacterium freudenreichii	2	0
1747	NA	Actinobacteria	Actinobacteria	Propionibacteriales	Propionibacteriaceae	Cutibacterium	Cutibacterium acnes	5	0
1750712	NA	NA	NA	NA	Baculoviridae	Betabaculovirus	Cnaphalocrocis medinalis granulovirus	1	0
1752188	NA	Actinobacteria	NA	NA	NA	NA	NA	5	0
1752732	NA	Candidatus Uhrbacteria	NA	NA	NA	NA	NA	2	0
1754190	Fungi	Chytridiomycota	Neocallimastigomycetes	Neocallimastigales	Neocallimastigaceae	Neocallimastix	Neocallimastix californiae	4	0
1754191	Fungi	Chytridiomycota	Neocallimastigomycetes	Neocallimastigales	Neocallimastigaceae	Piromyces	Piromyces finnis	34	0
1754192	Fungi	Chytridiomycota	Neocallimastigomycetes	Neocallimastigales	Neocallimastigaceae	Anaeromyces	Anaeromyces robustus	2	0
1756034	NA	NA	NA	NA	Orthomyxoviridae	Influenzavirus A	Influenza A virus	2	0
1758255	NA	Euryarchaeota	Halobacteria	Haloferacales	Halorubraceae	Halorubrum	Halorubrum aethiopicum	1	0
1760	NA	Actinobacteria	Actinobacteria	NA	NA	NA	NA	791	0
1761746	NA	Actinobacteria	Actinobacteria	Micrococcales	Micrococcaceae	Arthrobacter	Arthrobacter sp. ok909	1	0
1761781	NA	Firmicutes	Clostridia	Clostridiales	Clostridiaceae	Clostridium	Clostridium sp. DSM 8431	4	0
1761786	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Gordoniaceae	Gordonia	Gordonia sp. v-85	1	0
1761904	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. cf386	1	0
1763	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Mycobacteriaceae	Mycobacterium	NA	24	0
1765655	NA	Euryarchaeota	Halobacteria	Haloferacales	Halorubraceae	Halorubrum	Halorubrum tropicale	1	0
1766719	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Leptotrichiaceae	Caviibacter	Caviibacter abscessus	6	0
1768196	NA	Firmicutes	Erysipelotrichia	Erysipelotrichales	Erysipelotrichaceae	NA	Erysipelotrichaceae bacterium MTC7	1	0
1768767	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus sp. CCH8-H5	1	0
1769291	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Leptotrichiaceae	Oceanivirga	Oceanivirga salmonicida	6	0
1769418	NA	Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Actinomyces	Actinomyces sp. C10	1	0
1773	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Mycobacteriaceae	Mycobacterium	Mycobacterium tuberculosis	20	0
1777878	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus sp. DD10	4	0
1777881	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus sp. DD13	1	0
1778540	NA	Proteobacteria	Gammaproteobacteria	Enterobacterales	Pectobacteriaceae	Dickeya	Dickeya fangzhongdai	1	0
1778	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Mycobacteriaceae	Mycobacterium	Mycobacterium gordonae	1	0
1780	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Mycobacteriaceae	Mycobacterium	Mycobacterium malmoense	1	0
1781255	NA	Cyanobacteria	NA	Oscillatoriales	Desertifilaceae	Desertifilum	Desertifilum sp. IPPAS B-1220	1	0
1783272	NA	NA	NA	NA	NA	NA	NA	299	0
1785996	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Leptotrichiaceae	Leptotrichia	Leptotrichia sp. oral taxon 847	1	0
1785	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Mycobacteriaceae	Mycobacterium	Mycobacterium sp.	1	0
1787	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Mycobacteriaceae	Mycobacterium	Mycobacterium szulgai	1	0
1789683	Fungi	Ascomycota	Saccharomycetes	Saccharomycetales	Saccharomycetaceae	Kazachstania	Kazachstania saulgeensis	1	0
1792845	NA	Bacteroidetes	Sphingobacteriia	Sphingobacteriales	Sphingobacteriaceae	Mucilaginibacter	Mucilaginibacter pedocola	1	0
1794811	NA	NA	NA	NA	NA	NA	NA	2	0
1794840	NA	NA	NA	NA	NA	NA	NA	1	0
1797499	NA	Proteobacteria	Betaproteobacteria	NA	NA	NA	Betaproteobacteria bacterium RIFCSPLOWO2_12_FULL_64_23	1	0
1797546	NA	Candidatus Buchananbacteria	NA	NA	NA	NA	Candidatus Buchananbacteria bacterium RIFCSPLOWO2_01_FULL_46_12	1	0
1797647	NA	Chloroflexi	NA	NA	NA	NA	Chloroflexi bacterium RBG_16_54_11	1	0
1797673	NA	Chloroflexi	NA	NA	NA	NA	Chloroflexi bacterium RIFCSPLOWO2_12_FULL_71_12	1	0
1797808	NA	Proteobacteria	Deltaproteobacteria	NA	NA	NA	Deltaproteobacteria bacterium GWA2_54_12	1	0
1797846	NA	Proteobacteria	Deltaproteobacteria	NA	NA	NA	Deltaproteobacteria bacterium RBG_16_64_85	1	0
1798224	NA	Actinobacteria	Actinobacteria	Jiangellales	Jiangellaceae	Jiangella	Jiangella sp. DSM 45060	3	0
1798267	NA	Proteobacteria	Gammaproteobacteria	NA	NA	NA	Gammaproteobacteria bacterium RBG_16_66_13	1	0
1798559	NA	NA	NA	NA	NA	NA	candidate division KSB1 bacterium RBG_16_48_16	1	0
1798569	NA	Proteobacteria	Gammaproteobacteria	Legionellales	NA	NA	Legionellales bacterium RIFCSPHIGHO2_12_FULL_42_9	1	0
180088	Fungi	Basidiomycota	Agaricomycetes	Boletales	Rhizopogonaceae	Rhizopogon	Rhizopogon vesiculosus	2	0
180162	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Cetobacterium	NA	1	0
1801639	NA	Candidatus Moranbacteria	NA	NA	NA	NA	Candidatus Moranbacteria bacterium RIFCSPHIGHO2_02_FULL_40_12b	2	0
1801840	NA	Candidatus Omnitrophica	NA	NA	NA	NA	Omnitrophica WOR_2 bacterium GWA2_47_8	1	0
1801952	NA	Planctomycetes	NA	NA	NA	NA	Planctomycetes bacterium GWC2_45_44	1	0
180197	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Comamonadaceae	Giesbergeria	Giesbergeria anulus	1	0
1801991	NA	Candidatus Portnoybacteria	NA	NA	NA	NA	Candidatus Portnoybacteria bacterium RBG_13_41_18	2	0
1802055	NA	Candidatus Roizmanbacteria	NA	NA	NA	NA	Candidatus Roizmanbacteria bacterium RIFCSPLOWO2_01_FULL_35_13	1	0
1802106	NA	Candidatus Rokubacteria	NA	NA	NA	NA	Candidatus Rokubacteria bacterium RIFCSPLOWO2_02_FULL_72_37	1	0
1802307	NA	Candidatus Taylorbacteria	NA	NA	NA	NA	Candidatus Taylorbacteria bacterium RIFCSPHIGHO2_02_FULL_43_55	8	0
1802344	NA	Tenericutes	NA	NA	NA	NA	Tenericutes bacterium GWA2_35_7	6	0
1802368	NA	Candidatus Terrybacteria	NA	NA	NA	NA	Candidatus Terrybacteria bacterium RIFCSPLOWO2_01_FULL_48_14	2	0
1803429	NA	Acidobacteria	NA	NA	NA	NA	Acidobacteria bacterium 13_1_20CM_2_68_14	1	0
1804758	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. CB03911	1	0
1805323	NA	Candidatus Peregrinibacteria	NA	NA	NA	NA	Candidatus Peregrinibacteria bacterium CG1_02_54_53	1	0
1805496	NA	NA	NA	NA	NA	Moramonas	Moramonas marocensis	1	0
1812480	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. fd1-xmd	1	0
1813822	Fungi	NA	NA	NA	NA	NA	fungal sp. No.14919	1	0
1816695	NA	Firmicutes	Bacilli	Bacillales	Bacillaceae	Bacillus	Bacillus tuaregi	1	0
1817864	NA	Candidatus Fraserbacteria	NA	NA	NA	NA	Candidatus Fraserbacteria bacterium RBG_16_55_9	1	0
1817868	NA	Candidatus Handelsmanbacteria	NA	NA	NA	NA	Candidatus Handelsmanbacteria bacterium RIFCSPLOWO2_12_FULL_64_10	1	0
1817	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Nocardiaceae	Nocardia	NA	2	0
1827	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Nocardiaceae	Rhodococcus	NA	3	0
1828	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Nocardiaceae	Rhodococcus	Rhodococcus fascians	1	0
1834076	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Mycobacteriaceae	Mycobacterium	Mycobacterium sp. 1274756.6	1	0
1834079	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Mycobacteriaceae	Mycobacterium	Mycobacterium sp. 1477680.9	1	0
1834143	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Mycobacteriaceae	Mycobacterium	Mycobacterium sp. E3198	3	0
1834172	NA	Firmicutes	Bacilli	Lactobacillales	Enterococcaceae	Enterococcus	Enterococcus sp. 2F9_DIV0599	2	0
1834173	NA	Firmicutes	Bacilli	Lactobacillales	Enterococcaceae	Enterococcus	Enterococcus sp. 2G9_DIV0600	1	0
1835702	Fungi	Ascomycota	Eurotiomycetes	Eurotiales	Aspergillaceae	Penicillium	Penicillium arizonense	1	0
1835724	NA	Proteobacteria	Gammaproteobacteria	Enterobacterales	Erwiniaceae	Pantoea	Pantoea sp. OXWO6B1	2	0
1835	NA	Actinobacteria	Actinobacteria	Pseudonocardiales	Pseudonocardiaceae	Saccharopolyspora	NA	1	0
1836462	NA	Firmicutes	Bacilli	Bacillales	Bacillaceae	NA	Bacillaceae bacterium G1	1	0
1839	NA	Actinobacteria	Actinobacteria	Propionibacteriales	Nocardioidaceae	Nocardioides	NA	1	0
1840537	NA	Proteobacteria	Gammaproteobacteria	Thiotrichales	Piscirickettsiaceae	Cycloclasticus	Cycloclasticus sp. symbiont of Poecilosclerida sp. M	1	0
184064	NA	Firmicutes	Clostridia	Thermoanaerobacterales	Thermodesulfobiaceae	Thermodesulfobium	Thermodesulfobium narugense	1	0
1841857	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Odoribacteraceae	Culturomica	Culturomica massiliensis	1	0
1842532	NA	Proteobacteria	Deltaproteobacteria	Desulfuromonadales	Desulfuromonadaceae	Pelobacter	Pelobacter sp. SFB93	1	0
1844478	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. IB2014 011-1	2	0
184748	NA	Proteobacteria	Alphaproteobacteria	Rhodobacterales	Rhodobacteraceae	Paracoccus	Paracoccus seriniphilus	1	0
184870	NA	Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Varibaculum	Varibaculum cambriense	1	0
184917	NA	Proteobacteria	Deltaproteobacteria	Desulfovibrionales	Desulfovibrionaceae	Desulfovibrio	Desulfovibrio magneticus	2	0
1851	NA	Actinobacteria	Actinobacteria	Pseudonocardiales	Pseudonocardiaceae	Saccharomonospora	NA	2	0
1852365	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Fusobacterium	Fusobacterium massiliense	10	0
1852380	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium urinapleomorphum	2	0
1852390	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium fournierii	6	0
185431	NA	NA	NA	Kinetoplastida	Trypanosomatidae	Trypanosoma	Trypanosoma brucei	4	0
1854588	NA	Actinobacteria	Actinobacteria	Pseudonocardiales	Pseudonocardiaceae	Pseudonocardia	Pseudonocardia sp. MH-G8	1	0
1854	NA	Actinobacteria	Actinobacteria	Frankiales	Frankiaceae	Frankia	NA	7	0
1855319	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	Bradyrhizobiaceae	Bradyrhizobium	Bradyrhizobium sp. Ghvi	1	0
1855325	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella sp. KH2C16	1	0
1855346	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. 2131.1	1	0
1855352	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. TLI_053	1	0
1855728	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Comamonadaceae	Variovorax	Variovorax sp. KK3	1	0
1855912	NA	Acidobacteria	NA	NA	NA	Luteitalea	Luteitalea pratensis	1	0
1856278	NA	Proteobacteria	Gammaproteobacteria	Oceanospirillales	Oceanospirillaceae	Bermanella	Bermanella sp. 47_1433_sub80_T6	1	0
1856638	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus bovimastitidis	2	0
1858794	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Mycobacteriaceae	Mycobacterium	Mycobacterium talmoniae	2	0
1858805	Fungi	Basidiomycota	Dacrymycetes	Dacrymycetales	Dacrymycetaceae	Dacryopinax	Dacryopinax primogenitus	2	0
186103	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus pyogenes	1	0
1865	NA	Actinobacteria	Actinobacteria	Micromonosporales	Micromonosporaceae	Actinoplanes	NA	1	0
1867952	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	Methylocystaceae	Terasakiella	Terasakiella sp. PR1	2	0
186802	NA	Firmicutes	Clostridia	Clostridiales	NA	NA	NA	14	0
186803	NA	Firmicutes	Clostridia	Clostridiales	Lachnospiraceae	NA	NA	2	0
186804	NA	Firmicutes	Clostridia	Clostridiales	Peptostreptococcaceae	NA	NA	1	0
186807	NA	Firmicutes	Clostridia	Clostridiales	Peptococcaceae	NA	NA	2	0
186817	NA	Firmicutes	Bacilli	Bacillales	Bacillaceae	NA	NA	1	0
186826	NA	Firmicutes	Bacilli	Lactobacillales	NA	NA	NA	297	0
1868284	NA	Proteobacteria	Gammaproteobacteria	Oceanospirillales	Endozoicomonaceae	Endozoicomonas	Endozoicomonas sp. (ex Bugula neritina AB1)	1	0
1869	NA	Actinobacteria	Actinobacteria	Micromonosporales	Micromonosporaceae	Actinoplanes	Actinoplanes utahensis	1	0
1870994	NA	Firmicutes	Tissierellia	Tissierellales	Tissierellaceae	Urmitella	Urmitella timonensis	1	0
1871002	NA	Firmicutes	Negativicutes	Acidaminococcales	Acidaminococcaceae	Acidaminococcus	Acidaminococcus timonensis	1	0
187101	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Leptotrichiaceae	Sneathia	Sneathia amnii	214	0
1871336	NA	Firmicutes	Clostridia	Clostridiales	Peptostreptococcaceae	Criibacterium	Criibacterium bergeronii	3	0
187137	NA	Deinococcus-Thermus	Deinococci	Thermales	Thermaceae	Oceanithermus	Oceanithermus profundus	1	0
187145	NA	Calditrichaeota	Calditrichae	Calditrichales	Calditrichaceae	Caldithrix	Caldithrix abyssi	1	0
1872629	NA	Proteobacteria	Epsilonproteobacteria	Campylobacterales	Campylobacteraceae	Arcobacter	Arcobacter sp.	1	0
1873	NA	Actinobacteria	Actinobacteria	Micromonosporales	Micromonosporaceae	Micromonospora	NA	3	0
187491	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium glaucum	1	0
1881046	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Oxalobacteraceae	Massilia	Massilia sp. PDC64	1	0
1881058	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	Bradyrhizobiaceae	Bosea	Bosea sp. DSM 18164	1	0
1881061	NA	Proteobacteria	Alphaproteobacteria	Rhodobacterales	Rhodobacteraceae	Stappia	Stappia sp. ES.058	1	0
1882748	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	Beijerinckiaceae	Beijerinckia	Beijerinckia sp. 28-YEA-48	1	0
1882753	NA	Firmicutes	Bacilli	Bacillales	Thermoactinomycetaceae	Thermoactinomyces	Thermoactinomyces sp. DSM 45892	1	0
1882757	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. 3214.6	2	0
1883	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	NA	45	0
1885573	NA	Actinobacteria	Actinobacteria	Pseudonocardiales	Pseudonocardiaceae	Pseudonocardia	Pseudonocardia sp. Ae717_Ps2	1	0
1888195	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus himalayensis	1	0
1890286	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. LUP47B	1	0
1891289	NA	Firmicutes	Tissierellia	Tissierellales	NA	Sporanaerobacter	Sporanaerobacter sp. PP17-6a	1	0
189382	NA	Firmicutes	Bacilli	Bacillales	Bacillaceae	Bacillus	Bacillus aquimaris	1	0
189426	NA	Firmicutes	Bacilli	Bacillales	Paenibacillaceae	Paenibacillus	Paenibacillus odorifer	11	0
1894	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Kitasatospora	Kitasatospora aureofaciens	1	0
1895696	NA	Actinobacteria	Actinobacteria	NA	NA	NA	Actinobacteria bacterium 69-20	1	0
1895721	NA	Bacteroidetes	Bacteroidia	NA	NA	NA	Bacteroidia bacterium 44-10	1	0
1895809	NA	Actinobacteria	Actinobacteria	Pseudonocardiales	Pseudonocardiaceae	Pseudonocardia	Pseudonocardia sp. 73-21	2	0
1895813	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	NA	NA	Rhizobiales bacterium 63-7	1	0
1895848	NA	Proteobacteria	Alphaproteobacteria	Sphingomonadales	Sphingomonadaceae	Sphingomonas	Sphingomonas sp. 66-10	1	0
1895903	NA	Proteobacteria	Gammaproteobacteria	Legionellales	Legionellaceae	Legionella	Legionella sp. 40-6	1	0
1895921	NA	Bacteroidetes	NA	NA	NA	NA	Bacteroidetes bacterium 37-13	1	0
1896210	NA	Fibrobacteres	Fibrobacteria	Fibrobacterales	Fibrobacteraceae	Fibrobacter	Fibrobacter sp. UWH4	1	0
189622	NA	Apicomplexa	Aconoidasida	NA	Babesiidae	Babesia	Babesia ovata	11	0
1898203	NA	Firmicutes	Clostridia	Clostridiales	Lachnospiraceae	NA	Lachnospiraceae bacterium	2	0
190304	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Fusobacterium	Fusobacterium nucleatum	366	0
1903	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces corchorusii	1	0
1904441	NA	Proteobacteria	Alphaproteobacteria	Rhodobacterales	Rhodobacteraceae	NA	Rhodobacteraceae bacterium	1	0
1904961	NA	Actinobacteria	Actinobacteria	Streptosporangiales	Thermomonosporaceae	Actinomadura	Actinomadura sp. CNU-125	1	0
1904964	NA	Actinobacteria	Actinobacteria	Micrococcales	Micrococcaceae	Kocuria	Kocuria sp. CNJ-770	1	0
1904970	NA	Actinobacteria	Actinobacteria	Micrococcales	Intrasporangiaceae	Serinicoccus	Serinicoccus sp. CNJ-927	4	0
1906	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces fradiae	1	0
1911	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces griseus	1	0
1912214	NA	Firmicutes	Bacilli	Bacillales	Bacillaceae	Bacillus	Bacillus sp. FJAT-44921	1	0
1913988	NA	Proteobacteria	Alphaproteobacteria	NA	NA	NA	Alphaproteobacteria bacterium	1	0
191412	NA	Chlorobi	Chlorobia	Chlorobiales	Chlorobiaceae	NA	NA	1	0
1914307	NA	Proteobacteria	Gammaproteobacteria	Pseudomonadales	Moraxellaceae	Acinetobacter	Acinetobacter sp. LCT-H3	1	0
1915	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces lincolnensis	1	0
191610	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium atypicum	1	0
1917481	NA	Proteobacteria	Gammaproteobacteria	Methylococcales	Methylococcaceae	NA	Methylococcaceae bacterium NSP1-2	4	0
1917973	NA	Proteobacteria	Alphaproteobacteria	Sphingomonadales	Sphingomonadaceae	Sphingomonas	Sphingomonas sp. TZW2008	1	0
191863	NA	Verrucomicrobia	Spartobacteria	Chthoniobacterales	Chthoniobacteraceae	Chthoniobacter	Chthoniobacter flavus	1	0
1920422	NA	Firmicutes	Bacilli	Bacillales	Paenibacillaceae	Paenibacillus	Paenibacillus sp. FSL H8-0548	1	0
1926491	NA	Proteobacteria	Gammaproteobacteria	Oceanospirillales	Hahellaceae	Hahella	Hahella sp. CCB-MM4	1	0
1926608	NA	Chloroflexi	NA	NA	NA	NA	SAR202 cluster bacterium Ae2-Chloro-G2	1	0
1926885	NA	Actinobacteria	Actinobacteria	Streptosporangiales	Thermomonosporaceae	Actinomadura	Actinomadura sp. 5-2	1	0
1927129	NA	Euryarchaeota	Methanonatronarchaeia	NA	NA	Methanonatronarchaeum	Methanonatronarchaeum thermophilum	2	0
1928	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces rochei	1	0
192952	NA	Euryarchaeota	Methanomicrobia	Methanosarcinales	Methanosarcinaceae	Methanosarcina	Methanosarcina mazei	1	0
192	NA	Proteobacteria	Alphaproteobacteria	Rhodospirillales	Rhodospirillaceae	Azospirillum	Azospirillum brasilense	1	0
1930	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces scabiei	4	0
1938835	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. 1331.2	1	0
1940525	NA	Bacteroidetes	Bacteroidia	Marinilabiliales	Marinifilaceae	Labilibaculum	Labilibaculum manganireducens	2	0
1943582	NA	Cyanobacteria	NA	Synechococcales	Synechococcaceae	Synechococcus	Candidatus Synechococcus spongiarum	1	0
1943	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces griseoruber	2	0
194	NA	Proteobacteria	Epsilonproteobacteria	Campylobacterales	Campylobacteraceae	Campylobacter	NA	523	0
195	NA	Proteobacteria	Epsilonproteobacteria	Campylobacterales	Campylobacteraceae	Campylobacter	Campylobacter coli	4	0
196109	Fungi	Ascomycota	Sordariomycetes	Xylariales	Microdochiaceae	Microdochium	Microdochium bolleyi	2	0
196164	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium efficiens	9	0
1962181	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	NA	Ideonella	Ideonella sp. A 288	1	0
1962290	NA	Cyanobacteria	NA	Synechococcales	Leptolyngbyaceae	Leptolyngbya	Leptolyngbya ohadii	3	0
1964355	NA	Fibrobacteres	Fibrobacteria	Fibrobacterales	Fibrobacteraceae	Fibrobacter	Fibrobacter sp. UWB1	1	0
1964395	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Mycobacteriaceae	Mycobacterium	Mycobacterium sp. AFP003	2	0
1965452	NA	NA	NA	Caudovirales	Siphoviridae	NA	Streptomyces phage ToastyFinz	1	0
1965545	NA	Firmicutes	Clostridia	Clostridiales	Lachnospiraceae	Tyzzerella	Tyzzerella sp. An114	1	0
196	NA	Proteobacteria	Epsilonproteobacteria	Campylobacterales	Campylobacteraceae	Campylobacter	Campylobacter fetus	4	0
1970530	NA	Proteobacteria	Hydrogenophilalia	Hydrogenophilales	NA	NA	Hydrogenophilales bacterium 28-61-23	1	0
1970542	NA	Planctomycetes	Planctomycetia	NA	NA	NA	Planctomycetia bacterium 21-64-5	1	0
1970550	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	NA	NA	Rhizobiales bacterium 32-66-8	1	0
1970608	NA	Verrucomicrobia	NA	NA	NA	NA	Verrucomicrobia bacterium 12-59-8	1	0
1971	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces noursei	3	0
1972511	NA	Bacteroidetes	Sphingobacteriia	Sphingobacteriales	NA	NA	Sphingobacteriales bacterium TSM_CSS	1	0
1973486	NA	Cyanobacteria	NA	Nostocales	Rivulariaceae	Calothrix	Calothrix parasitica	1	0
1973905	NA	Chloroflexi	Anaerolineae	NA	NA	NA	Anaerolineae bacterium CG03_land_8_20_14_0_80_58_20	1	0
1973927	NA	Proteobacteria	Oligoflexia	Bdellovibrionales	NA	NA	Bdellovibrionales bacterium CG10_big_fil_rev_8_21_14_0_10_45_34	1	0
1973972	NA	Proteobacteria	Deltaproteobacteria	NA	NA	NA	Deltaproteobacteria bacterium CG07_land_8_20_14_0_80_60_11	1	0
1974407	NA	Candidatus Diapherotrites	NA	NA	NA	NA	Candidatus Diapherotrites archaeon CG11_big_fil_rev_8_21_14_0_20_37_9	1	0
1974577	NA	Candidatus Gracilibacteria	NA	NA	NA	NA	Candidatus Gracilibacteria bacterium CG_4_10_14_0_8_um_filter_38_28	1	0
1974610	NA	Candidatus Kaiserbacteria	NA	NA	NA	NA	Candidatus Kaiserbacteria bacterium CG10_big_fil_rev_8_21_14_0_10_51_14	1	0
197614	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus pasteurianus	1	0
1977087	NA	Proteobacteria	NA	NA	NA	NA	Proteobacteria bacterium	1	0
1977640	NA	NA	NA	NA	Mimiviridae	Klosneuvirus	Klosneuvirus KNV1	1	0
1977882	NA	Proteobacteria	Gammaproteobacteria	Pseudomonadales	Moraxellaceae	Acinetobacter	Acinetobacter sp. ANC 4999	1	0
1977884	NA	Proteobacteria	Gammaproteobacteria	Pseudomonadales	Moraxellaceae	Acinetobacter	Acinetobacter sp. ANC 4204	1	0
1978124	NA	Euryarchaeota	Methanomicrobia	Methanosarcinales	NA	NA	Methanosarcinales archaeon ex4572_44	1	0
197	NA	Proteobacteria	Epsilonproteobacteria	Campylobacterales	Campylobacteraceae	Campylobacter	Campylobacter jejuni	1	0
198252	NA	Proteobacteria	Alphaproteobacteria	Pelagibacterales	Pelagibacteraceae	Candidatus Pelagibacter	Candidatus Pelagibacter ubique	3	0
1985876	NA	Proteobacteria	Gammaproteobacteria	Enterobacterales	Enterobacteriaceae	Escherichia	Escherichia sp. ESNIH1	1	0
1986611	NA	Planctomycetes	Phycisphaerae	Phycisphaerales	Phycisphaeraceae	Phycisphaera	Phycisphaera sp. TMED9	1	0
1986638	NA	Proteobacteria	Alphaproteobacteria	Rhodospirillales	Rhodospirillaceae	Candidatus Endolissoclinum	Candidatus Endolissoclinum sp. TMED37	1	0
1986781	NA	NA	NA	NA	NA	NA	bacterium TMED274	1	0
1986837	NA	Planctomycetes	NA	NA	NA	NA	Planctomycetes bacterium TMED75	1	0
198730	Fungi	Ascomycota	Eurotiomycetes	Eurotiales	Trichocomaceae	Talaromyces	Talaromyces verruculosus	1	0
1992	NA	Actinobacteria	Actinobacteria	Streptosporangiales	Thermomonosporaceae	Actinomadura	Actinomadura echinospora	1	0
199684	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	Bradyrhizobiaceae	Bradyrhizobium	uncultured Bradyrhizobium sp.	1	0
1997	NA	Actinobacteria	Actinobacteria	Streptosporangiales	Streptosporangiaceae	Microtetraspora	Microtetraspora fusca	1	0
199	NA	Proteobacteria	Epsilonproteobacteria	Campylobacterales	Campylobacteraceae	Campylobacter	Campylobacter concisus	5	0
1	NA	NA	NA	NA	NA	NA	NA	26	0
200324	Fungi	Basidiomycota	Pucciniomycetes	Pucciniales	Pucciniaceae	Puccinia	Puccinia coronata	1	0
2003629	NA	Bacteroidetes	Sphingobacteriia	Sphingobacteriales	Sphingobacteriaceae	Pedobacter	Pedobacter sp. AJM	1	0
200378	NA	Actinobacteria	Actinobacteria	Pseudonocardiales	Pseudonocardiaceae	Lechevalieria	Lechevalieria fradiae	1	0
2004951	Fungi	Ascomycota	Sordariomycetes	Hypocreales	Cordycipitaceae	Cordyceps	Cordyceps sp. RAO-2017	1	0
2004952	Fungi	Ascomycota	Sordariomycetes	Hypocreales	Ophiocordycipitaceae	Ophiocordyceps	Ophiocordyceps camponoti-rufipedis	2	0
2004957	NA	NA	NA	NA	Genomoviridae	Gemykibivirus	Human associated gemykibivirus 2	1	0
2005569	NA	Proteobacteria	Gammaproteobacteria	Alteromonadales	Alteromonadaceae	Lacimicrobium	Lacimicrobium sp. SS2-24	1	0
2005709	NA	NA	NA	NA	NA	NA	bacterium BMS3Abin01	1	0
200795	NA	Chloroflexi	NA	NA	NA	NA	NA	2	0
2011009	NA	Firmicutes	Bacilli	Bacillales	Bacillaceae	Bacillus	Bacillus sp. FJAT-45505	1	0
201174	NA	Actinobacteria	NA	NA	NA	NA	NA	34	0
2013692	NA	Bacteroidetes	NA	NA	NA	NA	Bacteroidetes bacterium HGW-Bacteroidetes-23	1	0
2013723	NA	Chloroflexi	NA	NA	NA	NA	Chloroflexi bacterium HGW-Chloroflexi-1	2	0
2013736	NA	Proteobacteria	Deltaproteobacteria	NA	NA	NA	Deltaproteobacteria bacterium HGW-Deltaproteobacteria-1	1	0
2013789	NA	Firmicutes	NA	NA	NA	NA	Firmicutes bacterium HGW-Firmicutes-8	1	0
2013811	NA	Ignavibacteriae	NA	NA	NA	NA	Ignavibacteriae bacterium HGW-Ignavibacteriae-4	2	0
2013813	NA	Candidatus Melainabacteria	NA	NA	NA	NA	Candidatus Melainabacteria bacterium HGW-Melainabacteria-1	1	0
2013	NA	Actinobacteria	Actinobacteria	Streptosporangiales	Nocardiopsaceae	Nocardiopsis	NA	1	0
2018025	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Kitasatospora	Kitasatospora sp. MMS16-BH015	1	0
2019	NA	Actinobacteria	Actinobacteria	Streptosporangiales	Thermomonosporaceae	Thermomonospora	NA	1	0
2024223	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella sp. P3-122	1	0
2024349	NA	NA	NA	NA	NA	NA	Gemmata phage BHS4	1	0
2024580	NA	Actinobacteria	Actinobacteria	Micromonosporales	Micromonosporaceae	Plantactinospora	Plantactinospora sp. KBS50	2	0
2026724	NA	Chloroflexi	NA	NA	NA	NA	Chloroflexi bacterium	1	0
2026779	NA	Planctomycetes	Planctomycetia	Planctomycetales	Planctomycetaceae	NA	Planctomycetaceae bacterium	1	0
2026780	NA	Planctomycetes	NA	NA	NA	NA	Planctomycetes bacterium	1	0
2028570	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Nocardiaceae	Rhodococcus	Rhodococcus sp. ACS1	1	0
2030823	NA	Proteobacteria	Alphaproteobacteria	Rhodobacterales	Hyphomonadaceae	Robiginitomaculum	Robiginitomaculum sp.	1	0
2030880	NA	Proteobacteria	Gammaproteobacteria	NA	NA	NA	SAR86 cluster bacterium	3	0
203133	NA	Actinobacteria	Actinobacteria	Propionibacteriales	Propionibacteriaceae	Propionimicrobium	NA	1	0
203263	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium aquilae	3	0
2033506	NA	Firmicutes	Bacilli	Bacillales	Bacillaceae	Bacillus	Bacillus sp. AFS054943	1	0
2033654	NA	Actinobacteria	Actinobacteria	Micrococcales	Microbacteriaceae	Curtobacterium	Curtobacterium sp. 'Ferrero'	3	0
2033844	NA	Actinobacteria	Actinobacteria	Micromonosporales	Micromonosporaceae	Actinoplanes	Actinoplanes sp. SE50	2	0
2034272	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. rh34	1	0
203490	NA	Fusobacteria	Fusobacteriia	NA	NA	NA	NA	32	0
203491	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	NA	NA	NA	457	0
203492	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	NA	NA	185	0
203523	NA	Actinobacteria	Actinobacteria	Micromonosporales	Micromonosporaceae	Longispora	Longispora albida	1	0
2035245	NA	Actinobacteria	Actinobacteria	Micrococcales	Microbacteriaceae	Microcella	Microcella sp. HL-107	1	0
2035249	NA	Actinobacteria	Actinobacteria	Micromonosporales	Micromonosporaceae	Verrucosispora	Verrucosispora sp. CNZ293	1	0
2035407	NA	NA	NA	NA	NA	NA	bacterium HR12	1	0
2036037	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. Tue6028	4	0
203682	NA	Planctomycetes	NA	NA	NA	NA	NA	1	0
203	NA	Proteobacteria	Epsilonproteobacteria	Campylobacterales	Campylobacteraceae	Campylobacter	Campylobacter rectus	1	0
204457	NA	Proteobacteria	Alphaproteobacteria	Sphingomonadales	NA	NA	NA	1	0
2044594	NA	Candidatus Delongbacteria	NA	NA	NA	NA	Candidatus Delongbacteria bacterium	3	0
2044729	NA	Bacteroidetes	Cytophagia	Cytophagales	Cytophagaceae	Candidatus Nephrothrix	Candidatus Nephrothrix sp. EaCA	4	0
2044942	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	NA	NA	Fusobacteriales bacterium	2	0
2045015	NA	Firmicutes	Clostridia	Clostridiales	Peptostreptococcaceae	Peptostreptococcus	Peptostreptococcus sp. Marseille-P4308	1	0
2045	NA	Actinobacteria	Actinobacteria	Propionibacteriales	Nocardioidaceae	Pimelobacter	Pimelobacter simplex	1	0
2049	NA	Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	NA	NA	1	0
2053303	NA	Bacteroidetes	Bacteroidia	Marinilabiliales	NA	NA	Marinilabiliales bacterium	2	0
2053	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Gordoniaceae	Gordonia	NA	3	0
2058088	NA	Proteobacteria	Gammaproteobacteria	Vibrionales	Vibrionaceae	Vibrio	Vibrio sp. vnigr-6D03	1	0
2058135	NA	Bacteroidetes	Flavobacteriia	Flavobacteriales	Flavobacteriaceae	Olleya	Olleya sp. Bg11-27	1	0
2058924	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. A249	1	0
206041	NA	Bacteroidetes	Flavobacteriia	Flavobacteriales	Flavobacteriaceae	Flavobacterium	Flavobacterium gelidilacus	1	0
2066	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Kitasatospora	Kitasatospora setae	2	0
2067453	NA	Proteobacteria	Betaproteobacteria	Rhodocyclales	Zoogloeaceae	Uliginosibacterium	Uliginosibacterium sp. TH139	1	0
2069341	NA	Actinobacteria	Actinobacteria	Micromonosporales	Micromonosporaceae	Verrucosispora	Verrucosispora sp. ts21	1	0
206	NA	Proteobacteria	Epsilonproteobacteria	Campylobacterales	Campylobacteraceae	Campylobacter	Campylobacter sputorum	11	0
2070	NA	Actinobacteria	Actinobacteria	Pseudonocardiales	Pseudonocardiaceae	NA	NA	1	0
2072014	NA	Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Actinomyces	Actinomyces sp. 553	1	0
2074	NA	Actinobacteria	Actinobacteria	Pseudonocardiales	Pseudonocardiaceae	Pseudonocardia	Pseudonocardia autotrophica	3	0
207920	NA	Cyanobacteria	NA	Oscillatoriales	Oscillatoriaceae	Moorea	Moorea bouillonii	1	0
208443	NA	Actinobacteria	Actinobacteria	Pseudonocardiales	Pseudonocardiaceae	Amycolatopsis	Amycolatopsis balhimycina	1	0
208452	NA	Apicomplexa	Aconoidasida	Haemosporida	Plasmodiidae	Plasmodium	Plasmodium coatneyi	1	0
208479	NA	Firmicutes	Clostridia	Clostridiales	Lachnospiraceae	Lachnoclostridium	[Clostridium] bolteae	2	0
209882	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Fusobacterium	Fusobacterium nucleatum	90	0
209	NA	Proteobacteria	Epsilonproteobacteria	Campylobacterales	Helicobacteraceae	Helicobacter	NA	1	0
20	NA	Proteobacteria	Alphaproteobacteria	Caulobacterales	Caulobacteraceae	Phenylobacterium	NA	1	0
2102	NA	Tenericutes	Mollicutes	Mycoplasmatales	Mycoplasmataceae	Mycoplasma	Mycoplasma mycoides	1	0
210	NA	Proteobacteria	Epsilonproteobacteria	Campylobacterales	Helicobacteraceae	Helicobacter	Helicobacter pylori	2	0
211114	NA	Actinobacteria	Actinobacteria	Pseudonocardiales	Pseudonocardiaceae	Allokutzneria	Allokutzneria albata	1	0
2130	NA	Tenericutes	Mollicutes	Mycoplasmatales	Mycoplasmataceae	Ureaplasma	Ureaplasma urealyticum	3	0
213849	NA	Proteobacteria	Epsilonproteobacteria	Campylobacterales	NA	NA	NA	32	0
213	NA	Proteobacteria	Epsilonproteobacteria	Campylobacterales	Helicobacteraceae	Helicobacter	Helicobacter cinaedi	1	0
215243	Fungi	Ascomycota	Eurotiomycetes	Chaetothyriales	Herpotrichiellaceae	Exophiala	Exophiala oligosperma	1	0
216768	NA	Bacillariophyta	Coscinodiscophyceae	Rhizosoleniales	Rhizosoleniaceae	Rhizosolenia	Rhizosolenia imbricata	1	0
216816	NA	Actinobacteria	Actinobacteria	Bifidobacteriales	Bifidobacteriaceae	Bifidobacterium	Bifidobacterium longum	3	0
2173	NA	Euryarchaeota	Methanobacteria	Methanobacteriales	Methanobacteriaceae	Methanobrevibacter	Methanobrevibacter smithii	1	0
218822	NA	Actinobacteria	Actinobacteria	Pseudonocardiales	Pseudonocardiaceae	Amycolatopsis	Amycolatopsis lexingtonensis	1	0
2209	NA	Euryarchaeota	Methanomicrobia	Methanosarcinales	Methanosarcinaceae	Methanosarcina	Methanosarcina mazei	3	0
221822	NA	Proteobacteria	Alphaproteobacteria	Rhodobacterales	Rhodobacteraceae	Phaeobacter	Phaeobacter inhibens	2	0
222	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Alcaligenaceae	Achromobacter	NA	2	0
223967	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	Methylobacteriaceae	Methylobacterium	Methylobacterium populi	1	0
2248	NA	Euryarchaeota	Halobacteria	Haloferacales	Halorubraceae	Halorubrum	Halorubrum saccharovorum	13	0
225326	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium halotolerans	1	0
225359	Fungi	Ascomycota	Leotiomycetes	Erysiphales	Erysiphaceae	Erysiphe	Erysiphe pulchra	1	0
225762	NA	Actinobacteria	Actinobacteria	Streptosporangiales	Nocardiopsaceae	Nocardiopsis	Nocardiopsis alkaliphila	1	0
225849	NA	Proteobacteria	Gammaproteobacteria	Alteromonadales	Shewanellaceae	Shewanella	Shewanella piezotolerans	1	0
225906	NA	Firmicutes	Bacilli	Bacillales	Paenibacillaceae	Paenibacillus	Paenibacillus sanguinis	1	0
225991	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Comamonadaceae	Comamonas	Comamonas aquatica	1	0
227290	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	Rhizobiaceae	NA	NA	1	0
228230	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Mycobacteriaceae	Mycobacterium	Mycobacterium canariasense	1	0
22	NA	Proteobacteria	Gammaproteobacteria	Alteromonadales	Shewanellaceae	Shewanella	NA	1	0
232259	NA	Bacteroidetes	Cytophagia	Cytophagales	Cyclobacteriaceae	Belliella	Belliella baltica	1	0
2323	NA	NA	NA	NA	NA	NA	NA	1	0
234828	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium caspium	3	0
235205	NA	Proteobacteria	Gammaproteobacteria	NA	NA	NA	Bathymodiolus azoricus thioautotrophic gill symbiont	2	0
2371	NA	Proteobacteria	Gammaproteobacteria	Xanthomonadales	Xanthomonadaceae	Xylella	Xylella fastidiosa	1	0
2374	NA	Firmicutes	Negativicutes	Selenomonadales	Sporomusaceae	Acetonema	Acetonema longum	1	0
2383	NA	Firmicutes	Clostridia	Clostridiales	NA	Epulopiscium	NA	1	0
239498	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Tsukamurellaceae	Tsukamurella	Tsukamurella pseudospumae	3	0
240176	Fungi	Basidiomycota	Agaricomycetes	Agaricales	Psathyrellaceae	Coprinopsis	Coprinopsis cinerea	2	0
241555	NA	Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Helcococcus	Helcococcus sueciensis	1	0
242600	NA	Bacteroidetes	Flavobacteriia	Flavobacteriales	Ichthyobacteriaceae	Ichthyobacterium	Ichthyobacterium seriolicida	1	0
243230	NA	Deinococcus-Thermus	Deinococci	Deinococcales	Deinococcaceae	Deinococcus	Deinococcus radiodurans	4	0
245562	Fungi	Ascomycota	Dothideomycetes	NA	NA	Acidomyces	Acidomyces richmondensis	2	0
246196	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Mycobacteriaceae	Mycobacterium	Mycobacterium smegmatis	1	0
246409	Fungi	Mucoromycota	NA	Mucorales	Rhizopodaceae	Rhizopus	Rhizopus delemar	1	0
247156	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Nocardiaceae	Nocardia	Nocardia farcinica	2	0
253628	Fungi	Ascomycota	Dothideomycetes	Venturiales	Sympoventuriaceae	Verruconis	Verruconis gallopava	2	0
254877	Fungi	Ascomycota	Eurotiomycetes	Eurotiales	Aspergillaceae	Penicillium	Penicillium flavigenum	2	0
257758	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus pseudopneumoniae	8	0
258224	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium resistens	1	0
258591	NA	Proteobacteria	Gammaproteobacteria	Oceanospirillales	Halomonadaceae	Halomonas	Halomonas anticariensis	1	0
260936	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Nocardiaceae	Rhodococcus	Rhodococcus sp. RD6.2	26	0
261164	NA	Proteobacteria	Gammaproteobacteria	Pseudomonadales	Moraxellaceae	Psychrobacter	Psychrobacter alimentarius	2	0
261658	NA	NA	NA	Acytosteliales	Cavenderiaceae	Cavenderia	Cavenderia fasciculata	2	0
264148	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Gordoniaceae	Millisia	Millisia brevis	1	0
264199	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus thermophilus	18	0
265522	NA	NA	NA	NA	Polydnaviridae	Ichnovirus	Hyposoter fugitivus ichnovirus	1	0
265570	NA	Proteobacteria	Epsilonproteobacteria	NA	NA	Sulfurovum	NA	1	0
265	NA	Proteobacteria	Alphaproteobacteria	Rhodobacterales	Rhodobacteraceae	Paracoccus	NA	1	0
269621	Fungi	Basidiomycota	Microbotryomycetes	Microbotryales	Microbotryaceae	Microbotryum	Microbotryum intermedium	1	0
269666	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus marimammalium	2	0
2702	NA	Actinobacteria	Actinobacteria	Bifidobacteriales	Bifidobacteriaceae	Gardnerella	Gardnerella vaginalis	9	0
271091	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Psychrilyobacter	Psychrilyobacter atlanticus	2	0
2714	NA	Aquificae	Aquificae	Aquificales	Aquificaceae	Aquifex	Aquifex pyrophilus	3	0
27349	Fungi	Basidiomycota	Pucciniomycetes	Pucciniales	Pucciniaceae	Puccinia	Puccinia sorghi	1	0
2734	NA	Firmicutes	Clostridia	Clostridiales	Symbiobacteriaceae	Symbiobacterium	Symbiobacterium thermophilum	9	0
2745	NA	Proteobacteria	Gammaproteobacteria	Oceanospirillales	Halomonadaceae	Halomonas	NA	2	0
2759	NA	NA	NA	NA	NA	NA	NA	66	0
2769	NA	NA	Florideophyceae	Gigartinales	Gigartinaceae	Chondrus	Chondrus crispus	2	0
2786	NA	NA	Bangiophyceae	Bangiales	Bangiaceae	Porphyra	Porphyra umbilicalis	1	0
28005	NA	NA	NA	Kinetoplastida	Trypanosomatidae	Strigomonas	Strigomonas culicis	4	0
280239	NA	Actinobacteria	Actinobacteria	Streptosporangiales	Nocardiopsaceae	Nocardiopsis	Nocardiopsis chromatogenes	1	0
28037	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus mitis	1	0
280463	NA	NA	NA	Isochrysidales	Noelaerhabdaceae	Emiliania	Emiliania huxleyi	2	0
28056	NA	Actinobacteria	Actinobacteria	Micromonosporales	Micromonosporaceae	NA	NA	1	0
280772	NA	Proteobacteria	Gammaproteobacteria	NA	NA	NA	methanotrophic bacterial endosymbiont of Bathymodiolus sp.	2	0
28087	NA	Proteobacteria	Gammaproteobacteria	Legionellales	Legionellaceae	Legionella	Legionella sainthelensi	1	0
28183	NA	Spirochaetes	Spirochaetia	NA	Leptospiraceae	Leptospira	Leptospira santarosai	1	0
28188	NA	Bacteroidetes	Flavobacteriia	Flavobacteriales	Flavobacteriaceae	Capnocytophaga	Capnocytophaga canimorsus	10	0
28211	NA	Proteobacteria	Alphaproteobacteria	NA	NA	NA	NA	5	0
28216	NA	Proteobacteria	Betaproteobacteria	NA	NA	NA	NA	1	0
282669	NA	Proteobacteria	Gammaproteobacteria	Pseudomonadales	Moraxellaceae	Psychrobacter	Psychrobacter cibarius	1	0
282684	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Nocardiaceae	Nocardia	Nocardia miyunensis	1	0
28444	NA	Actinobacteria	Actinobacteria	Streptosporangiales	Streptosporangiaceae	Herbidospora	Herbidospora cretacea	1	0
28450	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Burkholderiaceae	Burkholderia	Burkholderia pseudomallei	11	0
285473	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces rubrolavendulae	1	0
286420	NA	Proteobacteria	Gammaproteobacteria	Oceanospirillales	Hahellaceae	Hahella	Hahella ganghwensis	4	0
286804	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Segniliparaceae	Segniliparus	Segniliparus rugosus	1	0
286	NA	Proteobacteria	Gammaproteobacteria	Pseudomonadales	Pseudomonadaceae	Pseudomonas	NA	3	0
287	NA	Proteobacteria	Gammaproteobacteria	Pseudomonadales	Pseudomonadaceae	Pseudomonas	Pseudomonas aeruginosa	2	0
28901	NA	Proteobacteria	Gammaproteobacteria	Enterobacterales	Enterobacteriaceae	Salmonella	Salmonella enterica	1	0
29007	Fungi	Chytridiomycota	Neocallimastigomycetes	Neocallimastigales	Neocallimastigaceae	NA	NA	2	0
290400	NA	Proteobacteria	Alphaproteobacteria	Rhodobacterales	Rhodobacteraceae	Jannaschia	Jannaschia sp. CCS1	1	0
291594	NA	Actinobacteria	Actinobacteria	Micromonosporales	Micromonosporaceae	Micromonospora	Micromonospora rifamycinica	1	0
291995	NA	Proteobacteria	Gammaproteobacteria	Pseudomonadales	Pseudomonadaceae	Pseudomonas	Pseudomonas azotifigens	1	0
29290	NA	Nitrospirae	Nitrospira	Nitrospirales	Nitrospiraceae	Candidatus Magnetobacterium	Candidatus Magnetobacterium bavaricum	2	0
293091	NA	Euryarchaeota	Halobacteria	Haloferacales	Haloferacaceae	Haloquadratum	Haloquadratum walsbyi	2	0
29321	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Turicella	Turicella otitidis	1	0
29348	NA	Firmicutes	Erysipelotrichia	Erysipelotrichales	Erysipelotrichaceae	Erysipelatoclostridium	[Clostridium] spiroforme	1	0
29359	NA	Firmicutes	Clostridia	Clostridiales	Peptostreptococcaceae	Asaccharospora	Asaccharospora irregularis	7	0
29448	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	Bradyrhizobiaceae	Bradyrhizobium	Bradyrhizobium elkanii	1	0
29497	NA	Proteobacteria	Gammaproteobacteria	Vibrionales	Vibrionaceae	Vibrio	Vibrio splendidus	5	0
294	NA	Proteobacteria	Gammaproteobacteria	Pseudomonadales	Pseudomonadaceae	Pseudomonas	Pseudomonas fluorescens	2	0
2951	NA	NA	Dinophyceae	Suessiales	Symbiodiniaceae	Symbiodinium	Symbiodinium microadriaticum	562	0
29547	NA	Proteobacteria	Epsilonproteobacteria	NA	NA	NA	NA	17	0
29845	Fungi	Ascomycota	Eurotiomycetes	Eurotiales	Aspergillaceae	Penicillium	Penicillium vulpinum	1	0
29882	Fungi	Basidiomycota	Agaricomycetes	Agaricales	Tricholomataceae	Laccaria	NA	1	0
299255	NA	Proteobacteria	Gammaproteobacteria	Alteromonadales	Ferrimonadaceae	Ferrimonas	Ferrimonas marina	1	0
299768	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus thermophilus	15	0
2	NA	NA	NA	NA	NA	NA	NA	3082	0
301102	NA	Proteobacteria	Gammaproteobacteria	Enterobacterales	Enterobacteriaceae	Enterobacter	Enterobacter hormaechei	1	0
302449	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium tuscaniense	5	0
303698	Fungi	Ascomycota	Eurotiomycetes	Eurotiales	Aspergillaceae	Penicillium	Penicillium steckii	1	0
303	NA	Proteobacteria	Gammaproteobacteria	Pseudomonadales	Pseudomonadaceae	Pseudomonas	Pseudomonas putida	1	0
3055	Viridiplantae	Chlorophyta	Chlorophyceae	Chlamydomonadales	Chlamydomonadaceae	Chlamydomonas	Chlamydomonas reinhardtii	9	0
3067	Viridiplantae	Chlorophyta	Chlorophyceae	Chlamydomonadales	Volvocaceae	Volvox	Volvox carteri	1	0
3068	Viridiplantae	Chlorophyta	Chlorophyceae	Chlamydomonadales	Volvocaceae	Volvox	Volvox carteri	110	0
307120	NA	Actinobacteria	Actinobacteria	Micromonosporales	Micromonosporaceae	Micromonospora	Micromonospora marina	1	0
3075	Viridiplantae	Chlorophyta	Trebouxiophyceae	Chlorellales	Chlorellaceae	Auxenochlorella	Auxenochlorella protothecoides	1	0
312017	NA	NA	Oligohymenophorea	Hymenostomatida	Tetrahymenidae	Tetrahymena	Tetrahymena thermophila	5	0
31271	NA	Apicomplexa	Aconoidasida	Haemosporida	Plasmodiidae	Plasmodium	Plasmodium chabaudi	30	0
314231	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	Aurantimonadaceae	Fulvimarina	Fulvimarina pelagi	2	0
314266	NA	Proteobacteria	Alphaproteobacteria	Sphingomonadales	Sphingomonadaceae	Sphingomonas	Sphingomonas sp. SKA58	1	0
314288	NA	Proteobacteria	Gammaproteobacteria	Vibrionales	Vibrionaceae	Vibrio	Vibrio alginolyticus	5	0
315405	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus gallolyticus	7	0
316330	NA	Actinobacteria	Actinobacteria	Streptosporangiales	Streptosporangiaceae	Microbispora	Microbispora sp. ATCC PTA-5024	2	0
3166	Viridiplantae	Chlorophyta	Chlorophyceae	NA	NA	NA	NA	1	0
317010	NA	Firmicutes	Bacilli	Lactobacillales	Enterococcaceae	Enterococcus	Enterococcus canintestini	2	0
32003	NA	Proteobacteria	Betaproteobacteria	Nitrosomonadales	NA	NA	NA	1	0
32008	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Burkholderiaceae	Burkholderia	NA	1	0
32012	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	NA	Thiomonas	NA	1	0
32022	NA	Proteobacteria	Epsilonproteobacteria	Campylobacterales	Campylobacteraceae	Campylobacter	Campylobacter jejuni	1	0
32067	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Leptotrichiaceae	Leptotrichia	NA	7	0
320778	NA	Proteobacteria	Gammaproteobacteria	Vibrionales	Vibrionaceae	Photobacterium	Photobacterium ganghwense	1	0
321146	Fungi	Ascomycota	Dothideomycetes	Capnodiales	Mycosphaerellaceae	Mycosphaerella	Mycosphaerella eumusae	1	0
321318	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Dietziaceae	Dietzia	Dietzia cinnamea	44	0
32207	NA	Actinobacteria	Actinobacteria	Micrococcales	Micrococcaceae	Rothia	NA	1	0
322159	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus thermophilus	14	0
327277	NA	Actinobacteria	Actinobacteria	Bifidobacteriales	Bifidobacteriaceae	Bifidobacterium	Bifidobacterium crudilactis	1	0
329	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Burkholderiaceae	Ralstonia	Ralstonia pickettii	1	0
33031	NA	Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Peptoniphilus	Peptoniphilus lacrimalis	1	0
33037	NA	Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Anaerococcus	Anaerococcus vaginalis	1	0
33057	NA	Proteobacteria	Betaproteobacteria	Rhodocyclales	Zoogloeaceae	Thauera	NA	1	0
33060	NA	Proteobacteria	Gammaproteobacteria	Enterobacterales	Yersiniaceae	Yersinia	Yersinia mollaretii	2	0
33097	Viridiplantae	Chlorophyta	Chlorophyceae	Chlamydomonadales	Volvocaceae	Gonium	Gonium pectorale	3	0
33194	Fungi	Ascomycota	Dothideomycetes	Pleosporales	Pleosporaceae	Bipolaris	NA	1	0
33203	Fungi	Ascomycota	Sordariomycetes	Hypocreales	Ophiocordycipitaceae	Purpureocillium	Purpureocillium lilacinum	1	0
332186	NA	Proteobacteria	Gammaproteobacteria	Alteromonadales	Shewanellaceae	Shewanella	Shewanella xiamenensis	1	0
332249	NA	Deinococcus-Thermus	Deinococci	Deinococcales	Trueperaceae	Truepera	Truepera radiovictrix	1	0
332949	NA	Firmicutes	Bacilli	Lactobacillales	Enterococcaceae	Enterococcus	Enterococcus silesiacus	1	0
332950	NA	Firmicutes	Bacilli	Lactobacillales	Enterococcaceae	Enterococcus	Enterococcus termitis	4	0
333138	NA	Firmicutes	Bacilli	Bacillales	Bacillaceae	Bacillus	Bacillus okhensis	1	0
336261	NA	Synergistetes	Synergistia	Synergistales	Synergistaceae	Thermovirga	Thermovirga lienii	1	0
33630	NA	NA	NA	NA	NA	NA	NA	2	0
336810	NA	Bacteroidetes	Flavobacteriia	Flavobacteriales	NA	Candidatus Sulcia	Candidatus Sulcia muelleri	1	0
33882	NA	Actinobacteria	Actinobacteria	Micrococcales	Microbacteriaceae	Microbacterium	NA	21	0
33895	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Mycobacteriaceae	Mycobacterium	Mycobacterium interjectum	1	0
33898	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces galbus	1	0
338	NA	Proteobacteria	Gammaproteobacteria	Xanthomonadales	Xanthomonadaceae	Xanthomonas	NA	1	0
33936	NA	Firmicutes	Bacilli	Bacillales	Bacillaceae	Aeribacillus	Aeribacillus pallidus	1	0
33958	NA	Firmicutes	Bacilli	Lactobacillales	Lactobacillaceae	NA	NA	1	0
33978	NA	Firmicutes	Bacilli	Bacillales	Planococcaceae	Caryophanon	Caryophanon tenue	1	0
340322	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium glutamicum	1	0
34033	NA	Proteobacteria	Deltaproteobacteria	NA	NA	NA	NA	1	0
340907	NA	NA	NA	Herpesvirales	Herpesviridae	Simplexvirus	Papiine alphaherpesvirus 2	1	0
34104	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Leptotrichiaceae	Streptobacillus	NA	2	0
34105	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Leptotrichiaceae	Streptobacillus	Streptobacillus moniliformis	1	0
341189	Fungi	Basidiomycota	Agaricomycetes	Boletales	Serpulaceae	Serpula	Serpula lacrymans	2	0
341663	Fungi	Ascomycota	Eurotiomycetes	Eurotiales	Aspergillaceae	Aspergillus	Aspergillus terreus	31	0
342613	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus agalactiae	1	0
342615	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus agalactiae	3	0
342616	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus agalactiae	1	0
34384	Fungi	Ascomycota	Eurotiomycetes	Onygenales	Arthrodermataceae	NA	NA	1	0
343	NA	Proteobacteria	Gammaproteobacteria	Xanthomonadales	Xanthomonadaceae	Xanthomonas	Xanthomonas translucens	2	0
345341	NA	Actinobacteria	Actinobacteria	Pseudonocardiales	Pseudonocardiaceae	Kutzneria	Kutzneria sp. 744	1	0
346	NA	Proteobacteria	Gammaproteobacteria	Xanthomonadales	Xanthomonadaceae	Xanthomonas	Xanthomonas citri	1	0
347253	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus salivarius	2	0
347515	NA	NA	NA	Kinetoplastida	Trypanosomatidae	Leishmania	Leishmania major	1	0
348043	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces davaonensis	3	0
348802	Fungi	Ascomycota	Eurotiomycetes	Chaetothyriales	Herpotrichiellaceae	Exophiala	Exophiala xenobiotica	3	0
348818	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptacidiphilus	Streptacidiphilus oryzae	1	0
349751	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium marinum	1	0
351016	NA	Proteobacteria	Alphaproteobacteria	Rhodobacterales	Rhodobacteraceae	Roseobacter	Roseobacter sp. AzwK-3b	1	0
351187	NA	Actinobacteria	Actinobacteria	Micromonosporales	Micromonosporaceae	Salinispora	Salinispora pacifica	2	0
352472	NA	NA	NA	Dictyosteliales	Dictyosteliaceae	Dictyostelium	Dictyostelium discoideum	2	0
35250	NA	NA	NA	Herpesvirales	Herpesviridae	Mardivirus	Gallid alphaherpesvirus 3	2	0
354242	NA	Proteobacteria	Epsilonproteobacteria	Campylobacterales	Campylobacteraceae	Campylobacter	Campylobacter jejuni	5	0
354243	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Mycobacteriaceae	Mycobacterium	Mycobacterium kumamotonense	1	0
35518	NA	Firmicutes	Clostridia	Clostridiales	Clostridiales Family XIII. Incertae Sedis	NA	[Eubacterium] nodatum	3	0
355249	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. Tu6071	3	0
355548	NA	Euryarchaeota	Halobacteria	Halobacteriales	Halobacteriaceae	Halobacterium	Halobacterium jilantaiense	1	0
355688	Fungi	Basidiomycota	Agaricomycetes	NA	NA	NA	NA	1	0
35623	NA	Tenericutes	Mollicutes	Acholeplasmatales	Acholeplasmataceae	Acholeplasma	Acholeplasma oculi	1	0
356662	NA	Proteobacteria	Betaproteobacteria	Neisseriales	Chromobacteriaceae	Leeia	Leeia oryzae	1	0
356	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	NA	NA	NA	2	0
35752	NA	Actinobacteria	Actinobacteria	Micromonosporales	Micromonosporaceae	Actinoplanes	Actinoplanes philippinensis	1	0
35754	NA	Actinobacteria	Actinobacteria	Micromonosporales	Micromonosporaceae	Dactylosporangium	Dactylosporangium aurantiacum	1	0
35755	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium kutscheri	5	0
35756	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium pilosum	2	0
35837	NA	Proteobacteria	Deltaproteobacteria	Syntrophobacterales	Syntrophobacteraceae	Desulfacinum	Desulfacinum infernum	1	0
358905	Fungi	Basidiomycota	Agaricomycetes	Sebacinales	Serendipitaceae	Serendipita	NA	1	0
360107	NA	Proteobacteria	Epsilonproteobacteria	Campylobacterales	Campylobacteraceae	Campylobacter	Campylobacter hominis	6	0
36022	Fungi	Ascomycota	Saccharomycetes	Saccharomycetales	Phaffomycetaceae	Cyberlindnera	Cyberlindnera fabianii	1	0
361077	NA	NA	NA	Dictyosteliales	Raperosteliaceae	Tieghemostelium	Tieghemostelium lacteum	2	0
361575	NA	Actinobacteria	Actinobacteria	Micrococcales	Micrococcaceae	Pseudarthrobacter	Pseudarthrobacter phenanthrenivorans	1	0
362787	NA	Chlamydiae	Chlamydiia	Parachlamydiales	Parachlamydiaceae	Candidatus Protochlamydia	Candidatus Protochlamydia amoebophila	1	0
363277	NA	Chloroflexi	Ktedonobacteria	Ktedonobacterales	Ktedonobacteraceae	Ktedonobacter	Ktedonobacter racemifer	1	0
36330	NA	Apicomplexa	Aconoidasida	Haemosporida	Plasmodiidae	Plasmodium	Plasmodium ovale	1	0
363858	NA	Firmicutes	Bacilli	Bacillales	Paenibacillaceae	Paenibacillus	Paenibacillus panacisoli	1	0
364410	NA	Proteobacteria	Alphaproteobacteria	Rhodospirillales	Acetobacteraceae	Granulibacter	Granulibacter bethesdensis	2	0
36651	Fungi	Ascomycota	Eurotiomycetes	Eurotiales	Aspergillaceae	Penicillium	Penicillium digitatum	1	0
366584	NA	Actinobacteria	Actinobacteria	Pseudonocardiales	Pseudonocardiaceae	Pseudonocardia	Pseudonocardia oroxyli	1	0
36744	NA	Tenericutes	Mollicutes	Mycoplasmatales	Mycoplasmataceae	Mycoplasma	Mycoplasma simbae	1	0
36805	NA	Actinobacteria	Actinobacteria	Micrococcales	Microbacteriaceae	Microbacterium	Microbacterium aurum	1	0
36809	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Mycobacteriaceae	Mycobacterium	Mycobacterium abscessus	8	0
36818	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces subrutilus	2	0
36834	NA	Firmicutes	Clostridia	Clostridiales	Clostridiaceae	Clostridium	Clostridium celatum	1	0
369333	NA	Firmicutes	Bacilli	Bacillales	Paenibacillaceae	Paenibacillus	Paenibacillus terrigena	1	0
369932	NA	Actinobacteria	Actinobacteria	Pseudonocardiales	Pseudonocardiaceae	Amycolatopsis	Amycolatopsis niigatensis	2	0
370354	NA	NA	NA	NA	Entamoebidae	Entamoeba	Entamoeba dispar	3	0
370355	NA	NA	NA	NA	Entamoebidae	Entamoeba	Entamoeba invadens	2	0
370736	NA	Actinobacteria	Actinobacteria	Micrococcales	Micrococcaceae	Zhihengliuella	Zhihengliuella halotolerans	1	0
371601	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Bacteroidaceae	Bacteroides	Bacteroides xylanisolvens	1	0
372443	NA	NA	NA	NA	Phycodnaviridae	Coccolithovirus	NA	1	0
372663	NA	Actinobacteria	Actinobacteria	Micrococcales	Promicromonosporaceae	Isoptericola	Isoptericola dokdonensis	2	0
37329	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Nocardiaceae	Nocardia	Nocardia farcinica	1	0
37332	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Nocardiaceae	Nocardia	Nocardia seriolae	2	0
37452	NA	Bacteroidetes	NA	NA	NA	NA	NA	2	0
374	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	Bradyrhizobiaceae	Bradyrhizobium	NA	1	0
37636	NA	Deinococcus-Thermus	Deinococci	Thermales	Thermaceae	Thermus	Thermus scotoductus	1	0
37637	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium pseudodiphtheriticum	2	0
37734	NA	Firmicutes	Bacilli	Lactobacillales	Enterococcaceae	Enterococcus	Enterococcus casseliflavus	1	0
37769	Fungi	Basidiomycota	Tremellomycetes	Tremellales	Cryptococcaceae	Cryptococcus	Cryptococcus gattii VGI	1	0
378806	NA	Proteobacteria	Deltaproteobacteria	Myxococcales	Archangiaceae	Stigmatella	Stigmatella aurantiaca	1	0
37914	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Dietziaceae	Dietzia	NA	2	0
379508	Fungi	Ascomycota	Saccharomycetes	Saccharomycetales	Debaryomycetaceae	Lodderomyces	Lodderomyces elongisporus	5	0
379	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	Rhizobiaceae	Rhizobium	NA	2	0
38027	NA	Euryarchaeota	Methanomicrobia	Methanosarcinales	Methanosarcinaceae	Methanosarcina	Methanosarcina siciliae	1	0
38038	Fungi	Ascomycota	Leotiomycetes	Helotiales	NA	Rhynchosporium	Rhynchosporium secalis	2	0
380749	NA	Aquificae	Aquificae	Aquificales	Aquificaceae	Hydrogenobaculum	Hydrogenobaculum sp. Y04AAS1	1	0
38284	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium accolens	2	0
38286	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium afermentans	4	0
38289	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium jeikeium	10	0
38302	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium mycetoides	2	0
38305	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium vitaeruminis	2	0
38310	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Nocardiaceae	Rhodococcus	Rhodococcus coprophilus	1	0
383855	Fungi	Ascomycota	Dothideomycetes	Capnodiales	Mycosphaerellaceae	Pseudocercospora	Pseudocercospora fijiensis	2	0
384	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	Rhizobiaceae	Rhizobium	Rhizobium leguminosarum	1	0
38501	NA	Actinobacteria	Actinobacteria	Geodermatophilales	Geodermatophilaceae	Blastococcus	NA	1	0
386891	NA	Proteobacteria	Gammaproteobacteria	Pseudomonadales	Moraxellaceae	Moraxella	Moraxella bovoculi	1	0
388400	NA	Firmicutes	Bacilli	Bacillales	Bacillaceae	Bacillus	Bacillus sp. B14905	4	0
391296	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus suis	3	0
392613	Fungi	Ascomycota	Eurotiomycetes	Onygenales	Ascosphaeraceae	Ascosphaera	Ascosphaera apis	1	0
392733	NA	Acidobacteria	Acidobacteriia	Acidobacteriales	Acidobacteriaceae	Terriglobus	NA	2	0
393310	NA	Proteobacteria	Alphaproteobacteria	Rhodospirillales	Rhodospirillaceae	Skermanella	Skermanella aerolata	2	0
393480	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Fusobacterium	Fusobacterium nucleatum	175	0
394734	NA	Actinobacteria	Actinobacteria	Propionibacteriales	Nocardioidaceae	Nocardioides	Nocardioides insulae	1	0
394935	NA	Proteobacteria	Betaproteobacteria	Neisseriales	Chromobacteriaceae	Chromobacterium	Chromobacterium haemolyticum	1	0
39498	NA	Firmicutes	Clostridia	Clostridiales	Peptostreptococcaceae	Peptoanaerobacter	[Eubacterium] yurii	1	0
396716	NA	Firmicutes	Bacilli	Lactobacillales	Lactobacillaceae	Lactobacillus	Lactobacillus hayakitensis	3	0
39717	NA	NA	NA	Euglyphida	Paulinellidae	Paulinella	Paulinella chromatophora	1	0
397278	NA	Actinobacteria	Actinobacteria	Propionibacteriales	Nocardioidaceae	Marmoricola	Marmoricola aequoreus	28	0
397288	NA	Firmicutes	Clostridia	Clostridiales	Lachnospiraceae	NA	Lachnospiraceae bacterium 3-1	1	0
39791	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium glucuronolyticum	134	0
398513	NA	Actinobacteria	Actinobacteria	Bifidobacteriales	Bifidobacteriaceae	Bifidobacterium	Bifidobacterium bifidum	1	0
39966	Fungi	Basidiomycota	Agaricomycetes	Agaricales	Lyophyllaceae	Hypsizygus	Hypsizygus marmoreus	1	0
40041	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus equi	1	0
40127	Fungi	Ascomycota	Sordariomycetes	Sordariales	Sordariaceae	Neurospora	Neurospora tetrasperma	1	0
401562	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	Aurantimonadaceae	Aureimonas	Aureimonas ureilytica	1	0
401625	Fungi	Basidiomycota	Exobasidiomycetes	Ceraceosorales	Ceraceosoraceae	Ceraceosorus	Ceraceosorus bombacis	1	0
40296	Fungi	Ascomycota	Eurotiomycetes	Eurotiales	Aspergillaceae	Penicillium	Penicillium italicum	1	0
403776	NA	Bacteroidetes	Sphingobacteriia	Sphingobacteriales	Sphingobacteriaceae	Sphingobacterium	Sphingobacterium sp. PM2-P1-29	8	0
40410	Fungi	Basidiomycota	Tremellomycetes	Tremellales	Cryptococcaceae	Cryptococcus	Cryptococcus neoformans	1	0
404236	NA	Proteobacteria	Alphaproteobacteria	Rhodobacterales	Rhodobacteraceae	Maritimibacter	Maritimibacter alkaliphilus	3	0
404386	NA	Actinobacteria	Actinobacteria	Streptosporangiales	Streptosporangiaceae	Nonomuraea	Nonomuraea coxensis	1	0
404692	Fungi	Ascomycota	Eurotiomycetes	Onygenales	NA	Coccidioides	Coccidioides immitis	1	0
40543	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Leptotrichiaceae	Sneathia	Sneathia sanguinegens	34793	0
405782	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptacidiphilus	Streptacidiphilus anmyonensis	2	0
406556	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus pneumoniae	2	0
407	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	Methylobacteriaceae	Methylobacterium	NA	1	0
41047	Fungi	Ascomycota	Eurotiomycetes	Eurotiales	Aspergillaceae	Aspergillus	Aspergillus thermomutatus	1	0
41067	Fungi	Ascomycota	Eurotiomycetes	Eurotiales	Aspergillaceae	Aspergillus	Aspergillus candidus	2	0
411459	NA	Firmicutes	Clostridia	Clostridiales	Lachnospiraceae	Blautia	Blautia obeum	7	0
411462	NA	Firmicutes	Clostridia	Clostridiales	Lachnospiraceae	Dorea	Dorea longicatena	1	0
411463	NA	Firmicutes	Clostridia	Clostridiales	Eubacteriaceae	Eubacterium	Eubacterium ventriosum	7	0
411466	NA	Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Actinomyces	Actinomyces odontolyticus	3	0
411467	NA	Firmicutes	Clostridia	Clostridiales	NA	Pseudoflavonifractor	Pseudoflavonifractor capillosus	15	0
411470	NA	Firmicutes	Clostridia	Clostridiales	Lachnospiraceae	Blautia	[Ruminococcus] gnavus	1	0
411484	NA	Firmicutes	Clostridia	Clostridiales	Clostridiaceae	Clostridium	Clostridium sp. SS2/1	2	0
411485	NA	Firmicutes	Clostridia	Clostridiales	Ruminococcaceae	Faecalibacterium	Faecalibacterium prausnitzii	1	0
411903	NA	Actinobacteria	Coriobacteriia	Coriobacteriales	Coriobacteriaceae	Collinsella	Collinsella aerofaciens	10	0
41294	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	Bradyrhizobiaceae	NA	NA	1	0
414771	NA	Firmicutes	Bacilli	Bacillales	Paenibacillaceae	Paenibacillus	Paenibacillus donghaensis	1	0
41688	Fungi	Ascomycota	Sordariomycetes	Microascales	Microascaceae	Lomentospora	Lomentospora prolificans	1	0
417305	NA	Proteobacteria	Betaproteobacteria	NA	NA	NA	uncultured beta proteobacterium CBNPD1 BAC clone 578	1	0
418495	NA	Actinobacteria	Actinobacteria	Pseudonocardiales	Pseudonocardiaceae	Saccharopolyspora	Saccharopolyspora shandongensis	2	0
41875	Viridiplantae	Chlorophyta	Mamiellophyceae	Mamiellales	Bathycoccaceae	Bathycoccus	Bathycoccus prasinos	3	0
418867	Fungi	Basidiomycota	Agaricomycetes	Hymenochaetales	Hymenochaetaceae	Phellinus	Phellinus noxius	2	0
419435	NA	NA	NA	NA	Polydnaviridae	Ichnovirus	Glypta fumiferanae ichnovirus	1	0
419479	NA	Actinobacteria	Actinobacteria	Jiangellales	Jiangellaceae	Jiangella	Jiangella alkaliphila	1	0
41	NA	Proteobacteria	Deltaproteobacteria	Myxococcales	Archangiaceae	Stigmatella	Stigmatella aurantiaca	1	0
420245	NA	NA	NA	Kinetoplastida	Trypanosomatidae	Leishmania	Leishmania braziliensis	1	0
420645	NA	Firmicutes	Bacilli	Lactobacillales	Lactobacillaceae	Lactobacillus	Lactobacillus equicursoris	1	0
420778	Fungi	Ascomycota	Dothideomycetes	Botryosphaeriales	Botryosphaeriaceae	Diplodia	Diplodia seriata	1	0
42197	NA	Actinobacteria	Actinobacteria	Pseudonocardiales	Pseudonocardiaceae	Actinosynnema	Actinosynnema pretiosum	1	0
42236	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces diastatochromogenes	2	0
42239	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sampsonii	1	0
42308	Fungi	Ascomycota	Sordariomycetes	Xylariales	Hypoxylaceae	Hypoxylon	NA	1	0
425265	Fungi	Basidiomycota	Malasseziomycetes	Malasseziales	Malasseziaceae	Malassezia	Malassezia globosa	1	0
426129	NA	Firmicutes	Clostridia	Clostridiales	Clostridiaceae	Alkaliphilus	Alkaliphilus peptidifermentans	1	0
42673	Fungi	Ascomycota	Sordariomycetes	Hypocreales	Nectriaceae	Fusarium	Fusarium nygamai	1	0
428127	NA	Firmicutes	Erysipelotrichia	Erysipelotrichales	Erysipelotrichaceae	Absiella	Absiella dolichum	9	0
42817	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium argentoratense	1	0
428993	NA	Proteobacteria	Gammaproteobacteria	Xanthomonadales	Xanthomonadaceae	Pseudoxanthomonas	Pseudoxanthomonas indica	1	0
429131	NA	NA	NA	Kinetoplastida	Trypanosomatidae	Trypanosoma	Trypanosoma rangeli	1	0
429728	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	Hyphomicrobiaceae	Devosia	Devosia crocina	1	0
431041	NA	Cyanobacteria	NA	Synechococcales	Synechococcaceae	Synechococcus	Candidatus Synechococcus spongiarum	1	0
431553	NA	Bacteroidetes	Cytophagia	Cytophagales	Cytophagaceae	Spirosoma	Spirosoma luteum	1	0
431554	NA	Bacteroidetes	Cytophagia	Cytophagales	Cytophagaceae	Spirosoma	Spirosoma spitsbergense	1	0
431895	NA	NA	NA	Choanoflagellida	Salpingoecidae	Monosiga	Monosiga brevicollis	32	0
432331	NA	Aquificae	Aquificae	Aquificales	Hydrogenothermaceae	Sulfurihydrogenibium	Sulfurihydrogenibium yellowstonense	1	0
432359	NA	Apicomplexa	Coccidia	Eucoccidiorida	Sarcocystidae	Toxoplasma	Toxoplasma gondii	1	0
43357	NA	Actinobacteria	Actinobacteria	Pseudonocardiales	Pseudonocardiaceae	Kutzneria	Kutzneria albida	1	0
433647	NA	Actinobacteria	Actinobacteria	Micrococcales	Microbacteriaceae	Cryobacterium	Cryobacterium mesophilum	1	0
433924	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Comamonadaceae	Pseudacidovorax	Pseudacidovorax intermedius	5	0
434	NA	Proteobacteria	Alphaproteobacteria	Rhodospirillales	Acetobacteraceae	Acetobacter	NA	2	0
435289	NA	Proteobacteria	Gammaproteobacteria	Xanthomonadales	Xanthomonadaceae	Lysobacter	Lysobacter spongiicola	1	0
435830	NA	Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Actinomyces	Actinomyces graevenitzii	1	0
435842	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus sp. C150	2	0
435998	NA	Proteobacteria	Gammaproteobacteria	Enterobacterales	Yersiniaceae	Serratia	Serratia marcescens	1	0
436010	Fungi	Basidiomycota	Agaricomycetes	Atheliales	Atheliaceae	Fibularhizoctonia	Fibularhizoctonia sp. CBS 109695	2	0
43670	NA	Actinobacteria	Actinobacteria	Micrococcales	Cellulomonadaceae	Cellulomonas	Cellulomonas cellasea	1	0
43768	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium matruchotii	1	0
43770	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium striatum	14	0
437897	NA	Firmicutes	Negativicutes	Selenomonadales	Selenomonadaceae	Megamonas	Megamonas funiformis	1	0
439219	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus henryi	1	0
43	NA	Proteobacteria	Deltaproteobacteria	Myxococcales	Archangiaceae	Cystobacter	Cystobacter fuscus	1	0
44013	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Burkholderiaceae	Polynucleobacter	NA	1	0
44056	NA	NA	Pelagophyceae	Pelagomonadales	NA	Aureococcus	Aureococcus anophagefferens	1	0
441959	Fungi	Ascomycota	Eurotiomycetes	Eurotiales	Trichocomaceae	Talaromyces	Talaromyces stipitatus	1	0
44249	NA	Firmicutes	Bacilli	Bacillales	Paenibacillaceae	Paenibacillus	NA	15	0
44415	NA	Apicomplexa	Coccidia	Eucoccidiorida	Eimeriidae	Eimeria	Eimeria mitis	1	0
445930	NA	Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Trueperella	Trueperella abortisuis	1	0
445972	NA	Firmicutes	Clostridia	Clostridiales	Ruminococcaceae	Anaerotruncus	Anaerotruncus colihominis	4	0
445973	NA	Firmicutes	Clostridia	Clostridiales	Peptostreptococcaceae	Intestinibacter	Intestinibacter bartlettii	4	0
445974	NA	Firmicutes	Erysipelotrichia	Erysipelotrichales	Erysipelotrichaceae	Erysipelatoclostridium	Erysipelatoclostridium ramosum	35	0
445975	NA	Actinobacteria	Coriobacteriia	Coriobacteriales	Coriobacteriaceae	Collinsella	Collinsella stercoris	1	0
445	NA	Proteobacteria	Gammaproteobacteria	Legionellales	Legionellaceae	Legionella	NA	3	0
446681	NA	Bacteroidetes	Flavobacteriia	Flavobacteriales	Flavobacteriaceae	Eudoraea	Eudoraea adriatica	1	0
44689	NA	NA	NA	Dictyosteliales	Dictyosteliaceae	Dictyostelium	Dictyostelium discoideum	15	0
449	NA	Proteobacteria	Gammaproteobacteria	Legionellales	Legionellaceae	Legionella	Legionella hackeliae	1	0
451864	Fungi	NA	NA	NA	NA	NA	NA	1	0
452589	Fungi	Ascomycota	Sordariomycetes	Hypocreales	Hypocreaceae	Trichoderma	Trichoderma atroviride	3	0
453364	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus pneumoniae	5	0
453816	NA	Proteobacteria	Oligoflexia	Bdellovibrionales	Bdellovibrionaceae	Bdellovibrio	Bdellovibrio exovorus	1	0
454130	Fungi	Ascomycota	Eurotiomycetes	Eurotiales	Aspergillaceae	Aspergillus	Aspergillus calidoustus	1	0
455360	NA	Proteobacteria	Alphaproteobacteria	Rhodospirillales	Rhodospirillaceae	Thalassobaculum	Thalassobaculum salexigens	2	0
456330	NA	Firmicutes	Clostridia	Thermoanaerobacterales	Thermoanaerobacteraceae	Caldanaerobius	Caldanaerobius fijiensis	1	0
45634	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus cristatus	1	0
456482	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Haemophilus	Haemophilus influenzae	2	0
45677	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Alcaligenaceae	Azohydromonas	Azohydromonas lata	1	0
457403	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Fusobacterium	Fusobacterium nucleatum	44	0
457425	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces albus	9	0
457429	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces pristinaespiralis	7	0
459495	NA	Cyanobacteria	NA	Oscillatoriales	Microcoleaceae	Arthrospira	Arthrospira platensis	1	0
46021	NA	NA	NA	NA	Phycodnaviridae	Chlorovirus	Paramecium bursaria Chlorella virus NY2A	1	0
461836	NA	NA	NA	NA	Apusomonadidae	Thecamonas	Thecamonas trahens	2	0
46206	NA	Firmicutes	Clostridia	Clostridiales	Lachnospiraceae	Pseudobutyrivibrio	Pseudobutyrivibrio ruminis	1	0
462910	NA	Firmicutes	Bacilli	Bacillales	Bacillaceae	Pontibacillus	Pontibacillus yanchengensis	1	0
463191	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sviceus	12	0
46352	NA	Actinobacteria	Actinobacteria	Micrococcales	Microbacteriaceae	Agrococcus	NA	1	0
46433	NA	NA	NA	NA	Reticulomyxidae	Reticulomyxa	Reticulomyxa filosa	70	0
465541	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. Mg1	4	0
467093	NA	Actinobacteria	Acidimicrobiia	Acidimicrobiales	Acidimicrobiaceae	Ilumatobacter	Ilumatobacter nonamiensis	2	0
467094	NA	Actinobacteria	Acidimicrobiia	Acidimicrobiales	Acidimicrobiaceae	Ilumatobacter	Ilumatobacter coccineus	1	0
467210	NA	Firmicutes	Clostridia	Clostridiales	Lachnospiraceae	Lachnoanaerobaculum	Lachnoanaerobaculum saburreum	9	0
469371	NA	Actinobacteria	Actinobacteria	NA	NA	Thermobispora	Thermobispora bispora	3	0
469599	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Fusobacterium	Fusobacterium periodonticum	9	0
469601	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Fusobacterium	Fusobacterium nucleatum	2	0
469604	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Fusobacterium	Fusobacterium nucleatum	7	0
469615	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Fusobacterium	Fusobacterium gonidiaformans	1	0
469618	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Fusobacterium	Fusobacterium varium	8	0
469621	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Fusobacterium	Fusobacterium periodonticum	6	0
469	NA	Proteobacteria	Gammaproteobacteria	Pseudomonadales	Moraxellaceae	Acinetobacter	NA	3	0
470	NA	Proteobacteria	Gammaproteobacteria	Pseudomonadales	Moraxellaceae	Acinetobacter	Acinetobacter baumannii	3	0
471872	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus infantarius	16	0
471875	NA	Firmicutes	Clostridia	Clostridiales	Ruminococcaceae	Ruminococcus	Ruminococcus lactaris	2	0
471876	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus pyogenes	2	0
473781	NA	Proteobacteria	Alphaproteobacteria	Sphingomonadales	Sphingomonadaceae	Sphingomonas	Sphingomonas sp. LH128	2	0
47420	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Comamonadaceae	Hydrogenophaga	NA	2	0
474995	Fungi	Ascomycota	Sordariomycetes	Hypocreales	Ophiocordycipitaceae	Ophiocordyceps	NA	1	0
4753	Fungi	Ascomycota	Pneumocystidomycetes	Pneumocystidales	Pneumocystidaceae	Pneumocystis	NA	1	0
47715	NA	Firmicutes	Bacilli	Lactobacillales	Lactobacillaceae	Lactobacillus	Lactobacillus rhamnosus	2	0
47735	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Bibersteinia	Bibersteinia trehalosi	4	0
47760	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces aurantiacus	1	0
47761	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces ochraceiscleroticus	1	0
47763	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces lydicus	1	0
47790	Viridiplantae	Chlorophyta	Chlorophyceae	Chlamydomonadales	Tetrabaenaceae	Tetrabaena	Tetrabaena socialis	2	0
47857	NA	Actinobacteria	Actinobacteria	Micromonosporales	Micromonosporaceae	Micromonospora	Micromonospora echinaurantiaca	1	0
47866	NA	Actinobacteria	Actinobacteria	Micromonosporales	Micromonosporaceae	Micromonospora	Micromonospora inyonensis	1	0
47872	NA	Actinobacteria	Actinobacteria	Micromonosporales	Micromonosporaceae	Micromonospora	Micromonospora purpureochromogenes	1	0
478801	NA	Actinobacteria	Actinobacteria	Micrococcales	Dermacoccaceae	Kytococcus	Kytococcus sedentarius	1	0
4792	NA	NA	Oomycetes	Peronosporales	NA	Phytophthora	Phytophthora parasitica	1	0
482628	NA	Proteobacteria	Epsilonproteobacteria	Campylobacterales	Campylobacteraceae	Campylobacter	Campylobacter jejuni	13	0
4829	Fungi	Mucoromycota	NA	Mucorales	Cunninghamellaceae	Absidia	Absidia glauca	1	0
483139	NA	Apicomplexa	Coccidia	Eucoccidiorida	Sarcocystidae	Cystoisospora	Cystoisospora suis	4	0
48479	NA	NA	NA	NA	NA	NA	NA	1	0
485602	NA	Actinobacteria	Actinobacteria	Pseudonocardiales	Pseudonocardiaceae	Actinophytocola	Actinophytocola xinjiangensis	1	0
48697	Fungi	Ascomycota	Eurotiomycetes	Eurotiales	Aspergillaceae	Penicillium	Penicillium freii	4	0
48782	NA	Spirochaetes	Spirochaetia	NA	Leptospiraceae	Leptospira	Leptospira fainei	1	0
4932	Fungi	Ascomycota	Saccharomycetes	Saccharomycetales	Saccharomycetaceae	Saccharomyces	Saccharomyces cerevisiae	2	0
49338	NA	Firmicutes	Clostridia	Clostridiales	Peptococcaceae	Desulfitobacterium	Desulfitobacterium hafniense	1	0
4952	Fungi	Ascomycota	Saccharomycetes	Saccharomycetales	Dipodascaceae	Yarrowia	Yarrowia lipolytica	1	0
497735	NA	Firmicutes	Bacilli	Bacillales	Paenibacillaceae	Brevibacillus	Brevibacillus panacihumi	1	0
498761	NA	Firmicutes	Clostridia	Clostridiales	Heliobacteriaceae	Heliobacterium	Heliobacterium modesticaldum	2	0
498846	NA	Candidatus Korarchaeota	NA	NA	NA	Candidatus Korarchaeum	Candidatus Korarchaeum cryptofilum	1	0
498848	NA	Deinococcus-Thermus	Deinococci	Thermales	Thermaceae	Thermus	Thermus aquaticus	1	0
499555	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Dietziaceae	Dietzia	Dietzia timorensis	2	0
5005	Fungi	Basidiomycota	Microbotryomycetes	Sporidiobolales	Sporidiobolaceae	Sporidiobolus	Sporidiobolus salmonicolor	1	0
500633	NA	Firmicutes	Clostridia	Clostridiales	Peptostreptococcaceae	NA	[Clostridium] hiranonis	2	0
5016	Fungi	Ascomycota	Dothideomycetes	Pleosporales	Pleosporaceae	Bipolaris	Bipolaris maydis	2	0
502393	NA	Firmicutes	Bacilli	Bacillales	NA	Gemella	Gemella asaccharolytica	14	0
502567	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus porci	1	0
503106	Fungi	Ascomycota	Leotiomycetes	Helotiales	Dermateaceae	Marssonina	Marssonina coronariae	7	0
5042	Fungi	Ascomycota	Eurotiomycetes	Eurotiales	NA	NA	NA	1	0
504474	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium urealyticum	1	0
5052	Fungi	Ascomycota	Eurotiomycetes	Eurotiales	Aspergillaceae	Aspergillus	NA	10	0
505341	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Gallibacterium	Gallibacterium salpingitidis	2	0
5061	Fungi	Ascomycota	Eurotiomycetes	Eurotiales	Aspergillaceae	Aspergillus	Aspergillus niger	1	0
506	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Alcaligenaceae	NA	NA	1	0
5073	Fungi	Ascomycota	Eurotiomycetes	Eurotiales	Aspergillaceae	Penicillium	NA	3	0
5078	Fungi	Ascomycota	Eurotiomycetes	Eurotiales	Aspergillaceae	Penicillium	Penicillium griseofulvum	1	0
508770	NA	Actinobacteria	Actinobacteria	Pseudonocardiales	Pseudonocardiaceae	Sciscionella	Sciscionella marina	1	0
508771	NA	Apicomplexa	Coccidia	Eucoccidiorida	Sarcocystidae	Toxoplasma	Toxoplasma gondii	3	0
510952	Fungi	Ascomycota	Sordariomycetes	Sordariales	Sordariaceae	Neurospora	Neurospora tetrasperma	1	0
511	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Alcaligenaceae	Alcaligenes	Alcaligenes faecalis	1	0
51314	NA	Apicomplexa	Coccidia	Eucoccidiorida	Eimeriidae	Eimeria	Eimeria brunetti	2	0
51315	NA	Apicomplexa	Coccidia	Eucoccidiorida	Eimeriidae	Eimeria	Eimeria necatrix	5	0
51316	NA	Apicomplexa	Coccidia	Eucoccidiorida	Eimeriidae	Eimeria	Eimeria praecox	2	0
5141	Fungi	Ascomycota	Sordariomycetes	Sordariales	Sordariaceae	Neurospora	Neurospora crassa	2	0
515849	Fungi	Ascomycota	Sordariomycetes	Sordariales	Lasiosphaeriaceae	Podospora	Podospora anserina	1	0
519963	Fungi	Ascomycota	Eurotiomycetes	Eurotiales	Elaphomycetaceae	Elaphomyces	Elaphomyces granulatus	1	0
520767	NA	Firmicutes	Clostridia	Thermoanaerobacterales	Thermoanaerobacterales Family III. Incertae Sedis	Thermovenabulum	Thermovenabulum gondwanense	1	0
5208	Fungi	Basidiomycota	Tremellomycetes	Tremellales	Cryptococcaceae	Cryptococcus	Cryptococcus depauperatus	1	0
520	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Alcaligenaceae	Bordetella	Bordetella pertussis	2	0
52288	NA	Apicomplexa	Aconoidasida	Haemosporida	Plasmodiidae	Plasmodium	Plasmodium inui	1	0
525245	NA	Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Actinomyces	Actinomyces coleocanis	1	0
525262	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium jeikeium	1	0
525263	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium lipophiloflavum	1	0
525264	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium pseudogenitalium	19	0
525268	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium striatum	2	0
525283	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Fusobacterium	Fusobacterium nucleatum	251	0
52770	NA	Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Actinomyces	Actinomyces hordeovulneris	1	0
5286	Fungi	Basidiomycota	Microbotryomycetes	Sporidiobolales	Sporidiobolaceae	Rhodotorula	Rhodotorula toruloides	2	0
52972	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Comamonadaceae	Polaromonas	NA	2	0
5303	Fungi	Basidiomycota	Agaricomycetes	Polyporales	NA	NA	NA	1	0
53335	NA	Proteobacteria	Gammaproteobacteria	Enterobacterales	Erwiniaceae	Pantoea	NA	1	0
53346	NA	Firmicutes	Bacilli	Lactobacillales	Enterococcaceae	Enterococcus	Enterococcus mundtii	3	0
53355	NA	Actinobacteria	Actinobacteria	Micrococcales	Intrasporangiaceae	Terrabacter	NA	1	0
53368	NA	Actinobacteria	Actinobacteria	Micromonosporales	Micromonosporaceae	Hamadaea	Hamadaea tsunoensis	1	0
5338	Fungi	Basidiomycota	Agaricomycetes	Agaricales	NA	NA	NA	1	0
53427	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Gordoniaceae	Gordonia	Gordonia hirsuta	1	0
535722	Fungi	Ascomycota	Eurotiomycetes	Onygenales	Arthrodermataceae	Nannizzia	Nannizzia gypsea	1	0
537970	NA	Proteobacteria	Epsilonproteobacteria	Campylobacterales	Helicobacteraceae	Helicobacter	Helicobacter canadensis	1	0
537972	NA	Proteobacteria	Epsilonproteobacteria	Campylobacterales	Helicobacteraceae	Helicobacter	Helicobacter pullorum	1	0
54005	NA	Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Peptoniphilus	Peptoniphilus harei	2	0
541095	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium lubricantis	2	0
543632	NA	Actinobacteria	Actinobacteria	Micromonosporales	Micromonosporaceae	Actinoplanes	Actinoplanes subtropicus	1	0
543	NA	Proteobacteria	Gammaproteobacteria	Enterobacterales	Enterobacteriaceae	NA	NA	1	0
5454	Fungi	Ascomycota	Dothideomycetes	Pleosporales	Didymellaceae	Ascochyta	Ascochyta rabiei	12	0
545774	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus gallolyticus	1	0
546275	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Fusobacterium	Fusobacterium periodonticum	21	0
546874	NA	Actinobacteria	Actinobacteria	Propionibacteriales	Nocardioidaceae	Friedmanniella	Friedmanniella sagamiharensis	2	0
5477	Fungi	Ascomycota	Saccharomycetes	Saccharomycetales	Pichiaceae	Ogataea	[Candida] boidinii	1	0
548476	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium aurimucosum	3	0
548477	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium glucuronolyticum	17	0
548478	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium glucuronolyticum	42	0
549	NA	Proteobacteria	Gammaproteobacteria	Enterobacterales	Erwiniaceae	Pantoea	Pantoea agglomerans	1	0
54	NA	Proteobacteria	Deltaproteobacteria	Myxococcales	Nannocystaceae	Nannocystis	Nannocystis exedens	1	0
5506	Fungi	Ascomycota	Sordariomycetes	Hypocreales	Nectriaceae	Fusarium	NA	3	0
550	NA	Proteobacteria	Gammaproteobacteria	Enterobacterales	Enterobacteriaceae	Enterobacter	Enterobacter cloacae	1	0
551996	NA	Bacteroidetes	Sphingobacteriia	Sphingobacteriales	Sphingobacteriaceae	Mucilaginibacter	Mucilaginibacter gossypii	1	0
552063	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	Bradyrhizobiaceae	Salinarimonas	Salinarimonas rosea	1	0
5529	Fungi	Ascomycota	Sordariomycetes	Hypocreales	Clavicipitaceae	Metarhizium	NA	1	0
552	NA	Proteobacteria	Gammaproteobacteria	Enterobacterales	Erwiniaceae	Erwinia	Erwinia amylovora	3	0
553218	NA	Proteobacteria	Epsilonproteobacteria	Campylobacterales	Campylobacteraceae	Campylobacter	Campylobacter rectus	1	0
553220	NA	Proteobacteria	Epsilonproteobacteria	Campylobacterales	Campylobacteraceae	Campylobacter	Campylobacter gracilis	1	0
553386	NA	Proteobacteria	Gammaproteobacteria	Oceanospirillales	Halomonadaceae	Halomonas	Halomonas jeotgali	1	0
553469	NA	Euryarchaeota	Halobacteria	Haloferacales	Haloferacaceae	Halogeometricum	Halogeometricum rufum	2	0
554155	Fungi	Ascomycota	Eurotiomycetes	Onygenales	Arthrodermataceae	Microsporum	Microsporum canis	1	0
554283	NA	Bacteroidetes	Flavobacteriia	Flavobacteriales	Flavobacteriaceae	Flavobacterium	Flavobacterium chungangense	1	0
5544	Fungi	Ascomycota	Sordariomycetes	Hypocreales	Hypocreaceae	Trichoderma	Trichoderma harzianum	1	0
5550	Fungi	Ascomycota	Eurotiomycetes	Onygenales	Arthrodermataceae	Trichophyton	NA	1	0
556263	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Fusobacterium	Fusobacterium necrophorum	24	0
556264	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Fusobacterium	Fusobacterium nucleatum	12	0
556266	NA	Proteobacteria	Gammaproteobacteria	Enterobacterales	Enterobacteriaceae	Escherichia	Escherichia coli	1	0
556548	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium freiburgense	1	0
55779	NA	Firmicutes	Clostridia	Thermoanaerobacterales	Thermoanaerobacteraceae	Moorella	Moorella glycerini	3	0
559295	Fungi	Ascomycota	Saccharomycetes	Saccharomycetales	Saccharomycetaceae	Lachancea	Lachancea thermotolerans	1	0
559298	Fungi	Ascomycota	Eurotiomycetes	Onygenales	Ajellomycetaceae	Blastomyces	Blastomyces gilchristii	1	0
55968	NA	Actinobacteria	Actinobacteria	Micrococcales	Microbacteriaceae	Leucobacter	NA	1	0
5599	Fungi	Ascomycota	Dothideomycetes	Pleosporales	Pleosporaceae	Alternaria	Alternaria alternata	2	0
560556	NA	Actinobacteria	Actinobacteria	Micromonosporales	Micromonosporaceae	Asanoa	Asanoa hainanensis	1	0
561177	NA	Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Anaerococcus	Anaerococcus hydrogenalis	1	0
561522	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus pyogenes	11	0
562	NA	Proteobacteria	Gammaproteobacteria	Enterobacterales	Enterobacteriaceae	Escherichia	Escherichia coli	3	0
56408	Fungi	Ascomycota	Saccharomycetes	Saccharomycetales	Saccharomycodaceae	Hanseniaspora	Hanseniaspora osmophila	1	0
56438	NA	Actinobacteria	Actinobacteria	Micromonosporales	Micromonosporaceae	Couchioplanes	Couchioplanes caeruleus	3	0
5643	Fungi	Basidiomycota	Agaricomycetes	Polyporales	Polyporaceae	Trametes	Trametes cinnabarina	1	0
564608	Viridiplantae	Chlorophyta	Mamiellophyceae	Mamiellales	Mamiellaceae	Micromonas	Micromonas pusilla	1	0
5684	NA	NA	NA	Kinetoplastida	Trypanosomatidae	Leptomonas	Leptomonas seymouri	2	0
56877	NA	Proteobacteria	Epsilonproteobacteria	Campylobacterales	Helicobacteraceae	Helicobacter	Helicobacter bizzozeronii	1	0
568860	NA	Actinobacteria	Actinobacteria	Streptosporangiales	Streptosporangiaceae	Nonomuraea	Nonomuraea wenchangensis	1	0
5691	NA	NA	NA	Kinetoplastida	Trypanosomatidae	Trypanosoma	Trypanosoma brucei	1	0
569360	Fungi	Ascomycota	Sordariomycetes	Hypocreales	Nectriaceae	Fusarium	NA	1	0
569365	Fungi	Ascomycota	Eurotiomycetes	Chaetothyriales	Herpotrichiellaceae	Cladophialophora	Cladophialophora immunda	1	0
5693	NA	NA	NA	Kinetoplastida	Trypanosomatidae	Trypanosoma	Trypanosoma cruzi	7	0
56	NA	Proteobacteria	Deltaproteobacteria	Myxococcales	Polyangiaceae	Sorangium	Sorangium cellulosum	1	0
571915	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium mustelae	1	0
572307	NA	Apicomplexa	Coccidia	Eucoccidiorida	Sarcocystidae	Neospora	Neospora caninum	5	0
572511	NA	Firmicutes	Clostridia	Clostridiales	Lachnospiraceae	Blautia	NA	1	0
57270	NA	Apicomplexa	Aconoidasida	Haemosporida	Plasmodiidae	Plasmodium	Plasmodium falciparum	4	0
573508	Fungi	Ascomycota	Eurotiomycetes	Eurotiales	Aspergillaceae	Aspergillus	Aspergillus cristatus	1	0
573658	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	NA	Candidatus Hodgkinia	Candidatus Hodgkinia cicadicola	3	0
573729	Fungi	Ascomycota	Sordariomycetes	Sordariales	Chaetomiaceae	Thermothelomyces	Thermothelomyces thermophila	1	0
574774	Fungi	Ascomycota	Dothideomycetes	NA	Gloniaceae	Glonium	Glonium stellatum	3	0
57493	NA	Actinobacteria	Actinobacteria	Micrococcales	Micrococcaceae	Kocuria	NA	1	0
5758	NA	NA	NA	NA	Entamoebidae	Entamoeba	NA	1	0
576137	Fungi	Ascomycota	Leotiomycetes	Helotiales	NA	Phialocephala	Phialocephala subalpina	1	0
5762	NA	NA	Heterolobosea	Schizopyrenida	Vahlkampfiidae	Naegleria	Naegleria gruberi	1	0
57665	NA	Proteobacteria	Epsilonproteobacteria	Campylobacterales	Campylobacteraceae	Sulfurospirillum	NA	8	0
578458	Fungi	Basidiomycota	Agaricomycetes	Agaricales	Schizophyllaceae	Schizophyllum	Schizophyllum commune	1	0
5786	NA	NA	NA	Dictyosteliales	Dictyosteliaceae	Dictyostelium	Dictyostelium purpureum	3	0
580058	NA	Apicomplexa	Aconoidasida	Haemosporida	Plasmodiidae	Plasmodium	Plasmodium falciparum	1	0
5801	NA	Apicomplexa	Coccidia	Eucoccidiorida	Eimeriidae	Eimeria	Eimeria acervulina	1	0
5802	NA	Apicomplexa	Coccidia	Eucoccidiorida	Eimeriidae	Eimeria	Eimeria tenella	6	0
58097	NA	Proteobacteria	Gammaproteobacteria	Enterobacterales	Enterobacteriaceae	Salmonella	Salmonella enterica	2	0
58117	NA	Actinobacteria	Actinobacteria	Streptosporangiales	Streptosporangiaceae	Microbispora	Microbispora rosea	1	0
5811	NA	Apicomplexa	Coccidia	Eucoccidiorida	Sarcocystidae	Toxoplasma	Toxoplasma gondii	1	0
5821	NA	Apicomplexa	Aconoidasida	Haemosporida	Plasmodiidae	Plasmodium	Plasmodium berghei	16	0
58291	Fungi	Mucoromycota	NA	Mucorales	Rhizopodaceae	Rhizopus	Rhizopus microsporus	1	0
5833	NA	Apicomplexa	Aconoidasida	Haemosporida	Plasmodiidae	Plasmodium	Plasmodium falciparum	8	0
584609	NA	Bacteroidetes	Flavobacteriia	Flavobacteriales	Flavobacteriaceae	Tenacibaculum	Tenacibaculum jejuense	1	0
5849	NA	Apicomplexa	Aconoidasida	Haemosporida	Plasmodiidae	Plasmodium	Plasmodium gallinaceum	1	0
584	NA	Proteobacteria	Gammaproteobacteria	Enterobacterales	Morganellaceae	Proteus	Proteus mirabilis	13	0
5850	NA	Apicomplexa	Aconoidasida	Haemosporida	Plasmodiidae	Plasmodium	Plasmodium knowlesi	12	0
5851	NA	Apicomplexa	Aconoidasida	Haemosporida	Plasmodiidae	Plasmodium	Plasmodium knowlesi	40	0
585455	NA	Proteobacteria	Gammaproteobacteria	NA	NA	Thiohalobacter	Thiohalobacter thiocyanaticus	1	0
5854	NA	Apicomplexa	Aconoidasida	Haemosporida	Plasmodiidae	Plasmodium	Plasmodium reichenowi	6	0
585529	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium genitalium	5	0
585530	NA	Actinobacteria	Actinobacteria	Micrococcales	Brevibacteriaceae	Brevibacterium	Brevibacterium mcbrellneri	4	0
5855	NA	Apicomplexa	Aconoidasida	Haemosporida	Plasmodiidae	Plasmodium	Plasmodium vivax	1	0
5857	NA	Apicomplexa	Aconoidasida	Haemosporida	Plasmodiidae	Plasmodium	Plasmodium fragile	1	0
5858	NA	Apicomplexa	Aconoidasida	Haemosporida	Plasmodiidae	Plasmodium	Plasmodium malariae	13	0
58627	Fungi	Ascomycota	Saccharomycetes	Saccharomycetales	Debaryomycetaceae	Debaryomyces	Debaryomyces fabryi	2	0
587909	NA	Actinobacteria	Actinobacteria	Pseudonocardiales	Pseudonocardiaceae	Yuhushiella	Yuhushiella deserti	1	0
588596	Fungi	Mucoromycota	Glomeromycetes	Glomerales	Glomeraceae	Rhizophagus	Rhizophagus irregularis	4	0
5888	NA	NA	Oligohymenophorea	Peniculida	Parameciidae	Paramecium	Paramecium tetraurelia	2	0
588	NA	Proteobacteria	Gammaproteobacteria	Enterobacterales	Morganellaceae	Providencia	Providencia stuartii	1	0
591158	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sp. AA4	3	0
592010	NA	Firmicutes	Bacilli	Lactobacillales	Aerococcaceae	Abiotrophia	Abiotrophia defectiva	1	0
59310	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus macedonicus	7	0
5932	NA	NA	Oligohymenophorea	Hymenostomatida	NA	Ichthyophthirius	Ichthyophthirius multifiliis	9	0
59561	NA	Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Trueperella	Trueperella bernardiae	1	0
59620	NA	Firmicutes	Clostridia	Clostridiales	Clostridiaceae	Clostridium	uncultured Clostridium sp.	4	0
596322	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus salivarius	1	0
59732	NA	Bacteroidetes	Flavobacteriia	Flavobacteriales	Flavobacteriaceae	Chryseobacterium	NA	1	0
59753	NA	Proteobacteria	Gammaproteobacteria	Oceanospirillales	Alcanivoracaceae	Alcanivorax	NA	1	0
59842	NA	Firmicutes	Bacilli	Bacillales	Paenibacillaceae	Paenibacillus	Paenibacillus chondroitinus	1	0
598660	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium pyruviciproducens	54967	0
60036	NA	Proteobacteria	Deltaproteobacteria	Desulfuromonadales	Geobacteraceae	Geobacter	Geobacter pelophilus	1	0
60172	Fungi	Ascomycota	Eurotiomycetes	Eurotiales	Aspergillaceae	Penicillium	Penicillium solitum	1	0
604332	NA	Deinococcus-Thermus	Deinococci	Thermales	Thermaceae	Meiothermus	Meiothermus rufus	1	0
611302	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Mycobacteriaceae	Mycobacterium	Mycobacterium tuberculosis	2	0
61171	NA	Firmicutes	Erysipelotrichia	Erysipelotrichales	Erysipelotrichaceae	Holdemania	Holdemania filiformis	2	0
611791	NA	NA	Oomycetes	Peronosporales	NA	Phytophthora	Phytophthora palmivora	1	0
61592	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium durum	1	0
61598	NA	Proteobacteria	Gammaproteobacteria	Chromatiales	Chromatiaceae	Lamprocystis	Lamprocystis purpurea	1	0
62322	NA	Proteobacteria	Gammaproteobacteria	Alteromonadales	Shewanellaceae	Shewanella	Shewanella baltica	1	0
62805	NA	NA	NA	NA	Retroviridae	NA	Human endogenous retrovirus W	1	0
630515	NA	Actinobacteria	Actinobacteria	Propionibacteriales	Propionibacteriaceae	Microlunatus	Microlunatus soli	6	0
63261	Fungi	Basidiomycota	Ustilaginomycetes	Ustilaginales	Ustilaginaceae	Moesziomyces	NA	1	0
633	NA	Proteobacteria	Gammaproteobacteria	Enterobacterales	Yersiniaceae	Yersinia	Yersinia pseudotuberculosis	1	0
634994	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Leptotrichiaceae	Leptotrichia	Leptotrichia hofstadii	61	0
635003	NA	Bacillariophyta	Bacillariophyceae	Bacillariales	Bacillariaceae	Fragilariopsis	Fragilariopsis cylindrus	8	0
636	NA	Proteobacteria	Gammaproteobacteria	Enterobacterales	Hafniaceae	Edwardsiella	Edwardsiella tarda	4	0
641407	NA	Lentisphaerae	NA	NA	NA	NA	NA	1	0
641	NA	Proteobacteria	Gammaproteobacteria	Vibrionales	Vibrionaceae	NA	NA	2	0
644281	NA	Euryarchaeota	Methanococci	Methanococcales	Methanocaldococcaceae	Methanocaldococcus	Methanocaldococcus sp. FS406-22	1	0
644352	Fungi	Ascomycota	Sordariomycetes	Magnaporthales	Magnaporthaceae	Gaeumannomyces	Gaeumannomyces tritici	1	0
644358	Fungi	Ascomycota	Sordariomycetes	Magnaporthales	Magnaporthaceae	Magnaporthiopsis	Magnaporthiopsis poae	5	0
64969	NA	Proteobacteria	Gammaproteobacteria	Oceanospirillales	Oceanospirillaceae	Oceanospirillum	Oceanospirillum multiglobuliferum	1	0
64972	NA	Proteobacteria	Gammaproteobacteria	Oceanospirillales	Oceanospirillaceae	Oceanobacter	Oceanobacter kriegii	2	0
649754	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium ammoniagenes	9	0
65058	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium ulcerans	11	0
653685	NA	Firmicutes	Bacilli	Bacillales	Bacillaceae	Bacillus	NA	2	0
65496	NA	Actinobacteria	Actinobacteria	Pseudonocardiales	Pseudonocardiaceae	Actinoalloteichus	NA	1	0
655819	Fungi	Ascomycota	Sordariomycetes	Hypocreales	Cordycipitaceae	Beauveria	Beauveria bassiana	3	0
655981	Fungi	Ascomycota	Leotiomycetes	NA	Pseudeurotiaceae	Pseudogymnoascus	Pseudogymnoascus destructans	1	0
656024	NA	Actinobacteria	Actinobacteria	Frankiales	Frankiaceae	Frankia	Frankia symbiont of Datisca glomerata	1	0
656088	NA	Tenericutes	Mollicutes	Mycoplasmatales	Mycoplasmataceae	Mycoplasma	NA	1	0
656916	Fungi	Ascomycota	Eurotiomycetes	Eurotiales	Aspergillaceae	Aspergillus	Aspergillus arachidicola	1	0
658057	NA	Proteobacteria	Alphaproteobacteria	Rhodobacterales	Rhodobacteraceae	Pacificibacter	Pacificibacter marinus	1	0
658858	NA	NA	NA	NA	Hexamitidae	Giardia	Giardia intestinalis	1	0
661190	NA	Proteobacteria	Alphaproteobacteria	Rhodospirillales	Acetobacteraceae	Neokomagataea	Neokomagataea thailandica	1	0
661399	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces caeruleatus	2	0
662755	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium resistens	1	0
663331	Fungi	Ascomycota	Eurotiomycetes	Onygenales	Arthrodermataceae	Trichophyton	Trichophyton benhamiae	1	0
663704	NA	Actinobacteria	Actinobacteria	Micrococcales	Microbacteriaceae	Leucobacter	Leucobacter sp. G161	1	0
66378	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces yerevanensis	1	0
664439	Fungi	Basidiomycota	Agaricomycetes	Boletales	Paxillaceae	Paxillus	Paxillus involutus	1	0
666	NA	Proteobacteria	Gammaproteobacteria	Vibrionales	Vibrionaceae	Vibrio	Vibrio cholerae	3	0
667019	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Comamonadaceae	Curvibacter	Curvibacter putative symbiont of Hydra magnipapillata	5	0
67003	NA	NA	NA	Kinetoplastida	Trypanosomatidae	Trypanosoma	Trypanosoma theileri	2	0
670483	Fungi	Basidiomycota	Agaricomycetes	Gloeophyllales	Gloeophyllaceae	Gloeophyllum	Gloeophyllum trabeum	3	0
670580	Fungi	Basidiomycota	Agaricomycetes	Polyporales	Dacryobolaceae	Postia	Postia placenta	2	0
670	NA	Proteobacteria	Gammaproteobacteria	Vibrionales	Vibrionaceae	Vibrio	Vibrio parahaemolyticus	1	0
671143	NA	candidate division NC10	NA	NA	NA	Candidatus Methylomirabilis	Candidatus Methylomirabilis oxyfera	2	0
671211	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Fusobacterium	Fusobacterium sp. oral taxon 203	35	0
671232	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	NA	8	0
67267	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces alboflavus	1	0
67297	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces flaveolus	2	0
672	NA	Proteobacteria	Gammaproteobacteria	Vibrionales	Vibrionaceae	Vibrio	Vibrio vulnificus	3	0
67365	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces sparsogenes	5	0
67373	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces varsoviensis	1	0
675864	NA	Actinobacteria	Actinobacteria	Propionibacteriales	Propionibacteriaceae	Auraticoccus	Auraticoccus monumenti	1	0
676202	NA	Actinobacteria	Actinobacteria	Micrococcales	Demequinaceae	Demequina	Demequina globuliformis	1	0
676517	NA	Proteobacteria	Gammaproteobacteria	Legionellales	Coxiellaceae	Diplorickettsia	Diplorickettsia massiliensis	1	0
67854	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Actinobacillus	Actinobacillus succinogenes	1	0
679318	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Nocardiaceae	Rhodococcus	Rhodococcus sp. WMMA185	1	0
679716	NA	NA	NA	Kinetoplastida	Trypanosomatidae	Trypanosoma	Trypanosoma brucei	57	0
68239	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces mirabilis	2	0
68249	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces pactum	1	0
68268	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces showdoensis	1	0
683082	NA	Proteobacteria	Epsilonproteobacteria	Campylobacterales	Campylobacteraceae	Campylobacter	Campylobacter jejuni	15	0
683228	NA	Actinobacteria	Actinobacteria	Micromonosporales	Micromonosporaceae	Micromonospora	Micromonospora yangpuensis	1	0
683260	NA	Actinobacteria	Actinobacteria	Streptosporangiales	Streptosporangiaceae	Nonomuraea	Nonomuraea maritima	1	0
683840	Fungi	Basidiomycota	Microbotryomycetes	Microbotryales	Microbotryaceae	Microbotryum	Microbotryum lychnidis-dioicae	1	0
683960	Fungi	Ascomycota	Saccharomycetes	Saccharomycetales	Phaffomycetaceae	Wickerhamomyces	Wickerhamomyces anomalus	1	0
68525	NA	Proteobacteria	NA	NA	NA	NA	NA	4	0
685588	Fungi	Basidiomycota	Agaricomycetes	Agaricales	Strophariaceae	Galerina	Galerina marginata	3	0
68565	NA	Actinobacteria	Actinobacteria	Streptosporangiales	Thermomonosporaceae	Actinomadura	Actinomadura hibisca	1	0
68766	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Fusobacterium	Fusobacterium sp.	3	0
687861	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	Bartonellaceae	Bartonella	Bartonella schoenbuchensis	4	0
688394	Fungi	Mucoromycota	NA	Mucorales	Lichtheimiaceae	Lichtheimia	Lichtheimia ramosa	1	0
68892	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus infantis	1	0
68	NA	Proteobacteria	Gammaproteobacteria	Xanthomonadales	Xanthomonadaceae	Lysobacter	NA	1	0
692275	Fungi	Ascomycota	Dothideomycetes	Capnodiales	Mycosphaerellaceae	Sphaerulina	Sphaerulina musiva	13	0
694068	Fungi	Basidiomycota	Agaricomycetes	Hymenochaetales	Hymenochaetaceae	Fomitiporia	Fomitiporia mediterranea	1	0
695850	NA	NA	Oomycetes	Saprolegniales	Saprolegniaceae	Saprolegnia	Saprolegnia parasitica	12	0
69710	NA	Spirochaetes	Spirochaetia	Spirochaetales	Spirochaetaceae	Treponema	Treponema vincentii	1	0
69771	Fungi	Ascomycota	Eurotiomycetes	Eurotiales	Aspergillaceae	Penicillium	Penicillium decumbens	1	0
698964	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium diphtheriae	5	0
69896	NA	Tenericutes	Mollicutes	Acholeplasmatales	Acholeplasmataceae	Candidatus Phytoplasma	Candidatus Phytoplasma solani	1	0
699431	NA	Euryarchaeota	Halobacteria	Haloferacales	Halorubraceae	Halolamina	Halolamina pelagica	1	0
702113	NA	Proteobacteria	Alphaproteobacteria	Sphingomonadales	Sphingomonadaceae	Novosphingobium	Novosphingobium sp. PP1Y	4	0
702438	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella oulorum	1	0
702969	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium sp. NML99-0020	2	0
703135	Fungi	Basidiomycota	Agaricomycetes	Agaricales	Amanitaceae	Amanita	Amanita thiersii	1	0
706433	NA	Firmicutes	Erysipelotrichia	Erysipelotrichales	Erysipelotrichaceae	Solobacterium	Solobacterium moorei	3	0
709323	NA	Firmicutes	Bacilli	Lactobacillales	Leuconostocaceae	Fructobacillus	Fructobacillus tropaeoli	2	0
70998	NA	Bacteroidetes	Saprospiria	Saprospirales	Lewinellaceae	Lewinella	Lewinella persica	1	0
710111	NA	Actinobacteria	Actinobacteria	Frankiales	Frankiaceae	Frankia	Frankia sp. QA3	1	0
710973	NA	Proteobacteria	Gammaproteobacteria	NA	NA	NA	uncultured gamma proteobacterium EB080_L93H08	1	0
712288	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Fusobacterium	Fusobacterium sp. oral taxon 370	8	0
712357	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Leptotrichiaceae	Leptotrichia	Leptotrichia sp. oral taxon 212	3	0
712359	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Leptotrichiaceae	Leptotrichia	Leptotrichia sp. oral taxon 215	1	0
715989	Fungi	Ascomycota	NA	NA	NA	NA	NA	1	0
716546	Fungi	Ascomycota	NA	NA	NA	NA	NA	1	0
71784	Fungi	Basidiomycota	Tremellomycetes	Tremellales	Naemateliaceae	Naematelia	Naematelia encephala	7	0
717944	Fungi	Basidiomycota	Agaricomycetes	Polyporales	Polyporaceae	Trametes	Trametes versicolor	1	0
71804	NA	NA	NA	Kinetoplastida	Trypanosomatidae	Trypanosoma	Trypanosoma grayi	1	0
721885	Fungi	Basidiomycota	Agaricomycetes	Russulales	Stereaceae	Stereum	Stereum hirsutum	1	0
72293	NA	Proteobacteria	Epsilonproteobacteria	Campylobacterales	Helicobacteraceae	NA	NA	1	0
72294	NA	Proteobacteria	Epsilonproteobacteria	Campylobacterales	Campylobacteraceae	NA	NA	28	0
722	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Actinobacillus	Actinobacillus seminis	1	0
723586	NA	NA	NA	NA	NA	NA	uncultured nuHF1 cluster bacterium HF0770_35I22	1	0
723611	NA	Proteobacteria	Alphaproteobacteria	Rhodospirillales	NA	NA	uncultured Rhodospirillales bacterium HF0500_23A22	2	0
72520	NA	Eustigmatophyceae	NA	Eustigmatales	Monodopsidaceae	Nannochloropsis	Nannochloropsis gaditana	1	0
728	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Avibacterium	Avibacterium paragallinarum	1	0
731	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Histophilus	Histophilus somni	3	0
73239	NA	Apicomplexa	Aconoidasida	Haemosporida	Plasmodiidae	Plasmodium	Plasmodium yoelii	4	0
739143	NA	Bacteroidetes	Flavobacteriia	Flavobacteriales	Flavobacteriaceae	Flavobacterium	Flavobacterium phragmitis	1	0
74030	NA	Proteobacteria	Alphaproteobacteria	Rhodobacterales	Rhodobacteraceae	Roseovarius	NA	1	0
741275	Fungi	Basidiomycota	Agaricomycetes	Corticiales	Punctulariaceae	Punctularia	Punctularia strigosozonata	1	0
741276	Fungi	Basidiomycota	Microbotryomycetes	Sporidiobolales	Sporidiobolaceae	Rhodotorula	Rhodotorula taiwanensis	1	0
742722	NA	Actinobacteria	Coriobacteriia	Coriobacteriales	Coriobacteriaceae	Collinsella	Collinsella sp. 4_8_47FAA	1	0
742814	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Fusobacterium	Fusobacterium necrophorum	2	0
744980	NA	Proteobacteria	Alphaproteobacteria	Rhodobacterales	Rhodobacteraceae	Roseibium	Roseibium sp. TrichSKD4	1	0
74700	NA	Tenericutes	Mollicutes	Entomoplasmatales	Entomoplasmataceae	Entomoplasma	Entomoplasma freundtii	1	0
747089	Fungi	Mucoromycota	Glomeromycetes	Glomerales	Glomeraceae	Rhizophagus	Rhizophagus irregularis	1	0
747294	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Comamonadaceae	Pseudorhodoferax	NA	1	0
747	NA	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Pasteurella	Pasteurella multocida	1	0
748671	NA	Firmicutes	Bacilli	Lactobacillales	Lactobacillaceae	Lactobacillus	Lactobacillus crispatus	1	0
75105	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Burkholderiaceae	Paraburkholderia	Paraburkholderia caribensis	1	0
754476	NA	Proteobacteria	Gammaproteobacteria	Thiotrichales	Piscirickettsiaceae	Methylophaga	Methylophaga nitratireducenticrescens	1	0
755172	NA	Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Peptoniphilus	Peptoniphilus coxii	3	0
756689	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Nocardiaceae	Nocardia	Nocardia amikacinitolerans	1	0
760570	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus parasanguinis	1	0
762948	NA	Actinobacteria	Actinobacteria	Micrococcales	Micrococcaceae	Rothia	Rothia dentocariosa	1	0
763407	Fungi	Mucoromycota	NA	Mucorales	Phycomycetaceae	Phycomyces	Phycomyces blakesleeanus	28	0
763665	Fungi	Zoopagomycota	NA	Kickxellales	Kickxellaceae	Coemansia	Coemansia reversa	2	0
764097	Fungi	Ascomycota	Saccharomycetes	Saccharomycetales	Saccharomycetaceae	Saccharomyces	Saccharomyces cerevisiae	1	0
765067	NA	Actinobacteria	Actinobacteria	Propionibacteriales	Propionibacteriaceae	Cutibacterium	Cutibacterium acnes	15	0
765076	NA	Actinobacteria	Actinobacteria	Propionibacteriales	Propionibacteriaceae	Cutibacterium	Cutibacterium acnes	1	0
765257	Fungi	Basidiomycota	Agaricomycetes	Boletales	Pisolithaceae	Pisolithus	Pisolithus microcarpus	1	0
765440	Fungi	Basidiomycota	Agaricomycetes	Atheliales	Atheliaceae	Piloderma	Piloderma croceum	1	0
765915	Fungi	Blastocladiomycota	Blastocladiomycetes	Blastocladiales	Catenariaceae	Catenaria	Catenaria anguillulae	1	0
766949	Fungi	Ascomycota	Saccharomycetes	Saccharomycetales	Saccharomycodaceae	Hanseniaspora	Hanseniaspora valbyensis	1	0
76728	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces vitaminophilus	2	0
767452	NA	Actinobacteria	Actinobacteria	Micrococcales	Intrasporangiaceae	Serinicoccus	Serinicoccus chungangensis	1	0
767463	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus thermophilus	3	0
767770	Fungi	Ascomycota	Eurotiomycetes	Eurotiales	Aspergillaceae	Aspergillus	Aspergillus tubingensis	1	0
76856	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Fusobacterium	Fusobacterium nucleatum	323	0
76857	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Fusobacterium	Fusobacterium nucleatum	78	0
76859	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Fusobacterium	Fusobacterium nucleatum	24	0
76860	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus constellatus	1	0
76978	NA	Proteobacteria	Alphaproteobacteria	Sphingomonadales	Sphingomonadaceae	Novosphingobium	Novosphingobium rosa	1	0
77044	Fungi	Ascomycota	Sordariomycetes	Xylariales	Xylariaceae	Rosellinia	Rosellinia necatrix	2	0
77133	NA	NA	NA	NA	NA	NA	uncultured bacterium	40	0
771870	Fungi	Ascomycota	Sordariomycetes	Sordariales	Sordariaceae	Sordaria	Sordaria macrospora	1	0
773	NA	Proteobacteria	Alphaproteobacteria	Rhizobiales	Bartonellaceae	Bartonella	NA	1	0
77519	NA	Apicomplexa	Aconoidasida	Haemosporida	Plasmodiidae	Plasmodium	Plasmodium gonderi	2	0
77643	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Mycobacteriaceae	Mycobacterium	NA	2	0
78156	Fungi	Ascomycota	Leotiomycetes	NA	Pseudeurotiaceae	Pseudogymnoascus	NA	1	0
795642	NA	Actinobacteria	Actinobacteria	Frankiales	Frankiaceae	Frankia	Frankia sp. G2	2	0
80864	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Comamonadaceae	NA	NA	1	0
80876	NA	Proteobacteria	Alphaproteobacteria	Rhodospirillales	Rhodospirillaceae	Insolitispirillum	Insolitispirillum peregrinum	1	0
80884	Fungi	Ascomycota	Sordariomycetes	Glomerellales	Glomerellaceae	Colletotrichum	Colletotrichum higginsianum	1	0
813	NA	Chlamydiae	Chlamydiia	Chlamydiales	Chlamydiaceae	Chlamydia	Chlamydia trachomatis	32	0
81529	NA	NA	NA	Choanoflagellida	Salpingoecidae	NA	NA	1	0
816	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Bacteroidaceae	Bacteroides	NA	1	0
81852	NA	Firmicutes	Bacilli	Lactobacillales	Enterococcaceae	NA	NA	4	0
82135	NA	Actinobacteria	Coriobacteriia	Coriobacteriales	Atopobiaceae	Atopobium	Atopobium vaginae	2	0
821	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Bacteroidaceae	Bacteroides	Bacteroides vulgatus	1	0
826	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Leptotrichiaceae	Sebaldella	Sebaldella termitidis	1	0
827	NA	Proteobacteria	Epsilonproteobacteria	Campylobacterales	Campylobacteraceae	Campylobacter	Campylobacter ureolyticus	16757	0
830	NA	Firmicutes	Clostridia	Clostridiales	Lachnospiraceae	Butyrivibrio	NA	1	0
83555	NA	Chlamydiae	Chlamydiia	Chlamydiales	Chlamydiaceae	Chlamydia	Chlamydia abortus	4	0
83558	NA	Chlamydiae	Chlamydiia	Chlamydiales	Chlamydiaceae	Chlamydia	Chlamydia pneumoniae	2	0
83681	NA	Actinobacteria	Actinobacteria	Streptosporangiales	Streptosporangiaceae	Nonomuraea	NA	1	0
83771	NA	Proteobacteria	Gammaproteobacteria	Aeromonadales	Succinivibrionaceae	Succinivibrio	Succinivibrio dextrinosolvens	5	0
838	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	NA	1	0
839	NA	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella ruminicola	1	0
847	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Oxalobacteraceae	Oxalobacter	Oxalobacter formigenes	1	0
848	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Fusobacterium	NA	46124	0
85006	NA	Actinobacteria	Actinobacteria	Micrococcales	NA	NA	NA	4	0
85007	NA	Actinobacteria	Actinobacteria	Corynebacteriales	NA	NA	NA	186	0
85025	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Nocardiaceae	NA	NA	8	0
85056	NA	NA	NA	Kinetoplastida	Trypanosomatidae	Trypanosoma	Trypanosoma cruzi	7	0
85057	NA	NA	NA	Kinetoplastida	Trypanosomatidae	Trypanosoma	Trypanosoma cruzi	4	0
850	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Fusobacterium	Fusobacterium mortiferum	2	0
851	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Fusobacterium	Fusobacterium nucleatum	38137	0
852	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Fusobacterium	Fusobacterium perfoetens	1	0
853	NA	Firmicutes	Clostridia	Clostridiales	Ruminococcaceae	Faecalibacterium	Faecalibacterium prausnitzii	7	0
854	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Fusobacterium	Fusobacterium russii	12	0
856822	Fungi	Ascomycota	Eurotiomycetes	Chaetothyriales	Herpotrichiellaceae	Fonsecaea	Fonsecaea nubica	2	0
857340	Fungi	Ascomycota	Sordariomycetes	Hypocreales	NA	Acremonium	Acremonium chrysogenum	1	0
858619	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium variabile	1	0
858893	Fungi	Ascomycota	Eurotiomycetes	Chaetothyriales	Herpotrichiellaceae	Exophiala	Exophiala dermatitidis	2	0
859	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Fusobacterium	Fusobacterium necrophorum	6	0
85	NA	Proteobacteria	Alphaproteobacteria	Rhodobacterales	Hyphomonadaceae	Hyphomonas	NA	1	0
86049	Fungi	Ascomycota	Eurotiomycetes	Chaetothyriales	Herpotrichiellaceae	Cladophialophora	Cladophialophora carrionii	3	0
860	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Fusobacterium	Fusobacterium periodonticum	109	0
861450	NA	Firmicutes	Negativicutes	Veillonellales	Veillonellaceae	Anaeroglobus	Anaeroglobus geminatus	3	0
861452	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Fusobacterium	Fusobacterium sp. oral taxon 370	36	0
861454	NA	Firmicutes	Clostridia	Clostridiales	Lachnospiraceae	NA	Lachnospiraceae bacterium oral taxon 082	1	0
86174	NA	Proteobacteria	Betaproteobacteria	Rhodocyclales	Zoogloeaceae	Thauera	Thauera butanivorans	1	0
862422	NA	Actinobacteria	Actinobacteria	Micrococcales	Cellulomonadaceae	Actinotalea	Actinotalea fermentans	1	0
862512	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium accolens	7	0
862970	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus anginosus	1	0
863522	NA	Acidobacteria	Acidobacteriia	Acidobacteriales	Acidobacteriaceae	Bryocella	Bryocella elongata	1	0
864141	NA	Apicomplexa	Aconoidasida	Haemosporida	Plasmodiidae	Plasmodium	Plasmodium ovale	1	0
864142	NA	Apicomplexa	Aconoidasida	Haemosporida	Plasmodiidae	Plasmodium	Plasmodium ovale	15	0
864565	NA	Firmicutes	Clostridia	Clostridiales	Peptostreptococcaceae	Peptoanaerobacter	[Eubacterium] yurii	2	0
864567	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus mitis	5	0
86635	Fungi	Mucoromycota	NA	Mucorales	Rhizopodaceae	Rhizopus	Rhizopus microsporus	1	0
866773	NA	Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Finegoldia	Finegoldia magna	1	0
86	NA	Proteobacteria	Alphaproteobacteria	Rhodobacterales	Hyphomonadaceae	Hyphomonas	Hyphomonas jannaschiana	1	0
870435	Fungi	Basidiomycota	Agaricomycetes	Boletales	Pisolithaceae	Pisolithus	Pisolithus tinctorius	1	0
875328	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Mycobacteriaceae	Mycobacterium	Mycobacterium sinense	1	0
87541	NA	Firmicutes	Bacilli	Lactobacillales	Aerococcaceae	Aerococcus	Aerococcus christensenii	3	0
87883	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Burkholderiaceae	Burkholderia	Burkholderia multivorans	4	0
879305	NA	Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Anaerococcus	Anaerococcus prevotii	1	0
879308	NA	Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Peptoniphilus	Peptoniphilus sp. oral taxon 375	2	0
879819	Fungi	Basidiomycota	Tremellomycetes	Trichosporonales	Trichosporonaceae	Cutaneotrichosporon	Cutaneotrichosporon oleaginosum	4	0
880072	NA	Proteobacteria	Deltaproteobacteria	Syntrophobacterales	Syntrophaceae	Desulfobacca	Desulfobacca acetoxidans	1	0
882086	NA	Actinobacteria	Actinobacteria	Pseudonocardiales	Pseudonocardiaceae	Saccharomonospora	Saccharomonospora xinjiangensis	2	0
882856	NA	Actinobacteria	Actinobacteria	Pseudonocardiales	Pseudonocardiaceae	Pseudonocardia	Pseudonocardia sp. P2	1	0
883077	NA	Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Actinomyces	Actinomyces turicensis	6	0
883114	NA	Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Helcococcus	Helcococcus kunzii	3	0
883165	NA	Proteobacteria	Epsilonproteobacteria	Campylobacterales	Campylobacteraceae	Campylobacter	Campylobacter ureolyticus	16	0
883168	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus urinalis	1	0
88431	NA	Firmicutes	Clostridia	Clostridiales	Lachnospiraceae	Dorea	Dorea longicatena	4	0
88456	NA	Apicomplexa	Coccidia	Eucoccidiorida	Eimeriidae	Cyclospora	Cyclospora cayetanensis	2	0
884684	NA	Firmicutes	Clostridia	Clostridiales	Ruminococcaceae	Mageeibacillus	Mageeibacillus indolicus	4	0
887929	NA	Firmicutes	Clostridia	Clostridiales	Eubacteriaceae	Pseudoramibacter	Pseudoramibacter alactolyticus	1	0
888048	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus parasanguinis	2	0
888056	NA	Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Actinomyces	Actinomyces sp. oral taxon 448	1	0
888062	NA	Firmicutes	Negativicutes	Veillonellales	Veillonellaceae	Dialister	Dialister micraerophilus	2	0
888742	NA	Proteobacteria	Betaproteobacteria	Neisseriales	Neisseriaceae	Neisseria	Neisseria bacilliformis	1	0
888745	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus agalactiae	1	0
888845	NA	Proteobacteria	Deltaproteobacteria	Myxococcales	NA	Minicystis	Minicystis rosea	1	0
889201	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus cristatus	1	0
889206	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus vestibularis	12	0
889948	NA	Candidatus Nanohaloarchaeota	Nanohaloarchaea	NA	NA	Candidatus Nanosalina	Candidatus Nanosalina sp. J07AB43	1	0
897	NA	Proteobacteria	Deltaproteobacteria	Desulfobacterales	Desulfobacteraceae	Desulfococcus	Desulfococcus multivorans	1	0
90262	Fungi	Mucoromycota	NA	Mucorales	Cunninghamellaceae	Absidia	Absidia repens	2	0
904306	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus vestibularis	8	0
906888	NA	Bacteroidetes	Flavobacteriia	Flavobacteriales	Flavobacteriaceae	Nonlabens	Nonlabens ulvanivorans	1	0
909768	NA	Proteobacteria	Gammaproteobacteria	Pseudomonadales	Moraxellaceae	Acinetobacter	NA	1	0
91061	NA	Firmicutes	Bacilli	NA	NA	NA	NA	244	0
911092	NA	Firmicutes	Clostridia	Thermoanaerobacterales	Thermoanaerobacteraceae	Caldanaerobacter	Caldanaerobacter subterraneus	1	0
912594	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Mycobacteriaceae	Mycobacterium	Mycobacterium iranicum	1	0
91347	NA	Proteobacteria	Gammaproteobacteria	Enterobacterales	NA	NA	NA	1	0
914238	Fungi	Ascomycota	Leotiomycetes	Helotiales	NA	Rhynchosporium	Rhynchosporium agropyri	1	0
91928	Fungi	Ascomycota	Eurotiomycetes	Chaetothyriales	Herpotrichiellaceae	Exophiala	Exophiala spinifera	1	0
92487	NA	Proteobacteria	Gammaproteobacteria	Thiotrichales	Thiotrichaceae	Thiothrix	Thiothrix eikelboomii	1	0
926570	NA	Proteobacteria	Alphaproteobacteria	Rhodospirillales	Acetobacteraceae	Acidiphilium	Acidiphilium multivorum	3	0
92942	NA	Cyanobacteria	NA	Nostocales	Nostocaceae	Nostoc	Nostoc linckia	1	0
929439	NA	NA	NA	Kinetoplastida	Trypanosomatidae	Leishmania	Leishmania mexicana	3	0
93064	NA	Proteobacteria	Alphaproteobacteria	Sphingomonadales	Sphingomonadaceae	Sphingomonas	Sphingomonas koreensis	1	0
930990	Fungi	Basidiomycota	Agaricomycetes	Cantharellales	Botryobasidiaceae	Botryobasidium	Botryobasidium botryosum	2	0
930991	Fungi	Basidiomycota	Agaricomycetes	Boletales	Paxillaceae	Paxillus	Paxillus rubicundulus	2	0
930992	Fungi	Basidiomycota	Agaricomycetes	Boletales	Suillaceae	Suillus	Suillus luteus	1	0
931537	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Nocardiaceae	Nocardia	Nocardia grenadensis	1	0
933084	Fungi	Basidiomycota	Agaricomycetes	Jaapiales	Jaapiaceae	Jaapia	Jaapia argillacea	1	0
935652	NA	Apicomplexa	Coccidia	Eucoccidiorida	Sarcocystidae	Toxoplasma	Toxoplasma gondii	3	0
935835	NA	Firmicutes	Bacilli	Bacillales	Bacillaceae	Bacillus	Bacillus sp. J13	1	0
935866	NA	Actinobacteria	Actinobacteria	Propionibacteriales	Nocardioidaceae	Nocardioides	Nocardioides sp. J54	2	0
936155	NA	Proteobacteria	Epsilonproteobacteria	Campylobacterales	Helicobacteraceae	Helicobacter	Helicobacter felis	4	0
936561	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Fusobacterium	Fusobacterium sp. CM1	10	0
936562	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Fusobacterium	Fusobacterium sp. CM21	1	0
936563	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Fusobacterium	Fusobacterium sp. CM22	15	0
936576	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus sp. ACS2	2	0
936587	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus sp. OBRC6	1	0
938293	NA	Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Anaerococcus	Anaerococcus provencensis	1	0
941280	NA	Proteobacteria	Gammaproteobacteria	Enterobacterales	Enterobacteriaceae	Escherichia	Escherichia coli	4	0
94208	Fungi	Ascomycota	Sordariomycetes	Hypocreales	Ophiocordycipitaceae	Tolypocladium	Tolypocladium paradoxum	1	0
943118	NA	Apicomplexa	Coccidia	Eucoccidiorida	Sarcocystidae	Toxoplasma	Toxoplasma gondii	4	0
943119	NA	Apicomplexa	Coccidia	Eucoccidiorida	Sarcocystidae	Toxoplasma	Toxoplasma gondii	1	0
943167	NA	Apicomplexa	Coccidia	Eucoccidiorida	Sarcocystidae	Toxoplasma	Toxoplasma gondii	2	0
943816	NA	Actinobacteria	Actinobacteria	Streptomycetales	Streptomycetaceae	Streptomyces	Streptomyces qinglanensis	1	0
944288	Fungi	Basidiomycota	Agaricomycetes	Amylocorticiales	Amylocorticiaceae	Plicaturopsis	Plicaturopsis crispa	1	0
944289	Fungi	Basidiomycota	Agaricomycetes	Agaricales	Omphalotaceae	Gymnopus	Gymnopus luxurians	2	0
945553	Fungi	Basidiomycota	Agaricomycetes	Agaricales	Strophariaceae	Hypholoma	Hypholoma sublateritium	1	0
946362	NA	NA	NA	Choanoflagellida	Salpingoecidae	Salpingoeca	Salpingoeca rosetta	21	0
94643	NA	Apicomplexa	Coccidia	Eucoccidiorida	Sarcocystidae	Besnoitia	Besnoitia besnoiti	6	0
948595	Fungi	Microsporidia	NA	NA	Pleistophoridae	Vavraia	Vavraia culicis	1	0
948	NA	Proteobacteria	Alphaproteobacteria	Rickettsiales	Anaplasmataceae	Anaplasma	Anaplasma phagocytophilum	2	0
95485	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Burkholderiaceae	Burkholderia	Burkholderia stabilis	1	0
95486	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Burkholderiaceae	Burkholderia	Burkholderia cenocepacia	2	0
970	NA	Firmicutes	Negativicutes	Selenomonadales	Selenomonadaceae	Selenomonas	NA	1	0
976	NA	Bacteroidetes	NA	NA	NA	NA	NA	3	0
98403	Fungi	Ascomycota	Sordariomycetes	Hypocreales	Ophiocordycipitaceae	Drechmeria	Drechmeria coniospora	227	0
984307	NA	Proteobacteria	Betaproteobacteria	Burkholderiales	Burkholderiaceae	Paraburkholderia	Paraburkholderia kururiensis	1	0
985895	Fungi	Ascomycota	Dothideomycetes	Pleosporales	Leptosphaeriaceae	Leptosphaeria	Leptosphaeria maculans	4	0
986075	NA	Firmicutes	Bacilli	Bacillales	Bacillaceae	Caldalkalibacillus	Caldalkalibacillus thermarum	2	0
986	NA	Bacteroidetes	Flavobacteriia	Flavobacteriales	Flavobacteriaceae	Flavobacterium	Flavobacterium johnsoniae	1	0
990650	Fungi	Basidiomycota	Agaricomycetes	Geastrales	Sphaerobolaceae	Sphaerobolus	Sphaerobolus stellatus	1	0
992067	NA	Proteobacteria	Epsilonproteobacteria	Campylobacterales	Helicobacteraceae	Helicobacter	Helicobacter pylori	3	0
99479	NA	Actinobacteria	Actinobacteria	Micrococcales	Intrasporangiaceae	Tetrasphaera	NA	1	0
996	NA	Bacteroidetes	Flavobacteriia	Flavobacteriales	Flavobacteriaceae	Flavobacterium	Flavobacterium columnare	1	0
997347	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Fusobacterium	Fusobacterium nucleatum	98	0
99807	NA	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium auriscanis	2	0
999414	NA	Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Fusobacterium	Fusobacterium nucleatum	3	0
999425	NA	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus sp. F0442	1	0
999810	Fungi	Ascomycota	Leotiomycetes	Helotiales	Sclerotiniaceae	Botrytis	Botrytis cinerea	2	0
