NCBI-TaxID	Kingdom	Phylum	Class	Order	Family	Genus	Species	Number_of_Reads	Relative_Abundance
999999	<not present>	<not present>	<not present>	<not present>	<not present>	Streptococcus	<not present>	1	0.0247156439
999999	<not present>	<not present>	<not present>	<not present>	<not present>	Enterococcus	<not present>	1	0.0339127577
999999	<not present>	<not present>	<not present>	<not present>	<not present>	Peptoniphilus	<not present>	1	0.0040068188
999999	<not present>	<not present>	<not present>	<not present>	<not present>	Actinotignum	<not present>	1	0.0827109819
999999	<not present>	<not present>	<not present>	<not present>	<not present>	Sneathia	<not present>	1	0.051688882
999999	<not present>	<not present>	<not present>	<not present>	<not present>	Propionibacterium	<not present>	1	0.0690837982
999999	<not present>	<not present>	<not present>	<not present>	<not present>	Campylobacter	<not present>	1	0.0170028995
999999	<not present>	<not present>	<not present>	<not present>	<not present>	Mobiluncus	<not present>	1	0.0251003318
999999	<not present>	<not present>	<not present>	<not present>	<not present>	Mycoplasma	<not present>	1	0.0922562329
999999	<not present>	<not present>	<not present>	<not present>	<not present>	Faecalibacterium	<not present>	1	0.0502190448
999999	<not present>	<not present>	<not present>	<not present>	<not present>	Catonella	<not present>	1	0.0424642261
999999	<not present>	<not present>	<not present>	<not present>	<not present>	Neisseria	<not present>	1	0.0937189445
999999	<not present>	<not present>	<not present>	<not present>	<not present>	Actinobaculum	<not present>	1	0.0379924888
999999	<not present>	<not present>	<not present>	<not present>	<not present>	Porphyromonas	<not present>	1	0.0522488204
999999	<not present>	<not present>	<not present>	<not present>	<not present>	Fusobacterium	<not present>	1	0.3176251308
