NCBI-TaxID	Kingdom	Phylum	Class	Order	Family	Genus	Species	Number_of_Reads	Relative_Abundance
999999	<not present>	<not present>	<not present>	<not present>	<not present>	Streptococcus	<not present>	1	0.1491507221
999999	<not present>	<not present>	<not present>	<not present>	<not present>	Enterococcus	<not present>	1	0.0161691282
999999	<not present>	<not present>	<not present>	<not present>	<not present>	Treponema	<not present>	1	0.0661783745
999999	<not present>	<not present>	<not present>	<not present>	<not present>	Peptoniphilus	<not present>	1	0.1199989413
999999	<not present>	<not present>	<not present>	<not present>	<not present>	Listeria	<not present>	1	0.2173008909
999999	<not present>	<not present>	<not present>	<not present>	<not present>	Actinotignum	<not present>	1	0.0113450668
999999	<not present>	<not present>	<not present>	<not present>	<not present>	Anaerococcus	<not present>	1	0.1199759993
999999	<not present>	<not present>	<not present>	<not present>	<not present>	Corynebacterium	<not present>	1	0.0524644928
999999	<not present>	<not present>	<not present>	<not present>	<not present>	Propionibacterium	<not present>	1	0.0436707361
999999	<not present>	<not present>	<not present>	<not present>	<not present>	Rothia	<not present>	1	0.0006897282
999999	<not present>	<not present>	<not present>	<not present>	<not present>	Streptobacillus	<not present>	1	0.0340916058
999999	<not present>	<not present>	<not present>	<not present>	<not present>	Dialister	<not present>	1	0.0528216529
999999	<not present>	<not present>	<not present>	<not present>	<not present>	Blautia	<not present>	1	0.115412177
999999	<not present>	<not present>	<not present>	<not present>	<not present>	Enterobacteriaceae gen. [C Escherichia/Shigella]	<not present>	1	0.0005698059
