NCBI-TaxID	Kingdom	Phylum	Class	Order	Family	Genus	Species	Number_of_Reads	Relative_Abundance
999999	<not present>	<not present>	<not present>	<not present>	<not present>	Streptococcus	<not present>	1	0.1682726837
999999	<not present>	<not present>	<not present>	<not present>	<not present>	Gemella	<not present>	1	0.4038919421
999999	<not present>	<not present>	<not present>	<not present>	<not present>	Propionibacterium	<not present>	1	0.0060448348
999999	<not present>	<not present>	<not present>	<not present>	<not present>	Moraxella	<not present>	1	0.1797537258
999999	<not present>	<not present>	<not present>	<not present>	<not present>	Prevotella	<not present>	1	0.2418966688
