NCBI-TaxID	Kingdom	Phylum	Class	Order	Family	Genus	Species	Number_of_Reads	Relative_Abundance
999999	<not present>	<not present>	<not present>	<not present>	<not present>	Actinomyces	<not present>	1	0.0293118449
999999	<not present>	<not present>	<not present>	<not present>	<not present>	Campylobacter	<not present>	1	0.5040703987
999999	<not present>	<not present>	<not present>	<not present>	<not present>	Blautia	<not present>	1	0.0035937194
999999	<not present>	<not present>	<not present>	<not present>	<not present>	Salmonella	<not present>	1	0.0075531654
999999	<not present>	<not present>	<not present>	<not present>	<not present>	Mannheimia	<not present>	1	0.135354399
