NCBI-TaxID	Kingdom	Phylum	Class	Order	Family	Genus	Species	Number_of_Reads	Relative_Abundance
0	NA	NA	Gammaproteobacteria	Myxococcales	Neisseriaceae	Azospirillum	Azorhizobium caulinodans	0	0
0	NA	NA	Alphaproteobacteria	Oscillatoriales	Enterobacteriaceae	Brucella	Buchnera aphidicola	0	0
0	NA	NA	Betaproteobacteria	Nitrosomonadales	Micrococcaceae	Pseudomonas	Cystobacter fuscus	0	0
0	NA	NA	Bacilli	Desulfuromonadales	Thermomonosporaceae	Xanthomonas	Archangium gephyra	0	0
0	NA	NA	Gammaproteobacteria	Pseudomonadales	Actinomycetaceae	Rhizobium	Chondromyces crocatus	0	0
0	NA	NA	Alphaproteobacteria	Burkholderiales	Streptomycetaceae	Acinetobacter	Sorangium cellulosum	0	0
0	NA	NA	Betaproteobacteria	Micrococcales	Bifidobacteriaceae	Neisseria	Vitreoscilla filiformis	0	0
0	NA	NA	Bacilli	Pseudonocardiales	Xanthomonadaceae	Alcaligenes	Lysobacter enzymogenes	0	0
0	NA	NA	Gammaproteobacteria	Streptomycetales	Comamonadaceae	Chromobacterium	Gemmata obscuriglobus	0	0
0	NA	NA	Alphaproteobacteria	Xanthomonadales	Promicromonosporaceae	Citrobacter	Borreliella burgdorferi	0	0
0	NA	NA	Betaproteobacteria	Oceanospirillales	Microbacteriaceae	Enterobacter	Borrelia turicatae	0	0
0	NA	NA	Bacilli	Flavobacteriales	Gallionellaceae	Klebsiella	Brachyspira hyodysenteriae	0	0
0	NA	NA	Gammaproteobacteria	Rhodospirillales	Burkholderiaceae	Aeromonas	Leptospira interrogans	0	0
0	NA	NA	Alphaproteobacteria	Sphingomonadales	Opitutaceae	Vibrio	Azospirillum brasilense	0	0
0	NA	NA	Betaproteobacteria	Neisseriales	Pseudomonadaceae	Haemophilus	Campylobacter coli	0	0
0	NA	NA	Bacilli	Rhodocyclales	Dermacoccaceae	Aerococcus	Campylobacter fetus	0	0
0	NA	NA	Gammaproteobacteria	Campylobacterales	Actinopolysporaceae	Bacillus	Campylobacter jejuni	0	0
0	NA	NA	Alphaproteobacteria	Myxococcales	Neisseriaceae	Clavibacter	Campylobacter concisus	0	0
0	NA	NA	Betaproteobacteria	Oscillatoriales	Enterobacteriaceae	Actinomyces	Campylobacter lari	0	0
0	NA	NA	Bacilli	Nitrosomonadales	Micrococcaceae	Bifidobacterium	Campylobacter sputorum	0	0
0	NA	NA	Gammaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Corynebacterium	Helicobacter pylori	0	0
0	NA	NA	Alphaproteobacteria	Pseudomonadales	Actinomycetaceae	Mycobacterium	Helicobacter mustelae	0	0
0	NA	NA	Betaproteobacteria	Burkholderiales	Streptomycetaceae	Nocardia	Elizabethkingia meningoseptica	0	0
0	NA	NA	Bacilli	Micrococcales	Bifidobacteriaceae	Rhodococcus	Chryseobacterium indologenes	0	0
0	NA	NA	Gammaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Pseudonocardia	Francisella tularensis	0	0
0	NA	NA	Alphaproteobacteria	Streptomycetales	Comamonadaceae	Streptomyces	Thermus thermophilus	0	0
0	NA	NA	Betaproteobacteria	Xanthomonadales	Promicromonosporaceae	Marinobacter	Pseudomonas aeruginosa	0	0
0	NA	NA	Bacilli	Oceanospirillales	Microbacteriaceae	Halomonas	Pseudoalteromonas atlantica	0	0
0	NA	NA	Gammaproteobacteria	Flavobacteriales	Gallionellaceae	Begomovirus	Burkholderia cepacia	0	0
0	NA	NA	Alphaproteobacteria	Rhodospirillales	Burkholderiaceae	Magnetospirillum	Pseudomonas fluorescens	0	0
0	NA	NA	Betaproteobacteria	Sphingomonadales	Opitutaceae	Rubrivivax	Pseudomonas fragi	0	0
0	NA	NA	Bacilli	Neisseriales	Pseudomonadaceae	Janthinobacterium	Pseudomonas putida	0	0
0	NA	NA	Gammaproteobacteria	Rhodocyclales	Dermacoccaceae	Burkholderia	Ralstonia solanacearum	0	0
0	NA	NA	Alphaproteobacteria	Campylobacterales	Actinopolysporaceae	Exiguobacterium	Pseudomonas stutzeri	0	0
0	NA	NA	Betaproteobacteria	Myxococcales	Neisseriaceae	Variovorax	Pseudomonas syringae	0	0
0	NA	NA	Bacilli	Oscillatoriales	Enterobacteriaceae	Rubrobacter	Xanthomonas campestris	0	0
0	NA	NA	Gammaproteobacteria	Nitrosomonadales	Micrococcaceae	Pseudoalteromonas	Azotobacter chroococcum	0	0
0	NA	NA	Alphaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Methylovorus	Agrobacterium tumefaciens	0	0
0	NA	NA	Betaproteobacteria	Pseudomonadales	Actinomycetaceae	Leclercia	Agrobacterium rhizogenes	0	0
0	NA	NA	Bacilli	Burkholderiales	Streptomycetaceae	Pandoraea	Bradyrhizobium japonicum	0	0
0	NA	NA	Gammaproteobacteria	Micrococcales	Bifidobacteriaceae	Arsenicicoccus	Bradyrhizobium sp.	0	0
0	NA	NA	Alphaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Zobellella	Sinorhizobium meliloti	0	0
0	NA	NA	Betaproteobacteria	Streptomycetales	Comamonadaceae	Mycobacteroides	Rhizobium leguminosarum	0	0
0	NA	NA	Bacilli	Xanthomonadales	Promicromonosporaceae	Luteipulveratus	Rhizobium phaseoli	0	0
0	NA	NA	Gammaproteobacteria	Oceanospirillales	Microbacteriaceae	Auritidibacter	Methylorubrum extorquens	0	0
0	NA	NA	Alphaproteobacteria	Flavobacteriales	Gallionellaceae	Komagataeibacter	Acetobacter aceti	0	0
0	NA	NA	Betaproteobacteria	Rhodospirillales	Burkholderiaceae	Pontimonas	Acetobacter pasteurianus	0	0
0	NA	NA	Bacilli	Sphingomonadales	Opitutaceae	Actinotignum	Legionella pneumophila	0	0
0	NA	NA	Gammaproteobacteria	Neisseriales	Pseudomonadaceae	Mycolicibacterium	Legionella hackeliae	0	0
0	NA	NA	Alphaproteobacteria	Rhodocyclales	Dermacoccaceae	Azospirillum	Legionella longbeachae	0	0
0	NA	NA	Betaproteobacteria	Campylobacterales	Actinopolysporaceae	Brucella	Legionella spiritensis	0	0
0	NA	NA	Bacilli	Myxococcales	Neisseriaceae	Pseudomonas	Acinetobacter baumannii	0	0
0	NA	NA	Gammaproteobacteria	Oscillatoriales	Enterobacteriaceae	Xanthomonas	Acinetobacter calcoaceticus	0	0
0	NA	NA	Alphaproteobacteria	Nitrosomonadales	Micrococcaceae	Rhizobium	Moraxella bovis	0	0
0	NA	NA	Betaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Acinetobacter	Moraxella catarrhalis	0	0
0	NA	NA	Bacilli	Pseudomonadales	Actinomycetaceae	Neisseria	Neisseria cinerea	0	0
0	NA	NA	Gammaproteobacteria	Burkholderiales	Streptomycetaceae	Alcaligenes	Neisseria gonorrhoeae	0	0
0	NA	NA	Alphaproteobacteria	Micrococcales	Bifidobacteriaceae	Chromobacterium	Neisseria lactamica	0	0
0	NA	NA	Betaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Citrobacter	Neisseria meningitidis	0	0
0	NA	NA	Bacilli	Streptomycetales	Comamonadaceae	Enterobacter	Neisseria mucosa	0	0
0	NA	NA	Gammaproteobacteria	Xanthomonadales	Promicromonosporaceae	Klebsiella	Neisseria polysaccharea	0	0
0	NA	NA	Alphaproteobacteria	Oceanospirillales	Microbacteriaceae	Aeromonas	Neisseria sicca	0	0
0	NA	NA	Betaproteobacteria	Flavobacteriales	Gallionellaceae	Vibrio	Neisseria elongata	0	0
0	NA	NA	Bacilli	Rhodospirillales	Burkholderiaceae	Haemophilus	Kingella kingae	0	0
0	NA	NA	Gammaproteobacteria	Sphingomonadales	Opitutaceae	Aerococcus	Alcaligenes faecalis	0	0
0	NA	NA	Alphaproteobacteria	Neisseriales	Pseudomonadaceae	Bacillus	Bordetella bronchiseptica	0	0
0	NA	NA	Betaproteobacteria	Rhodocyclales	Dermacoccaceae	Clavibacter	Bordetella parapertussis	0	0
0	NA	NA	Bacilli	Campylobacterales	Actinopolysporaceae	Actinomyces	Bordetella pertussis	0	0
0	NA	NA	Gammaproteobacteria	Myxococcales	Neisseriaceae	Bifidobacterium	Ochrobactrum anthropi	0	0
0	NA	NA	Alphaproteobacteria	Oscillatoriales	Enterobacteriaceae	Corynebacterium	Chromobacterium violaceum	0	0
0	NA	NA	Betaproteobacteria	Nitrosomonadales	Micrococcaceae	Mycobacterium	Eikenella corrodens	0	0
0	NA	NA	Bacilli	Desulfuromonadales	Thermomonosporaceae	Nocardia	Citrobacter koseri	0	0
0	NA	NA	Gammaproteobacteria	Pseudomonadales	Actinomycetaceae	Rhodococcus	Citrobacter freundii	0	0
0	NA	NA	Alphaproteobacteria	Burkholderiales	Streptomycetaceae	Pseudonocardia	Klebsiella aerogenes	0	0
0	NA	NA	Betaproteobacteria	Micrococcales	Bifidobacteriaceae	Streptomyces	Enterobacter cloacae	0	0
0	NA	NA	Bacilli	Pseudonocardiales	Xanthomonadaceae	Marinobacter	Pectobacterium carotovorum	0	0
0	NA	NA	Gammaproteobacteria	Streptomycetales	Comamonadaceae	Halomonas	Escherichia coli	0	0
0	NA	NA	Alphaproteobacteria	Xanthomonadales	Promicromonosporaceae	Begomovirus	Hafnia alvei	0	0
0	NA	NA	Betaproteobacteria	Oceanospirillales	Microbacteriaceae	Magnetospirillum	Klebsiella oxytoca	0	0
0	NA	NA	Bacilli	Flavobacteriales	Gallionellaceae	Rubrivivax	Klebsiella pneumoniae	0	0
0	NA	NA	Gammaproteobacteria	Rhodospirillales	Burkholderiaceae	Janthinobacterium	Morganella morganii	0	0
0	NA	NA	Alphaproteobacteria	Sphingomonadales	Opitutaceae	Burkholderia	Proteus mirabilis	0	0
0	NA	NA	Betaproteobacteria	Neisseriales	Pseudomonadaceae	Exiguobacterium	Proteus vulgaris	0	0
0	NA	NA	Bacilli	Rhodocyclales	Dermacoccaceae	Variovorax	Providencia rettgeri	0	0
0	NA	NA	Gammaproteobacteria	Campylobacterales	Actinopolysporaceae	Rubrobacter	Providencia stuartii	0	0
0	NA	NA	Alphaproteobacteria	Myxococcales	Neisseriaceae	Pseudoalteromonas	Serratia liquefaciens	0	0
0	NA	NA	Betaproteobacteria	Oscillatoriales	Enterobacteriaceae	Methylovorus	Serratia marcescens	0	0
0	NA	NA	Bacilli	Nitrosomonadales	Micrococcaceae	Leclercia	Xenorhabdus nematophila	0	0
0	NA	NA	Gammaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Pandoraea	Yersinia enterocolitica	0	0
0	NA	NA	Alphaproteobacteria	Pseudomonadales	Actinomycetaceae	Arsenicicoccus	Yersinia intermedia	0	0
0	NA	NA	Betaproteobacteria	Burkholderiales	Streptomycetaceae	Zobellella	Yersinia pestis	0	0
0	NA	NA	Bacilli	Micrococcales	Bifidobacteriaceae	Mycobacteroides	Yersinia pseudotuberculosis	0	0
0	NA	NA	Gammaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Luteipulveratus	Edwardsiella tarda	0	0
0	NA	NA	Alphaproteobacteria	Streptomycetales	Comamonadaceae	Auritidibacter	Aeromonas hydrophila	0	0
0	NA	NA	Betaproteobacteria	Xanthomonadales	Promicromonosporaceae	Komagataeibacter	Aeromonas salmonicida	0	0
0	NA	NA	Bacilli	Oceanospirillales	Microbacteriaceae	Pontimonas	Aeromonas caviae	0	0
0	NA	NA	Gammaproteobacteria	Flavobacteriales	Gallionellaceae	Actinotignum	Aeromonas media	0	0
0	NA	NA	Alphaproteobacteria	Rhodospirillales	Burkholderiaceae	Mycolicibacterium	Aeromonas schubertii	0	0
0	NA	NA	Betaproteobacteria	Sphingomonadales	Opitutaceae	Azospirillum	Aeromonas veronii	0	0
0	NA	NA	Bacilli	Neisseriales	Pseudomonadaceae	Brucella	Vibrio alginolyticus	0	0
0	NA	NA	Gammaproteobacteria	Rhodocyclales	Dermacoccaceae	Pseudomonas	Vibrio cholerae	0	0
0	NA	NA	Alphaproteobacteria	Campylobacterales	Actinopolysporaceae	Xanthomonas	Vibrio harveyi	0	0
0	NA	NA	Betaproteobacteria	Myxococcales	Neisseriaceae	Rhizobium	Vibrio parahaemolyticus	0	0
0	NA	NA	Bacilli	Oscillatoriales	Enterobacteriaceae	Acinetobacter	Vibrio vulnificus	0	0
0	NA	NA	Gammaproteobacteria	Nitrosomonadales	Micrococcaceae	Neisseria	Vibrio mimicus	0	0
0	NA	NA	Alphaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Alcaligenes	Vibrio fluvialis	0	0
0	NA	NA	Betaproteobacteria	Pseudomonadales	Actinomycetaceae	Chromobacterium	Vibrio campbellii	0	0
0	NA	NA	Bacilli	Burkholderiales	Streptomycetaceae	Citrobacter	Vibrio natriegens	0	0
0	NA	NA	Gammaproteobacteria	Micrococcales	Bifidobacteriaceae	Enterobacter	Aggregatibacter actinomycetemcomitans	0	0
0	NA	NA	Alphaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Klebsiella	Actinobacillus pleuropneumoniae	0	0
0	NA	NA	Betaproteobacteria	Streptomycetales	Comamonadaceae	Aeromonas	Actinobacillus suis	0	0
0	NA	NA	Bacilli	Xanthomonadales	Promicromonosporaceae	Vibrio	Haemophilus haemolyticus	0	0
0	NA	NA	Gammaproteobacteria	Oceanospirillales	Microbacteriaceae	Haemophilus	Haemophilus influenzae	0	0
0	NA	NA	Alphaproteobacteria	Flavobacteriales	Gallionellaceae	Aerococcus	Haemophilus parainfluenzae	0	0
0	NA	NA	Betaproteobacteria	Rhodospirillales	Burkholderiaceae	Bacillus	[Haemophilus] ducreyi	0	0
0	NA	NA	Bacilli	Sphingomonadales	Opitutaceae	Clavibacter	Histophilus somni	0	0
0	NA	NA	Gammaproteobacteria	Neisseriales	Pseudomonadaceae	Actinomyces	Aggregatibacter aphrophilus	0	0
0	NA	NA	Alphaproteobacteria	Rhodocyclales	Dermacoccaceae	Bifidobacterium	Glaesserella parasuis	0	0
0	NA	NA	Betaproteobacteria	Campylobacterales	Actinopolysporaceae	Corynebacterium	Pasteurella multocida	0	0
0	NA	NA	Bacilli	Myxococcales	Neisseriaceae	Mycobacterium	Pasteurella dagmatis	0	0
0	NA	NA	Gammaproteobacteria	Oscillatoriales	Enterobacteriaceae	Nocardia	Coxiella burnetii	0	0
0	NA	NA	Alphaproteobacteria	Nitrosomonadales	Micrococcaceae	Rhodococcus	Orientia tsutsugamushi	0	0
0	NA	NA	Betaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Pseudonocardia	Bacteroides thetaiotaomicron	0	0
0	NA	NA	Bacilli	Pseudomonadales	Actinomycetaceae	Streptomyces	Fusobacterium nucleatum	0	0
0	NA	NA	Gammaproteobacteria	Burkholderiales	Streptomycetaceae	Marinobacter	Faecalibacterium prausnitzii	0	0
0	NA	NA	Alphaproteobacteria	Micrococcales	Bifidobacteriaceae	Halomonas	Fusobacterium varium	0	0
0	NA	NA	Betaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Begomovirus	Fusobacterium periodonticum	0	0
0	NA	NA	Bacilli	Streptomycetales	Comamonadaceae	Magnetospirillum	Fusobacterium ulcerans	0	0
0	NA	NA	Gammaproteobacteria	Xanthomonadales	Promicromonosporaceae	Rubrivivax	Desulfococcus multivorans	0	0
0	NA	NA	Alphaproteobacteria	Oceanospirillales	Microbacteriaceae	Janthinobacterium	Desulfovibrio piger	0	0
0	NA	NA	Betaproteobacteria	Flavobacteriales	Gallionellaceae	Burkholderia	Thiomonas intermedia	0	0
0	NA	NA	Bacilli	Rhodospirillales	Burkholderiaceae	Exiguobacterium	Bdellovibrio bacteriovorus	0	0
0	NA	NA	Gammaproteobacteria	Sphingomonadales	Opitutaceae	Variovorax	Bacteriovorax stolpii	0	0
0	NA	NA	Alphaproteobacteria	Neisseriales	Pseudomonadaceae	Rubrobacter	Herbaspirillum seropedicae	0	0
0	NA	NA	Betaproteobacteria	Rhodocyclales	Dermacoccaceae	Pseudoalteromonas	Cellulophaga lytica	0	0
0	NA	NA	Bacilli	Campylobacterales	Actinopolysporaceae	Methylovorus	Flavobacterium johnsoniae	0	0
0	NA	NA	Gammaproteobacteria	Myxococcales	Neisseriaceae	Leclercia	Flavobacterium columnare	0	0
0	NA	NA	Alphaproteobacteria	Oscillatoriales	Enterobacteriaceae	Pandoraea	Sphingobacterium mizutaii	0	0
0	NA	NA	Betaproteobacteria	Nitrosomonadales	Micrococcaceae	Arsenicicoccus	Capnocytophaga sputigena	0	0
0	NA	NA	Bacilli	Desulfuromonadales	Thermomonosporaceae	Zobellella	Halorhodospira halochloris	0	0
0	NA	NA	Gammaproteobacteria	Pseudomonadales	Actinomycetaceae	Mycobacteroides	Rhodobacter sphaeroides	0	0
0	NA	NA	Alphaproteobacteria	Burkholderiales	Streptomycetaceae	Luteipulveratus	Rhodopseudomonas palustris	0	0
0	NA	NA	Betaproteobacteria	Micrococcales	Bifidobacteriaceae	Auritidibacter	Blastochloris viridis	0	0
0	NA	NA	Bacilli	Pseudonocardiales	Xanthomonadaceae	Komagataeibacter	Chloroflexus aurantiacus	0	0
0	NA	NA	Gammaproteobacteria	Streptomycetales	Comamonadaceae	Pontimonas	Piscirickettsia salmonis	0	0
0	NA	NA	Alphaproteobacteria	Xanthomonadales	Promicromonosporaceae	Actinotignum	Oenococcus oeni	0	0
0	NA	NA	Betaproteobacteria	Oceanospirillales	Microbacteriaceae	Mycolicibacterium	Pediococcus acidilactici	0	0
0	NA	NA	Bacilli	Flavobacteriales	Gallionellaceae	Azospirillum	Pediococcus pentosaceus	0	0
0	NA	NA	Gammaproteobacteria	Rhodospirillales	Burkholderiaceae	Brucella	Micrococcus luteus	0	0
0	NA	NA	Alphaproteobacteria	Sphingomonadales	Opitutaceae	Pseudomonas	Staphylococcus aureus	0	0
0	NA	NA	Betaproteobacteria	Neisseriales	Pseudomonadaceae	Xanthomonas	Staphylococcus carnosus	0	0
0	NA	NA	Bacilli	Rhodocyclales	Dermacoccaceae	Rhizobium	Staphylococcus epidermidis	0	0
0	NA	NA	Gammaproteobacteria	Campylobacterales	Actinopolysporaceae	Acinetobacter	Staphylococcus hyicus	0	0
0	NA	NA	Alphaproteobacteria	Myxococcales	Neisseriaceae	Neisseria	Staphylococcus simulans	0	0
0	NA	NA	Betaproteobacteria	Oscillatoriales	Enterobacteriaceae	Alcaligenes	Staphylococcus xylosus	0	0
0	NA	NA	Bacilli	Nitrosomonadales	Micrococcaceae	Chromobacterium	Staphylococcus warneri	0	0
0	NA	NA	Gammaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Citrobacter	Staphylococcus schleiferi	0	0
0	NA	NA	Alphaproteobacteria	Pseudomonadales	Actinomycetaceae	Enterobacter	Staphylococcus sciuri	0	0
0	NA	NA	Betaproteobacteria	Burkholderiales	Streptomycetaceae	Klebsiella	Streptococcus gordonii	0	0
0	NA	NA	Bacilli	Micrococcales	Bifidobacteriaceae	Aeromonas	Streptococcus oralis	0	0
0	NA	NA	Gammaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Vibrio	Streptococcus salivarius	0	0
0	NA	NA	Alphaproteobacteria	Streptomycetales	Comamonadaceae	Haemophilus	Streptococcus suis	0	0
0	NA	NA	Betaproteobacteria	Xanthomonadales	Promicromonosporaceae	Aerococcus	Streptococcus thermophilus	0	0
0	NA	NA	Bacilli	Oceanospirillales	Microbacteriaceae	Bacillus	Streptococcus mutans	0	0
0	NA	NA	Gammaproteobacteria	Flavobacteriales	Gallionellaceae	Clavibacter	Streptococcus sobrinus	0	0
0	NA	NA	Alphaproteobacteria	Rhodospirillales	Burkholderiaceae	Actinomyces	Streptococcus agalactiae	0	0
0	NA	NA	Betaproteobacteria	Sphingomonadales	Opitutaceae	Bifidobacterium	Streptococcus pneumoniae	0	0
0	NA	NA	Bacilli	Neisseriales	Pseudomonadaceae	Corynebacterium	Streptococcus pyogenes	0	0
0	NA	NA	Gammaproteobacteria	Rhodocyclales	Dermacoccaceae	Mycobacterium	Streptococcus sp. 'group B'	0	0
0	NA	NA	Alphaproteobacteria	Campylobacterales	Actinopolysporaceae	Nocardia	Streptococcus acidominimus	0	0
0	NA	NA	Betaproteobacteria	Myxococcales	Neisseriaceae	Rhodococcus	Streptococcus anginosus	0	0
0	NA	NA	Bacilli	Oscillatoriales	Enterobacteriaceae	Pseudonocardia	Streptococcus equinus	0	0
0	NA	NA	Gammaproteobacteria	Nitrosomonadales	Micrococcaceae	Streptomyces	Streptococcus intermedius	0	0
0	NA	NA	Alphaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Marinobacter	Streptococcus porcinus	0	0
0	NA	NA	Betaproteobacteria	Pseudomonadales	Actinomycetaceae	Halomonas	Streptococcus ferus	0	0
0	NA	NA	Bacilli	Burkholderiales	Streptomycetaceae	Begomovirus	Streptococcus parauberis	0	0
0	NA	NA	Gammaproteobacteria	Micrococcales	Bifidobacteriaceae	Magnetospirillum	Streptococcus uberis	0	0
0	NA	NA	Alphaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Rubrivivax	Enterococcus faecalis	0	0
0	NA	NA	Betaproteobacteria	Streptomycetales	Comamonadaceae	Janthinobacterium	Enterococcus faecium	0	0
0	NA	NA	Bacilli	Xanthomonadales	Promicromonosporaceae	Burkholderia	Enterococcus hirae	0	0
0	NA	NA	Gammaproteobacteria	Oceanospirillales	Microbacteriaceae	Exiguobacterium	Lactococcus lactis	0	0
0	NA	NA	Alphaproteobacteria	Flavobacteriales	Gallionellaceae	Variovorax	Lactococcus garvieae	0	0
0	NA	NA	Betaproteobacteria	Rhodospirillales	Burkholderiaceae	Rubrobacter	Planococcus kocurii	0	0
0	NA	NA	Bacilli	Sphingomonadales	Opitutaceae	Pseudoalteromonas	Aerococcus viridans	0	0
0	NA	NA	Gammaproteobacteria	Neisseriales	Pseudomonadaceae	Methylovorus	Bacillus amyloliquefaciens	0	0
0	NA	NA	Alphaproteobacteria	Rhodocyclales	Dermacoccaceae	Leclercia	Bacillus anthracis	0	0
0	NA	NA	Betaproteobacteria	Campylobacterales	Actinopolysporaceae	Pandoraea	Brevibacillus brevis	0	0
0	NA	NA	Bacilli	Myxococcales	Neisseriaceae	Arsenicicoccus	Bacillus cereus	0	0
0	NA	NA	Gammaproteobacteria	Oscillatoriales	Enterobacteriaceae	Zobellella	Bacillus coagulans	0	0
0	NA	NA	Alphaproteobacteria	Nitrosomonadales	Micrococcaceae	Mycobacteroides	Bacillus licheniformis	0	0
0	NA	NA	Betaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Luteipulveratus	Bacillus megaterium	0	0
0	NA	NA	Bacilli	Pseudomonadales	Actinomycetaceae	Auritidibacter	Bacillus mycoides	0	0
0	NA	NA	Gammaproteobacteria	Burkholderiales	Streptomycetaceae	Komagataeibacter	Paenibacillus polymyxa	0	0
0	NA	NA	Alphaproteobacteria	Micrococcales	Bifidobacteriaceae	Pontimonas	Bacillus pumilus	0	0
0	NA	NA	Betaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Actinotignum	Lysinibacillus sphaericus	0	0
0	NA	NA	Bacilli	Streptomycetales	Comamonadaceae	Mycolicibacterium	Bacillus subtilis	0	0
0	NA	NA	Gammaproteobacteria	Xanthomonadales	Promicromonosporaceae	Azospirillum	Parageobacillus thermoglucosidasius	0	0
0	NA	NA	Alphaproteobacteria	Oceanospirillales	Microbacteriaceae	Brucella	Bacillus thuringiensis	0	0
0	NA	NA	Betaproteobacteria	Flavobacteriales	Gallionellaceae	Pseudomonas	Bacillus lentus	0	0
0	NA	NA	Bacilli	Rhodospirillales	Burkholderiaceae	Xanthomonas	Bacillus smithii	0	0
0	NA	NA	Gammaproteobacteria	Sphingomonadales	Opitutaceae	Rhizobium	Virgibacillus halodenitrificans	0	0
0	NA	NA	Alphaproteobacteria	Neisseriales	Pseudomonadaceae	Acinetobacter	Clostridium botulinum	0	0
0	NA	NA	Betaproteobacteria	Rhodocyclales	Dermacoccaceae	Neisseria	Clostridium butyricum	0	0
0	NA	NA	Bacilli	Campylobacterales	Actinopolysporaceae	Alcaligenes	Clostridium cochlearium	0	0
0	NA	NA	Gammaproteobacteria	Myxococcales	Neisseriaceae	Chromobacterium	Clostridioides difficile	0	0
0	NA	NA	Alphaproteobacteria	Oscillatoriales	Enterobacteriaceae	Citrobacter	Clostridium formicaceticum	0	0
0	NA	NA	Betaproteobacteria	Nitrosomonadales	Micrococcaceae	Enterobacter	Clostridium pasteurianum	0	0
0	NA	NA	Bacilli	Desulfuromonadales	Thermomonosporaceae	Klebsiella	Clostridium perfringens	0	0
0	NA	NA	Gammaproteobacteria	Pseudomonadales	Actinomycetaceae	Aeromonas	Paeniclostridium sordellii	0	0
0	NA	NA	Alphaproteobacteria	Burkholderiales	Streptomycetaceae	Vibrio	Clostridium sporogenes	0	0
0	NA	NA	Betaproteobacteria	Micrococcales	Bifidobacteriaceae	Haemophilus	Acetoanaerobium sticklandii	0	0
0	NA	NA	Bacilli	Pseudonocardiales	Xanthomonadaceae	Aerococcus	Thermoanaerobacterium thermosaccharolyticum	0	0
0	NA	NA	Gammaproteobacteria	Streptomycetales	Comamonadaceae	Bacillus	Clostridium tyrobutyricum	0	0
0	NA	NA	Alphaproteobacteria	Xanthomonadales	Promicromonosporaceae	Clavibacter	Clostridium beijerinckii	0	0
0	NA	NA	Betaproteobacteria	Oceanospirillales	Microbacteriaceae	Actinomyces	Clostridium kluyveri	0	0
0	NA	NA	Bacilli	Flavobacteriales	Gallionellaceae	Bifidobacterium	Clostridium scatologenes	0	0
0	NA	NA	Gammaproteobacteria	Rhodospirillales	Burkholderiaceae	Corynebacterium	Clostridium baratii	0	0
0	NA	NA	Alphaproteobacteria	Sphingomonadales	Opitutaceae	Mycobacterium	Halobacillus halophilus	0	0
0	NA	NA	Betaproteobacteria	Neisseriales	Pseudomonadaceae	Nocardia	Sporosarcina ureae	0	0
0	NA	NA	Bacilli	Rhodocyclales	Dermacoccaceae	Rhodococcus	Leifsonia xyli	0	0
0	NA	NA	Gammaproteobacteria	Campylobacterales	Actinopolysporaceae	Pseudonocardia	Lactobacillus helveticus	0	0
0	NA	NA	Alphaproteobacteria	Myxococcales	Neisseriaceae	Streptomyces	Lactobacillus pentosus	0	0
0	NA	NA	Betaproteobacteria	Oscillatoriales	Enterobacteriaceae	Marinobacter	Lactobacillus plantarum	0	0
0	NA	NA	Bacilli	Nitrosomonadales	Micrococcaceae	Halomonas	Lactobacillus paracasei	0	0
0	NA	NA	Gammaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Begomovirus	Lactobacillus reuteri	0	0
0	NA	NA	Alphaproteobacteria	Pseudomonadales	Actinomycetaceae	Magnetospirillum	Lactobacillus amylovorus	0	0
0	NA	NA	Betaproteobacteria	Burkholderiales	Streptomycetaceae	Rubrivivax	Lactobacillus fermentum	0	0
0	NA	NA	Bacilli	Micrococcales	Bifidobacteriaceae	Janthinobacterium	Lactobacillus salivarius	0	0
0	NA	NA	Gammaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Burkholderia	Listeria ivanovii	0	0
0	NA	NA	Alphaproteobacteria	Streptomycetales	Comamonadaceae	Exiguobacterium	Listeria monocytogenes	0	0
0	NA	NA	Betaproteobacteria	Xanthomonadales	Promicromonosporaceae	Variovorax	Listeria welshimeri	0	0
0	NA	NA	Bacilli	Oceanospirillales	Microbacteriaceae	Rubrobacter	Erysipelothrix rhusiopathiae	0	0
0	NA	NA	Gammaproteobacteria	Flavobacteriales	Gallionellaceae	Pseudoalteromonas	Trueperella pyogenes	0	0
0	NA	NA	Alphaproteobacteria	Rhodospirillales	Burkholderiaceae	Methylovorus	Bifidobacterium angulatum	0	0
0	NA	NA	Betaproteobacteria	Sphingomonadales	Opitutaceae	Leclercia	Bifidobacterium breve	0	0
0	NA	NA	Bacilli	Neisseriales	Pseudomonadaceae	Pandoraea	Bifidobacterium pseudolongum	0	0
0	NA	NA	Gammaproteobacteria	Rhodocyclales	Dermacoccaceae	Arsenicicoccus	Corynebacterium ammoniagenes	0	0
0	NA	NA	Alphaproteobacteria	Campylobacterales	Actinopolysporaceae	Zobellella	Brevibacterium linens	0	0
0	NA	NA	Betaproteobacteria	Myxococcales	Neisseriaceae	Mycobacteroides	Corynebacterium stationis	0	0
0	NA	NA	Bacilli	Oscillatoriales	Enterobacteriaceae	Luteipulveratus	Cellulosimicrobium cellulans	0	0
0	NA	NA	Gammaproteobacteria	Nitrosomonadales	Micrococcaceae	Auritidibacter	Corynebacterium diphtheriae	0	0
0	NA	NA	Alphaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Komagataeibacter	Corynebacterium glutamicum	0	0
0	NA	NA	Betaproteobacteria	Pseudomonadales	Actinomycetaceae	Pontimonas	Corynebacterium pseudotuberculosis	0	0
0	NA	NA	Bacilli	Burkholderiales	Streptomycetaceae	Actinotignum	Corynebacterium renale	0	0
0	NA	NA	Gammaproteobacteria	Micrococcales	Bifidobacteriaceae	Mycolicibacterium	Eubacterium limosum	0	0
0	NA	NA	Alphaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Azospirillum	Cutibacterium acnes	0	0
0	NA	NA	Betaproteobacteria	Streptomycetales	Comamonadaceae	Brucella	Acidipropionibacterium acidipropionici	0	0
0	NA	NA	Bacilli	Xanthomonadales	Promicromonosporaceae	Pseudomonas	Mycobacterium avium	0	0
0	NA	NA	Gammaproteobacteria	Oceanospirillales	Microbacteriaceae	Xanthomonas	Mycolicibacterium fortuitum	0	0
0	NA	NA	Alphaproteobacteria	Flavobacteriales	Gallionellaceae	Rhizobium	Mycobacterium intracellulare	0	0
0	NA	NA	Betaproteobacteria	Rhodospirillales	Burkholderiaceae	Acinetobacter	Mycolicibacterium phlei	0	0
0	NA	NA	Bacilli	Sphingomonadales	Opitutaceae	Neisseria	Mycolicibacterium smegmatis	0	0
0	NA	NA	Gammaproteobacteria	Neisseriales	Pseudomonadaceae	Alcaligenes	Mycobacterium tuberculosis	0	0
0	NA	NA	Alphaproteobacteria	Rhodocyclales	Dermacoccaceae	Chromobacterium	Mycobacteroides chelonae	0	0
0	NA	NA	Betaproteobacteria	Campylobacterales	Actinopolysporaceae	Citrobacter	Mycobacterium marinum	0	0
0	NA	NA	Bacilli	Myxococcales	Neisseriaceae	Enterobacter	Mycolicibacter terrae	0	0
0	NA	NA	Gammaproteobacteria	Oscillatoriales	Enterobacteriaceae	Klebsiella	Mycolicibacterium aurum	0	0
0	NA	NA	Alphaproteobacteria	Nitrosomonadales	Micrococcaceae	Aeromonas	Mycolicibacterium neoaurum	0	0
0	NA	NA	Betaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Vibrio	Mycolicibacterium thermoresistibile	0	0
0	NA	NA	Bacilli	Pseudomonadales	Actinomycetaceae	Haemophilus	Rhodococcus rhodochrous	0	0
0	NA	NA	Gammaproteobacteria	Burkholderiales	Streptomycetaceae	Aerococcus	Rhodococcus ruber	0	0
0	NA	NA	Alphaproteobacteria	Micrococcales	Bifidobacteriaceae	Bacillus	Rhodococcus erythropolis	0	0
0	NA	NA	Betaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Clavibacter	Dermatophilus congolensis	0	0
0	NA	NA	Bacilli	Streptomycetales	Comamonadaceae	Actinomyces	Streptomyces actuosus	0	0
0	NA	NA	Gammaproteobacteria	Xanthomonadales	Promicromonosporaceae	Bifidobacterium	Streptomyces albus	0	0
0	NA	NA	Alphaproteobacteria	Oceanospirillales	Microbacteriaceae	Corynebacterium	Streptomyces ambofaciens	0	0
0	NA	NA	Betaproteobacteria	Flavobacteriales	Gallionellaceae	Mycobacterium	Streptomyces atratus	0	0
0	NA	NA	Bacilli	Rhodospirillales	Burkholderiaceae	Nocardia	Kitasatospora aureofaciens	0	0
0	NA	NA	Gammaproteobacteria	Sphingomonadales	Opitutaceae	Rhodococcus	Streptomyces clavuligerus	0	0
0	NA	NA	Alphaproteobacteria	Neisseriales	Pseudomonadaceae	Pseudonocardia	Streptomyces fradiae	0	0
0	NA	NA	Betaproteobacteria	Rhodocyclales	Dermacoccaceae	Streptomyces	Streptomyces glaucescens	0	0
0	NA	NA	Bacilli	Campylobacterales	Actinopolysporaceae	Marinobacter	Streptomyces hygroscopicus	0	0
0	NA	NA	Gammaproteobacteria	Myxococcales	Neisseriaceae	Halomonas	Streptomyces lincolnensis	0	0
0	NA	NA	Alphaproteobacteria	Oscillatoriales	Enterobacteriaceae	Begomovirus	Streptomyces reticuli	0	0
0	NA	NA	Betaproteobacteria	Nitrosomonadales	Micrococcaceae	Magnetospirillum	Streptomyces violaceoruber	0	0
0	NA	NA	Bacilli	Desulfuromonadales	Thermomonosporaceae	Rubrivivax	Streptomyces albireticuli	0	0
0	NA	NA	Gammaproteobacteria	Pseudomonadales	Actinomycetaceae	Janthinobacterium	Streptomyces chartreusis	0	0
0	NA	NA	Alphaproteobacteria	Burkholderiales	Streptomycetaceae	Burkholderia	Nocardiopsis dassonvillei	0	0
0	NA	NA	Betaproteobacteria	Micrococcales	Bifidobacteriaceae	Exiguobacterium	Aeromicrobium erythreum	0	0
0	NA	NA	Bacilli	Pseudonocardiales	Xanthomonadaceae	Variovorax	Pimelobacter simplex	0	0
0	NA	NA	Gammaproteobacteria	Streptomycetales	Comamonadaceae	Rubrobacter	Rothia dentocariosa	0	0
0	NA	NA	Alphaproteobacteria	Xanthomonadales	Promicromonosporaceae	Pseudoalteromonas	Mycoplasma capricolum	0	0
0	NA	NA	Betaproteobacteria	Oceanospirillales	Microbacteriaceae	Methylovorus	Mycoplasma gallisepticum	0	0
0	NA	NA	Bacilli	Flavobacteriales	Gallionellaceae	Leclercia	Mycoplasma mycoides	0	0
0	NA	NA	Gammaproteobacteria	Rhodospirillales	Burkholderiaceae	Pandoraea	Mycoplasma pneumoniae	0	0
0	NA	NA	Alphaproteobacteria	Sphingomonadales	Opitutaceae	Arsenicicoccus	Mycoplasma bovigenitalium	0	0
0	NA	NA	Betaproteobacteria	Neisseriales	Pseudomonadaceae	Zobellella	Mycoplasma californicum	0	0
0	NA	NA	Bacilli	Rhodocyclales	Dermacoccaceae	Mycobacteroides	Mycoplasma putrefaciens	0	0
0	NA	NA	Gammaproteobacteria	Campylobacterales	Actinopolysporaceae	Luteipulveratus	Spiroplasma citri	0	0
0	NA	NA	Alphaproteobacteria	Myxococcales	Neisseriaceae	Auritidibacter	Spiroplasma clarkii	0	0
0	NA	NA	Betaproteobacteria	Oscillatoriales	Enterobacteriaceae	Komagataeibacter	Mesoplasma florum	0	0
0	NA	NA	Bacilli	Nitrosomonadales	Micrococcaceae	Pontimonas	Methanobacterium formicicum	0	0
0	NA	NA	Gammaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Actinotignum	Sulfolobus solfataricus	0	0
0	NA	NA	Alphaproteobacteria	Pseudomonadales	Actinomycetaceae	Mycolicibacterium	Thermoanaerobacter kivui	0	0
0	NA	NA	Betaproteobacteria	Burkholderiales	Streptomycetaceae	Azospirillum	Xylella fastidiosa	0	0
0	NA	NA	Bacilli	Micrococcales	Bifidobacteriaceae	Brucella	Gardnerella vaginalis	0	0
0	NA	NA	Gammaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Pseudomonas	Brochothrix thermosphacta	0	0
0	NA	NA	Alphaproteobacteria	Streptomycetales	Comamonadaceae	Xanthomonas	Homo sapiens	0	0
0	NA	NA	Betaproteobacteria	Xanthomonadales	Promicromonosporaceae	Rhizobium	Pigeonpox virus	0	0
0	NA	NA	Bacilli	Oceanospirillales	Microbacteriaceae	Acinetobacter	Sheeppox virus	0	0
0	NA	NA	Gammaproteobacteria	Flavobacteriales	Gallionellaceae	Neisseria	Swinepox virus	0	0
0	NA	NA	Alphaproteobacteria	Rhodospirillales	Burkholderiaceae	Alcaligenes	Human alphaherpesvirus 3	0	0
0	NA	NA	Betaproteobacteria	Sphingomonadales	Opitutaceae	Chromobacterium	Clostridium phage c-st	0	0
0	NA	NA	Bacilli	Neisseriales	Pseudomonadaceae	Citrobacter	Raspberry ringspot virus	0	0
0	NA	NA	Gammaproteobacteria	Rhodocyclales	Dermacoccaceae	Enterobacter	Burkholderia mallei	0	0
0	NA	NA	Alphaproteobacteria	Campylobacterales	Actinopolysporaceae	Klebsiella	Sphingobium yanoikuyae	0	0
0	NA	NA	Betaproteobacteria	Myxococcales	Neisseriaceae	Aeromonas	Corynebacterium flavescens	0	0
0	NA	NA	Bacilli	Oscillatoriales	Enterobacteriaceae	Vibrio	Lysinibacillus fusiformis	0	0
0	NA	NA	Gammaproteobacteria	Nitrosomonadales	Micrococcaceae	Haemophilus	Staphylococcus lugdunensis	0	0
0	NA	NA	Alphaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Aerococcus	Lactobacillus curvatus	0	0
0	NA	NA	Betaproteobacteria	Pseudomonadales	Actinomycetaceae	Bacillus	Nostoc sp. PCC 7524	0	0
0	NA	NA	Bacilli	Burkholderiales	Streptomycetaceae	Clavibacter	Legionella sainthelensi	0	0
0	NA	NA	Gammaproteobacteria	Micrococcales	Bifidobacteriaceae	Actinomyces	Neisseria weaveri	0	0
0	NA	NA	Alphaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Bifidobacterium	Burkholderia gladioli	0	0
0	NA	NA	Betaproteobacteria	Streptomycetales	Comamonadaceae	Corynebacterium	Alteromonas macleodii	0	0
0	NA	NA	Bacilli	Xanthomonadales	Promicromonosporaceae	Mycobacterium	Pseudoalteromonas nigrifaciens	0	0
0	NA	NA	Gammaproteobacteria	Oceanospirillales	Microbacteriaceae	Nocardia	Francisella philomiragia	0	0
0	NA	NA	Alphaproteobacteria	Flavobacteriales	Gallionellaceae	Rhodococcus	Prevotella intermedia	0	0
0	NA	NA	Betaproteobacteria	Rhodospirillales	Burkholderiaceae	Pseudonocardia	Cronobacter sakazakii	0	0
0	NA	NA	Bacilli	Sphingomonadales	Opitutaceae	Streptomyces	Yersinia kristensenii	0	0
0	NA	NA	Gammaproteobacteria	Neisseriales	Pseudomonadaceae	Marinobacter	Capnocytophaga canimorsus	0	0
0	NA	NA	Alphaproteobacteria	Rhodocyclales	Dermacoccaceae	Halomonas	Capnocytophaga cynodegmi	0	0
0	NA	NA	Betaproteobacteria	Campylobacterales	Actinopolysporaceae	Begomovirus	Aliiarcobacter butzleri	0	0
0	NA	NA	Bacilli	Myxococcales	Neisseriaceae	Magnetospirillum	Arcanobacterium haemolyticum	0	0
0	NA	NA	Gammaproteobacteria	Oscillatoriales	Enterobacteriaceae	Rubrivivax	Neisseria subflava	0	0
0	NA	NA	Alphaproteobacteria	Nitrosomonadales	Micrococcaceae	Janthinobacterium	Burkholderia pseudomallei	0	0
0	NA	NA	Betaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Burkholderia	Leptospira alstonii	0	0
0	NA	NA	Bacilli	Pseudomonadales	Actinomycetaceae	Exiguobacterium	Salmonella enterica	0	0
0	NA	NA	Gammaproteobacteria	Burkholderiales	Streptomycetaceae	Variovorax	Streptomyces cattleya	0	0
0	NA	NA	Alphaproteobacteria	Micrococcales	Bifidobacteriaceae	Rubrobacter	Clostridium argentinense	0	0
0	NA	NA	Betaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Pseudoalteromonas	Staphylococcus cohnii	0	0
0	NA	NA	Bacilli	Streptomycetales	Comamonadaceae	Methylovorus	Staphylococcus kloosii	0	0
0	NA	NA	Gammaproteobacteria	Xanthomonadales	Promicromonosporaceae	Leclercia	Staphylococcus saprophyticus	0	0
0	NA	NA	Alphaproteobacteria	Oceanospirillales	Microbacteriaceae	Pandoraea	Staphylococcus capitis	0	0
0	NA	NA	Betaproteobacteria	Flavobacteriales	Gallionellaceae	Arsenicicoccus	Gemella morbillorum	0	0
0	NA	NA	Bacilli	Rhodospirillales	Burkholderiaceae	Zobellella	Synechococcus sp. WH 8103	0	0
0	NA	NA	Gammaproteobacteria	Sphingomonadales	Opitutaceae	Mycobacteroides	Acinetobacter haemolyticus	0	0
0	NA	NA	Alphaproteobacteria	Neisseriales	Pseudomonadaceae	Luteipulveratus	Moraxella ovis	0	0
0	NA	NA	Betaproteobacteria	Rhodocyclales	Dermacoccaceae	Auritidibacter	Pseudomonas savastanoi	0	0
0	NA	NA	Bacilli	Campylobacterales	Actinopolysporaceae	Komagataeibacter	Paucimonas lemoignei	0	0
0	NA	NA	Gammaproteobacteria	Myxococcales	Neisseriaceae	Pontimonas	Veillonella parvula	0	0
0	NA	NA	Alphaproteobacteria	Oscillatoriales	Enterobacteriaceae	Actinotignum	Pectobacterium atrosepticum	0	0
0	NA	NA	Betaproteobacteria	Nitrosomonadales	Micrococcaceae	Mycolicibacterium	Yersinia frederiksenii	0	0
0	NA	NA	Bacilli	Desulfuromonadales	Thermomonosporaceae	Azospirillum	Yersinia ruckeri	0	0
0	NA	NA	Gammaproteobacteria	Pseudomonadales	Actinomycetaceae	Brucella	Vibrio splendidus	0	0
0	NA	NA	Alphaproteobacteria	Burkholderiales	Streptomycetaceae	Pseudomonas	Borreliella garinii	0	0
0	NA	NA	Betaproteobacteria	Micrococcales	Bifidobacteriaceae	Xanthomonas	Taylorella equigenitalis	0	0
0	NA	NA	Bacilli	Pseudonocardiales	Xanthomonadaceae	Rhizobium	Amycolatopsis orientalis	0	0
0	NA	NA	Gammaproteobacteria	Streptomycetales	Comamonadaceae	Acinetobacter	Achromobacter denitrificans	0	0
0	NA	NA	Alphaproteobacteria	Xanthomonadales	Promicromonosporaceae	Neisseria	synthetic construct	0	0
0	NA	NA	Betaproteobacteria	Oceanospirillales	Microbacteriaceae	Alcaligenes	Parvimonas micra	0	0
0	NA	NA	Bacilli	Flavobacteriales	Gallionellaceae	Chromobacterium	Sphingopyxis macrogoltabida	0	0
0	NA	NA	Gammaproteobacteria	Rhodospirillales	Burkholderiaceae	Citrobacter	Pseudomonas viridiflava	0	0
0	NA	NA	Alphaproteobacteria	Sphingomonadales	Opitutaceae	Enterobacter	Anoxybacillus flavithermus	0	0
0	NA	NA	Betaproteobacteria	Neisseriales	Pseudomonadaceae	Klebsiella	Lactobacillus johnsonii	0	0
0	NA	NA	Bacilli	Rhodocyclales	Dermacoccaceae	Aeromonas	Rickettsia rhipicephali	0	0
0	NA	NA	Gammaproteobacteria	Campylobacterales	Actinopolysporaceae	Vibrio	Komagataeibacter europaeus	0	0
0	NA	NA	Alphaproteobacteria	Myxococcales	Neisseriaceae	Haemophilus	Paracoccus aminovorans	0	0
0	NA	NA	Betaproteobacteria	Oscillatoriales	Enterobacteriaceae	Aerococcus	Moraxella osloensis	0	0
0	NA	NA	Bacilli	Nitrosomonadales	Micrococcaceae	Bacillus	Variovorax paradoxus	0	0
0	NA	NA	Gammaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Clavibacter	Riemerella anatipestifer	0	0
0	NA	NA	Alphaproteobacteria	Pseudomonadales	Actinomycetaceae	Actinomyces	Streptobacillus moniliformis	0	0
0	NA	NA	Betaproteobacteria	Burkholderiales	Streptomycetaceae	Bifidobacterium	Bovine alphaherpesvirus 5	0	0
0	NA	NA	Bacilli	Micrococcales	Bifidobacteriaceae	Corynebacterium	Citrobacter amalonaticus	0	0
0	NA	NA	Gammaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Mycobacterium	Corynebacterium kutscheri	0	0
0	NA	NA	Alphaproteobacteria	Streptomycetales	Comamonadaceae	Nocardia	Corynebacterium cystitidis	0	0
0	NA	NA	Betaproteobacteria	Xanthomonadales	Promicromonosporaceae	Rhodococcus	Bifidobacterium choerinum	0	0
0	NA	NA	Bacilli	Oceanospirillales	Microbacteriaceae	Pseudonocardia	Rickettsia japonica	0	0
0	NA	NA	Gammaproteobacteria	Flavobacteriales	Gallionellaceae	Streptomyces	Bordetella holmesii	0	0
0	NA	NA	Alphaproteobacteria	Rhodospirillales	Burkholderiaceae	Marinobacter	Bacillus thermoamylovorans	0	0
0	NA	NA	Betaproteobacteria	Sphingomonadales	Opitutaceae	Halomonas	Clostridium saccharoperbutylacetonicum	0	0
0	NA	NA	Bacilli	Neisseriales	Pseudomonadaceae	Begomovirus	Mycobacteroides abscessus	0	0
0	NA	NA	Gammaproteobacteria	Rhodocyclales	Dermacoccaceae	Magnetospirillum	Gordonia rubripertincta	0	0
0	NA	NA	Alphaproteobacteria	Campylobacterales	Actinopolysporaceae	Rubrivivax	Nocardia brasiliensis	0	0
0	NA	NA	Betaproteobacteria	Myxococcales	Neisseriaceae	Janthinobacterium	Nocardia seriolae	0	0
0	NA	NA	Bacilli	Oscillatoriales	Enterobacteriaceae	Burkholderia	Helicobacter bilis	0	0
0	NA	NA	Gammaproteobacteria	Nitrosomonadales	Micrococcaceae	Exiguobacterium	Rhodococcus opacus	0	0
0	NA	NA	Alphaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Variovorax	Arthrobacter crystallopoietes	0	0
0	NA	NA	Betaproteobacteria	Pseudomonadales	Actinomycetaceae	Rubrobacter	Corynebacterium jeikeium	0	0
0	NA	NA	Bacilli	Burkholderiales	Streptomycetaceae	Pseudoalteromonas	Photobacterium damselae	0	0
0	NA	NA	Gammaproteobacteria	Micrococcales	Bifidobacteriaceae	Methylovorus	Streptomyces pristinaespiralis	0	0
0	NA	NA	Alphaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Leclercia	Corynebacterium minutissimum	0	0
0	NA	NA	Betaproteobacteria	Streptomycetales	Comamonadaceae	Pandoraea	Rhodococcus coprophilus	0	0
0	NA	NA	Bacilli	Xanthomonadales	Promicromonosporaceae	Arsenicicoccus	Methanococcus maripaludis	0	0
0	NA	NA	Gammaproteobacteria	Oceanospirillales	Microbacteriaceae	Zobellella	[Eubacterium] hallii	0	0
0	NA	NA	Alphaproteobacteria	Flavobacteriales	Gallionellaceae	Mycobacteroides	Mesorhizobium ciceri	0	0
0	NA	NA	Betaproteobacteria	Rhodospirillales	Burkholderiaceae	Luteipulveratus	Erythrobacter litoralis	0	0
0	NA	NA	Bacilli	Sphingomonadales	Opitutaceae	Auritidibacter	Acinetobacter johnsonii	0	0
0	NA	NA	Gammaproteobacteria	Neisseriales	Pseudomonadaceae	Komagataeibacter	Acinetobacter junii	0	0
0	NA	NA	Alphaproteobacteria	Rhodocyclales	Dermacoccaceae	Pontimonas	Acinetobacter radioresistens	0	0
0	NA	NA	Betaproteobacteria	Campylobacterales	Actinopolysporaceae	Actinotignum	Stenotrophomonas maltophilia	0	0
0	NA	NA	Bacilli	Myxococcales	Neisseriaceae	Mycolicibacterium	Xenorhabdus bovienii	0	0
0	NA	NA	Gammaproteobacteria	Oscillatoriales	Enterobacteriaceae	Azospirillum	Thioploca ingrica	0	0
0	NA	NA	Alphaproteobacteria	Nitrosomonadales	Micrococcaceae	Brucella	Brevundimonas vesicularis	0	0
0	NA	NA	Betaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Pseudomonas	Burkholderia plantarii	0	0
0	NA	NA	Bacilli	Pseudomonadales	Actinomycetaceae	Xanthomonas	Azoarcus communis	0	0
0	NA	NA	Gammaproteobacteria	Burkholderiales	Streptomycetaceae	Rhizobium	Actinosynnema pretiosum	0	0
0	NA	NA	Alphaproteobacteria	Micrococcales	Bifidobacteriaceae	Acinetobacter	Streptomyces sampsonii	0	0
0	NA	NA	Betaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Neisseria	Rubrobacter radiotolerans	0	0
0	NA	NA	Bacilli	Streptomycetales	Comamonadaceae	Alcaligenes	Pseudomonas alcaligenes	0	0
0	NA	NA	Gammaproteobacteria	Xanthomonadales	Promicromonosporaceae	Chromobacterium	Pseudoalteromonas luteoviolacea	0	0
0	NA	NA	Alphaproteobacteria	Oceanospirillales	Microbacteriaceae	Citrobacter	Pseudoalteromonas rubra	0	0
0	NA	NA	Betaproteobacteria	Flavobacteriales	Gallionellaceae	Enterobacter	Jonesia denitrificans	0	0
0	NA	NA	Bacilli	Rhodospirillales	Burkholderiaceae	Klebsiella	Rothia mucilaginosa	0	0
0	NA	NA	Gammaproteobacteria	Sphingomonadales	Opitutaceae	Aeromonas	Rhodococcus hoagii	0	0
0	NA	NA	Alphaproteobacteria	Neisseriales	Pseudomonadaceae	Vibrio	Corynebacterium striatum	0	0
0	NA	NA	Betaproteobacteria	Rhodocyclales	Dermacoccaceae	Haemophilus	Corynebacterium urealyticum	0	0
0	NA	NA	Bacilli	Campylobacterales	Actinopolysporaceae	Aerococcus	Paenibacillus durus	0	0
0	NA	NA	Gammaproteobacteria	Myxococcales	Neisseriaceae	Bacillus	Desulfovibrio fairfieldensis	0	0
0	NA	NA	Alphaproteobacteria	Oscillatoriales	Enterobacteriaceae	Clavibacter	Legionella lansingensis	0	0
0	NA	NA	Betaproteobacteria	Nitrosomonadales	Micrococcaceae	Actinomyces	Capnocytophaga haemolytica	0	0
0	NA	NA	Bacilli	Desulfuromonadales	Thermomonosporaceae	Bifidobacterium	Psychrobacter urativorans	0	0
0	NA	NA	Gammaproteobacteria	Pseudomonadales	Actinomycetaceae	Corynebacterium	Streptococcus cristatus	0	0
0	NA	NA	Alphaproteobacteria	Burkholderiales	Streptomycetaceae	Mycobacterium	Vibrio scophthalmi	0	0
0	NA	NA	Betaproteobacteria	Micrococcales	Bifidobacteriaceae	Nocardia	Staphylococcus pasteuri	0	0
0	NA	NA	Bacilli	Pseudonocardiales	Xanthomonadaceae	Rhodococcus	Anabaena sp. 90	0	0
0	NA	NA	Gammaproteobacteria	Streptomycetales	Comamonadaceae	Pseudonocardia	Pseudomonas mucidolens	0	0
0	NA	NA	Alphaproteobacteria	Xanthomonadales	Promicromonosporaceae	Streptomyces	Clostridium chauvoei	0	0
0	NA	NA	Betaproteobacteria	Oceanospirillales	Microbacteriaceae	Marinobacter	Massilia timonae	0	0
0	NA	NA	Bacilli	Flavobacteriales	Gallionellaceae	Halomonas	Borrelia miyamotoi	0	0
0	NA	NA	Gammaproteobacteria	Rhodospirillales	Burkholderiaceae	Begomovirus	Bacteroides caccae	0	0
0	NA	NA	Alphaproteobacteria	Sphingomonadales	Opitutaceae	Magnetospirillum	Streptomyces lydicus	0	0
0	NA	NA	Betaproteobacteria	Neisseriales	Pseudomonadaceae	Rubrivivax	Micromonospora aurantiaca	0	0
0	NA	NA	Bacilli	Rhodocyclales	Dermacoccaceae	Janthinobacterium	Pseudomonas amygdali	0	0
0	NA	NA	Gammaproteobacteria	Campylobacterales	Actinopolysporaceae	Burkholderia	Pseudomonas azotoformans	0	0
0	NA	NA	Alphaproteobacteria	Myxococcales	Neisseriaceae	Exiguobacterium	Pseudomonas fulva	0	0
0	NA	NA	Betaproteobacteria	Oscillatoriales	Enterobacteriaceae	Variovorax	Pseudomonas taetrolens	0	0
0	NA	NA	Bacilli	Nitrosomonadales	Micrococcaceae	Rubrobacter	Serratia fonticola	0	0
0	NA	NA	Gammaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Pseudoalteromonas	Mycoplasma pullorum	0	0
0	NA	NA	Alphaproteobacteria	Pseudomonadales	Actinomycetaceae	Methylovorus	Acinetobacter pittii	0	0
0	NA	NA	Betaproteobacteria	Burkholderiales	Streptomycetaceae	Leclercia	Xanthomonas fragariae	0	0
0	NA	NA	Bacilli	Micrococcales	Bifidobacteriaceae	Pandoraea	Candidatus Arthromitus sp. SFB-mouse	0	0
0	NA	NA	Gammaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Arsenicicoccus	Thermococcus profundus	0	0
0	NA	NA	Alphaproteobacteria	Streptomycetales	Comamonadaceae	Zobellella	Vibrio diabolicus	0	0
0	NA	NA	Betaproteobacteria	Xanthomonadales	Promicromonosporaceae	Mycobacteroides	Helicoverpa armigera nucleopolyhedrovirus	0	0
0	NA	NA	Bacilli	Oceanospirillales	Microbacteriaceae	Luteipulveratus	Pediococcus damnosus	0	0
0	NA	NA	Gammaproteobacteria	Flavobacteriales	Gallionellaceae	Auritidibacter	Aerococcus urinaeequi	0	0
0	NA	NA	Alphaproteobacteria	Rhodospirillales	Burkholderiaceae	Komagataeibacter	Tetragenococcus halophilus	0	0
0	NA	NA	Betaproteobacteria	Sphingomonadales	Opitutaceae	Pontimonas	Xestia c-nigrum granulovirus	0	0
0	NA	NA	Bacilli	Neisseriales	Pseudomonadaceae	Actinotignum	Lactobacillus gallinarum	0	0
0	NA	NA	Gammaproteobacteria	Rhodocyclales	Dermacoccaceae	Mycolicibacterium	Enterococcus durans	0	0
0	NA	NA	Alphaproteobacteria	Campylobacterales	Actinopolysporaceae	Azospirillum	Enterococcus mundtii	0	0
0	NA	NA	Betaproteobacteria	Myxococcales	Neisseriaceae	Brucella	Intrasporangium calvum	0	0
0	NA	NA	Bacilli	Oscillatoriales	Enterobacteriaceae	Pseudomonas	Pseudomonas citronellolis	0	0
0	NA	NA	Gammaproteobacteria	Nitrosomonadales	Micrococcaceae	Xanthomonas	Lactobacillus lindneri	0	0
0	NA	NA	Alphaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Rhizobium	Thermococcus barossii	0	0
0	NA	NA	Betaproteobacteria	Pseudomonadales	Actinomycetaceae	Acinetobacter	Raoultella ornithinolytica	0	0
0	NA	NA	Bacilli	Burkholderiales	Streptomycetaceae	Neisseria	Streptomyces venezuelae	0	0
0	NA	NA	Gammaproteobacteria	Micrococcales	Bifidobacteriaceae	Alcaligenes	Erwinia persicina	0	0
0	NA	NA	Alphaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Chromobacterium	Magnetospirillum gryphiswaldense	0	0
0	NA	NA	Betaproteobacteria	Streptomycetales	Comamonadaceae	Citrobacter	Vibrio anguillarum	0	0
0	NA	NA	Bacilli	Xanthomonadales	Promicromonosporaceae	Enterobacter	Thermococcus barophilus	0	0
0	NA	NA	Gammaproteobacteria	Oceanospirillales	Microbacteriaceae	Klebsiella	Xanthomonas sacchari	0	0
0	NA	NA	Alphaproteobacteria	Flavobacteriales	Gallionellaceae	Aeromonas	Rhizobium gallicum	0	0
0	NA	NA	Betaproteobacteria	Rhodospirillales	Burkholderiaceae	Vibrio	Thermus brockianus	0	0
0	NA	NA	Bacilli	Sphingomonadales	Opitutaceae	Haemophilus	Tsukamurella tyrosinosolvens	0	0
0	NA	NA	Gammaproteobacteria	Neisseriales	Pseudomonadaceae	Aerococcus	Citrobacter braakii	0	0
0	NA	NA	Alphaproteobacteria	Rhodocyclales	Dermacoccaceae	Bacillus	Burkholderia thailandensis	0	0
0	NA	NA	Betaproteobacteria	Campylobacterales	Actinopolysporaceae	Clavibacter	Colwellia sp. MT41	0	0
0	NA	NA	Bacilli	Myxococcales	Neisseriaceae	Actinomyces	Methanobacterium subterraneum	0	0
0	NA	NA	Gammaproteobacteria	Oscillatoriales	Enterobacteriaceae	Bifidobacterium	Actinotignum schaalii	0	0
0	NA	NA	Alphaproteobacteria	Nitrosomonadales	Micrococcaceae	Corynebacterium	Shewanella sp. MR-4	0	0
0	NA	NA	Betaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Mycobacterium	Paraburkholderia graminis	0	0
0	NA	NA	Bacilli	Pseudomonadales	Actinomycetaceae	Nocardia	Burkholderia pyrrocinia	0	0
0	NA	NA	Gammaproteobacteria	Burkholderiales	Streptomycetaceae	Rhodococcus	Burkholderia vietnamiensis	0	0
0	NA	NA	Alphaproteobacteria	Micrococcales	Bifidobacteriaceae	Pseudonocardia	Phaeobacter gallaeciensis	0	0
0	NA	NA	Betaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Streptomyces	Staphylococcus succinus	0	0
0	NA	NA	Bacilli	Streptomycetales	Comamonadaceae	Marinobacter	Dehalococcoides mccartyi	0	0
0	NA	NA	Gammaproteobacteria	Xanthomonadales	Promicromonosporaceae	Halomonas	Acholeplasma brassicae	0	0
0	NA	NA	Alphaproteobacteria	Oceanospirillales	Microbacteriaceae	Begomovirus	Enterobacter asburiae	0	0
0	NA	NA	Betaproteobacteria	Flavobacteriales	Gallionellaceae	Magnetospirillum	Lelliottia amnigena	0	0
0	NA	NA	Bacilli	Rhodospirillales	Burkholderiaceae	Rubrivivax	Pluralibacter gergoviae	0	0
0	NA	NA	Gammaproteobacteria	Sphingomonadales	Opitutaceae	Janthinobacterium	Kluyvera intermedia	0	0
0	NA	NA	Alphaproteobacteria	Neisseriales	Pseudomonadaceae	Burkholderia	Serratia ficaria	0	0
0	NA	NA	Betaproteobacteria	Rhodocyclales	Dermacoccaceae	Exiguobacterium	Serratia rubidaea	0	0
0	NA	NA	Bacilli	Campylobacterales	Actinopolysporaceae	Variovorax	Anomala cuprea entomopoxvirus	0	0
0	NA	NA	Gammaproteobacteria	Myxococcales	Neisseriaceae	Rubrobacter	Shewanella baltica	0	0
0	NA	NA	Alphaproteobacteria	Oscillatoriales	Enterobacteriaceae	Pseudoalteromonas	Azoarcus sp. BH72	0	0
0	NA	NA	Betaproteobacteria	Nitrosomonadales	Micrococcaceae	Methylovorus	Acinetobacter sp. ADP1	0	0
0	NA	NA	Bacilli	Desulfuromonadales	Thermomonosporaceae	Leclercia	Zobellia galactanivorans	0	0
0	NA	NA	Gammaproteobacteria	Pseudomonadales	Actinomycetaceae	Pandoraea	Bacillus pseudomycoides	0	0
0	NA	NA	Alphaproteobacteria	Burkholderiales	Streptomycetaceae	Arsenicicoccus	Corynebacterium ulcerans	0	0
0	NA	NA	Betaproteobacteria	Micrococcales	Bifidobacteriaceae	Zobellella	Cyanothece sp. PCC 7424	0	0
0	NA	NA	Bacilli	Pseudonocardiales	Xanthomonadaceae	Mycobacteroides	Legionella waltersii	0	0
0	NA	NA	Gammaproteobacteria	Streptomycetales	Comamonadaceae	Luteipulveratus	Streptomyces cavourensis	0	0
0	NA	NA	Alphaproteobacteria	Xanthomonadales	Promicromonosporaceae	Auritidibacter	Streptomyces alboflavus	0	0
0	NA	NA	Betaproteobacteria	Oceanospirillales	Microbacteriaceae	Komagataeibacter	Edwardsiella ictaluri	0	0
0	NA	NA	Bacilli	Flavobacteriales	Gallionellaceae	Pontimonas	Actinobacillus succinogenes	0	0
0	NA	NA	Gammaproteobacteria	Rhodospirillales	Burkholderiaceae	Actinotignum	Kitasatospora albolonga	0	0
0	NA	NA	Alphaproteobacteria	Sphingomonadales	Opitutaceae	Mycolicibacterium	Streptomyces bacillaris	0	0
0	NA	NA	Betaproteobacteria	Neisseriales	Pseudomonadaceae	Azospirillum	Streptomyces globosus	0	0
0	NA	NA	Bacilli	Rhodocyclales	Dermacoccaceae	Brucella	Streptomyces griseochromogenes	0	0
0	NA	NA	Gammaproteobacteria	Campylobacterales	Actinopolysporaceae	Pseudomonas	Streptomyces pactum	0	0
0	NA	NA	Alphaproteobacteria	Myxococcales	Neisseriaceae	Xanthomonas	Streptomyces albulus	0	0
0	NA	NA	Betaproteobacteria	Oscillatoriales	Enterobacteriaceae	Rhizobium	Cupriavidus basilensis	0	0
0	NA	NA	Bacilli	Nitrosomonadales	Micrococcaceae	Acinetobacter	Curtobacterium pusillum	0	0
0	NA	NA	Gammaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Neisseria	Caulobacter henricii	0	0
0	NA	NA	Alphaproteobacteria	Pseudomonadales	Actinomycetaceae	Alcaligenes	Moritella yayanosii	0	0
0	NA	NA	Betaproteobacteria	Burkholderiales	Streptomycetaceae	Chromobacterium	Caulobacter mirabilis	0	0
0	NA	NA	Bacilli	Micrococcales	Bifidobacteriaceae	Citrobacter	Staphylococcus piscifermentans	0	0
0	NA	NA	Gammaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Enterobacter	Pseudomonas plecoglossicida	0	0
0	NA	NA	Alphaproteobacteria	Streptomycetales	Comamonadaceae	Klebsiella	Antarctobacter heliothermus	0	0
0	NA	NA	Betaproteobacteria	Xanthomonadales	Promicromonosporaceae	Aeromonas	Pseudomonas balearica	0	0
0	NA	NA	Bacilli	Oceanospirillales	Microbacteriaceae	Vibrio	Ferroplasma acidiphilum	0	0
0	NA	NA	Gammaproteobacteria	Flavobacteriales	Gallionellaceae	Haemophilus	Paraburkholderia caribensis	0	0
0	NA	NA	Alphaproteobacteria	Rhodospirillales	Burkholderiaceae	Aerococcus	Streptomyces autolyticus	0	0
0	NA	NA	Betaproteobacteria	Sphingomonadales	Opitutaceae	Bacillus	Castellaniella defragrans	0	0
0	NA	NA	Bacilli	Neisseriales	Pseudomonadaceae	Clavibacter	Thermocrinis ruber	0	0
0	NA	NA	Gammaproteobacteria	Rhodocyclales	Dermacoccaceae	Actinomyces	Mannheimia haemolytica	0	0
0	NA	NA	Alphaproteobacteria	Campylobacterales	Actinopolysporaceae	Bifidobacterium	Roseateles depolymerans	0	0
0	NA	NA	Betaproteobacteria	Myxococcales	Neisseriaceae	Corynebacterium	Pseudomonas monteilii	0	0
0	NA	NA	Bacilli	Oscillatoriales	Enterobacteriaceae	Mycobacterium	Pseudomonas veronii	0	0
0	NA	NA	Gammaproteobacteria	Nitrosomonadales	Micrococcaceae	Nocardia	Myroides odoratimimus	0	0
0	NA	NA	Alphaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Rhodococcus	Solibacillus silvestris	0	0
0	NA	NA	Betaproteobacteria	Pseudomonadales	Actinomycetaceae	Pseudonocardia	Pseudomonas mosselii	0	0
0	NA	NA	Bacilli	Burkholderiales	Streptomycetaceae	Streptomyces	Bacillus clausii	0	0
0	NA	NA	Gammaproteobacteria	Micrococcales	Bifidobacteriaceae	Marinobacter	Bacillus gibsonii	0	0
0	NA	NA	Alphaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Halomonas	Bacillus horikoshii	0	0
0	NA	NA	Betaproteobacteria	Streptomycetales	Comamonadaceae	Begomovirus	Aliivibrio wodanis	0	0
0	NA	NA	Bacilli	Xanthomonadales	Promicromonosporaceae	Magnetospirillum	Moritella viscosa	0	0
0	NA	NA	Gammaproteobacteria	Oceanospirillales	Microbacteriaceae	Rubrivivax	Frateuria aurantia	0	0
0	NA	NA	Alphaproteobacteria	Flavobacteriales	Gallionellaceae	Janthinobacterium	Streptococcus pluranimalium	0	0
0	NA	NA	Betaproteobacteria	Rhodospirillales	Burkholderiaceae	Burkholderia	Cupriavidus gilardii	0	0
0	NA	NA	Bacilli	Sphingomonadales	Opitutaceae	Exiguobacterium	Obesumbacterium proteus	0	0
0	NA	NA	Gammaproteobacteria	Neisseriales	Pseudomonadaceae	Variovorax	Serratia plymuthica	0	0
0	NA	NA	Alphaproteobacteria	Rhodocyclales	Dermacoccaceae	Rubrobacter	Mycobacteroides immunogenum	0	0
0	NA	NA	Betaproteobacteria	Campylobacterales	Actinopolysporaceae	Pseudoalteromonas	Aminobacter aminovorans	0	0
0	NA	NA	Bacilli	Myxococcales	Neisseriaceae	Methylovorus	gamma proteobacterium HdN1	0	0
0	NA	NA	Gammaproteobacteria	Oscillatoriales	Enterobacteriaceae	Leclercia	Chlamydia pneumoniae	0	0
0	NA	NA	Alphaproteobacteria	Nitrosomonadales	Micrococcaceae	Pandoraea	Chlamydia suis	0	0
0	NA	NA	Betaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Arsenicicoccus	Stenotrophomonas nitritireducens	0	0
0	NA	NA	Bacilli	Pseudomonadales	Actinomycetaceae	Zobellella	Leclercia adecarboxylata	0	0
0	NA	NA	Gammaproteobacteria	Burkholderiales	Streptomycetaceae	Mycobacteroides	Lactobacillus amylolyticus	0	0
0	NA	NA	Alphaproteobacteria	Micrococcales	Bifidobacteriaceae	Luteipulveratus	Methanoculleus bourgensis	0	0
0	NA	NA	Betaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Auritidibacter	Clostridium aceticum	0	0
0	NA	NA	Bacilli	Streptomycetales	Comamonadaceae	Komagataeibacter	Pseudoclostridium thermosuccinogenes	0	0
0	NA	NA	Gammaproteobacteria	Xanthomonadales	Promicromonosporaceae	Pontimonas	Microbacterium chocolatum	0	0
0	NA	NA	Alphaproteobacteria	Oceanospirillales	Microbacteriaceae	Actinotignum	Lysobacter antibioticus	0	0
0	NA	NA	Betaproteobacteria	Flavobacteriales	Gallionellaceae	Mycolicibacterium	Synechococcus sp. WH 8102	0	0
0	NA	NA	Bacilli	Rhodospirillales	Burkholderiaceae	Azospirillum	European catfish virus	0	0
0	NA	NA	Gammaproteobacteria	Sphingomonadales	Opitutaceae	Brucella	Mannheimia varigena	0	0
0	NA	NA	Alphaproteobacteria	Neisseriales	Pseudomonadaceae	Pseudomonas	Thauera sp. MZ1T	0	0
0	NA	NA	Betaproteobacteria	Rhodocyclales	Dermacoccaceae	Xanthomonas	Achromobacter xylosoxidans	0	0
0	NA	NA	Bacilli	Campylobacterales	Actinopolysporaceae	Rhizobium	Methanoculleus sp. MAB1	0	0
0	NA	NA	Gammaproteobacteria	Myxococcales	Neisseriaceae	Acinetobacter	Bacillus flexus	0	0
0	NA	NA	Alphaproteobacteria	Oscillatoriales	Enterobacteriaceae	Neisseria	Aerococcus christensenii	0	0
0	NA	NA	Betaproteobacteria	Nitrosomonadales	Micrococcaceae	Alcaligenes	Xanthomonas gardneri	0	0
0	NA	NA	Bacilli	Desulfuromonadales	Thermomonosporaceae	Chromobacterium	Candidatus Paracaedibacter acanthamoebae	0	0
0	NA	NA	Gammaproteobacteria	Pseudomonadales	Actinomycetaceae	Citrobacter	Mycoplasma cloacale	0	0
0	NA	NA	Alphaproteobacteria	Burkholderiales	Streptomycetaceae	Enterobacter	Streptomyces malaysiensis	0	0
0	NA	NA	Betaproteobacteria	Micrococcales	Bifidobacteriaceae	Klebsiella	Herbaspirillum frisingense	0	0
0	NA	NA	Bacilli	Pseudonocardiales	Xanthomonadaceae	Aeromonas	Ketogulonicigenium vulgare	0	0
0	NA	NA	Gammaproteobacteria	Streptomycetales	Comamonadaceae	Vibrio	Pandoraea apista	0	0
0	NA	NA	Alphaproteobacteria	Xanthomonadales	Promicromonosporaceae	Haemophilus	Pandoraea norimbergensis	0	0
0	NA	NA	Betaproteobacteria	Oceanospirillales	Microbacteriaceae	Aerococcus	Pandoraea pnomenusa	0	0
0	NA	NA	Bacilli	Flavobacteriales	Gallionellaceae	Bacillus	Pandoraea pulmonicola	0	0
0	NA	NA	Gammaproteobacteria	Rhodospirillales	Burkholderiaceae	Clavibacter	Pandoraea sputorum	0	0
0	NA	NA	Alphaproteobacteria	Sphingomonadales	Opitutaceae	Actinomyces	Fervidobacterium pennivorans	0	0
0	NA	NA	Betaproteobacteria	Neisseriales	Pseudomonadaceae	Bifidobacterium	Shewanella sp. ANA-3	0	0
0	NA	NA	Bacilli	Rhodocyclales	Dermacoccaceae	Corynebacterium	Ramlibacter tataouinensis	0	0
0	NA	NA	Gammaproteobacteria	Campylobacterales	Actinopolysporaceae	Mycobacterium	Bordetella petrii	0	0
0	NA	NA	Alphaproteobacteria	Myxococcales	Neisseriaceae	Nocardia	Burkholderia stabilis	0	0
0	NA	NA	Betaproteobacteria	Oscillatoriales	Enterobacteriaceae	Rhodococcus	Burkholderia cenocepacia	0	0
0	NA	NA	Bacilli	Nitrosomonadales	Micrococcaceae	Pseudonocardia	Flavobacterium psychrophilum	0	0
0	NA	NA	Gammaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Streptomyces	Thauera chlorobenzoica	0	0
0	NA	NA	Alphaproteobacteria	Pseudomonadales	Actinomycetaceae	Marinobacter	Vitreoscilla sp. C1	0	0
0	NA	NA	Betaproteobacteria	Burkholderiales	Streptomycetaceae	Halomonas	Halobacteriovorax marinus	0	0
0	NA	NA	Bacilli	Micrococcales	Bifidobacteriaceae	Begomovirus	Bacillus sp. OxB-1	0	0
0	NA	NA	Gammaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Magnetospirillum	Calothrix sp. PCC 7507	0	0
0	NA	NA	Alphaproteobacteria	Streptomycetales	Comamonadaceae	Rubrivivax	Epizootic haematopoietic necrosis virus	0	0
0	NA	NA	Betaproteobacteria	Xanthomonadales	Promicromonosporaceae	Janthinobacterium	Austwickia chelonae	0	0
0	NA	NA	Bacilli	Oceanospirillales	Microbacteriaceae	Burkholderia	Burkholderia ubonensis	0	0
0	NA	NA	Gammaproteobacteria	Flavobacteriales	Gallionellaceae	Exiguobacterium	Nostoc sp. PCC 7120	0	0
0	NA	NA	Alphaproteobacteria	Rhodospirillales	Burkholderiaceae	Variovorax	Bordetella hinzii	0	0
0	NA	NA	Betaproteobacteria	Sphingomonadales	Opitutaceae	Rubrobacter	Pseudomonas frederiksbergensis	0	0
0	NA	NA	Bacilli	Neisseriales	Pseudomonadaceae	Pseudoalteromonas	Acetobacter tropicalis	0	0
0	NA	NA	Gammaproteobacteria	Rhodocyclales	Dermacoccaceae	Methylovorus	Microbacterium foliorum	0	0
0	NA	NA	Alphaproteobacteria	Campylobacterales	Actinopolysporaceae	Leclercia	Serratia sp. ATCC 39006	0	0
0	NA	NA	Betaproteobacteria	Myxococcales	Neisseriaceae	Pandoraea	Ralstonia mannitolilytica	0	0
0	NA	NA	Bacilli	Oscillatoriales	Enterobacteriaceae	Arsenicicoccus	Frankia casuarinae	0	0
0	NA	NA	Gammaproteobacteria	Nitrosomonadales	Micrococcaceae	Zobellella	Cupriavidus necator	0	0
0	NA	NA	Alphaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Mycobacteroides	Ensifer adhaerens	0	0
0	NA	NA	Betaproteobacteria	Pseudomonadales	Actinomycetaceae	Luteipulveratus	Acinetobacter bereziniae	0	0
0	NA	NA	Bacilli	Burkholderiales	Streptomycetaceae	Auritidibacter	Acinetobacter nosocomialis	0	0
0	NA	NA	Gammaproteobacteria	Micrococcales	Bifidobacteriaceae	Komagataeibacter	Tenacibaculum maritimum	0	0
0	NA	NA	Alphaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Pontimonas	Thioalkalivibrio paradoxus	0	0
0	NA	NA	Betaproteobacteria	Streptomycetales	Comamonadaceae	Actinotignum	Acinetobacter schindleri	0	0
0	NA	NA	Bacilli	Xanthomonadales	Promicromonosporaceae	Mycolicibacterium	Lactobacillus jensenii	0	0
0	NA	NA	Gammaproteobacteria	Oceanospirillales	Microbacteriaceae	Azospirillum	Actinomyces radicidentis	0	0
0	NA	NA	Alphaproteobacteria	Flavobacteriales	Gallionellaceae	Brucella	Leptolyngbya sp. PCC 7376	0	0
0	NA	NA	Betaproteobacteria	Rhodospirillales	Burkholderiaceae	Pseudomonas	Geoglobus ahangari	0	0
0	NA	NA	Bacilli	Sphingomonadales	Opitutaceae	Xanthomonas	Bradyrhizobium sp. ORS 278	0	0
0	NA	NA	Gammaproteobacteria	Neisseriales	Pseudomonadaceae	Rhizobium	Halomonas hydrothermalis	0	0
0	NA	NA	Alphaproteobacteria	Rhodocyclales	Dermacoccaceae	Acinetobacter	Cupriavidus metallidurans	0	0
0	NA	NA	Betaproteobacteria	Campylobacterales	Actinopolysporaceae	Neisseria	Bacillus sonorensis	0	0
0	NA	NA	Bacilli	Myxococcales	Neisseriaceae	Alcaligenes	Sphingobium cloacae	0	0
0	NA	NA	Gammaproteobacteria	Oscillatoriales	Enterobacteriaceae	Chromobacterium	Pseudarthrobacter sulfonivorans	0	0
0	NA	NA	Alphaproteobacteria	Nitrosomonadales	Micrococcaceae	Citrobacter	Pannonibacter phragmitetus	0	0
0	NA	NA	Betaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Enterobacter	Bordetella trematum	0	0
0	NA	NA	Bacilli	Pseudomonadales	Actinomycetaceae	Klebsiella	Thermotoga sp. RQ7	0	0
0	NA	NA	Gammaproteobacteria	Burkholderiales	Streptomycetaceae	Aeromonas	Stenotrophomonas acidaminiphila	0	0
0	NA	NA	Alphaproteobacteria	Micrococcales	Bifidobacteriaceae	Vibrio	Ovine atadenovirus D	0	0
0	NA	NA	Betaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Haemophilus	Culex nigripalpus nucleopolyhedrovirus	0	0
0	NA	NA	Bacilli	Streptomycetales	Comamonadaceae	Aerococcus	Rhodococcus jostii	0	0
0	NA	NA	Gammaproteobacteria	Xanthomonadales	Promicromonosporaceae	Bacillus	Citrobacter youngae	0	0
0	NA	NA	Alphaproteobacteria	Oceanospirillales	Microbacteriaceae	Clavibacter	secondary endosymbiont of Heteropsylla cubana	0	0
0	NA	NA	Betaproteobacteria	Flavobacteriales	Gallionellaceae	Actinomyces	Paraburkholderia caledonica	0	0
0	NA	NA	Bacilli	Rhodospirillales	Burkholderiaceae	Bifidobacterium	Paraburkholderia fungorum	0	0
0	NA	NA	Gammaproteobacteria	Sphingomonadales	Opitutaceae	Corynebacterium	Mycolicibacterium goodii	0	0
0	NA	NA	Alphaproteobacteria	Neisseriales	Pseudomonadaceae	Mycobacterium	Actinoplanes sp. SE50/110	0	0
0	NA	NA	Betaproteobacteria	Rhodocyclales	Dermacoccaceae	Nocardia	Ureaplasma parvum	0	0
0	NA	NA	Bacilli	Campylobacterales	Actinopolysporaceae	Rhodococcus	Nocardia cyriacigeorgica	0	0
0	NA	NA	Gammaproteobacteria	Myxococcales	Neisseriaceae	Pseudonocardia	Roseobacter virus SIO1	0	0
0	NA	NA	Alphaproteobacteria	Oscillatoriales	Enterobacteriaceae	Streptomyces	Corynebacterium testudinoris	0	0
0	NA	NA	Betaproteobacteria	Nitrosomonadales	Micrococcaceae	Marinobacter	Weissella cibaria	0	0
0	NA	NA	Bacilli	Desulfuromonadales	Thermomonosporaceae	Halomonas	Dietzia psychralcaliphila	0	0
0	NA	NA	Gammaproteobacteria	Pseudomonadales	Actinomycetaceae	Begomovirus	Oleiphilus messinensis	0	0
0	NA	NA	Alphaproteobacteria	Burkholderiales	Streptomycetaceae	Magnetospirillum	Rathayibacter toxicus	0	0
0	NA	NA	Betaproteobacteria	Micrococcales	Bifidobacteriaceae	Rubrivivax	Elephantid betaherpesvirus 1	0	0
0	NA	NA	Bacilli	Pseudonocardiales	Xanthomonadaceae	Janthinobacterium	Corynebacterium simulans	0	0
0	NA	NA	Gammaproteobacteria	Streptomycetales	Comamonadaceae	Burkholderia	Salinibacter ruber	0	0
0	NA	NA	Alphaproteobacteria	Xanthomonadales	Promicromonosporaceae	Exiguobacterium	Streptomyces parvulus	0	0
0	NA	NA	Betaproteobacteria	Oceanospirillales	Microbacteriaceae	Variovorax	Paracoccus yeei	0	0
0	NA	NA	Bacilli	Flavobacteriales	Gallionellaceae	Rubrobacter	Vibrio antiquarius	0	0
0	NA	NA	Gammaproteobacteria	Rhodospirillales	Burkholderiaceae	Pseudoalteromonas	Pseudoalteromonas issachenkonii	0	0
0	NA	NA	Alphaproteobacteria	Sphingomonadales	Opitutaceae	Methylovorus	Lactobacillus parabuchneri	0	0
0	NA	NA	Betaproteobacteria	Neisseriales	Pseudomonadaceae	Leclercia	Sphingomonas melonis	0	0
0	NA	NA	Bacilli	Rhodocyclales	Dermacoccaceae	Pandoraea	Nitrosomonas sp. AL212	0	0
0	NA	NA	Gammaproteobacteria	Campylobacterales	Actinopolysporaceae	Arsenicicoccus	Corynebacterium imitans	0	0
0	NA	NA	Alphaproteobacteria	Myxococcales	Neisseriaceae	Zobellella	Pseudomonas cremoricolorata	0	0
0	NA	NA	Betaproteobacteria	Oscillatoriales	Enterobacteriaceae	Mycobacteroides	Novosphingobium resinovorum	0	0
0	NA	NA	Bacilli	Nitrosomonadales	Micrococcaceae	Luteipulveratus	Cedecea neteri	0	0
0	NA	NA	Gammaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Auritidibacter	Leminorella richardii	0	0
0	NA	NA	Alphaproteobacteria	Pseudomonadales	Actinomycetaceae	Komagataeibacter	Megamonas hypermegale	0	0
0	NA	NA	Betaproteobacteria	Burkholderiales	Streptomycetaceae	Pontimonas	Collimonas fungivorans	0	0
0	NA	NA	Bacilli	Micrococcales	Bifidobacteriaceae	Actinotignum	Enterococcus gilvus	0	0
0	NA	NA	Gammaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Mycolicibacterium	Paenibacillus borealis	0	0
0	NA	NA	Alphaproteobacteria	Streptomycetales	Comamonadaceae	Azospirillum	Pseudoalteromonas phenolica	0	0
0	NA	NA	Betaproteobacteria	Xanthomonadales	Promicromonosporaceae	Brucella	Corynebacterium kroppenstedtii	0	0
0	NA	NA	Bacilli	Oceanospirillales	Microbacteriaceae	Pseudomonas	Corynebacterium phocae	0	0
0	NA	NA	Gammaproteobacteria	Flavobacteriales	Gallionellaceae	Xanthomonas	Corynebacterium camporealensis	0	0
0	NA	NA	Alphaproteobacteria	Rhodospirillales	Burkholderiaceae	Rhizobium	Corynebacterium singulare	0	0
0	NA	NA	Betaproteobacteria	Sphingomonadales	Opitutaceae	Acinetobacter	Microbacterium hominis	0	0
0	NA	NA	Bacilli	Neisseriales	Pseudomonadaceae	Neisseria	Virgibacillus necropolis	0	0
0	NA	NA	Gammaproteobacteria	Rhodocyclales	Dermacoccaceae	Alcaligenes	Streptomyces puniciscabiei	0	0
0	NA	NA	Alphaproteobacteria	Campylobacterales	Actinopolysporaceae	Chromobacterium	Blattabacterium punctulatus	0	0
0	NA	NA	Betaproteobacteria	Myxococcales	Neisseriaceae	Citrobacter	Blattabacterium clevelandi	0	0
0	NA	NA	Bacilli	Oscillatoriales	Enterobacteriaceae	Enterobacter	Mycobacterium sp. MCS	0	0
0	NA	NA	Gammaproteobacteria	Nitrosomonadales	Micrococcaceae	Klebsiella	Mycobacterium sp. JLS	0	0
0	NA	NA	Alphaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Aeromonas	Laribacter hongkongensis	0	0
0	NA	NA	Betaproteobacteria	Pseudomonadales	Actinomycetaceae	Vibrio	Paraburkholderia terricola	0	0
0	NA	NA	Bacilli	Burkholderiales	Streptomycetaceae	Haemophilus	Paraburkholderia hospita	0	0
0	NA	NA	Gammaproteobacteria	Micrococcales	Bifidobacteriaceae	Aerococcus	Clostridium saccharobutylicum	0	0
0	NA	NA	Alphaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Bacillus	Pseudomonas virus phiKZ	0	0
0	NA	NA	Betaproteobacteria	Streptomycetales	Comamonadaceae	Clavibacter	Paenibacillus stellifer	0	0
0	NA	NA	Bacilli	Xanthomonadales	Promicromonosporaceae	Actinomyces	Mycoplasma anatis	0	0
0	NA	NA	Gammaproteobacteria	Oceanospirillales	Microbacteriaceae	Bifidobacterium	Elizabethkingia miricola	0	0
0	NA	NA	Alphaproteobacteria	Flavobacteriales	Gallionellaceae	Corynebacterium	Candidatus Kuenenia stuttgartiensis	0	0
0	NA	NA	Betaproteobacteria	Rhodospirillales	Burkholderiaceae	Mycobacterium	Carboxydocella thermautotrophica	0	0
0	NA	NA	Bacilli	Sphingomonadales	Opitutaceae	Nocardia	Delftia tsuruhatensis	0	0
0	NA	NA	Gammaproteobacteria	Neisseriales	Pseudomonadaceae	Rhodococcus	Butyrivibrio hungatei	0	0
0	NA	NA	Alphaproteobacteria	Rhodocyclales	Dermacoccaceae	Pseudonocardia	Sneathia amnii	0	0
0	NA	NA	Betaproteobacteria	Campylobacterales	Actinopolysporaceae	Streptomyces	Corynebacterium glaucum	0	0
0	NA	NA	Bacilli	Myxococcales	Neisseriaceae	Marinobacter	Thalassolituus oleivorans	0	0
0	NA	NA	Gammaproteobacteria	Oscillatoriales	Enterobacteriaceae	Halomonas	Streptomyces koyangensis	0	0
0	NA	NA	Alphaproteobacteria	Nitrosomonadales	Micrococcaceae	Begomovirus	Pedobacter cryoconitis	0	0
0	NA	NA	Betaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Magnetospirillum	Paenibacillus odorifer	0	0
0	NA	NA	Bacilli	Pseudomonadales	Actinomycetaceae	Rubrivivax	Actinobacillus porcitonsillarum	0	0
0	NA	NA	Gammaproteobacteria	Burkholderiales	Streptomycetaceae	Janthinobacterium	Mycobacterium sp. KMS	0	0
0	NA	NA	Alphaproteobacteria	Micrococcales	Bifidobacteriaceae	Burkholderia	Ralstonia insidiosa	0	0
0	NA	NA	Betaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Exiguobacterium	Vibrio coralliilyticus	0	0
0	NA	NA	Bacilli	Streptomycetales	Comamonadaceae	Variovorax	Rhodococcus aetherivorans	0	0
0	NA	NA	Gammaproteobacteria	Xanthomonadales	Promicromonosporaceae	Rubrobacter	Corynebacterium atypicum	0	0
0	NA	NA	Alphaproteobacteria	Oceanospirillales	Microbacteriaceae	Pseudoalteromonas	Erythrobacter flavus	0	0
0	NA	NA	Betaproteobacteria	Flavobacteriales	Gallionellaceae	Methylovorus	Streptomyces niveus	0	0
0	NA	NA	Bacilli	Rhodospirillales	Burkholderiaceae	Leclercia	Sinorhizobium americanum	0	0
0	NA	NA	Gammaproteobacteria	Sphingomonadales	Opitutaceae	Pandoraea	Synechococcus sp. PCC 6312	0	0
0	NA	NA	Alphaproteobacteria	Neisseriales	Pseudomonadaceae	Arsenicicoccus	Synechococcus sp. PCC 7117	0	0
0	NA	NA	Betaproteobacteria	Rhodocyclales	Dermacoccaceae	Zobellella	Aeromonas dhakensis	0	0
0	NA	NA	Bacilli	Campylobacterales	Actinopolysporaceae	Mycobacteroides	Nocardioides sp. JS614	0	0
0	NA	NA	Gammaproteobacteria	Myxococcales	Neisseriaceae	Luteipulveratus	Malacobacter halophilus	0	0
0	NA	NA	Alphaproteobacteria	Oscillatoriales	Enterobacteriaceae	Auritidibacter	Streptococcus pasteurianus	0	0
0	NA	NA	Betaproteobacteria	Nitrosomonadales	Micrococcaceae	Komagataeibacter	Anoxybacillus gonensis	0	0
0	NA	NA	Bacilli	Desulfuromonadales	Thermomonosporaceae	Pontimonas	Pseudomonas koreensis	0	0
0	NA	NA	Gammaproteobacteria	Pseudomonadales	Actinomycetaceae	Actinotignum	Bacillus krulwichiae	0	0
0	NA	NA	Alphaproteobacteria	Burkholderiales	Streptomycetaceae	Mycolicibacterium	Dickeya dadantii	0	0
0	NA	NA	Betaproteobacteria	Micrococcales	Bifidobacteriaceae	Azospirillum	Dickeya zeae	0	0
0	NA	NA	Bacilli	Pseudonocardiales	Xanthomonadaceae	Brucella	Herminiimonas arsenicoxydans	0	0
0	NA	NA	Gammaproteobacteria	Streptomycetales	Comamonadaceae	Pseudomonas	Streptomyces sp. FR-008	0	0
0	NA	NA	Alphaproteobacteria	Xanthomonadales	Promicromonosporaceae	Xanthomonas	Kosakonia cowanii	0	0
0	NA	NA	Betaproteobacteria	Oceanospirillales	Microbacteriaceae	Rhizobium	Amycolatopsis japonica	0	0
0	NA	NA	Bacilli	Flavobacteriales	Gallionellaceae	Acinetobacter	[Clostridium] bolteae	0	0
0	NA	NA	Gammaproteobacteria	Rhodospirillales	Burkholderiaceae	Neisseria	Carnobacterium sp. 17-4	0	0
0	NA	NA	Alphaproteobacteria	Sphingomonadales	Opitutaceae	Alcaligenes	Escherichia albertii	0	0
0	NA	NA	Betaproteobacteria	Neisseriales	Pseudomonadaceae	Chromobacterium	Capnocytophaga sp. ChDC OS43	0	0
0	NA	NA	Bacilli	Rhodocyclales	Dermacoccaceae	Citrobacter	Acanthamoeba polyphaga mimivirus	0	0
0	NA	NA	Gammaproteobacteria	Campylobacterales	Actinopolysporaceae	Enterobacter	Mycobacterium sp. JS623	0	0
0	NA	NA	Alphaproteobacteria	Myxococcales	Neisseriaceae	Klebsiella	Halomonas campaniensis	0	0
0	NA	NA	Betaproteobacteria	Oscillatoriales	Enterobacteriaceae	Aeromonas	Staphylococcus nepalensis	0	0
0	NA	NA	Bacilli	Nitrosomonadales	Micrococcaceae	Vibrio	Entomoplasma luminosum	0	0
0	NA	NA	Gammaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Haemophilus	Entomoplasma somnilux	0	0
0	NA	NA	Alphaproteobacteria	Pseudomonadales	Actinomycetaceae	Aerococcus	Roseovarius mucosus	0	0
0	NA	NA	Betaproteobacteria	Burkholderiales	Streptomycetaceae	Bacillus	Pseudomonas rhizosphaerae	0	0
0	NA	NA	Bacilli	Micrococcales	Bifidobacteriaceae	Clavibacter	Bifidobacterium longum	0	0
0	NA	NA	Gammaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Actinomyces	Spiroplasma alleghenense	0	0
0	NA	NA	Alphaproteobacteria	Streptomycetales	Comamonadaceae	Bifidobacterium	Spiroplasma corruscae	0	0
0	NA	NA	Betaproteobacteria	Xanthomonadales	Promicromonosporaceae	Corynebacterium	Spiroplasma floricola	0	0
0	NA	NA	Bacilli	Oceanospirillales	Microbacteriaceae	Mycobacterium	Spiroplasma litorale	0	0
0	NA	NA	Gammaproteobacteria	Flavobacteriales	Gallionellaceae	Nocardia	Spiroplasma turonicum	0	0
0	NA	NA	Alphaproteobacteria	Rhodospirillales	Burkholderiaceae	Rhodococcus	Achromobacter spanius	0	0
0	NA	NA	Betaproteobacteria	Sphingomonadales	Opitutaceae	Pseudonocardia	Achromobacter insolitus	0	0
0	NA	NA	Bacilli	Neisseriales	Pseudomonadaceae	Streptomyces	Pseudomonas antarctica	0	0
0	NA	NA	Gammaproteobacteria	Rhodocyclales	Dermacoccaceae	Marinobacter	Treponema putidum	0	0
0	NA	NA	Alphaproteobacteria	Campylobacterales	Actinopolysporaceae	Halomonas	Helicobacter sp. MIT 01-6242	0	0
0	NA	NA	Betaproteobacteria	Myxococcales	Neisseriaceae	Begomovirus	Mycobacterium chimaera	0	0
0	NA	NA	Bacilli	Oscillatoriales	Enterobacteriaceae	Magnetospirillum	Methanobrevibacter sp. AbM4	0	0
0	NA	NA	Gammaproteobacteria	Nitrosomonadales	Micrococcaceae	Rubrivivax	Comamonas kerstersii	0	0
0	NA	NA	Alphaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Janthinobacterium	Mesoplasma syrphidae	0	0
0	NA	NA	Betaproteobacteria	Pseudomonadales	Actinomycetaceae	Burkholderia	Methanobrevibacter millerae	0	0
0	NA	NA	Bacilli	Burkholderiales	Streptomycetaceae	Exiguobacterium	Alteromonas stellipolaris	0	0
0	NA	NA	Gammaproteobacteria	Micrococcales	Bifidobacteriaceae	Variovorax	Pseudoalteromonas sp. SM9913	0	0
0	NA	NA	Alphaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Rubrobacter	Pseudomonas alkylphenolica	0	0
0	NA	NA	Betaproteobacteria	Streptomycetales	Comamonadaceae	Pseudoalteromonas	Pseudomonas psychrotolerans	0	0
0	NA	NA	Bacilli	Xanthomonadales	Promicromonosporaceae	Methylovorus	Akkermansia muciniphila	0	0
0	NA	NA	Gammaproteobacteria	Oceanospirillales	Microbacteriaceae	Leclercia	Rummeliibacillus stabekisii	0	0
0	NA	NA	Alphaproteobacteria	Flavobacteriales	Gallionellaceae	Pandoraea	endosymbiont 'TC1' of Trimyema compressum	0	0
0	NA	NA	Betaproteobacteria	Rhodospirillales	Burkholderiaceae	Arsenicicoccus	Klebsiella variicola	0	0
0	NA	NA	Bacilli	Sphingomonadales	Opitutaceae	Zobellella	Wolbachia endosymbiont of Cimex lectularius	0	0
0	NA	NA	Gammaproteobacteria	Neisseriales	Pseudomonadaceae	Mycobacteroides	Staphylococcus equorum	0	0
0	NA	NA	Alphaproteobacteria	Rhodocyclales	Dermacoccaceae	Luteipulveratus	Pseudoalteromonas aliena	0	0
0	NA	NA	Betaproteobacteria	Campylobacterales	Actinopolysporaceae	Auritidibacter	Neodiprion lecontei nucleopolyhedrovirus	0	0
0	NA	NA	Bacilli	Myxococcales	Neisseriaceae	Komagataeibacter	Haemophilus pittmaniae	0	0
0	NA	NA	Gammaproteobacteria	Oscillatoriales	Enterobacteriaceae	Pontimonas	Fictibacillus arsenicus	0	0
0	NA	NA	Alphaproteobacteria	Nitrosomonadales	Micrococcaceae	Actinotignum	Roseomonas gilardii	0	0
0	NA	NA	Betaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Mycolicibacterium	Shewanella marisflavi	0	0
0	NA	NA	Bacilli	Pseudomonadales	Actinomycetaceae	Azospirillum	Psychrobacter alimentarius	0	0
0	NA	NA	Gammaproteobacteria	Burkholderiales	Streptomycetaceae	Brucella	Nitrosomonas sp. Is79A3	0	0
0	NA	NA	Alphaproteobacteria	Micrococcales	Bifidobacteriaceae	Pseudomonas	Lysobacter gummosus	0	0
0	NA	NA	Betaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Xanthomonas	Yersinia aleksiciae	0	0
0	NA	NA	Bacilli	Streptomycetales	Comamonadaceae	Rhizobium	Bacillus muralis	0	0
0	NA	NA	Gammaproteobacteria	Xanthomonadales	Promicromonosporaceae	Acinetobacter	[Pseudomonas] mesoacidophila	0	0
0	NA	NA	Alphaproteobacteria	Oceanospirillales	Microbacteriaceae	Neisseria	Chelativorans sp. BNC1	0	0
0	NA	NA	Betaproteobacteria	Flavobacteriales	Gallionellaceae	Alcaligenes	Sphingorhabdus flavimaris	0	0
0	NA	NA	Bacilli	Rhodospirillales	Burkholderiaceae	Chromobacterium	Erythrobacter seohaensis	0	0
0	NA	NA	Gammaproteobacteria	Sphingomonadales	Opitutaceae	Citrobacter	Methylobacterium aquaticum	0	0
0	NA	NA	Alphaproteobacteria	Neisseriales	Pseudomonadaceae	Enterobacter	Ochrobactrum sp. A44	0	0
0	NA	NA	Betaproteobacteria	Rhodocyclales	Dermacoccaceae	Klebsiella	Mesorhizobium sp. WSM1497	0	0
0	NA	NA	Bacilli	Campylobacterales	Actinopolysporaceae	Aeromonas	Collimonas pratensis	0	0
0	NA	NA	Gammaproteobacteria	Myxococcales	Neisseriaceae	Vibrio	Microcella alkaliphila	0	0
0	NA	NA	Alphaproteobacteria	Oscillatoriales	Enterobacteriaceae	Haemophilus	Prosthecochloris sp. GSB1	0	0
0	NA	NA	Betaproteobacteria	Nitrosomonadales	Micrococcaceae	Aerococcus	Pseudoalteromonas sp. Bsw20308	0	0
0	NA	NA	Bacilli	Desulfuromonadales	Thermomonosporaceae	Bacillus	Sulfolobus virus STSV1	0	0
0	NA	NA	Gammaproteobacteria	Pseudomonadales	Actinomycetaceae	Clavibacter	Streptomyces rubrolavendulae	0	0
0	NA	NA	Alphaproteobacteria	Burkholderiales	Streptomycetaceae	Actinomyces	Bradyrhizobium sp. BTAi1	0	0
0	NA	NA	Betaproteobacteria	Micrococcales	Bifidobacteriaceae	Bifidobacterium	Beggiatoa leptomitoformis	0	0
0	NA	NA	Bacilli	Pseudonocardiales	Xanthomonadaceae	Corynebacterium	Arthrobacter sp. FB24	0	0
0	NA	NA	Gammaproteobacteria	Streptomycetales	Comamonadaceae	Mycobacterium	Jannaschia sp. CCS1	0	0
0	NA	NA	Alphaproteobacteria	Xanthomonadales	Promicromonosporaceae	Nocardia	Photorhabdus asymbiotica	0	0
0	NA	NA	Betaproteobacteria	Oceanospirillales	Microbacteriaceae	Rhodococcus	Bacillus altitudinis	0	0
0	NA	NA	Bacilli	Flavobacteriales	Gallionellaceae	Pseudonocardia	Methanobrevibacter olleyae	0	0
0	NA	NA	Gammaproteobacteria	Rhodospirillales	Burkholderiaceae	Streptomyces	Anoxybacillus amylolyticus	0	0
0	NA	NA	Alphaproteobacteria	Sphingomonadales	Opitutaceae	Marinobacter	Polaromonas sp. JS666	0	0
0	NA	NA	Betaproteobacteria	Neisseriales	Pseudomonadaceae	Halomonas	Frankia sp. EAN1pec	0	0
0	NA	NA	Bacilli	Rhodocyclales	Dermacoccaceae	Begomovirus	Frankia inefficax	0	0
0	NA	NA	Gammaproteobacteria	Campylobacterales	Actinopolysporaceae	Magnetospirillum	Pseudoalteromonas spongiae	0	0
0	NA	NA	Alphaproteobacteria	Myxococcales	Neisseriaceae	Rubrivivax	Tateyamaria omphalii	0	0
0	NA	NA	Betaproteobacteria	Oscillatoriales	Enterobacteriaceae	Janthinobacterium	Enterobacter ludwigii	0	0
0	NA	NA	Bacilli	Nitrosomonadales	Micrococcaceae	Burkholderia	Microbacterium paludicola	0	0
0	NA	NA	Gammaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Exiguobacterium	Staphylococcus simiae	0	0
0	NA	NA	Alphaproteobacteria	Pseudomonadales	Actinomycetaceae	Variovorax	Rhodovulum sp. MB263	0	0
0	NA	NA	Betaproteobacteria	Burkholderiales	Streptomycetaceae	Rubrobacter	Dokdonia sp. MED134	0	0
0	NA	NA	Bacilli	Micrococcales	Bifidobacteriaceae	Pseudoalteromonas	Polaribacter sp. MED152	0	0
0	NA	NA	Gammaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Methylovorus	Alteromonas mediterranea	0	0
0	NA	NA	Alphaproteobacteria	Streptomycetales	Comamonadaceae	Leclercia	Pseudoalteromonas tunicata	0	0
0	NA	NA	Betaproteobacteria	Xanthomonadales	Promicromonosporaceae	Pandoraea	Psychromonas sp. CNPT3	0	0
0	NA	NA	Bacilli	Oceanospirillales	Microbacteriaceae	Arsenicicoccus	Pseudoxanthomonas suwonensis	0	0
0	NA	NA	Gammaproteobacteria	Flavobacteriales	Gallionellaceae	Zobellella	Streptococcus gallolyticus	0	0
0	NA	NA	Alphaproteobacteria	Rhodospirillales	Burkholderiaceae	Mycobacteroides	Nostoc sp. PCC 7107	0	0
0	NA	NA	Betaproteobacteria	Sphingomonadales	Opitutaceae	Luteipulveratus	Gluconobacter albidus	0	0
0	NA	NA	Bacilli	Neisseriales	Pseudomonadaceae	Auritidibacter	Nonlabens sediminis	0	0
0	NA	NA	Gammaproteobacteria	Rhodocyclales	Dermacoccaceae	Komagataeibacter	Cyclobacterium amurskyense	0	0
0	NA	NA	Alphaproteobacteria	Campylobacterales	Actinopolysporaceae	Pontimonas	Dokdonella koreensis	0	0
0	NA	NA	Betaproteobacteria	Myxococcales	Neisseriaceae	Actinotignum	Pontibacter actiniarum	0	0
0	NA	NA	Bacilli	Oscillatoriales	Enterobacteriaceae	Mycolicibacterium	Paenibacillus sp. JDR-2	0	0
0	NA	NA	Gammaproteobacteria	Nitrosomonadales	Micrococcaceae	Azospirillum	Mesoplasma coleopterae	0	0
0	NA	NA	Alphaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Brucella	Neisseria zoodegmatis	0	0
0	NA	NA	Betaproteobacteria	Pseudomonadales	Actinomycetaceae	Pseudomonas	Nitrospira defluvii	0	0
0	NA	NA	Bacilli	Burkholderiales	Streptomycetaceae	Xanthomonas	Psychrobacter cryohalolentis	0	0
0	NA	NA	Gammaproteobacteria	Micrococcales	Bifidobacteriaceae	Rhizobium	Clostridium drakei	0	0
0	NA	NA	Alphaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Acinetobacter	Aquitalea magnusonii	0	0
0	NA	NA	Betaproteobacteria	Streptomycetales	Comamonadaceae	Neisseria	Providencia heimbachae	0	0
0	NA	NA	Bacilli	Xanthomonadales	Promicromonosporaceae	Alcaligenes	Rhodococcus qingshengii	0	0
0	NA	NA	Gammaproteobacteria	Oceanospirillales	Microbacteriaceae	Chromobacterium	Bradyrhizobium sp. S23321	0	0
0	NA	NA	Alphaproteobacteria	Flavobacteriales	Gallionellaceae	Citrobacter	Candidatus Sulcia muelleri	0	0
0	NA	NA	Betaproteobacteria	Rhodospirillales	Burkholderiaceae	Enterobacter	Gordonia sp. KTR9	0	0
0	NA	NA	Bacilli	Sphingomonadales	Opitutaceae	Klebsiella	Burkholderia oklahomensis	0	0
0	NA	NA	Gammaproteobacteria	Neisseriales	Pseudomonadaceae	Aeromonas	Invertebrate iridescent virus 22	0	0
0	NA	NA	Alphaproteobacteria	Rhodocyclales	Dermacoccaceae	Vibrio	Invertebrate iridescent virus 30	0	0
0	NA	NA	Betaproteobacteria	Campylobacterales	Actinopolysporaceae	Haemophilus	Psychrobacter sp. PRwf-1	0	0
0	NA	NA	Bacilli	Myxococcales	Neisseriaceae	Aerococcus	Acidovorax sp. KKS102	0	0
0	NA	NA	Gammaproteobacteria	Oscillatoriales	Enterobacteriaceae	Bacillus	Pedobacter ginsengisoli	0	0
0	NA	NA	Alphaproteobacteria	Nitrosomonadales	Micrococcaceae	Clavibacter	Granulibacter bethesdensis	0	0
0	NA	NA	Betaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Actinomyces	Sulfurospirillum cavolei	0	0
0	NA	NA	Bacilli	Pseudomonadales	Actinomycetaceae	Bifidobacterium	Caulobacter sp. K31	0	0
0	NA	NA	Gammaproteobacteria	Burkholderiales	Streptomycetaceae	Corynebacterium	Cupriavidus sp. USMAA1020	0	0
0	NA	NA	Alphaproteobacteria	Micrococcales	Bifidobacteriaceae	Mycobacterium	Rivularia sp. PCC 7116	0	0
0	NA	NA	Betaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Nocardia	Lactobacillus backii	0	0
0	NA	NA	Bacilli	Streptomycetales	Comamonadaceae	Rhodococcus	Halotalea alkalilenta	0	0
0	NA	NA	Gammaproteobacteria	Xanthomonadales	Promicromonosporaceae	Pseudonocardia	Pseudomonas protegens	0	0
0	NA	NA	Alphaproteobacteria	Oceanospirillales	Microbacteriaceae	Streptomyces	Hydrogenobaculum sp. Y04AAS1	0	0
0	NA	NA	Betaproteobacteria	Flavobacteriales	Gallionellaceae	Marinobacter	Cycloclasticus sp. P1	0	0
0	NA	NA	Bacilli	Rhodospirillales	Burkholderiaceae	Halomonas	Moraxella bovoculi	0	0
0	NA	NA	Gammaproteobacteria	Sphingomonadales	Opitutaceae	Begomovirus	Nitratiruptor sp. SB155-2	0	0
0	NA	NA	Alphaproteobacteria	Neisseriales	Pseudomonadaceae	Magnetospirillum	Sulfurovum sp. NBC37-1	0	0
0	NA	NA	Betaproteobacteria	Rhodocyclales	Dermacoccaceae	Rubrivivax	Candidatus Protochlamydia naegleriophila	0	0
0	NA	NA	Bacilli	Campylobacterales	Actinopolysporaceae	Janthinobacterium	Lactobacillus crustorum	0	0
0	NA	NA	Gammaproteobacteria	Myxococcales	Neisseriaceae	Burkholderia	Clostridium taeniosporum	0	0
0	NA	NA	Alphaproteobacteria	Oscillatoriales	Enterobacteriaceae	Exiguobacterium	Cyanothece sp. PCC 8802	0	0
0	NA	NA	Betaproteobacteria	Nitrosomonadales	Micrococcaceae	Variovorax	Thioalkalivibrio sp. K90mix	0	0
0	NA	NA	Bacilli	Desulfuromonadales	Thermomonosporaceae	Rubrobacter	Tessaracoccus flavescens	0	0
0	NA	NA	Gammaproteobacteria	Pseudomonadales	Actinomycetaceae	Pseudoalteromonas	Thermoanaerobacter sp. X514	0	0
0	NA	NA	Alphaproteobacteria	Burkholderiales	Streptomycetaceae	Methylovorus	Enterobacter sp. 638	0	0
0	NA	NA	Betaproteobacteria	Micrococcales	Bifidobacteriaceae	Leclercia	Pontibacter korlensis	0	0
0	NA	NA	Bacilli	Pseudonocardiales	Xanthomonadaceae	Pandoraea	Marinomonas sp. MWYL1	0	0
0	NA	NA	Gammaproteobacteria	Streptomycetales	Comamonadaceae	Arsenicicoccus	Corynebacterium ureicelerivorans	0	0
0	NA	NA	Alphaproteobacteria	Xanthomonadales	Promicromonosporaceae	Zobellella	Halobacillus mangrovi	0	0
0	NA	NA	Betaproteobacteria	Oceanospirillales	Microbacteriaceae	Mycobacteroides	Virgibacillus sp. SK37	0	0
0	NA	NA	Bacilli	Flavobacteriales	Gallionellaceae	Luteipulveratus	Anaeromyxobacter sp. Fw109-5	0	0
0	NA	NA	Gammaproteobacteria	Rhodospirillales	Burkholderiaceae	Auritidibacter	Natrinema sp. J7-2	0	0
0	NA	NA	Alphaproteobacteria	Sphingomonadales	Opitutaceae	Komagataeibacter	Sphingobium sp. MI1205	0	0
0	NA	NA	Betaproteobacteria	Neisseriales	Pseudomonadaceae	Pontimonas	Streptomyces xiamenensis	0	0
0	NA	NA	Bacilli	Rhodocyclales	Dermacoccaceae	Actinotignum	Bacillus aryabhattai	0	0
0	NA	NA	Gammaproteobacteria	Campylobacterales	Actinopolysporaceae	Mycolicibacterium	Cronobacter muytjensii	0	0
0	NA	NA	Alphaproteobacteria	Myxococcales	Neisseriaceae	Azospirillum	Cronobacter malonaticus	0	0
0	NA	NA	Betaproteobacteria	Oscillatoriales	Enterobacteriaceae	Brucella	[Polyangium] brachysporum	0	0
0	NA	NA	Bacilli	Nitrosomonadales	Micrococcaceae	Pseudomonas	Actinopolyspora erythraea	0	0
0	NA	NA	Gammaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Xanthomonas	Burkholderia sp. KJ006	0	0
0	NA	NA	Alphaproteobacteria	Pseudomonadales	Actinomycetaceae	Rhizobium	Enterococcus thailandicus	0	0
0	NA	NA	Betaproteobacteria	Burkholderiales	Streptomycetaceae	Acinetobacter	Azoarcus olearius	0	0
0	NA	NA	Bacilli	Micrococcales	Bifidobacteriaceae	Neisseria	Ochrobactrum pseudogrignonense	0	0
0	NA	NA	Gammaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Alcaligenes	Methylobacterium sp. 4-46	0	0
0	NA	NA	Alphaproteobacteria	Streptomycetales	Comamonadaceae	Chromobacterium	Lysobacter capsici	0	0
0	NA	NA	Betaproteobacteria	Xanthomonadales	Promicromonosporaceae	Citrobacter	Variovorax boronicumulans	0	0
0	NA	NA	Bacilli	Oceanospirillales	Microbacteriaceae	Enterobacter	Rhodobaca barguzinensis	0	0
0	NA	NA	Gammaproteobacteria	Flavobacteriales	Gallionellaceae	Klebsiella	Streptomyces sp. CNQ-509	0	0
0	NA	NA	Alphaproteobacteria	Rhodospirillales	Burkholderiaceae	Aeromonas	Pseudonocardia sp. AL041005-10	0	0
0	NA	NA	Betaproteobacteria	Sphingomonadales	Opitutaceae	Vibrio	Acetobacter senegalensis	0	0
0	NA	NA	Bacilli	Neisseriales	Pseudomonadaceae	Haemophilus	Kocuria flava	0	0
0	NA	NA	Gammaproteobacteria	Rhodocyclales	Dermacoccaceae	Aerococcus	Anaeromyxobacter sp. K	0	0
0	NA	NA	Alphaproteobacteria	Campylobacterales	Actinopolysporaceae	Bacillus	Agromyces aureus	0	0
0	NA	NA	Betaproteobacteria	Myxococcales	Neisseriaceae	Clavibacter	Chrysochromulina ericina virus	0	0
0	NA	NA	Bacilli	Oscillatoriales	Enterobacteriaceae	Actinomyces	Nocardia terpenica	0	0
0	NA	NA	Gammaproteobacteria	Nitrosomonadales	Micrococcaceae	Bifidobacterium	Bordetella flabilis	0	0
0	NA	NA	Alphaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Corynebacterium	Bordetella genomosp. 6	0	0
0	NA	NA	Betaproteobacteria	Pseudomonadales	Actinomycetaceae	Mycobacterium	Bordetella bronchialis	0	0
0	NA	NA	Bacilli	Burkholderiales	Streptomycetaceae	Nocardia	Bordetella genomosp. 13	0	0
0	NA	NA	Gammaproteobacteria	Micrococcales	Bifidobacteriaceae	Rhodococcus	Streptomyces sp. Mg1	0	0
0	NA	NA	Alphaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Pseudonocardia	Steroidobacter denitrificans	0	0
0	NA	NA	Betaproteobacteria	Streptomycetales	Comamonadaceae	Streptomyces	Pantoea vagans	0	0
0	NA	NA	Bacilli	Xanthomonadales	Promicromonosporaceae	Marinobacter	Geobacillus sp. WCH70	0	0
0	NA	NA	Gammaproteobacteria	Oceanospirillales	Microbacteriaceae	Halomonas	Devriesea agamarum	0	0
0	NA	NA	Alphaproteobacteria	Flavobacteriales	Gallionellaceae	Begomovirus	Halomonas beimenensis	0	0
0	NA	NA	Betaproteobacteria	Rhodospirillales	Burkholderiaceae	Magnetospirillum	Modestobacter marinus	0	0
0	NA	NA	Bacilli	Sphingomonadales	Opitutaceae	Rubrivivax	Myroides profundi	0	0
0	NA	NA	Gammaproteobacteria	Neisseriales	Pseudomonadaceae	Janthinobacterium	Mycobacterium dioxanotrophicus	0	0
0	NA	NA	Alphaproteobacteria	Rhodocyclales	Dermacoccaceae	Burkholderia	Burkholderia lata	0	0
0	NA	NA	Betaproteobacteria	Campylobacterales	Actinopolysporaceae	Exiguobacterium	Geoalkalibacter subterraneus	0	0
0	NA	NA	Bacilli	Myxococcales	Neisseriaceae	Variovorax	Pelosinus sp. UFO1	0	0
0	NA	NA	Gammaproteobacteria	Oscillatoriales	Enterobacteriaceae	Rubrobacter	Acinetobacter soli	0	0
0	NA	NA	Alphaproteobacteria	Nitrosomonadales	Micrococcaceae	Pseudoalteromonas	Burkholderia latens	0	0
0	NA	NA	Betaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Methylovorus	Burkholderia contaminans	0	0
0	NA	NA	Bacilli	Pseudomonadales	Actinomycetaceae	Leclercia	Burkholderia seminalis	0	0
0	NA	NA	Gammaproteobacteria	Burkholderiales	Streptomycetaceae	Pandoraea	Burkholderia diffusa	0	0
0	NA	NA	Alphaproteobacteria	Micrococcales	Bifidobacteriaceae	Arsenicicoccus	Helicoverpa armigera granulovirus	0	0
0	NA	NA	Betaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Zobellella	Bacillus velezensis	0	0
0	NA	NA	Bacilli	Streptomycetales	Comamonadaceae	Mycobacteroides	Kosakonia oryzae	0	0
0	NA	NA	Gammaproteobacteria	Xanthomonadales	Promicromonosporaceae	Luteipulveratus	Cyanothece sp. PCC 7822	0	0
0	NA	NA	Alphaproteobacteria	Oceanospirillales	Microbacteriaceae	Auritidibacter	Dietzia timorensis	0	0
0	NA	NA	Betaproteobacteria	Flavobacteriales	Gallionellaceae	Komagataeibacter	Malacobacter marinus	0	0
0	NA	NA	Bacilli	Rhodospirillales	Burkholderiaceae	Pontimonas	Oceanimonas sp. GK1	0	0
0	NA	NA	Gammaproteobacteria	Sphingomonadales	Opitutaceae	Actinotignum	Candidatus Azobacteroides pseudotrichonymphae	0	0
0	NA	NA	Alphaproteobacteria	Neisseriales	Pseudomonadaceae	Mycolicibacterium	Rufibacter tibetensis	0	0
0	NA	NA	Betaproteobacteria	Rhodocyclales	Dermacoccaceae	Azospirillum	Vagococcus teuberi	0	0
0	NA	NA	Bacilli	Campylobacterales	Actinopolysporaceae	Brucella	Paenibacillus xylanexedens	0	0
0	NA	NA	Gammaproteobacteria	Myxococcales	Neisseriaceae	Pseudomonas	Azospirillum thiophilum	0	0
0	NA	NA	Alphaproteobacteria	Oscillatoriales	Enterobacteriaceae	Xanthomonas	Prauserella marina	0	0
0	NA	NA	Betaproteobacteria	Nitrosomonadales	Micrococcaceae	Rhizobium	Flavobacteriaceae bacterium 3519-10	0	0
0	NA	NA	Bacilli	Desulfuromonadales	Thermomonosporaceae	Acinetobacter	Altererythrobacter marensis	0	0
0	NA	NA	Gammaproteobacteria	Pseudomonadales	Actinomycetaceae	Neisseria	Geobacillus sp. Y412MC61	0	0
0	NA	NA	Alphaproteobacteria	Burkholderiales	Streptomycetaceae	Alcaligenes	Dietzia lutea	0	0
0	NA	NA	Betaproteobacteria	Micrococcales	Bifidobacteriaceae	Chromobacterium	Francisella halioticida	0	0
0	NA	NA	Bacilli	Pseudonocardiales	Xanthomonadaceae	Citrobacter	Geobacillus sp. Y412MC52	0	0
0	NA	NA	Gammaproteobacteria	Streptomycetales	Comamonadaceae	Enterobacter	Leptopilina boulardi filamentous virus	0	0
0	NA	NA	Alphaproteobacteria	Xanthomonadales	Promicromonosporaceae	Klebsiella	Streptomyces gilvosporeus	0	0
0	NA	NA	Betaproteobacteria	Oceanospirillales	Microbacteriaceae	Aeromonas	Acidovorax carolinensis	0	0
0	NA	NA	Bacilli	Flavobacteriales	Gallionellaceae	Vibrio	Brachybacterium saurashtrense	0	0
0	NA	NA	Gammaproteobacteria	Rhodospirillales	Burkholderiaceae	Haemophilus	Chryseobacterium piperi	0	0
0	NA	NA	Alphaproteobacteria	Sphingomonadales	Opitutaceae	Aerococcus	Aeromonas aquatica	0	0
0	NA	NA	Betaproteobacteria	Neisseriales	Pseudomonadaceae	Bacillus	Bacillus safensis	0	0
0	NA	NA	Bacilli	Rhodocyclales	Dermacoccaceae	Clavibacter	Streptomyces sp. SM17	0	0
0	NA	NA	Gammaproteobacteria	Campylobacterales	Actinopolysporaceae	Actinomyces	Ochrobactrum pituitosum	0	0
0	NA	NA	Alphaproteobacteria	Myxococcales	Neisseriaceae	Bifidobacterium	Luteipulveratus mongoliensis	0	0
0	NA	NA	Betaproteobacteria	Oscillatoriales	Enterobacteriaceae	Corynebacterium	Corynebacterium mustelae	0	0
0	NA	NA	Bacilli	Nitrosomonadales	Micrococcaceae	Mycobacterium	Thermoanaerobacter sp. X513	0	0
0	NA	NA	Gammaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Nocardia	Francisella sp. TX077308	0	0
0	NA	NA	Alphaproteobacteria	Pseudomonadales	Actinomycetaceae	Rhodococcus	Pandoraea oxalativorans	0	0
0	NA	NA	Betaproteobacteria	Burkholderiales	Streptomycetaceae	Pseudonocardia	Polynucleobacter necessarius	0	0
0	NA	NA	Bacilli	Micrococcales	Bifidobacteriaceae	Streptomyces	Bacillus cytotoxicus	0	0
0	NA	NA	Gammaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Marinobacter	Geobacillus sp. Y4.1MC1	0	0
0	NA	NA	Alphaproteobacteria	Streptomycetales	Comamonadaceae	Halomonas	Tenacibaculum jejuense	0	0
0	NA	NA	Betaproteobacteria	Xanthomonadales	Promicromonosporaceae	Begomovirus	Thiohalobacter thiocyanaticus	0	0
0	NA	NA	Bacilli	Oceanospirillales	Microbacteriaceae	Magnetospirillum	Terribacillus aidingensis	0	0
0	NA	NA	Gammaproteobacteria	Flavobacteriales	Gallionellaceae	Rubrivivax	Pseudomonas chlororaphis	0	0
0	NA	NA	Alphaproteobacteria	Rhodospirillales	Burkholderiaceae	Janthinobacterium	Haloterrigena daqingensis	0	0
0	NA	NA	Betaproteobacteria	Sphingomonadales	Opitutaceae	Burkholderia	Brevundimonas naejangsanensis	0	0
0	NA	NA	Bacilli	Neisseriales	Pseudomonadaceae	Exiguobacterium	Alteromonas australica	0	0
0	NA	NA	Gammaproteobacteria	Rhodocyclales	Dermacoccaceae	Variovorax	Pantoea sp. At-9b	0	0
0	NA	NA	Alphaproteobacteria	Campylobacterales	Actinopolysporaceae	Rubrobacter	Arenibacter algicola	0	0
0	NA	NA	Betaproteobacteria	Myxococcales	Neisseriaceae	Pseudoalteromonas	Sphingobium sp. SYK-6	0	0
0	NA	NA	Bacilli	Oscillatoriales	Enterobacteriaceae	Methylovorus	Desulfovibrio sp. G11	0	0
0	NA	NA	Gammaproteobacteria	Nitrosomonadales	Micrococcaceae	Leclercia	Bacillus beveridgei	0	0
0	NA	NA	Alphaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Pandoraea	Vagococcus penaei	0	0
0	NA	NA	Betaproteobacteria	Pseudomonadales	Actinomycetaceae	Arsenicicoccus	Candidatus Arsenophonus lipoptenae	0	0
0	NA	NA	Bacilli	Burkholderiales	Streptomycetaceae	Zobellella	Short-finned eel ranavirus	0	0
0	NA	NA	Gammaproteobacteria	Micrococcales	Bifidobacteriaceae	Mycobacteroides	Burkholderia sp. CCGE1001	0	0
0	NA	NA	Alphaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Luteipulveratus	Burkholderia sp. CCGE1003	0	0
0	NA	NA	Betaproteobacteria	Streptomycetales	Comamonadaceae	Auritidibacter	Staphylococcus stepanovicii	0	0
0	NA	NA	Bacilli	Xanthomonadales	Promicromonosporaceae	Komagataeibacter	Paenalcaligenes hominis	0	0
0	NA	NA	Gammaproteobacteria	Oceanospirillales	Microbacteriaceae	Pontimonas	Methanocaldococcus sp. FS406-22	0	0
0	NA	NA	Alphaproteobacteria	Flavobacteriales	Gallionellaceae	Actinotignum	Micromonospora sp. L5	0	0
0	NA	NA	Betaproteobacteria	Rhodospirillales	Burkholderiaceae	Mycolicibacterium	Actinoplanes sp. N902-109	0	0
0	NA	NA	Bacilli	Sphingomonadales	Opitutaceae	Azospirillum	Neisseria sp. KEM232	0	0
0	NA	NA	Gammaproteobacteria	Neisseriales	Pseudomonadaceae	Brucella	Frankia symbiont of Datisca glomerata	0	0
0	NA	NA	Alphaproteobacteria	Rhodocyclales	Dermacoccaceae	Pseudomonas	Pandoraea vervacti	0	0
0	NA	NA	Betaproteobacteria	Campylobacterales	Actinopolysporaceae	Xanthomonas	Pandoraea faecigallinarum	0	0
0	NA	NA	Bacilli	Myxococcales	Neisseriaceae	Rhizobium	Halanaerobium hydrogeniformans	0	0
0	NA	NA	Gammaproteobacteria	Oscillatoriales	Enterobacteriaceae	Acinetobacter	Francisella noatunensis	0	0
0	NA	NA	Alphaproteobacteria	Nitrosomonadales	Micrococcaceae	Neisseria	Haloarcobacter bivalviorum	0	0
0	NA	NA	Betaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Alcaligenes	Azospirillum sp. TSH58	0	0
0	NA	NA	Bacilli	Pseudomonadales	Actinomycetaceae	Chromobacterium	Pantoea gaviniae	0	0
0	NA	NA	Gammaproteobacteria	Burkholderiales	Streptomycetaceae	Citrobacter	Rhodanobacter denitrificans	0	0
0	NA	NA	Alphaproteobacteria	Micrococcales	Bifidobacteriaceae	Enterobacter	Bacillus sp. 1NLA3E	0	0
0	NA	NA	Betaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Klebsiella	Tenacibaculum dicentrarchi	0	0
0	NA	NA	Bacilli	Streptomycetales	Comamonadaceae	Aeromonas	Cryobacterium arcticum	0	0
0	NA	NA	Gammaproteobacteria	Xanthomonadales	Promicromonosporaceae	Vibrio	Serratia sp. FGI94	0	0
0	NA	NA	Alphaproteobacteria	Oceanospirillales	Microbacteriaceae	Haemophilus	Vibrio casei	0	0
0	NA	NA	Betaproteobacteria	Flavobacteriales	Gallionellaceae	Aerococcus	Candidatus Babela massiliensis	0	0
0	NA	NA	Bacilli	Rhodospirillales	Burkholderiaceae	Bacillus	Rhodoplanes sp. Z2-YC6860	0	0
0	NA	NA	Gammaproteobacteria	Sphingomonadales	Opitutaceae	Clavibacter	Phaeobacter sp. LSS9	0	0
0	NA	NA	Alphaproteobacteria	Neisseriales	Pseudomonadaceae	Actinomyces	Azospirillum sp. M2T2B2	0	0
0	NA	NA	Betaproteobacteria	Rhodocyclales	Dermacoccaceae	Bifidobacterium	Martelella sp. AD-3	0	0
0	NA	NA	Bacilli	Campylobacterales	Actinopolysporaceae	Corynebacterium	Enterobacteriaceae bacterium strain FGI 57	0	0
0	NA	NA	Gammaproteobacteria	Myxococcales	Neisseriaceae	Mycobacterium	Mycobacterium marseillense	0	0
0	NA	NA	Alphaproteobacteria	Oscillatoriales	Enterobacteriaceae	Nocardia	Methylomonas koyamae	0	0
0	NA	NA	Betaproteobacteria	Nitrosomonadales	Micrococcaceae	Rhodococcus	Corynebacterium sp. NML98-0116	0	0
0	NA	NA	Bacilli	Desulfuromonadales	Thermomonosporaceae	Pseudonocardia	Aurantimicrobium minutum	0	0
0	NA	NA	Gammaproteobacteria	Pseudomonadales	Actinomycetaceae	Streptomyces	Actinomyces sp. oral taxon 414	0	0
0	NA	NA	Alphaproteobacteria	Burkholderiales	Streptomycetaceae	Marinobacter	Dietzia sp. oral taxon 368	0	0
0	NA	NA	Betaproteobacteria	Micrococcales	Bifidobacteriaceae	Halomonas	Haemophilus sp. oral taxon 036	0	0
0	NA	NA	Bacilli	Pseudonocardiales	Xanthomonadaceae	Begomovirus	Leptotrichia sp. oral taxon 498	0	0
0	NA	NA	Gammaproteobacteria	Streptomycetales	Comamonadaceae	Magnetospirillum	Olsenella sp. oral taxon 807	0	0
0	NA	NA	Alphaproteobacteria	Xanthomonadales	Promicromonosporaceae	Rubrivivax	Selenomonas sp. oral taxon 136	0	0
0	NA	NA	Betaproteobacteria	Oceanospirillales	Microbacteriaceae	Janthinobacterium	Alteromonas naphthalenivorans	0	0
0	NA	NA	Bacilli	Flavobacteriales	Gallionellaceae	Burkholderia	Mycobacterium shigaense	0	0
0	NA	NA	Gammaproteobacteria	Rhodospirillales	Burkholderiaceae	Exiguobacterium	Cycloclasticus sp. PY97N	0	0
0	NA	NA	Alphaproteobacteria	Sphingomonadales	Opitutaceae	Variovorax	Rahnella sp. Y9602	0	0
0	NA	NA	Betaproteobacteria	Neisseriales	Pseudomonadaceae	Rubrobacter	Delftia sp. Cs1-4	0	0
0	NA	NA	Bacilli	Rhodocyclales	Dermacoccaceae	Pseudoalteromonas	Sphingobacterium sp. 21	0	0
0	NA	NA	Gammaproteobacteria	Campylobacterales	Actinopolysporaceae	Methylovorus	Sphingomonas sp. MM-1	0	0
0	NA	NA	Alphaproteobacteria	Myxococcales	Neisseriaceae	Leclercia	Azoarcus sp. KH32C	0	0
0	NA	NA	Betaproteobacteria	Oscillatoriales	Enterobacteriaceae	Pandoraea	Pseudogulbenkiania sp. NH8B	0	0
0	NA	NA	Bacilli	Nitrosomonadales	Micrococcaceae	Arsenicicoccus	Halobacterium sp. DL1	0	0
0	NA	NA	Gammaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Zobellella	Sulfolobus turreted icosahedral virus 2	0	0
0	NA	NA	Alphaproteobacteria	Pseudomonadales	Actinomycetaceae	Mycobacteroides	Winogradskyella sp. PG-2	0	0
0	NA	NA	Betaproteobacteria	Burkholderiales	Streptomycetaceae	Luteipulveratus	Methylophaga nitratireducenticrescens	0	0
0	NA	NA	Bacilli	Micrococcales	Bifidobacteriaceae	Auritidibacter	Salinigranum rubrum	0	0
0	NA	NA	Gammaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Komagataeibacter	Clostridium sp. BNL1100	0	0
0	NA	NA	Alphaproteobacteria	Streptomycetales	Comamonadaceae	Pontimonas	Bacillus sp. WP8	0	0
0	NA	NA	Betaproteobacteria	Xanthomonadales	Promicromonosporaceae	Actinotignum	Acinetobacter indicus	0	0
0	NA	NA	Bacilli	Oceanospirillales	Microbacteriaceae	Mycolicibacterium	Burkholderia insecticola	0	0
0	NA	NA	Gammaproteobacteria	Flavobacteriales	Gallionellaceae	Azospirillum	Burkholderia sp. RPE67	0	0
0	NA	NA	Alphaproteobacteria	Rhodospirillales	Burkholderiaceae	Brucella	Mycolicibacterium litorale	0	0
0	NA	NA	Betaproteobacteria	Sphingomonadales	Opitutaceae	Pseudomonas	Weissella ceti	0	0
0	NA	NA	Bacilli	Neisseriales	Pseudomonadaceae	Xanthomonas	Serratia sp. AS12	0	0
0	NA	NA	Gammaproteobacteria	Rhodocyclales	Dermacoccaceae	Rhizobium	Serratia sp. AS13	0	0
0	NA	NA	Alphaproteobacteria	Campylobacterales	Actinopolysporaceae	Acinetobacter	Opitutaceae bacterium TAV5	0	0
0	NA	NA	Betaproteobacteria	Myxococcales	Neisseriaceae	Neisseria	Hydrogenophaga sp. PBC	0	0
0	NA	NA	Bacilli	Oscillatoriales	Enterobacteriaceae	Alcaligenes	Bacillus kochii	0	0
0	NA	NA	Gammaproteobacteria	Nitrosomonadales	Micrococcaceae	Chromobacterium	alpha proteobacterium HIMB5	0	0
0	NA	NA	Alphaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Citrobacter	Kibdelosporangium phytohabitans	0	0
0	NA	NA	Betaproteobacteria	Pseudomonadales	Actinomycetaceae	Enterobacter	Agrobacterium sp. H13-3	0	0
0	NA	NA	Bacilli	Burkholderiales	Streptomycetaceae	Klebsiella	Gemmatirosa kalamazoonesis	0	0
0	NA	NA	Gammaproteobacteria	Micrococcales	Bifidobacteriaceae	Aeromonas	Streptomyces sp. SirexAA-E	0	0
0	NA	NA	Alphaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Vibrio	Mycolicibacter sinensis	0	0
0	NA	NA	Betaproteobacteria	Streptomycetales	Comamonadaceae	Haemophilus	Cupriavidus sp. USMAA2-4	0	0
0	NA	NA	Bacilli	Xanthomonadales	Promicromonosporaceae	Aerococcus	Chryseobacterium sp. StRB126	0	0
0	NA	NA	Gammaproteobacteria	Oceanospirillales	Microbacteriaceae	Bacillus	Enterobacter bugandensis	0	0
0	NA	NA	Alphaproteobacteria	Flavobacteriales	Gallionellaceae	Clavibacter	Methylovorus sp. MP688	0	0
0	NA	NA	Betaproteobacteria	Rhodospirillales	Burkholderiaceae	Actinomyces	Plautia stali symbiont	0	0
0	NA	NA	Bacilli	Sphingomonadales	Opitutaceae	Bifidobacterium	Pseudoarcobacter ellisii	0	0
0	NA	NA	Gammaproteobacteria	Neisseriales	Pseudomonadaceae	Corynebacterium	Kangiella geojedonensis	0	0
0	NA	NA	Alphaproteobacteria	Rhodocyclales	Dermacoccaceae	Mycobacterium	Methylobacterium sp. AMS5	0	0
0	NA	NA	Betaproteobacteria	Campylobacterales	Actinopolysporaceae	Nocardia	Sandaracinus amylolyticus	0	0
0	NA	NA	Bacilli	Myxococcales	Neisseriaceae	Rhodococcus	Bradyrhizobium ottawaense	0	0
0	NA	NA	Gammaproteobacteria	Oscillatoriales	Enterobacteriaceae	Pseudonocardia	Rhodococcus sp. p52	0	0
0	NA	NA	Alphaproteobacteria	Nitrosomonadales	Micrococcaceae	Streptomyces	Arcobacter sp. L	0	0
0	NA	NA	Betaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Marinobacter	Rhizobacter gummiphilus	0	0
0	NA	NA	Bacilli	Pseudomonadales	Actinomycetaceae	Halomonas	Paraburkholderia sprentiae	0	0
0	NA	NA	Gammaproteobacteria	Burkholderiales	Streptomycetaceae	Begomovirus	Aeromonas rivipollensis	0	0
0	NA	NA	Alphaproteobacteria	Micrococcales	Bifidobacteriaceae	Magnetospirillum	Leuconostoc sp. C2	0	0
0	NA	NA	Betaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Rubrivivax	Deinococcus wulumuqiensis	0	0
0	NA	NA	Bacilli	Streptomycetales	Comamonadaceae	Janthinobacterium	Glaciecola sp. 4H-3-7+YE-5	0	0
0	NA	NA	Gammaproteobacteria	Xanthomonadales	Promicromonosporaceae	Burkholderia	Dokdonia sp. 4H-3-7-5	0	0
0	NA	NA	Alphaproteobacteria	Oceanospirillales	Microbacteriaceae	Exiguobacterium	Polaribacter reichenbachii	0	0
0	NA	NA	Betaproteobacteria	Flavobacteriales	Gallionellaceae	Variovorax	Gordonia iterans	0	0
0	NA	NA	Bacilli	Rhodospirillales	Burkholderiaceae	Rubrobacter	Defluviitoga tunisiensis	0	0
0	NA	NA	Gammaproteobacteria	Sphingomonadales	Opitutaceae	Pseudoalteromonas	Pusillimonas sp. T7-7	0	0
0	NA	NA	Alphaproteobacteria	Neisseriales	Pseudomonadaceae	Methylovorus	Lactobacillus ginsenosidimutans	0	0
0	NA	NA	Betaproteobacteria	Rhodocyclales	Dermacoccaceae	Leclercia	Staphylococcus phage S24-1	0	0
0	NA	NA	Bacilli	Campylobacterales	Actinopolysporaceae	Pandoraea	Pseudomonas sp. StFLB209	0	0
0	NA	NA	Gammaproteobacteria	Myxococcales	Neisseriaceae	Arsenicicoccus	Erwinia phage phiEaH2	0	0
0	NA	NA	Alphaproteobacteria	Oscillatoriales	Enterobacteriaceae	Zobellella	Sphingomonas sp. KC8	0	0
0	NA	NA	Betaproteobacteria	Nitrosomonadales	Micrococcaceae	Mycobacteroides	Rhodococcus sp. WB1	0	0
0	NA	NA	Bacilli	Desulfuromonadales	Thermomonosporaceae	Luteipulveratus	Planococcus plakortidis	0	0
0	NA	NA	Gammaproteobacteria	Pseudomonadales	Actinomycetaceae	Auritidibacter	Candidatus Arthromitus sp. SFB-rat-Yit	0	0
0	NA	NA	Alphaproteobacteria	Burkholderiales	Streptomycetaceae	Komagataeibacter	Halopenitus persicus	0	0
0	NA	NA	Betaproteobacteria	Micrococcales	Bifidobacteriaceae	Pontimonas	Corynebacterium epidermidicanis	0	0
0	NA	NA	Bacilli	Pseudonocardiales	Xanthomonadaceae	Actinotignum	Candidatus Gullanella endobia	0	0
0	NA	NA	Gammaproteobacteria	Streptomycetales	Comamonadaceae	Mycolicibacterium	Corynebacterium uterequi	0	0
0	NA	NA	Alphaproteobacteria	Xanthomonadales	Promicromonosporaceae	Azospirillum	Pantoea rwandensis	0	0
0	NA	NA	Betaproteobacteria	Oceanospirillales	Microbacteriaceae	Brucella	Thiolapillus brandeum	0	0
0	NA	NA	Bacilli	Flavobacteriales	Gallionellaceae	Pseudomonas	Acetobacter persici	0	0
0	NA	NA	Gammaproteobacteria	Rhodospirillales	Burkholderiaceae	Xanthomonas	Paracoccus zhejiangensis	0	0
0	NA	NA	Alphaproteobacteria	Sphingomonadales	Opitutaceae	Rhizobium	Synechococcus phage ACG-2014c	0	0
0	NA	NA	Betaproteobacteria	Neisseriales	Pseudomonadaceae	Acinetobacter	Leptolyngbya sp. O-77	0	0
0	NA	NA	Bacilli	Rhodocyclales	Dermacoccaceae	Neisseria	Comamonas serinivorans	0	0
0	NA	NA	Gammaproteobacteria	Campylobacterales	Actinopolysporaceae	Alcaligenes	Persicobacter sp. JZB09	0	0
0	NA	NA	Alphaproteobacteria	Myxococcales	Neisseriaceae	Chromobacterium	Dickeya solani	0	0
0	NA	NA	Betaproteobacteria	Oscillatoriales	Enterobacteriaceae	Citrobacter	Alcanivorax xenomutans	0	0
0	NA	NA	Bacilli	Nitrosomonadales	Micrococcaceae	Enterobacter	Megavirus chiliensis	0	0
0	NA	NA	Gammaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Klebsiella	Pseudonocardia sp. EC080619-01	0	0
0	NA	NA	Alphaproteobacteria	Pseudomonadales	Actinomycetaceae	Aeromonas	Pseudonocardia sp. EC080625-04	0	0
0	NA	NA	Betaproteobacteria	Burkholderiales	Streptomycetaceae	Vibrio	Burkholderia sp. YI23	0	0
0	NA	NA	Bacilli	Micrococcales	Bifidobacteriaceae	Haemophilus	Chromobacterium vaccinii	0	0
0	NA	NA	Gammaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Aerococcus	Brenneria goodwinii	0	0
0	NA	NA	Alphaproteobacteria	Streptomycetales	Comamonadaceae	Bacillus	Thermus sp. CCB_US3_UF1	0	0
0	NA	NA	Betaproteobacteria	Xanthomonadales	Promicromonosporaceae	Clavibacter	Vibrio sp. EJY3	0	0
0	NA	NA	Bacilli	Oceanospirillales	Microbacteriaceae	Actinomyces	Elizabethkingia anophelis	0	0
0	NA	NA	Gammaproteobacteria	Flavobacteriales	Gallionellaceae	Bifidobacterium	Halomonas sp. GFAJ-1	0	0
0	NA	NA	Alphaproteobacteria	Rhodospirillales	Burkholderiaceae	Corynebacterium	Arthrobacter sp. Rue61a	0	0
0	NA	NA	Betaproteobacteria	Sphingomonadales	Opitutaceae	Mycobacterium	Rhizobium sp. NT-26	0	0
0	NA	NA	Bacilli	Neisseriales	Pseudomonadaceae	Nocardia	Bacillus sp. JS	0	0
0	NA	NA	Gammaproteobacteria	Rhodocyclales	Dermacoccaceae	Rhodococcus	Dehalobacter sp. CF	0	0
0	NA	NA	Alphaproteobacteria	Campylobacterales	Actinopolysporaceae	Pseudonocardia	Klebsiella michiganensis	0	0
0	NA	NA	Betaproteobacteria	Myxococcales	Neisseriaceae	Streptomyces	Gordonia phthalatica	0	0
0	NA	NA	Bacilli	Oscillatoriales	Enterobacteriaceae	Marinobacter	Leptospira mayottensis	0	0
0	NA	NA	Gammaproteobacteria	Nitrosomonadales	Micrococcaceae	Halomonas	Mycobacterium paraintracellulare	0	0
0	NA	NA	Alphaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Begomovirus	Lactobacillus curieae	0	0
0	NA	NA	Betaproteobacteria	Pseudomonadales	Actinomycetaceae	Magnetospirillum	Lysinibacillus varians	0	0
0	NA	NA	Bacilli	Burkholderiales	Streptomycetaceae	Rubrivivax	Dehalobacter sp. DCA	0	0
0	NA	NA	Gammaproteobacteria	Micrococcales	Bifidobacteriaceae	Janthinobacterium	Pseudomonas furukawaii	0	0
0	NA	NA	Alphaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Burkholderia	Streptococcus sp. I-G2	0	0
0	NA	NA	Betaproteobacteria	Streptomycetales	Comamonadaceae	Exiguobacterium	Thermotoga sp. Cell2	0	0
0	NA	NA	Bacilli	Xanthomonadales	Promicromonosporaceae	Variovorax	Kosakonia sacchari	0	0
0	NA	NA	Gammaproteobacteria	Oceanospirillales	Microbacteriaceae	Rubrobacter	Candidatus Thiodictyon syntrophicum	0	0
0	NA	NA	Alphaproteobacteria	Flavobacteriales	Gallionellaceae	Pseudoalteromonas	Mycobacterium sp. MOTT36Y	0	0
0	NA	NA	Betaproteobacteria	Rhodospirillales	Burkholderiaceae	Methylovorus	Geitlerinema sp. PCC 7407	0	0
0	NA	NA	Bacilli	Sphingomonadales	Opitutaceae	Leclercia	Gloeocapsa sp. PCC 7428	0	0
0	NA	NA	Gammaproteobacteria	Neisseriales	Pseudomonadaceae	Pandoraea	Synechococcus sp. PCC 7502	0	0
0	NA	NA	Alphaproteobacteria	Rhodocyclales	Dermacoccaceae	Arsenicicoccus	Niabella ginsenosidivorans	0	0
0	NA	NA	Betaproteobacteria	Campylobacterales	Actinopolysporaceae	Zobellella	Prevotella jejuni	0	0
0	NA	NA	Bacilli	Myxococcales	Neisseriaceae	Mycobacteroides	Paenibacillus swuensis	0	0
0	NA	NA	Gammaproteobacteria	Oscillatoriales	Enterobacteriaceae	Luteipulveratus	Maribacter cobaltidurans	0	0
0	NA	NA	Alphaproteobacteria	Nitrosomonadales	Micrococcaceae	Auritidibacter	Pyrococcus sp. ST04	0	0
0	NA	NA	Betaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Komagataeibacter	Ferriphaselus amnicola	0	0
0	NA	NA	Bacilli	Pseudomonadales	Actinomycetaceae	Pontimonas	Campylobacter virus CP21	0	0
0	NA	NA	Gammaproteobacteria	Burkholderiales	Streptomycetaceae	Actinotignum	Aeromonas phage CC2	0	0
0	NA	NA	Alphaproteobacteria	Micrococcales	Bifidobacteriaceae	Mycolicibacterium	Pseudomonas sp. Lz4W	0	0
0	NA	NA	Betaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Azospirillum	Pseudomonas sp. UW4	0	0
0	NA	NA	Bacilli	Streptomycetales	Comamonadaceae	Brucella	Spirosoma aerolatum	0	0
0	NA	NA	Gammaproteobacteria	Xanthomonadales	Promicromonosporaceae	Pseudomonas	Clostridium bornimense	0	0
0	NA	NA	Alphaproteobacteria	Oceanospirillales	Microbacteriaceae	Xanthomonas	Lactobacillus kullabergensis	0	0
0	NA	NA	Betaproteobacteria	Flavobacteriales	Gallionellaceae	Rhizobium	Bradyrhizobium sp. CCGE-LA001	0	0
0	NA	NA	Bacilli	Rhodospirillales	Burkholderiaceae	Acinetobacter	Exiguobacterium sp. ZWU0009	0	0
0	NA	NA	Gammaproteobacteria	Sphingomonadales	Opitutaceae	Neisseria	Salipiger profundus	0	0
0	NA	NA	Alphaproteobacteria	Neisseriales	Pseudomonadaceae	Alcaligenes	Candidatus Nitrosopumilus sediminis	0	0
0	NA	NA	Betaproteobacteria	Rhodocyclales	Dermacoccaceae	Chromobacterium	Salimicrobium jeotgali	0	0
0	NA	NA	Bacilli	Campylobacterales	Actinopolysporaceae	Citrobacter	Mucilaginibacter sp. BJC16-A31	0	0
0	NA	NA	Gammaproteobacteria	Myxococcales	Neisseriaceae	Enterobacter	Pseudorhodoplanes sinuspersici	0	0
0	NA	NA	Alphaproteobacteria	Oscillatoriales	Enterobacteriaceae	Klebsiella	Janthinobacterium sp. B9-8	0	0
0	NA	NA	Betaproteobacteria	Nitrosomonadales	Micrococcaceae	Aeromonas	Sodalis praecaptivus	0	0
0	NA	NA	Bacilli	Desulfuromonadales	Thermomonosporaceae	Vibrio	Campylobacter iguaniorum	0	0
0	NA	NA	Gammaproteobacteria	Pseudomonadales	Actinomycetaceae	Haemophilus	Bacterioplanes sanyensis	0	0
0	NA	NA	Alphaproteobacteria	Burkholderiales	Streptomycetaceae	Aerococcus	Flammeovirgaceae bacterium 311	0	0
0	NA	NA	Betaproteobacteria	Micrococcales	Bifidobacteriaceae	Bacillus	Pseudomonas sp. FGI182	0	0
0	NA	NA	Bacilli	Pseudonocardiales	Xanthomonadaceae	Clavibacter	Nostoc sp. 'Peltigera membranacea cyanobiont' N6	0	0
0	NA	NA	Gammaproteobacteria	Streptomycetales	Comamonadaceae	Actinomyces	Streptomyces sp. 769	0	0
0	NA	NA	Alphaproteobacteria	Xanthomonadales	Promicromonosporaceae	Bifidobacterium	Edwardsiella piscicida	0	0
0	NA	NA	Betaproteobacteria	Oceanospirillales	Microbacteriaceae	Corynebacterium	Chryseobacterium camelliae	0	0
0	NA	NA	Bacilli	Flavobacteriales	Gallionellaceae	Mycobacterium	Streptomyces sp. PAMC 26508	0	0
0	NA	NA	Gammaproteobacteria	Rhodospirillales	Burkholderiaceae	Nocardia	Liberibacter crescens	0	0
0	NA	NA	Alphaproteobacteria	Sphingomonadales	Opitutaceae	Rhodococcus	Mycobacterium sp. VKM Ac-1817D	0	0
0	NA	NA	Betaproteobacteria	Neisseriales	Pseudomonadaceae	Pseudonocardia	Bradyrhizobium icense	0	0
0	NA	NA	Bacilli	Rhodocyclales	Dermacoccaceae	Streptomyces	Pseudomonas sp. URMO17WK12:I11	0	0
0	NA	NA	Gammaproteobacteria	Campylobacterales	Actinopolysporaceae	Marinobacter	Magnetospira sp. QH-2	0	0
0	NA	NA	Alphaproteobacteria	Myxococcales	Neisseriaceae	Halomonas	Pseudomonas sp. ATCC 13867	0	0
0	NA	NA	Betaproteobacteria	Oscillatoriales	Enterobacteriaceae	Begomovirus	Aquabacterium olei	0	0
0	NA	NA	Bacilli	Nitrosomonadales	Micrococcaceae	Magnetospirillum	Intestinimonas butyriciproducens	0	0
0	NA	NA	Gammaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Rubrivivax	Myxococcus hansupus	0	0
0	NA	NA	Alphaproteobacteria	Pseudomonadales	Actinomycetaceae	Janthinobacterium	Mucilaginibacter sp. PAMC 26640	0	0
0	NA	NA	Betaproteobacteria	Burkholderiales	Streptomycetaceae	Burkholderia	Invertebrate iridovirus 22	0	0
0	NA	NA	Bacilli	Micrococcales	Bifidobacteriaceae	Exiguobacterium	Invertebrate iridovirus 25	0	0
0	NA	NA	Gammaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Variovorax	Planococcus versutus	0	0
0	NA	NA	Alphaproteobacteria	Streptomycetales	Comamonadaceae	Rubrobacter	Lactobacillus bombi	0	0
0	NA	NA	Betaproteobacteria	Xanthomonadales	Promicromonosporaceae	Pseudoalteromonas	Flavobacterium commune	0	0
0	NA	NA	Bacilli	Oceanospirillales	Microbacteriaceae	Methylovorus	Salinispira pacifica	0	0
0	NA	NA	Gammaproteobacteria	Flavobacteriales	Gallionellaceae	Leclercia	Kiritimatiella glycovorans	0	0
0	NA	NA	Alphaproteobacteria	Rhodospirillales	Burkholderiaceae	Pandoraea	Salinivirga cyanobacteriivorans	0	0
0	NA	NA	Betaproteobacteria	Sphingomonadales	Opitutaceae	Arsenicicoccus	Deinococcus soli Cha et al. 2016	0	0
0	NA	NA	Bacilli	Neisseriales	Pseudomonadaceae	Zobellella	Bacillus phage MG-B1	0	0
0	NA	NA	Gammaproteobacteria	Rhodocyclales	Dermacoccaceae	Mycobacteroides	Sphingobium sp. TKS	0	0
0	NA	NA	Alphaproteobacteria	Campylobacterales	Actinopolysporaceae	Luteipulveratus	Capnocytophaga sp. oral taxon 864	0	0
0	NA	NA	Betaproteobacteria	Myxococcales	Neisseriaceae	Auritidibacter	Capnocytophaga sp. oral taxon 878	0	0
0	NA	NA	Bacilli	Oscillatoriales	Enterobacteriaceae	Komagataeibacter	Acinetobacter equi	0	0
0	NA	NA	Gammaproteobacteria	Nitrosomonadales	Micrococcaceae	Pontimonas	Chryseobacterium gallinarum	0	0
0	NA	NA	Alphaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Actinotignum	Sphingomonas sp. Cra20	0	0
0	NA	NA	Betaproteobacteria	Pseudomonadales	Actinomycetaceae	Mycolicibacterium	Mycobacterium phage Phrux	0	0
0	NA	NA	Bacilli	Burkholderiales	Streptomycetaceae	Azospirillum	Serratia sp. FS14	0	0
0	NA	NA	Gammaproteobacteria	Micrococcales	Bifidobacteriaceae	Brucella	Bordetella pseudohinzii	0	0
0	NA	NA	Alphaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Pseudomonas	Brachybacterium ginsengisoli	0	0
0	NA	NA	Betaproteobacteria	Streptomycetales	Comamonadaceae	Xanthomonas	Sphingobium baderi	0	0
0	NA	NA	Bacilli	Xanthomonadales	Promicromonosporaceae	Rhizobium	Tessaracoccus aquimaris	0	0
0	NA	NA	Gammaproteobacteria	Oceanospirillales	Microbacteriaceae	Acinetobacter	Salinarchaeum sp. Harcht-Bsk1	0	0
0	NA	NA	Alphaproteobacteria	Flavobacteriales	Gallionellaceae	Neisseria	Variibacter gotjawalensis	0	0
0	NA	NA	Betaproteobacteria	Rhodospirillales	Burkholderiaceae	Alcaligenes	[Enterobacter] lignolyticus	0	0
0	NA	NA	Bacilli	Sphingomonadales	Opitutaceae	Chromobacterium	Gordonibacter urolithinfaciens	0	0
0	NA	NA	Gammaproteobacteria	Neisseriales	Pseudomonadaceae	Citrobacter	Formosa sp. Hel1_33_131	0	0
0	NA	NA	Alphaproteobacteria	Rhodocyclales	Dermacoccaceae	Enterobacter	Reinekea forsetii	0	0
0	NA	NA	Betaproteobacteria	Campylobacterales	Actinopolysporaceae	Klebsiella	Pseudomonas sp. JY-Q	0	0
0	NA	NA	Bacilli	Myxococcales	Neisseriaceae	Aeromonas	Geobacter anodireducens	0	0
0	NA	NA	Gammaproteobacteria	Oscillatoriales	Enterobacteriaceae	Vibrio	Pseudoalteromonas piratica	0	0
0	NA	NA	Alphaproteobacteria	Nitrosomonadales	Micrococcaceae	Haemophilus	Croceicoccus naphthovorans	0	0
0	NA	NA	Betaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Aerococcus	Pandoravirus dulcis	0	0
0	NA	NA	Bacilli	Pseudomonadales	Actinomycetaceae	Bacillus	Aureimonas sp. AU20	0	0
0	NA	NA	Gammaproteobacteria	Burkholderiales	Streptomycetaceae	Clavibacter	Synechococcus sp. UTEX 2973	0	0
0	NA	NA	Alphaproteobacteria	Micrococcales	Bifidobacteriaceae	Actinomyces	Streptomyces pluripotens	0	0
0	NA	NA	Betaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Bifidobacterium	Flavobacterium faecale	0	0
0	NA	NA	Bacilli	Streptomycetales	Comamonadaceae	Corynebacterium	Bradyrhizobium diazoefficiens	0	0
0	NA	NA	Gammaproteobacteria	Xanthomonadales	Promicromonosporaceae	Mycobacterium	Hymenobacter sp. APR13	0	0
0	NA	NA	Alphaproteobacteria	Oceanospirillales	Microbacteriaceae	Nocardia	Arthrobacter sp. QXT-31	0	0
0	NA	NA	Betaproteobacteria	Flavobacteriales	Gallionellaceae	Rhodococcus	Dyella jiangningensis	0	0
0	NA	NA	Bacilli	Rhodospirillales	Burkholderiaceae	Pseudonocardia	Gemmatimonas phototrophica	0	0
0	NA	NA	Gammaproteobacteria	Sphingomonadales	Opitutaceae	Streptomyces	Methanobacterium sp. MB1	0	0
0	NA	NA	Alphaproteobacteria	Neisseriales	Pseudomonadaceae	Marinobacter	Spirosoma radiotolerans	0	0
0	NA	NA	Betaproteobacteria	Rhodocyclales	Dermacoccaceae	Halomonas	Rufibacter sp. DG15C	0	0
0	NA	NA	Bacilli	Campylobacterales	Actinopolysporaceae	Begomovirus	Rufibacter sp. DG31D	0	0
0	NA	NA	Gammaproteobacteria	Myxococcales	Neisseriaceae	Magnetospirillum	Flagellimonas sp. HME9304	0	0
0	NA	NA	Alphaproteobacteria	Oscillatoriales	Enterobacteriaceae	Rubrivivax	Methyloceanibacter caenitepidi	0	0
0	NA	NA	Betaproteobacteria	Nitrosomonadales	Micrococcaceae	Janthinobacterium	Burkholderia sp. BDU6	0	0
0	NA	NA	Bacilli	Desulfuromonadales	Thermomonosporaceae	Burkholderia	Paludisphaera borealis	0	0
0	NA	NA	Gammaproteobacteria	Pseudomonadales	Actinomycetaceae	Exiguobacterium	Cupriavidus sp. USMAHM13	0	0
0	NA	NA	Alphaproteobacteria	Burkholderiales	Streptomycetaceae	Variovorax	Sphingomonas sp. LK11	0	0
0	NA	NA	Betaproteobacteria	Micrococcales	Bifidobacteriaceae	Rubrobacter	Vulgatibacter incomptus	0	0
0	NA	NA	Bacilli	Pseudonocardiales	Xanthomonadaceae	Pseudoalteromonas	Celeribacter marinus	0	0
0	NA	NA	Gammaproteobacteria	Streptomycetales	Comamonadaceae	Methylovorus	Bacteroidales bacterium CF	0	0
0	NA	NA	Alphaproteobacteria	Xanthomonadales	Promicromonosporaceae	Leclercia	Bacillus filamentosus	0	0
0	NA	NA	Betaproteobacteria	Oceanospirillales	Microbacteriaceae	Pandoraea	Bradyrhizobium sp. 3 85S1MB	0	0
0	NA	NA	Bacilli	Flavobacteriales	Gallionellaceae	Arsenicicoccus	Bradyrhizobium sp. 2 39S1MB	0	0
0	NA	NA	Gammaproteobacteria	Rhodospirillales	Burkholderiaceae	Zobellella	Halobacterium hubeiense	0	0
0	NA	NA	Alphaproteobacteria	Sphingomonadales	Opitutaceae	Mycobacteroides	Candidatus Tachikawaea gelatinosa	0	0
0	NA	NA	Betaproteobacteria	Neisseriales	Pseudomonadaceae	Luteipulveratus	Candidatus Nitrosopelagicus brevis	0	0
0	NA	NA	Bacilli	Rhodocyclales	Dermacoccaceae	Auritidibacter	Hymenobacter sedentarius	0	0
0	NA	NA	Gammaproteobacteria	Campylobacterales	Actinopolysporaceae	Komagataeibacter	Pseudomonas sp. TKP	0	0
0	NA	NA	Alphaproteobacteria	Myxococcales	Neisseriaceae	Pontimonas	Bordetella genomosp. 8	0	0
0	NA	NA	Betaproteobacteria	Oscillatoriales	Enterobacteriaceae	Actinotignum	Geosporobacter ferrireducens	0	0
0	NA	NA	Bacilli	Nitrosomonadales	Micrococcaceae	Mycolicibacterium	Mucinivorans hirudinis	0	0
0	NA	NA	Gammaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Azospirillum	Methanosarcina sp. Kolksee	0	0
0	NA	NA	Alphaproteobacteria	Pseudomonadales	Actinomycetaceae	Brucella	Methanosarcina sp. MTP4	0	0
0	NA	NA	Betaproteobacteria	Burkholderiales	Streptomycetaceae	Pseudomonas	Methanosarcina sp. WH1	0	0
0	NA	NA	Bacilli	Micrococcales	Bifidobacteriaceae	Xanthomonas	Methanosarcina sp. WWM596	0	0
0	NA	NA	Gammaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Rhizobium	Thermosipho sp. 1070	0	0
0	NA	NA	Alphaproteobacteria	Streptomycetales	Comamonadaceae	Acinetobacter	Streptomyces leeuwenhoekii	0	0
0	NA	NA	Betaproteobacteria	Xanthomonadales	Promicromonosporaceae	Neisseria	Ectothiorhodospira sp. BSL-9	0	0
0	NA	NA	Bacilli	Oceanospirillales	Microbacteriaceae	Alcaligenes	Aneurinibacillus sp. XH2	0	0
0	NA	NA	Gammaproteobacteria	Flavobacteriales	Gallionellaceae	Chromobacterium	Sediminicola sp. YIK13	0	0
0	NA	NA	Alphaproteobacteria	Rhodospirillales	Burkholderiaceae	Citrobacter	Chlamydia gallinacea	0	0
0	NA	NA	Betaproteobacteria	Sphingomonadales	Opitutaceae	Enterobacter	Bacteroidetes bacterium Omega	0	0
0	NA	NA	Bacilli	Neisseriales	Pseudomonadaceae	Klebsiella	Octadecabacter temperatus	0	0
0	NA	NA	Gammaproteobacteria	Rhodocyclales	Dermacoccaceae	Aeromonas	Comamonadaceae bacterium A1	0	0
0	NA	NA	Alphaproteobacteria	Campylobacterales	Actinopolysporaceae	Vibrio	Myroides sp. ZB35	0	0
0	NA	NA	Betaproteobacteria	Myxococcales	Neisseriaceae	Haemophilus	Shewanella sp. phage 1/40	0	0
0	NA	NA	Bacilli	Oscillatoriales	Enterobacteriaceae	Aerococcus	Thermosipho sp. 1063	0	0
0	NA	NA	Gammaproteobacteria	Nitrosomonadales	Micrococcaceae	Bacillus	Paenibacillus yonginensis	0	0
0	NA	NA	Alphaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Clavibacter	Klebsiella quasipneumoniae	0	0
0	NA	NA	Betaproteobacteria	Pseudomonadales	Actinomycetaceae	Actinomyces	Burkholderiales bacterium GJ-E10	0	0
0	NA	NA	Bacilli	Burkholderiales	Streptomycetaceae	Bifidobacterium	Zhongshania aliphaticivorans	0	0
0	NA	NA	Gammaproteobacteria	Micrococcales	Bifidobacteriaceae	Corynebacterium	Novibacillus thermophilus	0	0
0	NA	NA	Alphaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Mycobacterium	Nonlabens sp. MIC269	0	0
0	NA	NA	Betaproteobacteria	Streptomycetales	Comamonadaceae	Nocardia	Methylobacterium sp. C1	0	0
0	NA	NA	Bacilli	Xanthomonadales	Promicromonosporaceae	Rhodococcus	Hartmannibacter diazotrophicus	0	0
0	NA	NA	Gammaproteobacteria	Oceanospirillales	Microbacteriaceae	Pseudonocardia	Hymenobacter sp. PAMC 26628	0	0
0	NA	NA	Alphaproteobacteria	Flavobacteriales	Gallionellaceae	Streptomyces	Pantoea sp. PSNIH1	0	0
0	NA	NA	Betaproteobacteria	Rhodospirillales	Burkholderiaceae	Marinobacter	Rhodoferax saidenbachensis	0	0
0	NA	NA	Bacilli	Sphingomonadales	Opitutaceae	Halomonas	Lacinutrix venerupis	0	0
0	NA	NA	Gammaproteobacteria	Neisseriales	Pseudomonadaceae	Begomovirus	Corynebacterium sp. ATCC 6931	0	0
0	NA	NA	Alphaproteobacteria	Rhodocyclales	Dermacoccaceae	Magnetospirillum	Anoxybacillus sp. B2M1	0	0
0	NA	NA	Betaproteobacteria	Campylobacterales	Actinopolysporaceae	Rubrivivax	Anoxybacillus sp. B7M1	0	0
0	NA	NA	Bacilli	Myxococcales	Neisseriaceae	Janthinobacterium	Flavobacterium gilvum	0	0
0	NA	NA	Gammaproteobacteria	Oscillatoriales	Enterobacteriaceae	Burkholderia	Flavisolibacter tropicus	0	0
0	NA	NA	Alphaproteobacteria	Nitrosomonadales	Micrococcaceae	Exiguobacterium	Arthrobacter sp. PAMC 25486	0	0
0	NA	NA	Betaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Variovorax	Streptomyces sp. M56	0	0
0	NA	NA	Bacilli	Pseudomonadales	Actinomycetaceae	Rubrobacter	Paracoccus mutanolyticus	0	0
0	NA	NA	Gammaproteobacteria	Burkholderiales	Streptomycetaceae	Pseudoalteromonas	Escherichia marmotae	0	0
0	NA	NA	Alphaproteobacteria	Micrococcales	Bifidobacteriaceae	Methylovorus	Pseudomonas sp. Os17	0	0
0	NA	NA	Betaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Leclercia	Rhodococcus biphenylivorans	0	0
0	NA	NA	Bacilli	Streptomycetales	Comamonadaceae	Pandoraea	Campylobacter sp. RM16704	0	0
0	NA	NA	Gammaproteobacteria	Xanthomonadales	Promicromonosporaceae	Arsenicicoccus	Prochlorococcus sp. MIT 0604	0	0
0	NA	NA	Alphaproteobacteria	Oceanospirillales	Microbacteriaceae	Zobellella	Prochlorococcus sp. MIT 0801	0	0
0	NA	NA	Betaproteobacteria	Flavobacteriales	Gallionellaceae	Mycobacteroides	Burkholderia stagnalis	0	0
0	NA	NA	Bacilli	Rhodospirillales	Burkholderiaceae	Luteipulveratus	Burkholderia territorii	0	0
0	NA	NA	Gammaproteobacteria	Sphingomonadales	Opitutaceae	Auritidibacter	Halomonas sp. KO116	0	0
0	NA	NA	Alphaproteobacteria	Neisseriales	Pseudomonadaceae	Komagataeibacter	Candidatus Arthromitus sp. SFB-mouse-NL	0	0
0	NA	NA	Betaproteobacteria	Rhodocyclales	Dermacoccaceae	Pontimonas	[Mycobacterium] stephanolepidis	0	0
0	NA	NA	Bacilli	Campylobacterales	Actinopolysporaceae	Actinotignum	Lacimicrobium alkaliphilum	0	0
0	NA	NA	Gammaproteobacteria	Myxococcales	Neisseriaceae	Mycolicibacterium	Bosea vaviloviae	0	0
0	NA	NA	Alphaproteobacteria	Oscillatoriales	Enterobacteriaceae	Azospirillum	Planococcus sp. PAMC 21323	0	0
0	NA	NA	Betaproteobacteria	Nitrosomonadales	Micrococcaceae	Brucella	Rickettsiales bacterium Ac37b	0	0
0	NA	NA	Bacilli	Desulfuromonadales	Thermomonosporaceae	Pseudomonas	Lawsonella clevelandensis	0	0
0	NA	NA	Gammaproteobacteria	Pseudomonadales	Actinomycetaceae	Xanthomonas	Paracoccus sp. BM15	0	0
0	NA	NA	Alphaproteobacteria	Burkholderiales	Streptomycetaceae	Rhizobium	Polaribacter sp. BM10	0	0
0	NA	NA	Betaproteobacteria	Micrococcales	Bifidobacteriaceae	Acinetobacter	Coriobacteriaceae bacterium 68-1-3	0	0
0	NA	NA	Bacilli	Pseudonocardiales	Xanthomonadaceae	Neisseria	Brevundimonas sp. DS20	0	0
0	NA	NA	Gammaproteobacteria	Streptomycetales	Comamonadaceae	Alcaligenes	Vibrio hyugaensis	0	0
0	NA	NA	Alphaproteobacteria	Xanthomonadales	Promicromonosporaceae	Chromobacterium	Streptomyces lunaelactis	0	0
0	NA	NA	Betaproteobacteria	Oceanospirillales	Microbacteriaceae	Citrobacter	Paenibacillus sp. FSL R5-0345	0	0
0	NA	NA	Bacilli	Flavobacteriales	Gallionellaceae	Enterobacter	Paenibacillus sp. FSL H7-0737	0	0
0	NA	NA	Gammaproteobacteria	Rhodospirillales	Burkholderiaceae	Klebsiella	Methylomonas denitrificans	0	0
0	NA	NA	Alphaproteobacteria	Sphingomonadales	Opitutaceae	Aeromonas	Sphingobacterium sp. ML3W	0	0
0	NA	NA	Betaproteobacteria	Neisseriales	Pseudomonadaceae	Vibrio	Treponema sp. OMZ 838	0	0
0	NA	NA	Bacilli	Rhodocyclales	Dermacoccaceae	Haemophilus	Bacillus phage Mater	0	0
0	NA	NA	Gammaproteobacteria	Campylobacterales	Actinopolysporaceae	Aerococcus	Candidatus Izimaplasma sp. HR1	0	0
0	NA	NA	Alphaproteobacteria	Myxococcales	Neisseriaceae	Bacillus	Prochlorococcus phage P-TIM68	0	0
0	NA	NA	Betaproteobacteria	Oscillatoriales	Enterobacteriaceae	Clavibacter	Staphylococcus phage BP39	0	0
0	NA	NA	Bacilli	Nitrosomonadales	Micrococcaceae	Actinomyces	Mycobacterium sp. EPa45	0	0
0	NA	NA	Gammaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Bifidobacterium	Marinitoga sp. 1137	0	0
0	NA	NA	Alphaproteobacteria	Pseudomonadales	Actinomycetaceae	Corynebacterium	Diaphorobacter polyhydroxybutyrativorans	0	0
0	NA	NA	Betaproteobacteria	Burkholderiales	Streptomycetaceae	Mycobacterium	Bacillus weihaiensis	0	0
0	NA	NA	Bacilli	Micrococcales	Bifidobacteriaceae	Nocardia	Francisella sp. FSC1006	0	0
0	NA	NA	Gammaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Rhodococcus	Haloplanus sp. CBA1112	0	0
0	NA	NA	Alphaproteobacteria	Streptomycetales	Comamonadaceae	Pseudonocardia	Haloplanus sp. CBA1113	0	0
0	NA	NA	Betaproteobacteria	Xanthomonadales	Promicromonosporaceae	Streptomyces	Woeseia oceani	0	0
0	NA	NA	Bacilli	Oceanospirillales	Microbacteriaceae	Marinobacter	Bradymonas sediminis	0	0
0	NA	NA	Gammaproteobacteria	Flavobacteriales	Gallionellaceae	Halomonas	Mucilaginibacter gotjawali	0	0
0	NA	NA	Alphaproteobacteria	Rhodospirillales	Burkholderiaceae	Begomovirus	Blastomonas fulva	0	0
0	NA	NA	Betaproteobacteria	Sphingomonadales	Opitutaceae	Magnetospirillum	Sphingomonas panacis	0	0
0	NA	NA	Bacilli	Neisseriales	Pseudomonadaceae	Rubrivivax	Streptomyces sp. CCM_MD2014	0	0
0	NA	NA	Gammaproteobacteria	Rhodocyclales	Dermacoccaceae	Janthinobacterium	Curtobacterium sp. MR_MD2014	0	0
0	NA	NA	Alphaproteobacteria	Campylobacterales	Actinopolysporaceae	Burkholderia	Mycobacterium sp. QIA-37	0	0
0	NA	NA	Betaproteobacteria	Myxococcales	Neisseriaceae	Exiguobacterium	Fermentimonas caenicola	0	0
0	NA	NA	Bacilli	Oscillatoriales	Enterobacteriaceae	Variovorax	Rhodococcus sp. B7740	0	0
0	NA	NA	Gammaproteobacteria	Nitrosomonadales	Micrococcaceae	Rubrobacter	Rhodovulum sp. P5	0	0
0	NA	NA	Alphaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Pseudoalteromonas	Carnobacterium sp. CP1	0	0
0	NA	NA	Betaproteobacteria	Pseudomonadales	Actinomycetaceae	Methylovorus	Bacillus sp. X1(2014)	0	0
0	NA	NA	Bacilli	Burkholderiales	Streptomycetaceae	Leclercia	Paenibacillus sp. IHBB 10380	0	0
0	NA	NA	Gammaproteobacteria	Micrococcales	Bifidobacteriaceae	Pandoraea	Mycobacterium sp. NRRL B-3805	0	0
0	NA	NA	Alphaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Arsenicicoccus	Rhodococcus sp. 2G	0	0
0	NA	NA	Betaproteobacteria	Streptomycetales	Comamonadaceae	Zobellella	Rhizobium sp. ACO-34A	0	0
0	NA	NA	Bacilli	Xanthomonadales	Promicromonosporaceae	Mycobacteroides	Geobacillus virus E3	0	0
0	NA	NA	Gammaproteobacteria	Oceanospirillales	Microbacteriaceae	Luteipulveratus	Bacillus sp. YP1	0	0
0	NA	NA	Alphaproteobacteria	Flavobacteriales	Gallionellaceae	Auritidibacter	Candidatus Kinetoplastibacterium sorsogonicusi	0	0
0	NA	NA	Betaproteobacteria	Rhodospirillales	Burkholderiaceae	Komagataeibacter	Acidilobus sp. 7A	0	0
0	NA	NA	Bacilli	Sphingomonadales	Opitutaceae	Pontimonas	Mycobacteroides saopaulense	0	0
0	NA	NA	Gammaproteobacteria	Neisseriales	Pseudomonadaceae	Actinotignum	Edwardsiella sp. EA181011	0	0
0	NA	NA	Alphaproteobacteria	Rhodocyclales	Dermacoccaceae	Mycolicibacterium	Halocynthiibacter arcticus	0	0
0	NA	NA	Betaproteobacteria	Campylobacterales	Actinopolysporaceae	Azospirillum	Candidatus Nitrosopumilus adriaticus	0	0
0	NA	NA	Bacilli	Myxococcales	Neisseriaceae	Brucella	Phaeobacter piscinae	0	0
0	NA	NA	Gammaproteobacteria	Oscillatoriales	Enterobacteriaceae	Pseudomonas	Sulfurospirillum sp. UCH001	0	0
0	NA	NA	Alphaproteobacteria	Nitrosomonadales	Micrococcaceae	Xanthomonas	Candidatus Methylopumilus planktonicus	0	0
0	NA	NA	Betaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Rhizobium	Clostridium phage phiCD211	0	0
0	NA	NA	Bacilli	Pseudomonadales	Actinomycetaceae	Acinetobacter	Myroides sp. A21	0	0
0	NA	NA	Gammaproteobacteria	Burkholderiales	Streptomycetaceae	Neisseria	Pseudomonas cerasi	0	0
0	NA	NA	Alphaproteobacteria	Micrococcales	Bifidobacteriaceae	Alcaligenes	Massilia sp. YMA4	0	0
0	NA	NA	Betaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Chromobacterium	Planococcus faecalis	0	0
0	NA	NA	Bacilli	Streptomycetales	Comamonadaceae	Citrobacter	Pandoravirus inopinatum	0	0
0	NA	NA	Gammaproteobacteria	Xanthomonadales	Promicromonosporaceae	Enterobacter	Acinetobacter sp. NCu2D-2	0	0
0	NA	NA	Alphaproteobacteria	Oceanospirillales	Microbacteriaceae	Klebsiella	Euzebya sp. DY32-46	0	0
0	NA	NA	Betaproteobacteria	Flavobacteriales	Gallionellaceae	Aeromonas	Pyrococcus kukulkanii	0	0
0	NA	NA	Bacilli	Rhodospirillales	Burkholderiaceae	Vibrio	Confluentimicrobium sp. EMB200-NS6	0	0
0	NA	NA	Gammaproteobacteria	Sphingomonadales	Opitutaceae	Haemophilus	Methanobrevibacter sp. YE315	0	0
0	NA	NA	Alphaproteobacteria	Neisseriales	Pseudomonadaceae	Aerococcus	Sphingomonas hengshuiensis	0	0
0	NA	NA	Betaproteobacteria	Rhodocyclales	Dermacoccaceae	Bacillus	Halomonas sp. R57-5	0	0
0	NA	NA	Bacilli	Campylobacterales	Actinopolysporaceae	Clavibacter	Pseudomonas sp. MRSN12121	0	0
0	NA	NA	Gammaproteobacteria	Myxococcales	Neisseriaceae	Actinomyces	Actinoalloteichus sp. GBA129-24	0	0
0	NA	NA	Alphaproteobacteria	Oscillatoriales	Enterobacteriaceae	Bifidobacterium	Actinoalloteichus sp. ADI127-7	0	0
0	NA	NA	Betaproteobacteria	Nitrosomonadales	Micrococcaceae	Corynebacterium	Geminocystis sp. NIES-3708	0	0
0	NA	NA	Bacilli	Desulfuromonadales	Thermomonosporaceae	Mycobacterium	Geminocystis sp. NIES-3709	0	0
0	NA	NA	Gammaproteobacteria	Pseudomonadales	Actinomycetaceae	Nocardia	Nostoc sp. 'Lobaria pulmonaria (5183) cyanobiont'	0	0
0	NA	NA	Alphaproteobacteria	Burkholderiales	Streptomycetaceae	Rhodococcus	Cnuibacter physcomitrellae	0	0
0	NA	NA	Betaproteobacteria	Micrococcales	Bifidobacteriaceae	Pseudonocardia	Lutibacter profundi	0	0
0	NA	NA	Bacilli	Pseudonocardiales	Xanthomonadaceae	Streptomyces	Pseudomonas kribbensis	0	0
0	NA	NA	Gammaproteobacteria	Streptomycetales	Comamonadaceae	Marinobacter	Bacillus sp. LM 4-2	0	0
0	NA	NA	Alphaproteobacteria	Xanthomonadales	Promicromonosporaceae	Halomonas	Dermabacter vaginalis	0	0
0	NA	NA	Betaproteobacteria	Oceanospirillales	Microbacteriaceae	Begomovirus	Planctomyces sp. SH-PL14	0	0
0	NA	NA	Bacilli	Flavobacteriales	Gallionellaceae	Magnetospirillum	Citromicrobium sp. JL477	0	0
0	NA	NA	Gammaproteobacteria	Rhodospirillales	Burkholderiaceae	Rubrivivax	Planctomyces sp. SH-PL62	0	0
0	NA	NA	Alphaproteobacteria	Sphingomonadales	Opitutaceae	Janthinobacterium	Proteus phage vB_PmiM_Pm5461	0	0
0	NA	NA	Betaproteobacteria	Neisseriales	Pseudomonadaceae	Burkholderia	Acinetobacter sp. ACNIH1	0	0
0	NA	NA	Bacilli	Rhodocyclales	Dermacoccaceae	Exiguobacterium	Aeromonas sp. ASNIH1	0	0
0	NA	NA	Gammaproteobacteria	Campylobacterales	Actinopolysporaceae	Variovorax	Aeromonas sp. ASNIH4	0	0
0	NA	NA	Alphaproteobacteria	Myxococcales	Neisseriaceae	Rubrobacter	Burkholderia sp. MSMB617WGS	0	0
0	NA	NA	Betaproteobacteria	Oscillatoriales	Enterobacteriaceae	Pseudoalteromonas	Burkholderia sp. MSMB0266	0	0
0	NA	NA	Bacilli	Nitrosomonadales	Micrococcaceae	Methylovorus	Burkholderia sp. MSMB0852	0	0
0	NA	NA	Gammaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Leclercia	Burkholderia sp. NRF60-BP8	0	0
0	NA	NA	Alphaproteobacteria	Pseudomonadales	Actinomycetaceae	Pandoraea	Burkholderia sp. MSMB0856	0	0
0	NA	NA	Betaproteobacteria	Burkholderiales	Streptomycetaceae	Arsenicicoccus	Verrucomicrobia bacterium IMCC26134	0	0
0	NA	NA	Bacilli	Micrococcales	Bifidobacteriaceae	Zobellella	Magnetospirillum sp. ME-1	0	0
0	NA	NA	Gammaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Mycobacteroides	Pseudonocardia sp. HH130629-09	0	0
0	NA	NA	Alphaproteobacteria	Streptomycetales	Comamonadaceae	Luteipulveratus	Streptomyces alfalfae	0	0
0	NA	NA	Betaproteobacteria	Xanthomonadales	Promicromonosporaceae	Auritidibacter	Devosia sp. H5989	0	0
0	NA	NA	Bacilli	Oceanospirillales	Microbacteriaceae	Komagataeibacter	Maribacter sp. 1_2014MBL_MicDiv	0	0
0	NA	NA	Gammaproteobacteria	Flavobacteriales	Gallionellaceae	Pontimonas	Janthinobacterium sp. 1_2014MBL_MicDiv	0	0
0	NA	NA	Alphaproteobacteria	Rhodospirillales	Burkholderiaceae	Actinotignum	Anabaena sp. WA102	0	0
0	NA	NA	Betaproteobacteria	Sphingomonadales	Opitutaceae	Mycolicibacterium	Bacillus paralicheniformis	0	0
0	NA	NA	Bacilli	Neisseriales	Pseudomonadaceae	Azospirillum	Streptomyces sp. CFMR 7	0	0
0	NA	NA	Gammaproteobacteria	Rhodocyclales	Dermacoccaceae	Brucella	Pseudomonas sp. CCOS 191	0	0
0	NA	NA	Alphaproteobacteria	Campylobacterales	Actinopolysporaceae	Pseudomonas	Edwardsiella sp. LADL05-105	0	0
0	NA	NA	Betaproteobacteria	Myxococcales	Neisseriaceae	Xanthomonas	Corynebacterium crudilactis	0	0
0	NA	NA	Bacilli	Oscillatoriales	Enterobacteriaceae	Rhizobium	Arthrobacter sp. YC-RL1	0	0
0	NA	NA	Gammaproteobacteria	Nitrosomonadales	Micrococcaceae	Acinetobacter	Caldimicrobium thiodismutans	0	0
0	NA	NA	Alphaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Neisseria	Rhodococcus sp. PBTS 2	0	0
0	NA	NA	Betaproteobacteria	Pseudomonadales	Actinomycetaceae	Alcaligenes	Alloactinosynnema sp. L-07	0	0
0	NA	NA	Bacilli	Burkholderiales	Streptomycetaceae	Chromobacterium	Kallithea virus	0	0
0	NA	NA	Gammaproteobacteria	Micrococcales	Bifidobacteriaceae	Citrobacter	Gokushovirinae Bog1183_53	0	0
0	NA	NA	Alphaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Enterobacter	Mitsuaria sp. 7	0	0
0	NA	NA	Betaproteobacteria	Streptomycetales	Comamonadaceae	Klebsiella	Ottowia sp. oral taxon 894	0	0
0	NA	NA	Bacilli	Xanthomonadales	Promicromonosporaceae	Aeromonas	Campylobacter sp. RM6137	0	0
0	NA	NA	Gammaproteobacteria	Oceanospirillales	Microbacteriaceae	Vibrio	Campylobacter sp. RM8964	0	0
0	NA	NA	Alphaproteobacteria	Flavobacteriales	Gallionellaceae	Haemophilus	Campylobacter sp. RM12175	0	0
0	NA	NA	Betaproteobacteria	Rhodospirillales	Burkholderiaceae	Aerococcus	Leptospirillum sp. Group II 'CF-1'	0	0
0	NA	NA	Bacilli	Sphingomonadales	Opitutaceae	Bacillus	Streptomyces sp. Tue 6075	0	0
0	NA	NA	Gammaproteobacteria	Neisseriales	Pseudomonadaceae	Clavibacter	Methylophilus sp. TWE2	0	0
0	NA	NA	Alphaproteobacteria	Rhodocyclales	Dermacoccaceae	Actinomyces	Magnetospirillum sp. XM-1	0	0
0	NA	NA	Betaproteobacteria	Campylobacterales	Actinopolysporaceae	Bifidobacterium	Bacillus glycinifermentans	0	0
0	NA	NA	Bacilli	Myxococcales	Neisseriaceae	Corynebacterium	Mesorhizobium oceanicum	0	0
0	NA	NA	Gammaproteobacteria	Oscillatoriales	Enterobacteriaceae	Mycobacterium	Sphingobium hydrophobicum	0	0
0	NA	NA	Alphaproteobacteria	Nitrosomonadales	Micrococcaceae	Nocardia	Cuniculiplasma divulgatum	0	0
0	NA	NA	Betaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Rhodococcus	Labrenzia sp. CP4	0	0
0	NA	NA	Bacilli	Pseudomonadales	Actinomycetaceae	Pseudonocardia	Thermococcus sp. 2319x1	0	0
0	NA	NA	Gammaproteobacteria	Burkholderiales	Streptomycetaceae	Streptomyces	Megasphaera hexanoica	0	0
0	NA	NA	Alphaproteobacteria	Micrococcales	Bifidobacteriaceae	Marinobacter	Sulfurifustis variabilis	0	0
0	NA	NA	Betaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Halomonas	Hungateiclostridium saccincola	0	0
0	NA	NA	Bacilli	Streptomycetales	Comamonadaceae	Begomovirus	Massilia sp. NR 4-1	0	0
0	NA	NA	Gammaproteobacteria	Xanthomonadales	Promicromonosporaceae	Magnetospirillum	Limnohabitans sp. 63ED37-2	0	0
0	NA	NA	Alphaproteobacteria	Oceanospirillales	Microbacteriaceae	Rubrivivax	Limnohabitans sp. 103DPR2	0	0
0	NA	NA	Betaproteobacteria	Flavobacteriales	Gallionellaceae	Janthinobacterium	Burkholderia sp. HB1	0	0
0	NA	NA	Bacilli	Rhodospirillales	Burkholderiaceae	Burkholderia	Akkermansia glycaniphila	0	0
0	NA	NA	Gammaproteobacteria	Sphingomonadales	Opitutaceae	Exiguobacterium	Herbinix luporum	0	0
0	NA	NA	Alphaproteobacteria	Neisseriales	Pseudomonadaceae	Variovorax	Mycobacterium sp. YC-RL4	0	0
0	NA	NA	Betaproteobacteria	Rhodocyclales	Dermacoccaceae	Rubrobacter	Chryseobacterium glaciei	0	0
0	NA	NA	Bacilli	Campylobacterales	Actinopolysporaceae	Pseudoalteromonas	Lake Sarah-associated circular virus-6	0	0
0	NA	NA	Gammaproteobacteria	Myxococcales	Neisseriaceae	Methylovorus	Bartonella apis	0	0
0	NA	NA	Alphaproteobacteria	Oscillatoriales	Enterobacteriaceae	Leclercia	Pseudonocardia sp. EC080610-09	0	0
0	NA	NA	Betaproteobacteria	Nitrosomonadales	Micrococcaceae	Pandoraea	Streptomyces spongiicola	0	0
0	NA	NA	Bacilli	Desulfuromonadales	Thermomonosporaceae	Arsenicicoccus	Arthrobacter sp. LS16	0	0
0	NA	NA	Gammaproteobacteria	Pseudomonadales	Actinomycetaceae	Zobellella	Brevibacillus phage Sundance	0	0
0	NA	NA	Alphaproteobacteria	Burkholderiales	Streptomycetaceae	Mycobacteroides	Enterobacter sp. FY-07	0	0
0	NA	NA	Betaproteobacteria	Micrococcales	Bifidobacteriaceae	Luteipulveratus	Paenibacillus sp. 32O-W	0	0
0	NA	NA	Bacilli	Pseudonocardiales	Xanthomonadaceae	Auritidibacter	Microbacterium sp. CGR1	0	0
0	NA	NA	Gammaproteobacteria	Streptomycetales	Comamonadaceae	Komagataeibacter	Bordetella sp. H567	0	0
0	NA	NA	Alphaproteobacteria	Xanthomonadales	Promicromonosporaceae	Pontimonas	Oblitimonas alkaliphila	0	0
0	NA	NA	Betaproteobacteria	Oceanospirillales	Microbacteriaceae	Actinotignum	Psychrobacter sp. P2G3	0	0
0	NA	NA	Bacilli	Flavobacteriales	Gallionellaceae	Mycolicibacterium	Psychrobacter sp. P11G5	0	0
0	NA	NA	Gammaproteobacteria	Rhodospirillales	Burkholderiaceae	Azospirillum	Kocuria sp. BT304	0	0
0	NA	NA	Alphaproteobacteria	Sphingomonadales	Opitutaceae	Brucella	Citrobacter sp. FDAARGOS_156	0	0
0	NA	NA	Betaproteobacteria	Neisseriales	Pseudomonadaceae	Pseudomonas	Faecalibaculum rodentium	0	0
0	NA	NA	Bacilli	Rhodocyclales	Dermacoccaceae	Xanthomonas	Negativicoccus massiliensis	0	0
0	NA	NA	Gammaproteobacteria	Campylobacterales	Actinopolysporaceae	Rhizobium	Chelatococcus sp. CO-6	0	0
0	NA	NA	Alphaproteobacteria	Myxococcales	Neisseriaceae	Acinetobacter	Rhizobium sp. N1314	0	0
0	NA	NA	Betaproteobacteria	Oscillatoriales	Enterobacteriaceae	Neisseria	Rhizobium sp. N731	0	0
0	NA	NA	Bacilli	Nitrosomonadales	Micrococcaceae	Alcaligenes	Rhizobium sp. N324	0	0
0	NA	NA	Gammaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Chromobacterium	Arthrobacter sp. ERGS1:01	0	0
0	NA	NA	Alphaproteobacteria	Pseudomonadales	Actinomycetaceae	Citrobacter	Methylovulum psychrotolerans	0	0
0	NA	NA	Betaproteobacteria	Burkholderiales	Streptomycetaceae	Enterobacter	Thermococcus piezophilus	0	0
0	NA	NA	Bacilli	Micrococcales	Bifidobacteriaceae	Klebsiella	Turicibacter sp. H121	0	0
0	NA	NA	Gammaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Aeromonas	Microbacterium sp. No. 7	0	0
0	NA	NA	Alphaproteobacteria	Streptomycetales	Comamonadaceae	Vibrio	Alteromonas sp. BL110	0	0
0	NA	NA	Betaproteobacteria	Xanthomonadales	Promicromonosporaceae	Haemophilus	Aquimarina sp. AD1	0	0
0	NA	NA	Bacilli	Oceanospirillales	Microbacteriaceae	Aerococcus	Aquimarina sp. AD10	0	0
0	NA	NA	Gammaproteobacteria	Flavobacteriales	Gallionellaceae	Bacillus	Aquimarina sp. BL5	0	0
0	NA	NA	Alphaproteobacteria	Rhodospirillales	Burkholderiaceae	Clavibacter	Staphylococcus sp. AntiMn-1	0	0
0	NA	NA	Betaproteobacteria	Sphingomonadales	Opitutaceae	Actinomyces	Marinifilaceae bacterium SPP2	0	0
0	NA	NA	Bacilli	Neisseriales	Pseudomonadaceae	Bifidobacterium	Pseudoalteromonas sp. 1_2015MBL_MicDiv	0	0
0	NA	NA	Gammaproteobacteria	Rhodocyclales	Dermacoccaceae	Corynebacterium	Chryseobacterium sp. IHB B 17019	0	0
0	NA	NA	Alphaproteobacteria	Campylobacterales	Actinopolysporaceae	Mycobacterium	Streptomyces sp. CdTB01	0	0
0	NA	NA	Betaproteobacteria	Myxococcales	Neisseriaceae	Nocardia	Pedobacter sp. PACM 27299	0	0
0	NA	NA	Bacilli	Oscillatoriales	Enterobacteriaceae	Rhodococcus	Methylomonas sp. DH-1	0	0
0	NA	NA	Gammaproteobacteria	Nitrosomonadales	Micrococcaceae	Pseudonocardia	Acidianus bottle-shaped virus 3	0	0
0	NA	NA	Alphaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Streptomyces	Algibacter alginicilyticus	0	0
0	NA	NA	Betaproteobacteria	Pseudomonadales	Actinomycetaceae	Marinobacter	Corynebacterium provencense	0	0
0	NA	NA	Bacilli	Burkholderiales	Streptomycetaceae	Halomonas	Agarilytica rhodophyticola	0	0
0	NA	NA	Gammaproteobacteria	Micrococcales	Bifidobacteriaceae	Begomovirus	Burkholderia sp. Bp7605	0	0
0	NA	NA	Alphaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Magnetospirillum	Polynucleobacter sp. MWH-Creno-4B4	0	0
0	NA	NA	Betaproteobacteria	Streptomycetales	Comamonadaceae	Rubrivivax	Marinobacter sp. LQ44	0	0
0	NA	NA	Bacilli	Xanthomonadales	Promicromonosporaceae	Janthinobacterium	Nostoc sp. NIES-3756	0	0
0	NA	NA	Gammaproteobacteria	Oceanospirillales	Microbacteriaceae	Burkholderia	Streptomyces sp. 4F	0	0
0	NA	NA	Alphaproteobacteria	Flavobacteriales	Gallionellaceae	Exiguobacterium	Fischerella sp. NIES-3754	0	0
0	NA	NA	Betaproteobacteria	Rhodospirillales	Burkholderiaceae	Variovorax	Paraphotobacterium marinum	0	0
0	NA	NA	Bacilli	Sphingomonadales	Opitutaceae	Rubrobacter	Elizabethkingia bruuniana	0	0
0	NA	NA	Gammaproteobacteria	Neisseriales	Pseudomonadaceae	Pseudoalteromonas	Elizabethkingia ursingii	0	0
0	NA	NA	Alphaproteobacteria	Rhodocyclales	Dermacoccaceae	Methylovorus	Nitratireductor sp. OM-1	0	0
0	NA	NA	Betaproteobacteria	Campylobacterales	Actinopolysporaceae	Leclercia	Celeribacter ethanolicus	0	0
0	NA	NA	Bacilli	Myxococcales	Neisseriaceae	Pandoraea	Aeromonas sp. ASNIH5	0	0
0	NA	NA	Gammaproteobacteria	Oscillatoriales	Enterobacteriaceae	Arsenicicoccus	Acinetobacter sp. ACNIH2	0	0
0	NA	NA	Alphaproteobacteria	Nitrosomonadales	Micrococcaceae	Zobellella	Achromobacter sp. AONIH1	0	0
0	NA	NA	Betaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Mycobacteroides	Serratia sp. SSNIH1	0	0
0	NA	NA	Bacilli	Pseudomonadales	Actinomycetaceae	Luteipulveratus	Serinicoccus sp. JLT9	0	0
0	NA	NA	Gammaproteobacteria	Burkholderiales	Streptomycetaceae	Auritidibacter	Caulobacteraceae bacterium OTSz_A_272	0	0
0	NA	NA	Alphaproteobacteria	Micrococcales	Bifidobacteriaceae	Komagataeibacter	Streptococcus sp. A12	0	0
0	NA	NA	Betaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Pontimonas	Serratia sp. YD25	0	0
0	NA	NA	Bacilli	Streptomycetales	Comamonadaceae	Actinotignum	Paraburkholderia caffeinilytica	0	0
0	NA	NA	Gammaproteobacteria	Xanthomonadales	Promicromonosporaceae	Mycolicibacterium	cyanobacterium endosymbiont of Rhopalodia gibberula	0	0
0	NA	NA	Alphaproteobacteria	Oceanospirillales	Microbacteriaceae	Azospirillum	Flavobacterium crassostreae	0	0
0	NA	NA	Betaproteobacteria	Flavobacteriales	Gallionellaceae	Brucella	Thalassotalea crassostreae	0	0
0	NA	NA	Bacilli	Rhodospirillales	Burkholderiaceae	Pseudomonas	Paenibacillus crassostreae	0	0
0	NA	NA	Gammaproteobacteria	Sphingomonadales	Opitutaceae	Xanthomonas	Deinococcus actinosclerus	0	0
0	NA	NA	Alphaproteobacteria	Neisseriales	Pseudomonadaceae	Rhizobium	Paucibacter sp. KCTC 42545	0	0
0	NA	NA	Betaproteobacteria	Rhodocyclales	Dermacoccaceae	Acinetobacter	Salinicola tamaricis	0	0
0	NA	NA	Bacilli	Campylobacterales	Actinopolysporaceae	Neisseria	Polaribacter vadi	0	0
0	NA	NA	Gammaproteobacteria	Myxococcales	Neisseriaceae	Alcaligenes	Candidatus Hoaglandella endobia	0	0
0	NA	NA	Alphaproteobacteria	Oscillatoriales	Enterobacteriaceae	Chromobacterium	Chromobacterium rhizoryzae	0	0
0	NA	NA	Betaproteobacteria	Nitrosomonadales	Micrococcaceae	Citrobacter	Streptomyces qaidamensis	0	0
0	NA	NA	Bacilli	Desulfuromonadales	Thermomonosporaceae	Enterobacter	Flavobacterium arcticum	0	0
0	NA	NA	Gammaproteobacteria	Pseudomonadales	Actinomycetaceae	Klebsiella	Arcticibacterium luteifluviistationis	0	0
0	NA	NA	Alphaproteobacteria	Burkholderiales	Streptomycetaceae	Aeromonas	Acinetobacter lactucae	0	0
0	NA	NA	Betaproteobacteria	Micrococcales	Bifidobacteriaceae	Vibrio	Gemella sp. oral taxon 928	0	0
0	NA	NA	Bacilli	Pseudonocardiales	Xanthomonadaceae	Haemophilus	Leptotrichia sp. oral taxon 847	0	0
0	NA	NA	Gammaproteobacteria	Streptomycetales	Comamonadaceae	Aerococcus	Pseudomonas versuta	0	0
0	NA	NA	Alphaproteobacteria	Xanthomonadales	Promicromonosporaceae	Bacillus	Acinetobacter larvae	0	0
0	NA	NA	Betaproteobacteria	Oceanospirillales	Microbacteriaceae	Clavibacter	Methanosphaera sp. BMS	0	0
0	NA	NA	Bacilli	Flavobacteriales	Gallionellaceae	Actinomyces	Bosea sp. PAMC 26642	0	0
0	NA	NA	Gammaproteobacteria	Rhodospirillales	Burkholderiaceae	Bifidobacterium	Yangia sp. CCB-MM3	0	0
0	NA	NA	Alphaproteobacteria	Sphingomonadales	Opitutaceae	Corynebacterium	Stenotrophomonas sp. KCTC 12332	0	0
0	NA	NA	Betaproteobacteria	Neisseriales	Pseudomonadaceae	Mycobacterium	Burkholderia sp. PAMC 26561	0	0
0	NA	NA	Bacilli	Rhodocyclales	Dermacoccaceae	Nocardia	Variovorax sp. PAMC 28711	0	0
0	NA	NA	Gammaproteobacteria	Campylobacterales	Actinopolysporaceae	Rhodococcus	Burkholderia sp. PAMC 28687	0	0
0	NA	NA	Alphaproteobacteria	Myxococcales	Neisseriaceae	Pseudonocardia	Bacteroides caecimuris	0	0
0	NA	NA	Betaproteobacteria	Oscillatoriales	Enterobacteriaceae	Streptomyces	Blautia sp. YL58	0	0
0	NA	NA	Bacilli	Nitrosomonadales	Micrococcaceae	Marinobacter	Flavivirga eckloniae	0	0
0	NA	NA	Gammaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Halomonas	Burkholderia sp. OLGA172	0	0
0	NA	NA	Alphaproteobacteria	Pseudomonadales	Actinomycetaceae	Begomovirus	Amycolatopsis albispora	0	0
0	NA	NA	Betaproteobacteria	Burkholderiales	Streptomycetaceae	Magnetospirillum	Mycobacterium phage Bipper	0	0
0	NA	NA	Bacilli	Micrococcales	Bifidobacteriaceae	Rubrivivax	Rhodococcus sp. MTM3W5.2	0	0
0	NA	NA	Gammaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Janthinobacterium	Candidatus Promineofilum breve	0	0
0	NA	NA	Alphaproteobacteria	Streptomycetales	Comamonadaceae	Burkholderia	Arthrobacter sp. ZXY-2	0	0
0	NA	NA	Betaproteobacteria	Xanthomonadales	Promicromonosporaceae	Exiguobacterium	Stanieria sp. NIES-3757	0	0
0	NA	NA	Bacilli	Oceanospirillales	Microbacteriaceae	Variovorax	Acinetobacter sp. LoGeW2-3	0	0
0	NA	NA	Gammaproteobacteria	Flavobacteriales	Gallionellaceae	Rubrobacter	Herminiimonas arsenitoxidans	0	0
0	NA	NA	Alphaproteobacteria	Rhodospirillales	Burkholderiaceae	Pseudoalteromonas	Immundisolibacter cernigliae	0	0
0	NA	NA	Betaproteobacteria	Sphingomonadales	Opitutaceae	Methylovorus	Streptomyces sp. fd1-xmd	0	0
0	NA	NA	Bacilli	Neisseriales	Pseudomonadaceae	Leclercia	Enterobacter roggenkampii	0	0
0	NA	NA	Gammaproteobacteria	Rhodocyclales	Dermacoccaceae	Pandoraea	Campylobacter hepaticus	0	0
0	NA	NA	Alphaproteobacteria	Campylobacterales	Actinopolysporaceae	Arsenicicoccus	Shigella sp. PAMC 28760	0	0
0	NA	NA	Betaproteobacteria	Myxococcales	Neisseriaceae	Zobellella	Streptococcus halotolerans	0	0
0	NA	NA	Bacilli	Oscillatoriales	Enterobacteriaceae	Mycobacteroides	Colwellia sp. PAMC 20917	0	0
0	NA	NA	Gammaproteobacteria	Nitrosomonadales	Micrococcaceae	Luteipulveratus	Desulfuromonas sp. DDH964	0	0
0	NA	NA	Alphaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Auritidibacter	Synechococcus sp. NIES-970	0	0
0	NA	NA	Betaproteobacteria	Pseudomonadales	Actinomycetaceae	Komagataeibacter	Bacillus sp. IHB B 7164	0	0
0	NA	NA	Bacilli	Burkholderiales	Streptomycetaceae	Pontimonas	Pseudomonas sp. MYb193	0	0
0	NA	NA	Gammaproteobacteria	Micrococcales	Bifidobacteriaceae	Actinotignum	Stenotrophomonas sp. MYb57	0	0
0	NA	NA	Alphaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Mycolicibacterium	Brevundimonas sp. GW460-12-10-14-LB2	0	0
0	NA	NA	Betaproteobacteria	Streptomycetales	Comamonadaceae	Azospirillum	Streptomyces nigra	0	0
0	NA	NA	Bacilli	Xanthomonadales	Promicromonosporaceae	Brucella	Desulfotomaculum ferrireducens	0	0
0	NA	NA	Gammaproteobacteria	Oceanospirillales	Microbacteriaceae	Pseudomonas	Lachnoclostridium sp. YL32	0	0
0	NA	NA	Alphaproteobacteria	Flavobacteriales	Gallionellaceae	Xanthomonas	Burkholderiales bacterium YL45	0	0
0	NA	NA	Betaproteobacteria	Rhodospirillales	Burkholderiaceae	Rhizobium	Maribacter sp. T28	0	0
0	NA	NA	Bacilli	Sphingomonadales	Opitutaceae	Acinetobacter	Bacillus sp. FJAT-14266	0	0
0	NA	NA	Gammaproteobacteria	Neisseriales	Pseudomonadaceae	Neisseria	Streptomyces sp. S8	0	0
0	NA	NA	Alphaproteobacteria	Rhodocyclales	Dermacoccaceae	Alcaligenes	Bacillus sp. FDAARGOS_235	0	0
0	NA	NA	Betaproteobacteria	Campylobacterales	Actinopolysporaceae	Chromobacterium	Streptococcus sp. FDAARGOS_192	0	0
0	NA	NA	Bacilli	Myxococcales	Neisseriaceae	Citrobacter	Streptomyces sp. RTd22	0	0
0	NA	NA	Gammaproteobacteria	Oscillatoriales	Enterobacteriaceae	Enterobacter	Gordonibacter massiliensis	0	0
0	NA	NA	Alphaproteobacteria	Nitrosomonadales	Micrococcaceae	Klebsiella	Pelobacter sp. SFB93	0	0
0	NA	NA	Betaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Aeromonas	Acidovorax sp. RAC01	0	0
0	NA	NA	Bacilli	Pseudomonadales	Actinomycetaceae	Vibrio	Sinorhizobium sp. RAC02	0	0
0	NA	NA	Gammaproteobacteria	Burkholderiales	Streptomycetaceae	Haemophilus	Blastomonas sp. RAC04	0	0
0	NA	NA	Alphaproteobacteria	Micrococcales	Bifidobacteriaceae	Aerococcus	Bosea sp. RAC05	0	0
0	NA	NA	Betaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Bacillus	Methyloversatilis sp. RAC08	0	0
0	NA	NA	Bacilli	Streptomycetales	Comamonadaceae	Clavibacter	Rhodoferax koreense	0	0
0	NA	NA	Gammaproteobacteria	Xanthomonadales	Promicromonosporaceae	Actinomyces	Sphingobium sp. RAC03	0	0
0	NA	NA	Alphaproteobacteria	Oceanospirillales	Microbacteriaceae	Bifidobacterium	Phaeobacter porticola	0	0
0	NA	NA	Betaproteobacteria	Flavobacteriales	Gallionellaceae	Corynebacterium	Lactobacillus allii	0	0
0	NA	NA	Bacilli	Rhodospirillales	Burkholderiaceae	Mycobacterium	Capnocytophaga stomatis	0	0
0	NA	NA	Gammaproteobacteria	Sphingomonadales	Opitutaceae	Nocardia	Exiguobacterium sp. U13-1	0	0
0	NA	NA	Alphaproteobacteria	Neisseriales	Pseudomonadaceae	Rhodococcus	Arthrobacter sp. U41	0	0
0	NA	NA	Betaproteobacteria	Rhodocyclales	Dermacoccaceae	Pseudonocardia	Auricoccus indicus	0	0
0	NA	NA	Bacilli	Campylobacterales	Actinopolysporaceae	Streptomyces	Streptomyces sp. SAT1	0	0
0	NA	NA	Gammaproteobacteria	Myxococcales	Neisseriaceae	Marinobacter	Rhodobacter sp. LPB0142	0	0
0	NA	NA	Alphaproteobacteria	Oscillatoriales	Enterobacteriaceae	Halomonas	Tenacibaculum todarodis	0	0
0	NA	NA	Betaproteobacteria	Nitrosomonadales	Micrococcaceae	Begomovirus	Arcobacter sp. LPB0137	0	0
0	NA	NA	Bacilli	Desulfuromonadales	Thermomonosporaceae	Magnetospirillum	Arachidicoccus sp. BS20	0	0
0	NA	NA	Gammaproteobacteria	Pseudomonadales	Actinomycetaceae	Rubrivivax	Orrella dioscoreae	0	0
0	NA	NA	Alphaproteobacteria	Burkholderiales	Streptomycetaceae	Janthinobacterium	Bacillus phage Belinda	0	0
0	NA	NA	Betaproteobacteria	Micrococcales	Bifidobacteriaceae	Burkholderia	Pseudomonas silesiensis	0	0
0	NA	NA	Bacilli	Pseudonocardiales	Xanthomonadaceae	Exiguobacterium	Neisseria sp. 10022	0	0
0	NA	NA	Gammaproteobacteria	Streptomycetales	Comamonadaceae	Variovorax	Neisseria sp. 10023	0	0
0	NA	NA	Alphaproteobacteria	Xanthomonadales	Promicromonosporaceae	Rubrobacter	Macrococcus canis	0	0
0	NA	NA	Betaproteobacteria	Oceanospirillales	Microbacteriaceae	Pseudoalteromonas	Luteitalea pratensis	0	0
0	NA	NA	Bacilli	Flavobacteriales	Gallionellaceae	Methylovorus	Bacillus sp. H15-1	0	0
0	NA	NA	Gammaproteobacteria	Rhodospirillales	Burkholderiaceae	Leclercia	Pseudomonas sp. TCU-HL1	0	0
0	NA	NA	Alphaproteobacteria	Sphingomonadales	Opitutaceae	Pandoraea	Acidovorax sp. T1	0	0
0	NA	NA	Betaproteobacteria	Neisseriales	Pseudomonadaceae	Arsenicicoccus	Halothiobacillus sp. LS2	0	0
0	NA	NA	Bacilli	Rhodocyclales	Dermacoccaceae	Zobellella	Phyllobacterium zundukense	0	0
0	NA	NA	Gammaproteobacteria	Campylobacterales	Actinopolysporaceae	Mycobacteroides	Legionella clemsonensis	0	0
0	NA	NA	Alphaproteobacteria	Myxococcales	Neisseriaceae	Luteipulveratus	Enterobacter sp. HK169	0	0
0	NA	NA	Betaproteobacteria	Oscillatoriales	Enterobacteriaceae	Auritidibacter	Nostoc sp. CENA543	0	0
0	NA	NA	Bacilli	Nitrosomonadales	Micrococcaceae	Komagataeibacter	Paenibacillus sp. BIHB4019	0	0
0	NA	NA	Gammaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Pontimonas	Paenibacillus ihbetae	0	0
0	NA	NA	Alphaproteobacteria	Pseudomonadales	Actinomycetaceae	Actinotignum	Anaerococcus mediterraneensis	0	0
0	NA	NA	Betaproteobacteria	Burkholderiales	Streptomycetaceae	Mycolicibacterium	Flavobacteriaceae bacterium	0	0
0	NA	NA	Bacilli	Micrococcales	Bifidobacteriaceae	Azospirillum	Acinetobacter defluvii	0	0
0	NA	NA	Gammaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Brucella	Halodesulfurarchaeum formicicum	0	0
0	NA	NA	Alphaproteobacteria	Streptomycetales	Comamonadaceae	Pseudomonas	Bacillus phage Stitch	0	0
0	NA	NA	Betaproteobacteria	Xanthomonadales	Promicromonosporaceae	Xanthomonas	Marinobacter salinus	0	0
0	NA	NA	Bacilli	Oceanospirillales	Microbacteriaceae	Rhizobium	Mycobacterium sp. djl-10	0	0
0	NA	NA	Gammaproteobacteria	Flavobacteriales	Gallionellaceae	Acinetobacter	Acinetobacter sp. WCHAc010034	0	0
0	NA	NA	Alphaproteobacteria	Rhodospirillales	Burkholderiaceae	Neisseria	Acinetobacter wuhouensis	0	0
0	NA	NA	Betaproteobacteria	Sphingomonadales	Opitutaceae	Alcaligenes	Microvirga ossetica	0	0
0	NA	NA	Bacilli	Neisseriales	Pseudomonadaceae	Chromobacterium	Synechococcus phage S-CAM22	0	0
0	NA	NA	Gammaproteobacteria	Rhodocyclales	Dermacoccaceae	Citrobacter	Erwinia phage vB_EamM_Asesino	0	0
0	NA	NA	Alphaproteobacteria	Campylobacterales	Actinopolysporaceae	Enterobacter	Halomonas sp. 1513	0	0
0	NA	NA	Betaproteobacteria	Myxococcales	Neisseriaceae	Klebsiella	Candidatus Planktophila dulcis	0	0
0	NA	NA	Bacilli	Oscillatoriales	Enterobacteriaceae	Aeromonas	Candidatus Nanopelagicus abundans	0	0
0	NA	NA	Gammaproteobacteria	Nitrosomonadales	Micrococcaceae	Vibrio	Streptococcus himalayensis	0	0
0	NA	NA	Alphaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Haemophilus	Sulfolobus sp. A20	0	0
0	NA	NA	Betaproteobacteria	Pseudomonadales	Actinomycetaceae	Aerococcus	Fuerstia marisgermanicae	0	0
0	NA	NA	Bacilli	Burkholderiales	Streptomycetaceae	Bacillus	Porphyrobacter sp. LM 6	0	0
0	NA	NA	Gammaproteobacteria	Micrococcales	Bifidobacteriaceae	Clavibacter	Amycolatopsis sp. AA4	0	0
0	NA	NA	Alphaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Actinomyces	Halomonas aestuarii	0	0
0	NA	NA	Betaproteobacteria	Streptomycetales	Comamonadaceae	Bifidobacterium	Spiroplasma sp. TU-14	0	0
0	NA	NA	Bacilli	Xanthomonadales	Promicromonosporaceae	Corynebacterium	Rhodocyclaceae bacterium	0	0
0	NA	NA	Gammaproteobacteria	Oceanospirillales	Microbacteriaceae	Mycobacterium	Pseudomonas sp. LPH1	0	0
0	NA	NA	Alphaproteobacteria	Flavobacteriales	Gallionellaceae	Nocardia	Natrialbaceae archaeon JW/NM-HA 15	0	0
0	NA	NA	Betaproteobacteria	Rhodospirillales	Burkholderiaceae	Rhodococcus	Brachybacterium sp. P6-10-X1	0	0
0	NA	NA	Bacilli	Sphingomonadales	Opitutaceae	Pseudonocardia	Oceanisphaera avium	0	0
0	NA	NA	Gammaproteobacteria	Neisseriales	Pseudomonadaceae	Streptomyces	Tumebacillus avium	0	0
0	NA	NA	Alphaproteobacteria	Rhodocyclales	Dermacoccaceae	Marinobacter	Rhodobacteraceae bacterium	0	0
0	NA	NA	Betaproteobacteria	Campylobacterales	Actinopolysporaceae	Halomonas	Betaproteobacteria bacterium GR16-43	0	0
0	NA	NA	Bacilli	Myxococcales	Neisseriaceae	Begomovirus	Pectobacterium parmentieri	0	0
0	NA	NA	Gammaproteobacteria	Oscillatoriales	Enterobacteriaceae	Magnetospirillum	Curtobacterium sp. BH-2-1-1	0	0
0	NA	NA	Alphaproteobacteria	Nitrosomonadales	Micrococcaceae	Rubrivivax	Lelliottia jeotgali	0	0
0	NA	NA	Betaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Janthinobacterium	Nonomuraea sp. ATCC 55076	0	0
0	NA	NA	Bacilli	Pseudomonadales	Actinomycetaceae	Burkholderia	Tessaracoccus sp. T2.5-30	0	0
0	NA	NA	Gammaproteobacteria	Burkholderiales	Streptomycetaceae	Exiguobacterium	Amycolatopsis sp. BJA-103	0	0
0	NA	NA	Alphaproteobacteria	Micrococcales	Bifidobacteriaceae	Variovorax	Marinilactibacillus sp. 15R	0	0
0	NA	NA	Betaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Rubrobacter	Virgibacillus sp. 6R	0	0
0	NA	NA	Bacilli	Streptomycetales	Comamonadaceae	Pseudoalteromonas	Tenericutes bacterium MZ-XQ	0	0
0	NA	NA	Gammaproteobacteria	Xanthomonadales	Promicromonosporaceae	Methylovorus	Tenericutes bacterium MO-XQ	0	0
0	NA	NA	Alphaproteobacteria	Oceanospirillales	Microbacteriaceae	Leclercia	Methanobacterium sp. MZ-A1	0	0
0	NA	NA	Betaproteobacteria	Flavobacteriales	Gallionellaceae	Pandoraea	Actinomyces sp. VUL4_3	0	0
0	NA	NA	Bacilli	Rhodospirillales	Burkholderiaceae	Arsenicicoccus	Peptoniphilus sp. ING2-D1G	0	0
0	NA	NA	Gammaproteobacteria	Sphingomonadales	Opitutaceae	Zobellella	Spiroplasma sp. NBRC 100390	0	0
0	NA	NA	Alphaproteobacteria	Neisseriales	Pseudomonadaceae	Mycobacteroides	Enterobacter sp. SA187	0	0
0	NA	NA	Betaproteobacteria	Rhodocyclales	Dermacoccaceae	Luteipulveratus	Thioclava nitratireducens	0	0
0	NA	NA	Bacilli	Campylobacterales	Actinopolysporaceae	Auritidibacter	Microbacterium sp. 1.5R	0	0
0	NA	NA	Gammaproteobacteria	Myxococcales	Neisseriaceae	Komagataeibacter	Alteromonas sp. RW2A1	0	0
0	NA	NA	Alphaproteobacteria	Oscillatoriales	Enterobacteriaceae	Pontimonas	Aeromonas sp. ASNIH7	0	0
0	NA	NA	Betaproteobacteria	Nitrosomonadales	Micrococcaceae	Actinotignum	Enterobacteriaceae bacterium ENNIH2	0	0
0	NA	NA	Bacilli	Desulfuromonadales	Thermomonosporaceae	Mycolicibacterium	Leclercia sp. LSNIH1	0	0
0	NA	NA	Gammaproteobacteria	Pseudomonadales	Actinomycetaceae	Azospirillum	Leclercia sp. LSNIH3	0	0
0	NA	NA	Alphaproteobacteria	Burkholderiales	Streptomycetaceae	Brucella	Enterobacteriaceae bacterium ENNIH3	0	0
0	NA	NA	Betaproteobacteria	Micrococcales	Bifidobacteriaceae	Pseudomonas	Delftia sp. HK171	0	0
0	NA	NA	Bacilli	Pseudonocardiales	Xanthomonadaceae	Xanthomonas	Mariprofundus aestuarium	0	0
0	NA	NA	Gammaproteobacteria	Streptomycetales	Comamonadaceae	Rhizobium	Geobacillus genomosp. 3	0	0
0	NA	NA	Alphaproteobacteria	Xanthomonadales	Promicromonosporaceae	Acinetobacter	Candidatus Fonsibacter ubiquis	0	0
0	NA	NA	Betaproteobacteria	Oceanospirillales	Microbacteriaceae	Neisseria	Paraburkholderia sp. SOS3	0	0
0	NA	NA	Bacilli	Flavobacteriales	Gallionellaceae	Alcaligenes	Enterovirus AN12	0	0
0	NA	NA	Gammaproteobacteria	Rhodospirillales	Burkholderiaceae	Chromobacterium	Sodalis endosymbiont of Henestaris halophilus	0	0
0	NA	NA	Alphaproteobacteria	Sphingomonadales	Opitutaceae	Citrobacter	Sporosarcina sp. P37	0	0
0	NA	NA	Betaproteobacteria	Neisseriales	Pseudomonadaceae	Enterobacter	Sporosarcina sp. P33	0	0
0	NA	NA	Bacilli	Rhodocyclales	Dermacoccaceae	Klebsiella	Halorientalis sp. IM1011	0	0
0	NA	NA	Gammaproteobacteria	Campylobacterales	Actinopolysporaceae	Aeromonas	Sphingobacterium sp. B29	0	0
0	NA	NA	Alphaproteobacteria	Myxococcales	Neisseriaceae	Vibrio	Bartonella sp. WD16.2	0	0
0	NA	NA	Betaproteobacteria	Oscillatoriales	Enterobacteriaceae	Haemophilus	Bartonella sp. A1379B	0	0
0	NA	NA	Bacilli	Nitrosomonadales	Micrococcaceae	Aerococcus	Bartonella sp. Raccoon60	0	0
0	NA	NA	Gammaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Bacillus	Klebsiella sp. M5al	0	0
0	NA	NA	Alphaproteobacteria	Pseudomonadales	Actinomycetaceae	Clavibacter	Winogradskyella sp. J14-2	0	0
0	NA	NA	Betaproteobacteria	Burkholderiales	Streptomycetaceae	Actinomyces	Seonamhaeicola sp. S2-3	0	0
0	NA	NA	Bacilli	Micrococcales	Bifidobacteriaceae	Bifidobacterium	Microbacterium sp. TPU 3598	0	0
0	NA	NA	Gammaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Corynebacterium	Aquaspirillum sp. LM1	0	0
0	NA	NA	Alphaproteobacteria	Streptomycetales	Comamonadaceae	Mycobacterium	Janthinobacterium sp. LM6	0	0
0	NA	NA	Betaproteobacteria	Xanthomonadales	Promicromonosporaceae	Nocardia	Sphingomonas sp. LM7	0	0
0	NA	NA	Bacilli	Oceanospirillales	Microbacteriaceae	Rhodococcus	Murine roseolovirus	0	0
0	NA	NA	Gammaproteobacteria	Flavobacteriales	Gallionellaceae	Pseudonocardia	Nostocales cyanobacterium HT-58-2	0	0
0	NA	NA	Alphaproteobacteria	Rhodospirillales	Burkholderiaceae	Streptomyces	Phoenicibacter massiliensis	0	0
0	NA	NA	Betaproteobacteria	Sphingomonadales	Opitutaceae	Marinobacter	Cellvibrio sp. PSBB023	0	0
0	NA	NA	Bacilli	Neisseriales	Pseudomonadaceae	Halomonas	Calothrix sp. NIES-2098	0	0
0	NA	NA	Gammaproteobacteria	Rhodocyclales	Dermacoccaceae	Begomovirus	Noumeavirus	0	0
0	NA	NA	Alphaproteobacteria	Campylobacterales	Actinopolysporaceae	Magnetospirillum	Actinomyces gaoshouyii	0	0
0	NA	NA	Betaproteobacteria	Myxococcales	Neisseriaceae	Rubrivivax	Sphingomonas sp. NIC1	0	0
0	NA	NA	Bacilli	Oscillatoriales	Enterobacteriaceae	Janthinobacterium	Streptomyces sp. MOE7	0	0
0	NA	NA	Gammaproteobacteria	Nitrosomonadales	Micrococcaceae	Burkholderia	Streptomyces sp. 3211	0	0
0	NA	NA	Alphaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Exiguobacterium	Colwellia beringensis	0	0
0	NA	NA	Betaproteobacteria	Pseudomonadales	Actinomycetaceae	Variovorax	Streptomyces sp. Sge12	0	0
0	NA	NA	Bacilli	Burkholderiales	Streptomycetaceae	Rubrobacter	Chromatiaceae bacterium 2141T.STBD.0c.01a	0	0
0	NA	NA	Gammaproteobacteria	Micrococcales	Bifidobacteriaceae	Pseudoalteromonas	Cryobacterium sp. LW097	0	0
0	NA	NA	Alphaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Methylovorus	Cellulosimicrobium sp. TH-20	0	0
0	NA	NA	Betaproteobacteria	Streptomycetales	Comamonadaceae	Leclercia	Rhizobium sp. NXC14	0	0
0	NA	NA	Bacilli	Xanthomonadales	Promicromonosporaceae	Pandoraea	Pseudomonas sp. M30-35	0	0
0	NA	NA	Gammaproteobacteria	Oceanospirillales	Microbacteriaceae	Arsenicicoccus	Altererythrobacter mangrovi	0	0
0	NA	NA	Alphaproteobacteria	Flavobacteriales	Gallionellaceae	Zobellella	Streptomyces sp. CLI2509	0	0
0	NA	NA	Betaproteobacteria	Rhodospirillales	Burkholderiaceae	Mycobacteroides	Sulfuriferula sp. AH1	0	0
0	NA	NA	Bacilli	Sphingomonadales	Opitutaceae	Luteipulveratus	Desulfobulbus sp. ORNL	0	0
0	NA	NA	Gammaproteobacteria	Neisseriales	Pseudomonadaceae	Auritidibacter	Sphingobacteriaceae bacterium GW460-11-11-14-LB5	0	0
0	NA	NA	Alphaproteobacteria	Rhodocyclales	Dermacoccaceae	Komagataeibacter	Cellvibrio sp. PSBB006	0	0
0	NA	NA	Betaproteobacteria	Campylobacterales	Actinopolysporaceae	Pontimonas	Bat associated cyclovirus 11	0	0
0	NA	NA	Bacilli	Myxococcales	Neisseriaceae	Actinotignum	Rhodococcus sp. S2-17	0	0
0	NA	NA	Gammaproteobacteria	Oscillatoriales	Enterobacteriaceae	Mycolicibacterium	Lactobacillales bacterium	0	0
0	NA	NA	Alphaproteobacteria	Nitrosomonadales	Micrococcaceae	Azospirillum	Sphingobacterium sp. G1-14	0	0
0	NA	NA	Betaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Brucella	Cellulomonas sp. PSBB021	0	0
0	NA	NA	Bacilli	Pseudomonadales	Actinomycetaceae	Pseudomonas	Stenotrophomonas sp. WZN-1	0	0
0	NA	NA	Gammaproteobacteria	Burkholderiales	Streptomycetaceae	Xanthomonas	Legionella endosymbiont of Polyplax serrata	0	0
0	NA	NA	Alphaproteobacteria	Micrococcales	Bifidobacteriaceae	Rhizobium	Chondrocystis sp. NIES-4102	0	0
0	NA	NA	Betaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Acinetobacter	Calothrix sp. NIES-4101	0	0
0	NA	NA	Bacilli	Streptomycetales	Comamonadaceae	Neisseria	Calothrix sp. NIES-3974	0	0
0	NA	NA	Gammaproteobacteria	Xanthomonadales	Promicromonosporaceae	Alcaligenes	Calothrix sp. NIES-4071	0	0
0	NA	NA	Alphaproteobacteria	Oceanospirillales	Microbacteriaceae	Chromobacterium	Thauera sp. K11	0	0
0	NA	NA	Betaproteobacteria	Flavobacteriales	Gallionellaceae	Citrobacter	Luteimonas sp. 100111	0	0
0	NA	NA	Bacilli	Rhodospirillales	Burkholderiaceae	Enterobacter	Francisella sp. FDC440	0	0
0	NA	NA	Gammaproteobacteria	Sphingomonadales	Opitutaceae	Klebsiella	Sagittula sp. P11	0	0
0	NA	NA	Alphaproteobacteria	Neisseriales	Pseudomonadaceae	Aeromonas	Bacillus sp. MD-5	0	0
0	NA	NA	Betaproteobacteria	Rhodocyclales	Dermacoccaceae	Vibrio	Chryseobacterium sp. T16E-39	0	0
0	NA	NA	Bacilli	Campylobacterales	Actinopolysporaceae	Haemophilus	Virgibacillus phasianinus	0	0
0	NA	NA	Gammaproteobacteria	Myxococcales	Neisseriaceae	Aerococcus	Brachybacterium sp. VM2412	0	0
0	NA	NA	Alphaproteobacteria	Oscillatoriales	Enterobacteriaceae	Bacillus	Brachybacterium sp. VR2415	0	0
0	NA	NA	Betaproteobacteria	Nitrosomonadales	Micrococcaceae	Clavibacter	Kitasatospora sp. MMS16-BH015	0	0
0	NA	NA	Bacilli	Desulfuromonadales	Thermomonosporaceae	Actinomyces	Roseomonas sp. FDAARGOS_362	0	0
0	NA	NA	Gammaproteobacteria	Pseudomonadales	Actinomycetaceae	Bifidobacterium	Pseudomonas sp. FDAARGOS_380	0	0
0	NA	NA	Alphaproteobacteria	Burkholderiales	Streptomycetaceae	Corynebacterium	Rhizobium sp. TAL182	0	0
0	NA	NA	Betaproteobacteria	Micrococcales	Bifidobacteriaceae	Mycobacterium	Arthrobacter sp. YN	0	0
0	NA	NA	Bacilli	Pseudonocardiales	Xanthomonadaceae	Nocardia	Ahniella affigens	0	0
0	NA	NA	Gammaproteobacteria	Streptomycetales	Comamonadaceae	Rhodococcus	Porphyrobacter HT-58-2	0	0
0	NA	NA	Alphaproteobacteria	Xanthomonadales	Promicromonosporaceae	Pseudonocardia	Plantactinospora sp. KBS50	0	0
0	NA	NA	Betaproteobacteria	Oceanospirillales	Microbacteriaceae	Streptomyces	Staphylococcus sp. M0911	0	0
0	NA	NA	Bacilli	Flavobacteriales	Gallionellaceae	Marinobacter	Parabacteroides sp. CT06	0	0
0	NA	NA	Gammaproteobacteria	Rhodospirillales	Burkholderiaceae	Halomonas	Bacillus sp. 1s-1	0	0
0	NA	NA	Alphaproteobacteria	Sphingomonadales	Opitutaceae	Begomovirus	Rhodothermaceae bacterium	0	0
0	NA	NA	Betaproteobacteria	Neisseriales	Pseudomonadaceae	Magnetospirillum	Providencia sp. WCHPr000369	0	0
0	NA	NA	Bacilli	Rhodocyclales	Dermacoccaceae	Rubrivivax	Mariniflexile sp. TRM1-10	0	0
0	NA	NA	Gammaproteobacteria	Campylobacterales	Actinopolysporaceae	Janthinobacterium	Rhizobium sp. 11515TR	0	0
0	NA	NA	Alphaproteobacteria	Myxococcales	Neisseriaceae	Burkholderia	Chitinophaga caeni	0	0
0	NA	NA	Betaproteobacteria	Oscillatoriales	Enterobacteriaceae	Exiguobacterium	Shewanella sp. WE21	0	0
0	NA	NA	Bacilli	Nitrosomonadales	Micrococcaceae	Variovorax	Serratia sp. MYb239	0	0
0	NA	NA	Gammaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Rubrobacter	Actinoplanes sp. SE50	0	0
0	NA	NA	Alphaproteobacteria	Pseudomonadales	Actinomycetaceae	Pseudoalteromonas	Rhodobacter sp. CZR27	0	0
0	NA	NA	Betaproteobacteria	Burkholderiales	Streptomycetaceae	Methylovorus	Gemella sp. ND 6198	0	0
0	NA	NA	Bacilli	Micrococcales	Bifidobacteriaceae	Leclercia	Pectobacterium polaris	0	0
0	NA	NA	Gammaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Pandoraea	Natronolimnobius sp. AArc1	0	0
0	NA	NA	Alphaproteobacteria	Streptomycetales	Comamonadaceae	Arsenicicoccus	Candidatus Nitrosocaldus islandicus	0	0
0	NA	NA	Betaproteobacteria	Xanthomonadales	Promicromonosporaceae	Zobellella	Massilia violaceinigra	0	0
0	NA	NA	Bacilli	Oceanospirillales	Microbacteriaceae	Mycobacteroides	Nocardioides sp. 78	0	0
0	NA	NA	Gammaproteobacteria	Flavobacteriales	Gallionellaceae	Luteipulveratus	Thalassospira marina	0	0
0	NA	NA	Alphaproteobacteria	Rhodospirillales	Burkholderiaceae	Auritidibacter	Solibacillus sp. R5-41	0	0
0	NA	NA	Betaproteobacteria	Sphingomonadales	Opitutaceae	Komagataeibacter	Rhizobium sp. NXC24	0	0
0	NA	NA	Bacilli	Neisseriales	Pseudomonadaceae	Pontimonas	Pseudomonas sp. HLS-6	0	0
0	NA	NA	Gammaproteobacteria	Rhodocyclales	Dermacoccaceae	Actinotignum	Streptomyces dengpaensis	0	0
0	NA	NA	Alphaproteobacteria	Campylobacterales	Actinopolysporaceae	Mycolicibacterium	Mycobacterium sp. PYR15	0	0
0	NA	NA	Betaproteobacteria	Myxococcales	Neisseriaceae	Azospirillum	Rubrobacter indioceani	0	0
0	NA	NA	Bacilli	Oscillatoriales	Enterobacteriaceae	Brucella	Dietzia sp. JS16-p6b	0	0
0	NA	NA	Gammaproteobacteria	Nitrosomonadales	Micrococcaceae	Pseudomonas	Oceanobacillus sp. 160	0	0
0	NA	NA	Alphaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Xanthomonas	Bacillus sp. Y-01	0	0
0	NA	NA	Betaproteobacteria	Pseudomonadales	Actinomycetaceae	Rhizobium	Enterobacteriaceae bacterium S05	0	0
0	NA	NA	Bacilli	Burkholderiales	Streptomycetaceae	Acinetobacter	Bradyrhizobium sp. SK17	0	0
0	NA	NA	Gammaproteobacteria	Micrococcales	Bifidobacteriaceae	Neisseria	Enterococcus sp. CR-Ec1	0	0
0	NA	NA	Alphaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Alcaligenes	Lacinutrix sp. Bg11-31	0	0
0	NA	NA	Betaproteobacteria	Streptomycetales	Comamonadaceae	Chromobacterium	Alteromonas sp. MB-3u-76	0	0
0	NA	NA	Bacilli	Xanthomonadales	Promicromonosporaceae	Citrobacter	Nonlabens sp. MB-3u-79	0	0
0	NA	NA	Gammaproteobacteria	Oceanospirillales	Microbacteriaceae	Enterobacter	Olleya sp. Bg11-27	0	0
0	NA	NA	Alphaproteobacteria	Flavobacteriales	Gallionellaceae	Klebsiella	Planococcus sp. MB-3u-03	0	0
0	NA	NA	Betaproteobacteria	Rhodospirillales	Burkholderiaceae	Aeromonas	Polaribacter sp. ALD11	0	0
0	NA	NA	Bacilli	Sphingomonadales	Opitutaceae	Vibrio	Shewanella sp. Pdp11	0	0
0	NA	NA	Gammaproteobacteria	Neisseriales	Pseudomonadaceae	Haemophilus	Chromobacterium sp. ATCC 53434	0	0
0	NA	NA	Alphaproteobacteria	Rhodocyclales	Dermacoccaceae	Aerococcus	Gordonia sp. YC-JH1	0	0
0	NA	NA	Betaproteobacteria	Campylobacterales	Actinopolysporaceae	Bacillus	Streptomyces sp. CMB-StM0423	0	0
0	NA	NA	Bacilli	Myxococcales	Neisseriaceae	Clavibacter	Enterococcus sp. FDAARGOS_163	0	0
0	NA	NA	Gammaproteobacteria	Oscillatoriales	Enterobacteriaceae	Actinomyces	Enterococcus sp. FDAARGOS_375	0	0
0	NA	NA	Alphaproteobacteria	Nitrosomonadales	Micrococcaceae	Bifidobacterium	Neorhizobium sp. SOG26	0	0
0	NA	NA	Betaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Corynebacterium	Paracoccus sp. CBA4604	0	0
0	NA	NA	Bacilli	Pseudomonadales	Actinomycetaceae	Mycobacterium	Citrobacter freundii complex sp. CFNIH2	0	0
0	NA	NA	Gammaproteobacteria	Burkholderiales	Streptomycetaceae	Nocardia	Pseudomonas sp. NC02	0	0
0	NA	NA	Alphaproteobacteria	Micrococcales	Bifidobacteriaceae	Rhodococcus	Methylobacterium sp. DM1	0	0
0	NA	NA	Betaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Pseudonocardia	Azoarcus sp. SY39	0	0
0	NA	NA	Bacilli	Streptomycetales	Comamonadaceae	Streptomyces	Pseudomonas sp. XWY-1	0	0
0	NA	NA	Gammaproteobacteria	Xanthomonadales	Promicromonosporaceae	Marinobacter	Tamlana sp. UJ94	0	0
0	NA	NA	Alphaproteobacteria	Oceanospirillales	Microbacteriaceae	Halomonas	Sulfitobacter sp. JL08	0	0
0	NA	NA	Betaproteobacteria	Flavobacteriales	Gallionellaceae	Begomovirus	Gammaproteobacteria bacterium ESL0073	0	0
0	NA	NA	Bacilli	Rhodospirillales	Burkholderiaceae	Magnetospirillum	Lysinibacillus sp. YS11	0	0
0	NA	NA	Gammaproteobacteria	Sphingomonadales	Opitutaceae	Rubrivivax	Actinoalloteichus sp. AHMU CJ021	0	0
0	NA	NA	Alphaproteobacteria	Neisseriales	Pseudomonadaceae	Janthinobacterium	Streptomyces sp. Go-475	0	0
0	NA	NA	Betaproteobacteria	Rhodocyclales	Dermacoccaceae	Burkholderia	Massilia armeniaca	0	0
0	NA	NA	Bacilli	Campylobacterales	Actinopolysporaceae	Exiguobacterium	Citrobacter freundii complex sp. CFNIH9	0	0
0	NA	NA	Gammaproteobacteria	Myxococcales	Neisseriaceae	Variovorax	Arthrobacter sp. PGP41	0	0
0	NA	NA	Alphaproteobacteria	Oscillatoriales	Enterobacteriaceae	Rubrobacter	Corynebacterium sp. 2184	0	0
0	NA	NA	Betaproteobacteria	Nitrosomonadales	Micrococcaceae	Pseudoalteromonas	Actinomyces sp. Z16	0	0
0	NA	NA	Bacilli	Desulfuromonadales	Thermomonosporaceae	Methylovorus	Acinetobacter sp. SWBY1	0	0
0	NA	NA	Gammaproteobacteria	Pseudomonadales	Actinomycetaceae	Leclercia	Aeromicrobium sp. 592	0	0
0	NA	NA	Alphaproteobacteria	Burkholderiales	Streptomycetaceae	Pandoraea	Zoogloeaceae bacteirum Par-f-2	0	0
0	NA	NA	Betaproteobacteria	Micrococcales	Bifidobacteriaceae	Arsenicicoccus	Corynebacterium sp. 2183	0	0
0	NA	NA	Bacilli	Pseudonocardiales	Xanthomonadaceae	Zobellella	Agromyces sp. 30A	0	0
0	NA	NA	Gammaproteobacteria	Streptomycetales	Comamonadaceae	Mycobacteroides	Peptostreptococcaceae bacterium oral taxon 929	0	0
0	NA	NA	Alphaproteobacteria	Xanthomonadales	Promicromonosporaceae	Luteipulveratus	Clostridiaceae bacterium 14S0207	0	0
0	NA	NA	Betaproteobacteria	Oceanospirillales	Microbacteriaceae	Auritidibacter	Microvirga sp. 17 mud 1-3	0	0
0	NA	NA	Bacilli	Flavobacteriales	Gallionellaceae	Komagataeibacter	Pseudomonas sp. SWI36	0	0
0	NA	NA	Gammaproteobacteria	Rhodospirillales	Burkholderiaceae	Pontimonas	Streptomyces sp. CB09001	0	0
0	NA	NA	Alphaproteobacteria	Sphingomonadales	Opitutaceae	Actinotignum	Devosia sp. I507	0	0
0	NA	NA	Betaproteobacteria	Neisseriales	Pseudomonadaceae	Mycolicibacterium	Natronolimnobius sp. AArc-Mg	0	0
0	NA	NA	Bacilli	Rhodocyclales	Dermacoccaceae	Azospirillum	Mordavella sp. Marseille-P3756	0	0
0	NA	NA	Gammaproteobacteria	Campylobacterales	Actinopolysporaceae	Brucella	Streptomyces sp. WAC00288	0	0
0	NA	NA	Alphaproteobacteria	Myxococcales	Neisseriaceae	Pseudomonas	Aureitalea sp. RR4-38	0	0
0	NA	NA	Betaproteobacteria	Oscillatoriales	Enterobacteriaceae	Xanthomonas	Ruegeria sp. NKC1-1	0	0
0	NA	NA	Bacilli	Nitrosomonadales	Micrococcaceae	Rhizobium	Idiomarina sp. OT37-5b	0	0
0	NA	NA	Gammaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Acinetobacter	Microbacterium sp. str. 'China'	0	0
0	NA	NA	Alphaproteobacteria	Pseudomonadales	Actinomycetaceae	Neisseria	Aeromicrobium sp. A1-2	0	0
0	NA	NA	Betaproteobacteria	Burkholderiales	Streptomycetaceae	Alcaligenes	Thalassococcus sp. SH-1	0	0
0	NA	NA	Bacilli	Micrococcales	Bifidobacteriaceae	Chromobacterium	Oscillibacter sp. PEA192	0	0
0	NA	NA	Gammaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Citrobacter	Erysipelotrichaceae bacterium GAM147	0	0
0	NA	NA	Alphaproteobacteria	Streptomycetales	Comamonadaceae	Enterobacter	Melaminivora sp. SC2-9	0	0
0	NA	NA	Betaproteobacteria	Xanthomonadales	Promicromonosporaceae	Klebsiella	Ottowia oryzae	0	0
0	NA	NA	Bacilli	Oceanospirillales	Microbacteriaceae	Aeromonas	Simplicispira suum	0	0
0	NA	NA	Gammaproteobacteria	Flavobacteriales	Gallionellaceae	Vibrio	Candidatus Phycorickettsia trachydisci	0	0
0	NA	NA	Alphaproteobacteria	Rhodospirillales	Burkholderiaceae	Haemophilus	Variovorax sp. PMC12	0	0
0	NA	NA	Betaproteobacteria	Sphingomonadales	Opitutaceae	Aerococcus	Streptacidiphilus sp. DSM 106435	0	0
0	NA	NA	Bacilli	Neisseriales	Pseudomonadaceae	Bacillus	Gramella sp. SH35	0	0
0	NA	NA	Gammaproteobacteria	Rhodocyclales	Dermacoccaceae	Clavibacter	Streptomyces sp. P3	0	0
0	NA	NA	Alphaproteobacteria	Campylobacterales	Actinopolysporaceae	Actinomyces	Halomonas sp. SF2003	0	0
0	NA	NA	Betaproteobacteria	Myxococcales	Neisseriaceae	Bifidobacterium	Megasphaera stantonii	0	0
0	NA	NA	Bacilli	Oscillatoriales	Enterobacteriaceae	Corynebacterium	Lelliottia sp. WB101	0	0
0	NA	NA	Gammaproteobacteria	Nitrosomonadales	Micrococcaceae	Mycobacterium	Arthrospira sp. TJSD092	0	0
0	NA	NA	Alphaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Nocardia	Tessaracoccus sp. Marseille-P5995	0	0
0	NA	NA	Betaproteobacteria	Pseudomonadales	Actinomycetaceae	Rhodococcus	Colwellia sp. Arc7-D	0	0
0	NA	NA	Bacilli	Burkholderiales	Streptomycetaceae	Pseudonocardia	Flavobacterium sp. HYN0048	0	0
0	NA	NA	Gammaproteobacteria	Micrococcales	Bifidobacteriaceae	Streptomyces	Vibrio sp. dhg	0	0
0	NA	NA	Alphaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Marinobacter	Gammaproteobacteria bacterium DM2	0	0
0	NA	NA	Betaproteobacteria	Streptomycetales	Comamonadaceae	Halomonas	Lysinibacillus sp. 2017	0	0
0	NA	NA	Bacilli	Xanthomonadales	Promicromonosporaceae	Begomovirus	Rhodobacteraceae bacterium BAR1	0	0
0	NA	NA	Gammaproteobacteria	Oceanospirillales	Microbacteriaceae	Magnetospirillum	Actinotignum sp. 313	0	0
0	NA	NA	Alphaproteobacteria	Flavobacteriales	Gallionellaceae	Rubrivivax	Catenovulum sp. CCB-QB4	0	0
0	NA	NA	Betaproteobacteria	Rhodospirillales	Burkholderiaceae	Janthinobacterium	Limnobaculum parvum	0	0
0	NA	NA	Bacilli	Sphingomonadales	Opitutaceae	Burkholderia	Streptococcus sp. Z15	0	0
0	NA	NA	Gammaproteobacteria	Neisseriales	Pseudomonadaceae	Exiguobacterium	Streptomyces sp. HNM0039	0	0
0	NA	NA	Alphaproteobacteria	Rhodocyclales	Dermacoccaceae	Variovorax	Pseudarcicella sp. HME7025	0	0
0	NA	NA	Betaproteobacteria	Campylobacterales	Actinopolysporaceae	Rubrobacter	Salinimonas sp. HMF8227	0	0
0	NA	NA	Bacilli	Myxococcales	Neisseriaceae	Pseudoalteromonas	Flavobacterium sp. HYN0056	0	0
0	NA	NA	Gammaproteobacteria	Oscillatoriales	Enterobacteriaceae	Methylovorus	Streptomyces sp. ZFG47	0	0
0	NA	NA	Alphaproteobacteria	Nitrosomonadales	Micrococcaceae	Leclercia	Thauera hydrothermalis	0	0
0	NA	NA	Betaproteobacteria	Desulfuromonadales	Thermomonosporaceae	Pandoraea	Flavobacterium sp. MEBiC07310	0	0
0	NA	NA	Bacilli	Pseudomonadales	Actinomycetaceae	Arsenicicoccus	Phenylobacterium sp. HYN0004	0	0
0	NA	NA	Gammaproteobacteria	Burkholderiales	Streptomycetaceae	Zobellella	Pseudomonas sp. 31-12	0	0
0	NA	NA	Alphaproteobacteria	Micrococcales	Bifidobacteriaceae	Mycobacteroides	Streptomyces sp. NEAU-S7GS2	0	0
0	NA	NA	Betaproteobacteria	Pseudonocardiales	Xanthomonadaceae	Luteipulveratus	Chromobacterium sp. IIBBL 112-1	0	0
0	NA	NA	Bacilli	Streptomycetales	Comamonadaceae	Auritidibacter	Chromobacterium sp. IIBBL 274-1	0	0
0	NA	NA	Gammaproteobacteria	Xanthomonadales	Promicromonosporaceae	Komagataeibacter	Methylobacterium sp. 17SD2-17	0	0
0	NA	NA	Alphaproteobacteria	Oceanospirillales	Microbacteriaceae	Pontimonas	Methylobacterium sp. 17Sr1-1	0	0
0	NA	NA	Betaproteobacteria	Flavobacteriales	Gallionellaceae	Actinotignum	Methylobacterium sp. 17Sr1-28	0	0
0	NA	NA	Bacilli	Rhodospirillales	Burkholderiaceae	Mycolicibacterium	Psychrobacter sp. YP14	0	0
0	NA	NA	Gammaproteobacteria	Sphingomonadales	Opitutaceae	Azospirillum	Arthrobacter sp. DCT5	0	0
0	NA	NA	Alphaproteobacteria	Neisseriales	Pseudomonadaceae	Brucella	Paraliobacillus sp. X-1125	0	0
0	NA	NA	Betaproteobacteria	Rhodocyclales	Dermacoccaceae	Pseudomonas	Pseudomonas sp. LG1E9	0	0
0	NA	NA	Bacilli	Campylobacterales	Actinopolysporaceae	Xanthomonas	Sphingomonas sp. FARSPH	0	0
0	NA	NA	Gammaproteobacteria	Myxococcales	Neisseriaceae	Rhizobium	Flavobacterium sp. HYN0086	0	0
0	NA	NA	Alphaproteobacteria	Oscillatoriales	Enterobacteriaceae	Acinetobacter	Paracoccus sp. SC2-6	0	0
0	NA	NA	Betaproteobacteria	Nitrosomonadales	Micrococcaceae	Neisseria	Runella sp. HYN0085	0	0
0	NA	NA	Bacilli	Desulfuromonadales	Thermomonosporaceae	Alcaligenes	Alteromonas sp. RKMC-009	0	0
0	NA	NA	Gammaproteobacteria	Pseudomonadales	Actinomycetaceae	Chromobacterium	Bacillus sp. DM2	0	0
0	NA	NA	Alphaproteobacteria	Burkholderiales	Streptomycetaceae	Citrobacter	Hydromonas sp. F02	0	0
0	NA	NA	Betaproteobacteria	Micrococcales	Bifidobacteriaceae	Enterobacter	Kordia sp. SMS9	0	0
0	NA	NA	Bacilli	Pseudonocardiales	Xanthomonadaceae	Klebsiella	Humibacter sp. BT305	0	0
0	NA	NA	Gammaproteobacteria	Streptomycetales	Comamonadaceae	Aeromonas	Streptomyces sp. GSSD-12	0	0
0	NA	NA	Alphaproteobacteria	Xanthomonadales	Promicromonosporaceae	Vibrio	Sporosarcina sp. PTS2304	0	0
0	NA	NA	Betaproteobacteria	Oceanospirillales	Microbacteriaceae	Haemophilus	Ornithinimicrobium sp. AMA3305	0	0
0	NA	NA	Bacilli	Flavobacteriales	Gallionellaceae	Aerococcus	Moraxellaceae bacterium HYN0046	0	0
0	NA	NA	Gammaproteobacteria	Rhodospirillales	Burkholderiaceae	Bacillus	Lysobacter sp. TY2-98	0	0
0	NA	NA	Alphaproteobacteria	Sphingomonadales	Opitutaceae	Clavibacter	Flavobacterium sp. CJ74	0	0
0	NA	NA	Betaproteobacteria	Neisseriales	Pseudomonadaceae	Actinomyces	Solimonas sp. K1W22B-7	0	0
0	NA	NA	Bacilli	Rhodocyclales	Dermacoccaceae	Bifidobacterium	Salinimonas sp. N102	0	0
0	NA	NA	Gammaproteobacteria	Campylobacterales	Actinopolysporaceae	Corynebacterium	Stenotrophomonas sp. G4	0	0
0	NA	NA	Alphaproteobacteria	Myxococcales	Neisseriaceae	Mycobacterium	Streptomyces sp. CC0208	0	0
0	NA	NA	Betaproteobacteria	Oscillatoriales	Enterobacteriaceae	Nocardia	Pseudoflavitalea sp. 5GH32-13	0	0
