NCBI-TaxID	Kingdom	Phylum	Class	Order	Family	Genus	Species	Number_of_Reads	Relative_Abundance
10375	<not present>	<not present>	<not present>	<not present>	<not present>	Lymphocryptovirus	<not present>	28	0
475	<not present>	<not present>	<not present>	<not present>	<not present>	Moraxella	<not present>	907	0
838	<not present>	<not present>	<not present>	<not present>	<not present>	Prevotella	<not present>	1687	0
1301	<not present>	<not present>	<not present>	<not present>	<not present>	Streptococcus	<not present>	1213	0
1378	<not present>	<not present>	<not present>	<not present>	<not present>	Gemella	<not present>	11275	0
