NCBI-TaxID	Kingdom	Phylum	Class	Order	Family	Genus	Species	Number_of_Reads	Relative_Abundance	Sub-Species	Filename
33029	Bacteria	Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Anaerococcus	Anaerococcus hydrogenalis	59690	0.011325504221268	DSM 7454	ABXA01.1.fsa_nt.fna
38303	Bacteria	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium pseudogenitalium	14103	0.00194396736432379	ATCC 33035	ABYQ02.1.fsa_nt.fna
849	Bacteria	Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Fusobacterium	Fusobacterium gonidiaformans	195326	0.0378816695294421	3-1-5R strain 3_1_5R	ACDD01.1.fsa_nt.fna
507750	Bacteria	Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Peptoniphilus	Peptoniphilus duerdenii	198442	0.0341762036279647	ATCC BAA-1640	AEEH01.1.fsa_nt.fna
54005	Bacteria	Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Peptoniphilus	Peptoniphilus harei	1909	0.000372733320650776	ACS-146-V-Sch2b	AENP01.1.fsa_nt.fna
33034	Bacteria	Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Anaerococcus	Anaerococcus prevotii	136245	0.0287796467413551	ACS-065-V-Col13	AEXM01.1.fsa_nt.fna
202789	Bacteria	Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Actinobaculum	Actinobaculum massiliense	276476	0.0490385009886578	ACS-171-V-Col2	AGWL01.1.fsa_nt.fna
131111	Bacteria	Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Actinomyces	Actinomyces turicensis	85661	0.0157354952558543	ACS-279-V-Col4	AGWQ01.1.fsa_nt.fna
33012	Bacteria	Actinobacteria	Actinobacteria	Propionibacteriales	Propionibacteriaceae	Propionimicrobium	Propionimicrobium lymphophilum	60444	0.00958155007067931	ACS-093-V-SCH5	AGZR01.1.fsa_nt.fna
28125	Bacteria	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella bivia	54259	0.00771826215667388	DSM 20514	AJVZ01.1.fsa_nt.fna
322095	Bacteria	Bacteroidetes	Bacteroidia	Bacteroidales	Porphyromonadaceae	Porphyromonas	Porphyromonas somerae	102582	0.0156042528013662	DSM 23386	AQVC01.1.fsa_nt.fna
501496	Bacteria	Bacteroidetes	Bacteroidia	Bacteroidales	Porphyromonadaceae	Porphyromonas	Porphyromonas bennonis	1067	0.000189055770888887	DSM 23058	AQWR01.1.fsa_nt.fna
827	Bacteria	Proteobacteria	Epsilonproteobacteria	Campylobacterales	Campylobacteraceae	Campylobacter	Campylobacter ureolyticus	5839	0.001202894657893	DSM 20703	ARGD01.1.fsa_nt.fna
1351	Bacteria	Firmicutes	Bacilli	Lactobacillales	Enterococcaceae	Enterococcus	Enterococcus faecalis	1138	0.000139274949460797	13-SD-W-01	ATIO01.1.fsa_nt.fna
190146	Bacteria	Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Actinotignum	Actinotignum urinale	358	6.68308116250759e-05	DSM 15805	ATUY01.1.fsa_nt.fna
33012	Bacteria	Actinobacteria	Actinobacteria	Propionibacteriales	Propionibacteriaceae	Propionimicrobium	Propionimicrobium lymphophilum	138301	0.024356504934651	DSM 4903	AUIB01.1.fsa_nt.fna
28128	Bacteria	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella corporis	5223	0.000670895402656685	strain=DSM 18810	AUME01.1.fsa_nt.fna
1111134	Bacteria	Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Peptoniphilus	Peptoniphilus sp. BV3C26	11942	0.00222279025701421	NA	AWXB01.1.fsa_nt.fna
1111131	Bacteria	Actinobacteria	Actinobacteria	Actinobacteria	Propionibacteriales	Propionibacteriaceae	Propionimicrobium sp. BV2F7	15873	0.002805882970625	NA	AZIS01.1.fsa_nt.fna
28130	Bacteria	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella disiens	45854	0.00587673378281528	JCM 6334	BAIS01.1.fsa_nt.fna
386414	Bacteria	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella timonensis	104129	0.0119399053959255	4401737	CBQQ01.1.fsa_nt.fna
59505	Bacteria	Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Actinotignum	Actinobaculum schaalii	68242	0.0113294706336559	strain CCUG 27420	CP008802.1.fsa_nt.fna
851	Bacteria	Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Fusobacterium	Fusobacterium nucleatum	43197	0.00712141405863497	NA	GCF_000007325.1_ASM732v1_genomic.fna
1282	Bacteria	Firmicutes	Bacilli	Bacillales	Staphylococcaceae	Staphylococcus	Staphylococcus epidermidis	439	6.1364105135553e-05	NA	GCF_000007645.1_ASM764v1_genomic.fna
1351	Bacteria	Firmicutes	Bacilli	Lactobacillales	Enterococcaceae	Enterococcus	Enterococcus faecalis	10366	0.00110598019716366	NA	GCF_000007785.1_ASM778v1_genomic.fna
1747	Bacteria	Actinobacteria	Actinobacteria	Propionibacteriales	Propionibacteriaceae	Cutibacterium	Cutibacterium acnes	583	8.1631109378428e-05	NA	GCF_000008345.1_ASM834v1_genomic.fna
210	Bacteria	Proteobacteria	Epsilonproteobacteria	Campylobacterales	Helicobacteraceae	Helicobacter	Helicobacter Pylori	31898	0.00685605196981241	NA	GCF_000008525.1_ASM852v1_genomic.fna
817	Bacteria	Bacteroidetes	Bacteroidia	Bacteroidales	Bacteroidaceae	Bacteroides	Bacteroides fragilis	130	8.77485465786617e-06	NA	GCF_000009925.1_ASM992v1_genomic.fna
2130	Bacteria	Tenericutes	Mollicutes	Mycoplasmatales	Mycoplasmataceae	Ureaplasma	Ureaplasma urealyticum	507361	0.207988946810409	NA	GCF_000021265.1_ASM2126v1_genomic.fna
34105	Bacteria	Fusobacteria	Fusobacteriia	Fusobacteriales	Leptotrichiaceae	Streptobacillus	Streptobacillus moniliformis	14685	0.00314613528752742	NA	GCF_000024565.1_ASM2456v1_genomic.fna
29466	Bacteria	Firmicutes	Negativicutes	Veillonellales	Veillonellaceae	Veillonella	Veillonella parvula	5973	0.00100426529021094	NA	GCF_000024945.1_ASM2494v1_genomic.fna
28037	Bacteria	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus mitis	1176	0.000196393013628357	NA	GCF_000027165.1_ASM2716v1_genomic.fna
725	Bacteria	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Haemophilus	Haemophilus influenzae	56649	0.0110963583213211	NA	GCF_000027305.1_ASM2730v1_genomic.fna
480	Bacteria	Proteobacteria	Gammaproteobacteria	Pseudomonadales	Moraxellaceae	Moraxella	Moraxella catarrhalis	3903	0.000750915542671977	NA	GCF_000092265.1_ASM9226v1_genomic.fna
1322	Bacteria	Firmicutes	Clostridia	Clostridiales	Lachnospiraceae	Blautia	Blautia hansenii	1614	0.000189162797778147	NA	GCF_000156675.1_ASM15667v1_genomic.fna
61171	Bacteria	Firmicutes	Erysipelotrichia	Erysipelotrichales	Erysipelotrichaceae	Holdemania	Holdemania filiformis	3975	0.000362321205302868	NA	GCF_000157995.1_ASM15799v1_genomic.fna
38284	Bacteria	Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium accolens	276340	0.0406468731053084	NA	GCF_000159115.1_ASM15911v1_genomic.fna
43997	Bacteria	Firmicutes	Clostridia	Clostridiales	Lachnospiraceae	Catonella	Catonella morbi	245952	0.0253420957595503	NA	GCF_000160035.2_ASM16003v2_genomic.fna
218538	Bacteria	Firmicutes	Negativicutes	Veillonellales	Veillonellaceae	Dialister	Dialister invisus	83645	0.0158154982367873	NA	GCF_000160055.1_ASM16005v1_genomic.fna
46125	Bacteria	Firmicutes	Bacilli	Lactobacillales	Aerococcaceae	Abiotrophia	Abiotrophia defectiva	81863	0.0143614417587129	NA	GCF_000160075.2_ASM16007v2_genomic.fna
629741	Bacteria	Proteobacteria	Betaproteobacteria	Neisseriales	Neisseriaceae	Kingella	Kingella oralis	6071	0.000904304827759908	NA	GCF_000160435.1_ASM16043v1_genomic.fna
754	Bacteria	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Pasteurella	Pasteurella dagmatis	84210	0.0133383717603262	NA	GCF_000163475.1_ASM16347v1_genomic.fna
1318	Bacteria	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus parasanguinis	91549	0.0152387778943179	NA	GCF_000164675.2_ASM16467v2_genomic.fna
563032	Bacteria	Actinobacteria	Actinobacteria	Micrococcales	Micrococcaceae	Rothia	Rothia dentocariosa	32172	0.00460219190304767	NA	GCF_000164695.2_ASM16469v2_genomic.fna
1379	Bacteria	Firmicutes	Bacilli	Bacillales	Bacillales Family XI. Incertae Sedis	Gemella	Gemella haemolysans	4524	0.000846360987735283	NA	GCF_000173915.1_ASM17391v1_genomic.fna
203	Bacteria	Proteobacteria	Epsilonproteobacteria	Campylobacterales	Campylobacteraceae	Campylobacter	Campylobacter rectus	1862	0.000265607760439496	NA	GCF_000174175.1_ASM17417v1_genomic.fna
28127	Bacteria	Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella buccalis	35827	0.00423323631439102	NA	GCF_000177075.1_ASM17707v1_genomic.fna
118748	Bacteria	Firmicutes	Erysipelotrichia	Erysipelotrichales	Erysipelotrichaceae	Bulleidia	Bulleidia extructa	52928	0.013365855352662	NA	GCF_000177375.1_ASM17737v1_genomic.fna
488	Bacteria	Proteobacteria	Betaproteobacteria	Neisseriales	Neisseriaceae	Neisseria	Neisseria mucosa	80428	0.0132902236560975	NA	GCF_000186165.1_Neis_muco_C102_V1_genomic.fna
594	Bacteria	Proteobacteria	Gammaproteobacteria	Enterobacterales	Enterobacteriaceae	Salmonella	Salmonella enterica	69252	0.00483584973725163	NA	GCF_000195995.1_ASM19599v1_genomic.fna
1638	Bacteria	Firmicutes	Bacilli	Bacillales	Listeriaceae	Listeria	Listeria monocytogenes	37	4.50461935745294e-06	NA	GCF_000196035.1_ASM19603v1_genomic.fna
1308	Bacteria	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus thermophilus	5504	0.00102238520719514	NA	GCF_000253395.1_ASM25339v1_genomic.fna
45201	Bacteria	Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Mannheimia	Mannheimia haemolytica	8389	0.00110083499871478	NA	GCF_000376645.1_ASM37664v1_genomic.fna
596324	Bacteria	Spirochaetes	Spirochaetia	Spirochaetales	Spirochaetaceae	Treponema	Treponema vincentii	69566	0.00925876890371138	NA	GCF_000412995.1_Trep_vinc_F0403_V1_genomic.fna
157692	Bacteria	Fusobacteria	Fusobacteriia	Fusobacteriales	Leptotrichiaceae	Leptotrichia	Leptotrichia goodfellowii	24137	0.00379314308233001	NA	GCF_000516535.1_ASM51653v1_genomic.fna
495	Bacteria	Proteobacteria	Betaproteobacteria	Neisseriales	Neisseriaceae	Neisseria	Neisseria elongata	137180	0.0217921074982766	NA	GCF_000818035.1_ASM81803v1_genomic.fna
33032	Bacteria	Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Anaerococcus	Anaerococcus lactolyticus	127864	0.0236657773352756	S7-1-13	JRMW01.1.fsa_nt.fna
40543	Bacteria	Fusobacteria	Fusobacteriia	Fusobacteriales	Leptotrichiaceae	Sneathia	Sneathia sanguinegens	37140	0.0103128804456418	strain CCUG41628	LOQF01.1.fsa_nt.fna
755172	Bacteria	Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Peptoniphilus	Peptoniphilus coxii	151842	0.0296598360376903	strain DNF00729	LSDG01.1.fsa_nt.fna
2097	Bacteria	Tenericutes	Mollicutes	Mycoplasmatales	Mycoplasmataceae	Mycoplasma	Mycoplasma genitalium	15557	0.00961419701483075	G37	NC_000908.2.fsa_nt.fna
1311	Bacteria	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus agalactiae	98621	0.015986650004009	NEM316	NC_004368.1.fsa_nt.fna
33034	Bacteria	Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Anaerococcus	Anaerococcus prevotii	56822	0.0108173979385524	DSM 20548	NC_013171.1.fsa_nt.fna
2051	Bacteria	Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Mobiluncus	Mobiluncus curtisii	428934	0.0716367194436469	ATCC 43063	NC_014246.1.fsa_nt.fna
1328	Bacteria	Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus anginosus	100903	0.0161943292020046	C238	NC_022239.1.fsa_nt.fna
827	Bacteria	Proteobacteria	Epsilonproteobacteria	Campylobacterales	Campylobacteraceae	Campylobacter	Campylobacter ureolyticus	435683	0.0951260390052954	RIGS 9880	NZ_CP012195.1.fsa_nt.fna
