NCBI-TaxID	Kingdom	Phylum	Class	Order	Family	Genus	Species	Number_of_Reads	Relative_Abundance
4751	Fungi							1	100.0
1239		Firmicutes						21005	0.0
1760		Actinobacteria						10658	0.0
203691		Spirochaetes						4354	0.0
4890	Fungi	Ascomycota						1	0.0
32066		Fusobacteria						4845	0.0
1224		Proteobacteria						18811	0.0
544448		Tenericutes						963	0.0
976		Bacteroidetes						13146	0.0
1737404		Firmicutes	Tissierellia					4997	0.0
186801		Firmicutes	Clostridia					1788	0.0
147550	Fungi	Ascomycota	Sordariomycetes					1	0.0
91061		Firmicutes	Bacilli					11096	0.0
29547		Proteobacteria	Epsilonproteobacteria					2292	0.0
1236		Proteobacteria	Gammaproteobacteria					11408	0.0
28216		Proteobacteria	Betaproteobacteria					5005	0.0
1760		Actinobacteria	Actinobacteria					10634	0.0
203490		Fusobacteria	Fusobacteriia					4845	0.0
526524		Firmicutes	Erysipelotrichia					26	0.0
200643		Bacteroidetes	Bacteroidia					13085	0.0
31969		Tenericutes	Mollicutes					963	0.0
203692		Spirochaetes	Spirochaetia					4354	0.0
909932		Firmicutes	Negativicutes					2467	0.0
526525		Firmicutes	Erysipelotrichia	Erysipelotrichales				26	0.0
2085		Tenericutes	Mollicutes	Mycoplasmatales				963	0.0
1385		Firmicutes	Bacilli	Bacillales				16	0.0
203491		Fusobacteria	Fusobacteriia	Fusobacteriales				4845	0.0
85006		Actinobacteria	Actinobacteria	Micrococcales				2280	0.0
2037		Actinobacteria	Actinobacteria	Actinomycetales				6177	0.0
186802		Firmicutes	Clostridia	Clostridiales				1788	0.0
213849		Proteobacteria	Epsilonproteobacteria	Campylobacterales				2292	0.0
85007		Actinobacteria	Actinobacteria	Corynebacteriales				613	0.0
91347		Proteobacteria	Gammaproteobacteria	Enterobacterales				4801	0.0
206351		Proteobacteria	Betaproteobacteria	Neisseriales				5001	0.0
1843489		Firmicutes	Negativicutes	Veillonellales				2467	0.0
186826		Firmicutes	Bacilli	Lactobacillales				10846	0.0
136		Spirochaetes	Spirochaetia	Spirochaetales				4354	0.0
171549		Bacteroidetes	Bacteroidia	Bacteroidales				13085	0.0
1737405		Firmicutes	Tissierellia	Tissierellales				4991	0.0
135625		Proteobacteria	Gammaproteobacteria	Pasteurellales				6503	0.0
85009		Actinobacteria	Actinobacteria	Propionibacteriales				1421	0.0
5125	Fungi	Ascomycota	Sordariomycetes	Hypocreales				1	0.0
72274		Proteobacteria	Gammaproteobacteria	Pseudomonadales				70	0.0
137		Spirochaetes	Spirochaetia	Spirochaetales	Spirochaetaceae			4353	0.0
203492		Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae			2910	0.0
186803		Firmicutes	Clostridia	Clostridiales	Lachnospiraceae			1771	0.0
1300		Firmicutes	Bacilli	Lactobacillales	Streptococcaceae			7897	0.0
186827		Firmicutes	Bacilli	Lactobacillales	Aerococcaceae			2850	0.0
31977		Firmicutes	Negativicutes	Veillonellales	Veillonellaceae			2467	0.0
2092		Tenericutes	Mollicutes	Mycoplasmatales	Mycoplasmataceae			963	0.0
171552		Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae			11186	0.0
1268		Actinobacteria	Actinobacteria	Micrococcales	Micrococcaceae			2280	0.0
186802		Firmicutes	Clostridia	Clostridiales	Clostridiales_Family_XIII_Incertae_Sedis			8	0.0
72294		Proteobacteria	Epsilonproteobacteria	Campylobacterales	Campylobacteraceae			82	0.0
468		Proteobacteria	Gammaproteobacteria	Pseudomonadales	Moraxellaceae			70	0.0
1570339		Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae			4991	0.0
2049		Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae			6177	0.0
543		Proteobacteria	Gammaproteobacteria	Enterobacterales	Enterobacteriaceae			4729	0.0
712		Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae			6503	0.0
1129771		Fusobacteria	Fusobacteriia	Fusobacteriales	Leptotrichiaceae			1926	0.0
1653		Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae			613	0.0
72293		Proteobacteria	Epsilonproteobacteria	Campylobacterales	Helicobacteraceae			2210	0.0
128827		Firmicutes	Erysipelotrichia	Erysipelotrichales	Erysipelotrichaceae			26	0.0
186804		Firmicutes	Clostridia	Clostridiales	Peptostreptococcaceae			1	0.0
481		Proteobacteria	Betaproteobacteria	Neisseriales	Neisseriaceae			5000	0.0
171551		Bacteroidetes	Bacteroidia	Bacteroidales	Porphyromonadaceae			1652	0.0
81852		Firmicutes	Bacilli	Lactobacillales	Enterococcaceae			73	0.0
31957		Actinobacteria	Actinobacteria	Propionibacteriales	Propionibacteriaceae			1421	0.0
815		Bacteroidetes	Bacteroidia	Bacteroidales	Bacteroidaceae			1	0.0
29465		Firmicutes	Negativicutes	Veillonellales	Veillonellaceae	Veillonella		117	0.0
75984		Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Mannheimia		156	0.0
482		Proteobacteria	Betaproteobacteria	Neisseriales	Neisseriaceae	Neisseria		4671	0.0
838		Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella		11157	0.0
1350		Firmicutes	Bacilli	Lactobacillales	Enterococcaceae	Enterococcus		73	0.0
2050		Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Mobiluncus		82	0.0
1654		Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Actinomyces		2459	0.0
43996		Firmicutes	Clostridia	Clostridiales	Lachnospiraceae	Catonella		1744	0.0
1330547		Proteobacteria	Gammaproteobacteria	Enterobacterales	Enterobacteriaceae	Kosakonia		20	0.0
1716		Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium		601	0.0
508215		Actinobacteria	Actinobacteria	Micrococcales	Micrococcaceae	Rothia		2280	0.0
590		Proteobacteria	Gammaproteobacteria	Enterobacterales	Enterobacteriaceae	Salmonella		3989	0.0
2129		Tenericutes	Mollicutes	Mycoplasmatales	Mycoplasmataceae	Ureaplasma		54	0.0
543311		Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Parvimonas		3	0.0
165779		Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Anaerococcus		3804	0.0
2093		Tenericutes	Mollicutes	Mycoplasmatales	Mycoplasmataceae	Mycoplasma		907	0.0
123375		Firmicutes	Erysipelotrichia	Erysipelotrichales	Erysipelotrichaceae	Solobacterium		3	0.0
209		Proteobacteria	Epsilonproteobacteria	Campylobacterales	Helicobacteraceae	Helicobacter		2210	0.0
39948		Firmicutes	Negativicutes	Veillonellales	Veillonellaceae	Dialister		2346	0.0
203133		Actinobacteria	Actinobacteria	Propionibacteriales	Propionibacteriaceae	Propionimicrobium		1419	0.0
724		Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Haemophilus		2836	0.0
34104		Fusobacteria	Fusobacteriia	Fusobacteriales	Leptotrichiaceae	Streptobacillus		623	0.0
1301		Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus		7893	0.0
745		Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Pasteurella		3436	0.0
43994		Firmicutes	Clostridia	Clostridiales	Lachnospiraceae	Johnsonella		2	0.0
475		Proteobacteria	Gammaproteobacteria	Pseudomonadales	Moraxellaceae	Moraxella		70	0.0
157		Spirochaetes	Spirochaetia	Spirochaetales	Spirochaetaceae	Treponema		4352	0.0
1653174		Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Actinotignum		3560	0.0
194		Proteobacteria	Epsilonproteobacteria	Campylobacterales	Campylobacteraceae	Campylobacter		82	0.0
816		Bacteroidetes	Bacteroidia	Bacteroidales	Bacteroidaceae	Bacteroides		1	0.0
46123		Firmicutes	Bacilli	Lactobacillales	Aerococcaceae	Abiotrophia		2850	0.0
1279388		Firmicutes	Erysipelotrichia	Erysipelotrichales	Erysipelotrichaceae	Kandleria		1	0.0
1378		Firmicutes	Bacilli	Bacillales		Gemella		16	0.0
1257		Firmicutes	Clostridia	Clostridiales	Peptostreptococcaceae	Peptostreptococcus		1	0.0
32067		Fusobacteria	Fusobacteriia	Fusobacteriales	Leptotrichiaceae	Leptotrichia		1290	0.0
61170		Firmicutes	Erysipelotrichia	Erysipelotrichales	Erysipelotrichaceae	Holdemania		22	0.0
162289		Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Peptoniphilus		1035	0.0
848		Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Fusobacterium		2909	0.0
32257		Proteobacteria	Betaproteobacteria	Neisseriales	Neisseriaceae	Kingella		100	0.0
168808		Fusobacteria	Fusobacteriia	Fusobacteriales	Leptotrichiaceae	Sneathia		9	0.0
76833		Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Actinobaculum		43	0.0
836		Bacteroidetes	Bacteroidia	Bacteroidales	Porphyromonadaceae	Porphyromonas		1630	0.0
186802		Firmicutes	Clostridia	Clostridiales	Clostridiales_Family_XIII_Incertae_Sedis		[Eubacterium]_infirmum	8	0.0
543311		Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Parvimonas	Parvimonas_micra	3	0.0
838		Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella_disiens	2638	0.0
76833		Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Actinobaculum	Actinobaculum_massiliense	43	0.0
165779		Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Anaerococcus	Anaerococcus_senegalensis	45	0.0
75984		Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Mannheimia	Mannheimia_haemolytica	154	0.0
165779		Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Anaerococcus	Anaerococcus_prevotii	2799	0.0
32257		Proteobacteria	Betaproteobacteria	Neisseriales	Neisseriaceae	Kingella	Kingella_oralis	100	0.0
1653174		Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Actinotignum	Actinotignum_urinale	3	0.0
1301		Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus_thermophilus	59	0.0
816		Bacteroidetes	Bacteroidia	Bacteroidales	Bacteroidaceae	Bacteroides	Bacteroides_faecis	1	0.0
61170		Firmicutes	Erysipelotrichia	Erysipelotrichales	Erysipelotrichaceae	Holdemania	Holdemania_filiformis	19	0.0
848		Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Fusobacterium	Fusobacterium_nucleatum	1201	0.0
123375		Firmicutes	Erysipelotrichia	Erysipelotrichales	Erysipelotrichaceae	Solobacterium	Solobacterium_moorei	3	0.0
745		Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Pasteurella	Pasteurella_dagmatis	3377	0.0
1654		Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Actinomyces	Actinomyces_turicensis	2439	0.0
724		Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Haemophilus	Haemophilus_influenzae	279	0.0
2050		Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Mobiluncus	Mobiluncus_curtisii	77	0.0
171551		Bacteroidetes	Bacteroidia	Bacteroidales	Porphyromonadaceae		Porphyromonadaceae_bacterium_FC4	1	0.0
165779		Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Anaerococcus	Anaerococcus_sp_Marseille-P2143	2	0.0
1716		Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium_accolens	23	0.0
838		Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella_sp_DNF00663	1	0.0
1737404		Firmicutes	Tissierellia				Tissierellia_bacterium_KA00581	1	0.0
838		Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella_copri	2	0.0
157		Spirochaetes	Spirochaetia	Spirochaetales	Spirochaetaceae	Treponema	Treponema_vincentii	4102	0.0
194		Proteobacteria	Epsilonproteobacteria	Campylobacterales	Campylobacteraceae	Campylobacter	Campylobacter_ureolyticus	71	0.0
838		Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella_oulorum	1	0.0
838		Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella_sp_HMSC069G02	2	0.0
1378		Firmicutes	Bacilli	Bacillales		Gemella	Gemella_asaccharolytica	1	0.0
475		Proteobacteria	Gammaproteobacteria	Pseudomonadales	Moraxellaceae	Moraxella	Moraxella_catarrhalis	6	0.0
1279388		Firmicutes	Erysipelotrichia	Erysipelotrichales	Erysipelotrichaceae	Kandleria	Kandleria_vitulina	1	0.0
1378		Firmicutes	Bacilli	Bacillales		Gemella	Gemella_haemolysans	15	0.0
1330547		Proteobacteria	Gammaproteobacteria	Enterobacterales	Enterobacteriaceae	Kosakonia	Kosakonia_oryzae	20	0.0
46123		Firmicutes	Bacilli	Lactobacillales	Aerococcaceae	Abiotrophia	Abiotrophia_defectiva	2415	0.0
194		Proteobacteria	Epsilonproteobacteria	Campylobacterales	Campylobacteraceae	Campylobacter	Campylobacter_sp_10_1_50	2	0.0
590		Proteobacteria	Gammaproteobacteria	Enterobacterales	Enterobacteriaceae	Salmonella	Salmonella_enterica	3769	0.0
1301		Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus_agalactiae	39	0.0
162289		Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Peptoniphilus	Peptoniphilus_duerdenii	537	0.0
34104		Fusobacteria	Fusobacteriia	Fusobacteriales	Leptotrichiaceae	Streptobacillus	Streptobacillus_moniliformis	565	0.0
838		Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella_ihumii	2	0.0
838		Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella_timonensis	4187	0.0
165779		Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Anaerococcus	Anaerococcus_vaginalis	3	0.0
836		Bacteroidetes	Bacteroidia	Bacteroidales	Porphyromonadaceae	Porphyromonas	Porphyromonas_uenonis	1	0.0
39948		Firmicutes	Negativicutes	Veillonellales	Veillonellaceae	Dialister	Dialister_invisus	2346	0.0
838		Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella_bivia	3206	0.0
209		Proteobacteria	Epsilonproteobacteria	Campylobacterales	Helicobacteraceae	Helicobacter	Helicobacter_pylori	2156	0.0
838		Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella_corporis	45	0.0
186802		Firmicutes	Clostridia	Clostridiales			Clostridiales_bacterium_KA00134	2	0.0
508215		Actinobacteria	Actinobacteria	Micrococcales	Micrococcaceae	Rothia	Rothia_dentocariosa	205	0.0
482		Proteobacteria	Betaproteobacteria	Neisseriales	Neisseriaceae	Neisseria	Neisseria_mucosa	25	0.0
1653174		Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Actinotignum	Actinotignum_schaalii	2944	0.0
848		Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Fusobacterium	Fusobacterium_gonidiaformans	58	0.0
165779		Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Anaerococcus	Anaerococcus_hydrogenalis	1	0.0
1301		Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus_anginosus	452	0.0
2093		Tenericutes	Mollicutes	Mycoplasmatales	Mycoplasmataceae	Mycoplasma	Mycoplasma_genitalium	903	0.0
32067		Fusobacteria	Fusobacteriia	Fusobacteriales	Leptotrichiaceae	Leptotrichia	Leptotrichia_goodfellowii	1287	0.0
162289		Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Peptoniphilus	Peptoniphilus_grossensis	2	0.0
43996		Firmicutes	Clostridia	Clostridiales	Lachnospiraceae	Catonella	Catonella_morbi	1744	0.0
162289		Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Peptoniphilus	Peptoniphilus_harei	8	0.0
1350		Firmicutes	Bacilli	Lactobacillales	Enterococcaceae	Enterococcus	Enterococcus_faecalis	26	0.0
43994		Firmicutes	Clostridia	Clostridiales	Lachnospiraceae	Johnsonella	Johnsonella_ignava	2	0.0
838		Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella_bergensis	1	0.0
168808		Fusobacteria	Fusobacteriia	Fusobacteriales	Leptotrichiaceae	Sneathia	Sneathia_amnii	9	0.0
171549		Bacteroidetes	Bacteroidia	Bacteroidales			Bacteroidales_bacterium_KA00344	3	0.0
1301		Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus_parasanguinis	949	0.0
836		Bacteroidetes	Bacteroidia	Bacteroidales	Porphyromonadaceae	Porphyromonas	Porphyromonas_sp_HMSC077F02	1590	0.0
2129		Tenericutes	Mollicutes	Mycoplasmatales	Mycoplasmataceae	Ureaplasma	Ureaplasma_urealyticum	43	0.0
165779		Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Anaerococcus	Anaerococcus_rubeinfantis	2	0.0
162289		Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Peptoniphilus	Peptoniphilus_obesi	2	0.0
1257		Firmicutes	Clostridia	Clostridiales	Peptostreptococcaceae	Peptostreptococcus	Peptostreptococcus_anaerobius	1	0.0
203133		Actinobacteria	Actinobacteria	Propionibacteriales	Propionibacteriaceae	Propionimicrobium	Propionimicrobium_lymphophilum	1414	0.0
165779		Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Anaerococcus	Anaerococcus_lactolyticus	733	0.0
482		Proteobacteria	Betaproteobacteria	Neisseriales	Neisseriaceae	Neisseria	Neisseria_elongata	951	0.0
165779		Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Anaerococcus	Anaerococcus_sp_HMSC065G05	1	0.0
1716		Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium_pseudogenitalium	318	0.0
31977		Firmicutes	Negativicutes	Veillonellales	Veillonellaceae		Veillonellaceae_bacterium_KA00182	1	0.0
29465		Firmicutes	Negativicutes	Veillonellales	Veillonellaceae	Veillonella	Veillonella_parvula	60	0.0
162289		Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Peptoniphilus	Peptoniphilus_coxii	438	0.0
