NCBI-TaxID	Kingdom	Phylum	Class	Order	Family	Genus	Species	Number_of_Reads	Relative_Abundance
4751	Fungi							1	100.0
203691		Spirochaetes						4675	0.0
1224		Proteobacteria						833	0.0
1239		Firmicutes						15208	0.0
32066		Fusobacteria						3589	0.0
4890	Fungi	Ascomycota						1	0.0
976		Bacteroidetes						6536	0.0
1760		Actinobacteria						2625	0.0
29547		Proteobacteria	Epsilonproteobacteria					14	0.0
186801		Firmicutes	Clostridia					2019	0.0
147550	Fungi	Ascomycota	Sordariomycetes					1	0.0
91061		Firmicutes	Bacilli					12512	0.0
1737404		Firmicutes	Tissierellia					299	0.0
1760		Actinobacteria	Actinobacteria					2619	0.0
1236		Proteobacteria	Gammaproteobacteria					303	0.0
28216		Proteobacteria	Betaproteobacteria					90	0.0
203490		Fusobacteria	Fusobacteriia					3589	0.0
909932		Firmicutes	Negativicutes					131	0.0
203692		Spirochaetes	Spirochaetia					4675	0.0
200643		Bacteroidetes	Bacteroidia					6514	0.0
186802		Firmicutes	Clostridia	Clostridiales				2017	0.0
135625		Proteobacteria	Gammaproteobacteria	Pasteurellales				53	0.0
1737405		Firmicutes	Tissierellia	Tissierellales				298	0.0
85007		Actinobacteria	Actinobacteria	Corynebacteriales				1095	0.0
171549		Bacteroidetes	Bacteroidia	Bacteroidales				6513	0.0
203491		Fusobacteria	Fusobacteriia	Fusobacteriales				3589	0.0
186826		Firmicutes	Bacilli	Lactobacillales				4569	0.0
136		Spirochaetes	Spirochaetia	Spirochaetales				4675	0.0
1385		Firmicutes	Bacilli	Bacillales				7851	0.0
68295		Firmicutes	Clostridia	Thermoanaerobacterales				2	0.0
2037		Actinobacteria	Actinobacteria	Actinomycetales				637	0.0
85009		Actinobacteria	Actinobacteria	Propionibacteriales				439	0.0
213849		Proteobacteria	Epsilonproteobacteria	Campylobacterales				14	0.0
85004		Actinobacteria	Actinobacteria	Bifidobacteriales				3	0.0
1843489		Firmicutes	Negativicutes	Veillonellales				126	0.0
206351		Proteobacteria	Betaproteobacteria	Neisseriales				90	0.0
91347		Proteobacteria	Gammaproteobacteria	Enterobacterales				240	0.0
5125	Fungi	Ascomycota	Sordariomycetes	Hypocreales				1	0.0
85006		Actinobacteria	Actinobacteria	Micrococcales				358	0.0
1300		Firmicutes	Bacilli	Lactobacillales	Streptococcaceae			3660	0.0
186820		Firmicutes	Bacilli	Bacillales	Listeriaceae			55	0.0
90964		Firmicutes	Bacilli	Bacillales	Staphylococcaceae			7705	0.0
712		Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae			53	0.0
137		Spirochaetes	Spirochaetia	Spirochaetales	Spirochaetaceae			4675	0.0
171551		Bacteroidetes	Bacteroidia	Bacteroidales	Porphyromonadaceae			412	0.0
186806		Firmicutes	Clostridia	Clostridiales	Eubacteriaceae			907	0.0
1268		Actinobacteria	Actinobacteria	Micrococcales	Micrococcaceae			356	0.0
481		Proteobacteria	Betaproteobacteria	Neisseriales	Neisseriaceae			88	0.0
72294		Proteobacteria	Epsilonproteobacteria	Campylobacterales	Campylobacteraceae			13	0.0
31953		Actinobacteria	Actinobacteria	Bifidobacteriales	Bifidobacteriaceae			3	0.0
186803		Firmicutes	Clostridia	Clostridiales	Lachnospiraceae			1006	0.0
31977		Firmicutes	Negativicutes	Veillonellales	Veillonellaceae			126	0.0
1653		Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae			1095	0.0
171552		Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae			5150	0.0
203492		Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae			2884	0.0
31957		Actinobacteria	Actinobacteria	Propionibacteriales	Propionibacteriaceae			439	0.0
815		Bacteroidetes	Bacteroidia	Bacteroidales	Bacteroidaceae			782	0.0
186827		Firmicutes	Bacilli	Lactobacillales	Aerococcaceae			895	0.0
543		Proteobacteria	Gammaproteobacteria	Enterobacterales	Enterobacteriaceae			231	0.0
1570339		Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae			298	0.0
2049		Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae			637	0.0
1129771		Fusobacteria	Fusobacteriia	Fusobacteriales	Leptotrichiaceae			702	0.0
186814		Firmicutes	Clostridia	Thermoanaerobacterales	Thermoanaerobacteraceae			2	0.0
572511		Firmicutes	Clostridia	Clostridiales	Lachnospiraceae	Blautia		241	0.0
836		Bacteroidetes	Bacteroidia	Bacteroidales	Porphyromonadaceae	Porphyromonas		397	0.0
194		Proteobacteria	Epsilonproteobacteria	Campylobacterales	Campylobacteraceae	Campylobacter		12	0.0
184869		Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Varibaculum		44	0.0
165779		Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Anaerococcus		58	0.0
1330547		Proteobacteria	Gammaproteobacteria	Enterobacterales	Enterobacteriaceae	Kosakonia		28	0.0
1378		Firmicutes	Bacilli	Bacillales		Gemella		65	0.0
29465		Firmicutes	Negativicutes	Veillonellales	Veillonellaceae	Veillonella		124	0.0
1637		Firmicutes	Bacilli	Bacillales	Listeriaceae	Listeria		55	0.0
1716		Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium		1065	0.0
590		Proteobacteria	Gammaproteobacteria	Enterobacterales	Enterobacteriaceae	Salmonella		119	0.0
203133		Actinobacteria	Actinobacteria	Propionibacteriales	Propionibacteriaceae	Propionimicrobium		437	0.0
46123		Firmicutes	Bacilli	Lactobacillales	Aerococcaceae	Abiotrophia		894	0.0
34104		Fusobacteria	Fusobacteriia	Fusobacteriales	Leptotrichiaceae	Streptobacillus		388	0.0
1301		Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus		3660	0.0
32067		Fusobacteria	Fusobacteriia	Fusobacteriales	Leptotrichiaceae	Leptotrichia		300	0.0
140458		Firmicutes	Clostridia	Thermoanaerobacterales	Thermoanaerobacteraceae	Thermacetogenium		2	0.0
162289		Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Peptoniphilus		1	0.0
157		Spirochaetes	Spirochaetia	Spirochaetales	Spirochaetaceae	Treponema		4675	0.0
1730		Firmicutes	Clostridia	Clostridiales	Eubacteriaceae	Eubacterium		907	0.0
482		Proteobacteria	Betaproteobacteria	Neisseriales	Neisseriaceae	Neisseria		82	0.0
150022		Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Finegoldia		216	0.0
561		Proteobacteria	Gammaproteobacteria	Enterobacterales	Enterobacteriaceae	Escherichia		6	0.0
745		Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Pasteurella		51	0.0
1279		Firmicutes	Bacilli	Bacillales	Staphylococcaceae	Staphylococcus		7701	0.0
838		Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella		5142	0.0
419014		Actinobacteria	Actinobacteria	Bifidobacteriales	Bifidobacteriaceae	Alloscardovia		3	0.0
848		Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Fusobacterium		2883	0.0
508215		Actinobacteria	Actinobacteria	Micrococcales	Micrococcaceae	Rothia		356	0.0
1653174		Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Actinotignum		589	0.0
816		Bacteroidetes	Bacteroidia	Bacteroidales	Bacteroidaceae	Bacteroides		781	0.0
194		Proteobacteria	Epsilonproteobacteria	Campylobacterales	Campylobacteraceae	Campylobacter	Campylobacter_concisus	3	0.0
1378		Firmicutes	Bacilli	Bacillales		Gemella	Gemella_sanguinis	1	0.0
1637		Firmicutes	Bacilli	Bacillales	Listeriaceae	Listeria	Listeria_monocytogenes	35	0.0
745		Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Pasteurella	Pasteurella_dagmatis	45	0.0
482		Proteobacteria	Betaproteobacteria	Neisseriales	Neisseriaceae	Neisseria	Neisseria_mucosa	1	0.0
838		Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella_bivia	332	0.0
1653174		Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Actinotignum	Actinotignum_urinale	467	0.0
1279		Firmicutes	Bacilli	Bacillales	Staphylococcaceae	Staphylococcus	Staphylococcus_aureus	207	0.0
572511		Firmicutes	Clostridia	Clostridiales	Lachnospiraceae	Blautia	Blautia_hansenii	199	0.0
194		Proteobacteria	Epsilonproteobacteria	Campylobacterales	Campylobacteraceae	Campylobacter	Campylobacter_curvus	1	0.0
203133		Actinobacteria	Actinobacteria	Propionibacteriales	Propionibacteriaceae	Propionimicrobium	Propionimicrobium_lymphophilum	437	0.0
29465		Firmicutes	Negativicutes	Veillonellales	Veillonellaceae	Veillonella	Veillonella_parvula	57	0.0
836		Bacteroidetes	Bacteroidia	Bacteroidales	Porphyromonadaceae	Porphyromonas	Porphyromonas_sp_HMSC065F10	54	0.0
194		Proteobacteria	Epsilonproteobacteria	Campylobacterales	Campylobacteraceae	Campylobacter	Campylobacter_sp_10_1_50	5	0.0
157		Spirochaetes	Spirochaetia	Spirochaetales	Spirochaetaceae	Treponema	Treponema_vincentii	4468	0.0
165779		Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Anaerococcus	Anaerococcus_lactolyticus	53	0.0
1301		Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus_anginosus	734	0.0
590		Proteobacteria	Gammaproteobacteria	Enterobacterales	Enterobacteriaceae	Salmonella	Salmonella_enterica	115	0.0
836		Bacteroidetes	Bacteroidia	Bacteroidales	Porphyromonadaceae	Porphyromonas	Porphyromonas_sp_HMSC077F02	314	0.0
1730		Firmicutes	Clostridia	Clostridiales	Eubacteriaceae	Eubacterium	Eubacterium_ventriosum	906	0.0
848		Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Fusobacterium	Fusobacterium_gonidiaformans	553	0.0
1279		Firmicutes	Bacilli	Bacillales	Staphylococcaceae	Staphylococcus	Staphylococcus_epidermidis	32	0.0
816		Bacteroidetes	Bacteroidia	Bacteroidales	Bacteroidaceae	Bacteroides	Bacteroides_fragilis	82	0.0
419014		Actinobacteria	Actinobacteria	Bifidobacteriales	Bifidobacteriaceae	Alloscardovia	Alloscardovia_sp_HMSC034E08	3	0.0
561		Proteobacteria	Gammaproteobacteria	Enterobacterales	Enterobacteriaceae	Escherichia	Escherichia_coli	3	0.0
32067		Fusobacteria	Fusobacteriia	Fusobacteriales	Leptotrichiaceae	Leptotrichia	Leptotrichia_goodfellowii	295	0.0
508215		Actinobacteria	Actinobacteria	Micrococcales	Micrococcaceae	Rothia	Rothia_dentocariosa	44	0.0
1653174		Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Actinotignum	Actinotignum_schaalii	110	0.0
1301		Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus_pseudopneumoniae	1	0.0
162289		Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Peptoniphilus	Peptoniphilus_duerdenii	1	0.0
1330547		Proteobacteria	Gammaproteobacteria	Enterobacterales	Enterobacteriaceae	Kosakonia	Kosakonia_oryzae	28	0.0
34104		Fusobacteria	Fusobacteriia	Fusobacteriales	Leptotrichiaceae	Streptobacillus	Streptobacillus_moniliformis	346	0.0
1716		Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium_pseudogenitalium	799	0.0
572511		Firmicutes	Clostridia	Clostridiales	Lachnospiraceae	Blautia	Blautia_sp_Marseille-P3201T	1	0.0
140458		Firmicutes	Clostridia	Thermoanaerobacterales	Thermoanaerobacteraceae	Thermacetogenium	Thermacetogenium_phaeum	2	0.0
150022		Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Finegoldia	Finegoldia_magna	216	0.0
836		Bacteroidetes	Bacteroidia	Bacteroidales	Porphyromonadaceae	Porphyromonas	Porphyromonas_uenonis	1	0.0
184869		Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Varibaculum	Varibaculum_cambriense	44	0.0
838		Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella_copri	1	0.0
1378		Firmicutes	Bacilli	Bacillales		Gemella	Gemella_haemolysans	46	0.0
838		Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella_timonensis	4269	0.0
1716		Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium_aurimucosum	23	0.0
46123		Firmicutes	Bacilli	Lactobacillales	Aerococcaceae	Abiotrophia	Abiotrophia_defectiva	823	0.0
1301		Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus_oralis	1	0.0
