NCBI-TaxID	Kingdom	Phylum	Class	Order	Family	Genus	Species	Number_of_Reads	Relative_Abundance
203691		Spirochaetes						455	0.0
1239		Firmicutes						11075	0.0
1224		Proteobacteria						8923	0.0
1760		Actinobacteria						11246	0.0
544448		Tenericutes						56	0.0
976		Bacteroidetes						4647	0.0
32066		Fusobacteria						407	0.0
31969		Tenericutes	Mollicutes					56	0.0
29547		Proteobacteria	Epsilonproteobacteria					250	0.0
91061		Firmicutes	Bacilli					7360	0.0
526524		Firmicutes	Erysipelotrichia					921	0.0
1236		Proteobacteria	Gammaproteobacteria					8583	0.0
1760		Actinobacteria	Actinobacteria					11232	0.0
186801		Firmicutes	Clostridia					1913	0.0
203692		Spirochaetes	Spirochaetia					455	0.0
909932		Firmicutes	Negativicutes					215	0.0
200643		Bacteroidetes	Bacteroidia					4646	0.0
1737404		Firmicutes	Tissierellia					336	0.0
203490		Fusobacteria	Fusobacteriia					407	0.0
2037		Actinobacteria	Actinobacteria	Actinomycetales				4145	0.0
213849		Proteobacteria	Epsilonproteobacteria	Campylobacterales				250	0.0
135625		Proteobacteria	Gammaproteobacteria	Pasteurellales				380	0.0
2085		Tenericutes	Mollicutes	Mycoplasmatales				56	0.0
186826		Firmicutes	Bacilli	Lactobacillales				5828	0.0
171549		Bacteroidetes	Bacteroidia	Bacteroidales				4646	0.0
136		Spirochaetes	Spirochaetia	Spirochaetales				455	0.0
1385		Firmicutes	Bacilli	Bacillales				1481	0.0
186802		Firmicutes	Clostridia	Clostridiales				1913	0.0
85009		Actinobacteria	Actinobacteria	Propionibacteriales				448	0.0
85007		Actinobacteria	Actinobacteria	Corynebacteriales				5128	0.0
1843489		Firmicutes	Negativicutes	Veillonellales				214	0.0
91347		Proteobacteria	Gammaproteobacteria	Enterobacterales				8029	0.0
72274		Proteobacteria	Gammaproteobacteria	Pseudomonadales				135	0.0
203491		Fusobacteria	Fusobacteriia	Fusobacteriales				407	0.0
1737405		Firmicutes	Tissierellia	Tissierellales				335	0.0
85006		Actinobacteria	Actinobacteria	Micrococcales				1416	0.0
526525		Firmicutes	Erysipelotrichia	Erysipelotrichales				921	0.0
72293		Proteobacteria	Epsilonproteobacteria	Campylobacterales	Helicobacteraceae			235	0.0
543		Proteobacteria	Gammaproteobacteria	Enterobacterales	Enterobacteriaceae			7936	0.0
90964		Firmicutes	Bacilli	Bacillales	Staphylococcaceae			1408	0.0
2049		Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae			4145	0.0
72294		Proteobacteria	Epsilonproteobacteria	Campylobacterales	Campylobacteraceae			14	0.0
2092		Tenericutes	Mollicutes	Mycoplasmatales	Mycoplasmataceae			56	0.0
1268		Actinobacteria	Actinobacteria	Micrococcales	Micrococcaceae			1414	0.0
1129771		Fusobacteria	Fusobacteriia	Fusobacteriales	Leptotrichiaceae			45	0.0
31957		Actinobacteria	Actinobacteria	Propionibacteriales	Propionibacteriaceae			448	0.0
1570339		Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae			335	0.0
1653		Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae			5127	0.0
128827		Firmicutes	Erysipelotrichia	Erysipelotrichales	Erysipelotrichaceae			921	0.0
1300		Firmicutes	Bacilli	Lactobacillales	Streptococcaceae			5781	0.0
712		Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae			380	0.0
31977		Firmicutes	Negativicutes	Veillonellales	Veillonellaceae			214	0.0
171551		Bacteroidetes	Bacteroidia	Bacteroidales	Porphyromonadaceae			311	0.0
137		Spirochaetes	Spirochaetia	Spirochaetales	Spirochaetaceae			455	0.0
541000		Firmicutes	Clostridia	Clostridiales	Ruminococcaceae			906	0.0
203492		Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae			361	0.0
171552		Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae			4293	0.0
468		Proteobacteria	Gammaproteobacteria	Pseudomonadales	Moraxellaceae			135	0.0
186803		Firmicutes	Clostridia	Clostridiales	Lachnospiraceae			883	0.0
508215		Actinobacteria	Actinobacteria	Micrococcales	Micrococcaceae	Rothia		1414	0.0
2050		Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Mobiluncus		85	0.0
43996		Firmicutes	Clostridia	Clostridiales	Lachnospiraceae	Catonella		396	0.0
203133		Actinobacteria	Actinobacteria	Propionibacteriales	Propionibacteriaceae	Propionimicrobium		447	0.0
61170		Firmicutes	Erysipelotrichia	Erysipelotrichales	Erysipelotrichaceae	Holdemania		920	0.0
184869		Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Varibaculum		10	0.0
2129		Tenericutes	Mollicutes	Mycoplasmatales	Mycoplasmataceae	Ureaplasma		56	0.0
1654		Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Actinomyces		74	0.0
34104		Fusobacteria	Fusobacteriia	Fusobacteriales	Leptotrichiaceae	Streptobacillus		35	0.0
157		Spirochaetes	Spirochaetia	Spirochaetales	Spirochaetaceae	Treponema		455	0.0
724		Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Haemophilus		199	0.0
1653174		Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Actinotignum		3929	0.0
1301		Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus		5767	0.0
745		Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Pasteurella		74	0.0
168808		Fusobacteria	Fusobacteriia	Fusobacteriales	Leptotrichiaceae	Sneathia		7	0.0
75984		Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Mannheimia		65	0.0
165779		Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Anaerococcus		318	0.0
475		Proteobacteria	Gammaproteobacteria	Pseudomonadales	Moraxellaceae	Moraxella		135	0.0
572511		Firmicutes	Clostridia	Clostridiales	Lachnospiraceae	Blautia		82	0.0
848		Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Fusobacterium		360	0.0
1716		Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium		5086	0.0
1378		Firmicutes	Bacilli	Bacillales		Gemella		63	0.0
1279		Firmicutes	Bacilli	Bacillales	Staphylococcaceae	Staphylococcus		1406	0.0
590		Proteobacteria	Gammaproteobacteria	Enterobacterales	Enterobacteriaceae	Salmonella		6876	0.0
209		Proteobacteria	Epsilonproteobacteria	Campylobacterales	Helicobacteraceae	Helicobacter		235	0.0
836		Bacteroidetes	Bacteroidia	Bacteroidales	Porphyromonadaceae	Porphyromonas		299	0.0
39948		Firmicutes	Negativicutes	Veillonellales	Veillonellaceae	Dialister		207	0.0
194		Proteobacteria	Epsilonproteobacteria	Campylobacterales	Campylobacteraceae	Campylobacter		13	0.0
838		Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella		4284	0.0
76833		Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Actinobaculum		35	0.0
216851		Firmicutes	Clostridia	Clostridiales	Ruminococcaceae	Faecalibacterium		897	0.0
1330547		Proteobacteria	Gammaproteobacteria	Enterobacterales	Enterobacteriaceae	Kosakonia		16	0.0
34104		Fusobacteria	Fusobacteriia	Fusobacteriales	Leptotrichiaceae	Streptobacillus	Streptobacillus_moniliformis	31	0.0
165779		Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Anaerococcus	Anaerococcus_senegalensis	6	0.0
508215		Actinobacteria	Actinobacteria	Micrococcales	Micrococcaceae	Rothia	Rothia_dentocariosa	98	0.0
1279		Firmicutes	Bacilli	Bacillales	Staphylococcaceae	Staphylococcus	Staphylococcus_epidermidis	13	0.0
2050		Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Mobiluncus	Mobiluncus_curtisii	80	0.0
475		Proteobacteria	Gammaproteobacteria	Pseudomonadales	Moraxellaceae	Moraxella	Moraxella_catarrhalis	41	0.0
43996		Firmicutes	Clostridia	Clostridiales	Lachnospiraceae	Catonella	Catonella_morbi	396	0.0
165779		Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Anaerococcus	Anaerococcus_prevotii	174	0.0
838		Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella_bivia	3786	0.0
848		Fusobacteria	Fusobacteriia	Fusobacteriales	Fusobacteriaceae	Fusobacterium	Fusobacterium_gonidiaformans	72	0.0
745		Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Pasteurella	Pasteurella_dagmatis	67	0.0
165779		Firmicutes	Tissierellia	Tissierellales	Peptoniphilaceae	Anaerococcus	Anaerococcus_lactolyticus	37	0.0
1716		Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium_aurimucosum	19	0.0
168808		Fusobacteria	Fusobacteriia	Fusobacteriales	Leptotrichiaceae	Sneathia	Sneathia_amnii	7	0.0
1378		Firmicutes	Bacilli	Bacillales		Gemella	Gemella_haemolysans	43	0.0
1716		Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium_pyruviciproducens	679	0.0
1330547		Proteobacteria	Gammaproteobacteria	Enterobacterales	Enterobacteriaceae	Kosakonia	Kosakonia_oryzae	16	0.0
572511		Firmicutes	Clostridia	Clostridiales	Lachnospiraceae	Blautia	Blautia_hansenii	45	0.0
838		Bacteroidetes	Bacteroidia	Bacteroidales	Prevotellaceae	Prevotella	Prevotella_disiens	111	0.0
590		Proteobacteria	Gammaproteobacteria	Enterobacterales	Enterobacteriaceae	Salmonella	Salmonella_enterica	6601	0.0
1654		Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Actinomyces	Actinomyces_turicensis	72	0.0
1279		Firmicutes	Bacilli	Bacillales	Staphylococcaceae	Staphylococcus	Staphylococcus_aureus	77	0.0
76833		Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Actinobaculum	Actinobaculum_massiliense	35	0.0
75984		Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Mannheimia	Mannheimia_haemolytica	65	0.0
216851		Firmicutes	Clostridia	Clostridiales	Ruminococcaceae	Faecalibacterium	Faecalibacterium_prausnitzii	897	0.0
1301		Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus_anginosus	564	0.0
61170		Firmicutes	Erysipelotrichia	Erysipelotrichales	Erysipelotrichaceae	Holdemania	Holdemania_filiformis	882	0.0
572511		Firmicutes	Clostridia	Clostridiales	Lachnospiraceae	Blautia	[Ruminococcus]_torques	23	0.0
209		Proteobacteria	Epsilonproteobacteria	Campylobacterales	Helicobacteraceae	Helicobacter	Helicobacter_pylori	225	0.0
1301		Firmicutes	Bacilli	Lactobacillales	Streptococcaceae	Streptococcus	Streptococcus_thermophilus	2246	0.0
1716		Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium_accolens	797	0.0
836		Bacteroidetes	Bacteroidia	Bacteroidales	Porphyromonadaceae	Porphyromonas	Porphyromonas_sp_HMSC077F02	287	0.0
1716		Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium_glucuronolyticum	30	0.0
1653174		Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Actinotignum	Actinotignum_urinale	124	0.0
724		Proteobacteria	Gammaproteobacteria	Pasteurellales	Pasteurellaceae	Haemophilus	Haemophilus_influenzae	20	0.0
157		Spirochaetes	Spirochaetia	Spirochaetales	Spirochaetaceae	Treponema	Treponema_vincentii	438	0.0
1716		Actinobacteria	Actinobacteria	Corynebacteriales	Corynebacteriaceae	Corynebacterium	Corynebacterium_pseudogenitalium	99	0.0
2129		Tenericutes	Mollicutes	Mycoplasmatales	Mycoplasmataceae	Ureaplasma	Ureaplasma_urealyticum	44	0.0
1653174		Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Actinotignum	Actinotignum_schaalii	3328	0.0
184869		Actinobacteria	Actinobacteria	Actinomycetales	Actinomycetaceae	Varibaculum	Varibaculum_cambriense	10	0.0
39948		Firmicutes	Negativicutes	Veillonellales	Veillonellaceae	Dialister	Dialister_invisus	206	0.0
203133		Actinobacteria	Actinobacteria	Propionibacteriales	Propionibacteriaceae	Propionimicrobium	Propionimicrobium_lymphophilum	446	0.0
