NCBI-TaxID	Kingdom	Phylum	Class	Order	Family	Genus	Species	Number_of_Reads	Relative_Abundance
1	<not present>	<not present>	<not present>	<not present>	<not present>	Streptococcus	<not present>	1	1
1	<not present>	<not present>	<not present>	<not present>	<not present>	Enterococcus	<not present>	1	1
1	<not present>	<not present>	<not present>	<not present>	<not present>	Peptoniphilus	<not present>	1	1
1	<not present>	<not present>	<not present>	<not present>	<not present>	Actinotignum	<not present>	1	1
1	<not present>	<not present>	<not present>	<not present>	<not present>	Sneathia	<not present>	1	1
1	<not present>	<not present>	<not present>	<not present>	<not present>	Campylobacter	<not present>	1	1
1	<not present>	<not present>	<not present>	<not present>	<not present>	Mobiluncus	<not present>	1	1
1	<not present>	<not present>	<not present>	<not present>	<not present>	Mycoplasma	<not present>	1	1
1	<not present>	<not present>	<not present>	<not present>	<not present>	Faecalibacterium	<not present>	1	1
1	<not present>	<not present>	<not present>	<not present>	<not present>	Catonella	<not present>	1	1
1	<not present>	<not present>	<not present>	<not present>	<not present>	Neisseria	<not present>	1	1
1	<not present>	<not present>	<not present>	<not present>	<not present>	Actinobaculum	<not present>	1	1
1	<not present>	<not present>	<not present>	<not present>	<not present>	Porphyromonas	<not present>	1	1
1	<not present>	<not present>	<not present>	<not present>	<not present>	Fusobacterium	<not present>	1	1
