NCBI-TaxID	Kingdom	Phylum	Class	Order	Family	Genus	Species	Number_of_Reads	Relative_Abundance
1	<not present>	<not present>	<not present>	<not present>	<not present>	Streptococcus	<not present>	1	1
1	<not present>	<not present>	<not present>	<not present>	<not present>	Gemella	<not present>	1	1
1	<not present>	<not present>	<not present>	<not present>	<not present>	Moraxella	<not present>	1	1
1	<not present>	<not present>	<not present>	<not present>	<not present>	Prevotella	<not present>	1	1
