NCBI-TaxID	Kingdom	Phylum	Class	Order	Family	Genus	Species	Number_of_Reads	Relative_Abundance
1	<not present>	<not present>	<not present>	<not present>	<not present>	Actinomyces	<not present>	1	1
1	<not present>	<not present>	<not present>	<not present>	<not present>	Campylobacter	<not present>	1	1
1	<not present>	<not present>	<not present>	<not present>	<not present>	Blautia	<not present>	1	1
1	<not present>	<not present>	<not present>	<not present>	<not present>	Salmonella	<not present>	1	1
1	<not present>	<not present>	<not present>	<not present>	<not present>	Mannheimia	<not present>	1	1
