NCBI-TaxID	Kingdom	Phylum	Class	Order	Family	Genus	Species	Number_of_Reads	Relative_Abundance
1	<not present>	<not present>	<not present>	<not present>	<not present>	Streptococcus	<not present>	1	1
1	<not present>	<not present>	<not present>	<not present>	<not present>	Enterococcus	<not present>	1	1
1	<not present>	<not present>	<not present>	<not present>	<not present>	Treponema	<not present>	1	1
1	<not present>	<not present>	<not present>	<not present>	<not present>	Peptoniphilus	<not present>	1	1
1	<not present>	<not present>	<not present>	<not present>	<not present>	Listeria	<not present>	1	1
1	<not present>	<not present>	<not present>	<not present>	<not present>	Actinotignum	<not present>	1	1
1	<not present>	<not present>	<not present>	<not present>	<not present>	Anaerococcus	<not present>	1	1
1	<not present>	<not present>	<not present>	<not present>	<not present>	Corynebacterium	<not present>	1	1
1	<not present>	<not present>	<not present>	<not present>	<not present>	Rothia	<not present>	1	1
1	<not present>	<not present>	<not present>	<not present>	<not present>	Streptobacillus	<not present>	1	1
1	<not present>	<not present>	<not present>	<not present>	<not present>	Dialister	<not present>	1	1
1	<not present>	<not present>	<not present>	<not present>	<not present>	Blautia	<not present>	1	1
