NCBI-TaxID	Kingdom	Phylum	Class	Order	Family	Genus	Species	Number_of_Reads	Relative_Abundance
1224	NA	Proteobacteria	NA	NA	NA	NA	NA	3054019	0
194	NA	Proteobacteria	Epsilonproteobacteria	Campylobacterales	Campylobacteraceae	Campylobacter	Campylobacter_ureolyticus	2968913	0
194	NA	Proteobacteria	Epsilonproteobacteria	Campylobacterales	Campylobacteraceae	Campylobacter	NA	3038547	0
213849	NA	Proteobacteria	Epsilonproteobacteria	Campylobacterales	NA	NA	NA	3048196	0
29547	NA	Proteobacteria	Epsilonproteobacteria	NA	NA	NA	NA	3048881	0
72294	NA	Proteobacteria	Epsilonproteobacteria	Campylobacterales	Campylobacteraceae	NA	NA	3045205	0
