NCBI-TaxID	Kingdom	Phylum	Class	Order	Family	Genus	Species	Number_of_Reads	Relative_Abundance
1239	NA	Firmicutes	NA	NA	NA	NA	NA	6796246	0
1730	NA	Firmicutes	Clostridia	Clostridiales	Eubacteriaceae	Eubacterium	Eubacterium_ventriosum	6323581	0
1730	NA	Firmicutes	Clostridia	Clostridiales	Eubacteriaceae	Eubacterium	NA	6338343	0
186801	NA	Firmicutes	Clostridia	NA	NA	NA	NA	6673854	0
186802	NA	Firmicutes	Clostridia	Clostridiales	NA	NA	NA	6673095	0
186806	NA	Firmicutes	Clostridia	Clostridiales	Eubacteriaceae	NA	NA	6338747	0
