NCBI-TaxID	Kingdom	Phylum	Class	Order	Family	Genus	Species	Number_of_Reads	Relative_Abundance
999999	<not present>	<not present>	<not present>	<not present>	<not present>	Staphylococcus	<not present>	1	0.0074280825
999999	<not present>	<not present>	<not present>	<not present>	<not present>	Streptococcus	<not present>	1	0.0042049435
999999	<not present>	<not present>	<not present>	<not present>	<not present>	Gemella	<not present>	1	0.0880941381
999999	<not present>	<not present>	<not present>	<not present>	<not present>	Finegoldia	<not present>	1	0.1408844009
999999	<not present>	<not present>	<not present>	<not present>	<not present>	Treponema	<not present>	1	0.004836159
999999	<not present>	<not present>	<not present>	<not present>	<not present>	Listeria	<not present>	1	0.0273228718
999999	<not present>	<not present>	<not present>	<not present>	<not present>	Actinotignum	<not present>	1	0.034811494
999999	<not present>	<not present>	<not present>	<not present>	<not present>	Anaerococcus	<not present>	1	0.2269579112
999999	<not present>	<not present>	<not present>	<not present>	<not present>	Corynebacterium	<not present>	1	0.0143099066
999999	<not present>	<not present>	<not present>	<not present>	<not present>	Eubacterium	<not present>	1	0.0009758406
999999	<not present>	<not present>	<not present>	<not present>	<not present>	Varibaculum	<not present>	1	0.0251358077
999999	<not present>	<not present>	<not present>	<not present>	<not present>	Campylobacter	<not present>	1	0.0117107845
999999	<not present>	<not present>	<not present>	<not present>	<not present>	Propionimicrobium	<not present>	1	0.013253453
999999	<not present>	<not present>	<not present>	<not present>	<not present>	Veillonella	<not present>	1	0.100013408
999999	<not present>	<not present>	<not present>	<not present>	<not present>	Leptotrichia	<not present>	1	0.0716760062
999999	<not present>	<not present>	<not present>	<not present>	<not present>	Rothia	<not present>	1	0.0145898722
999999	<not present>	<not present>	<not present>	<not present>	<not present>	Streptobacillus	<not present>	1	0.0296375358
999999	<not present>	<not present>	<not present>	<not present>	<not present>	Abiotrophia	<not present>	1	0.010957069
999999	<not present>	<not present>	<not present>	<not present>	<not present>	Neisseria	<not present>	1	0.0216472808
999999	<not present>	<not present>	<not present>	<not present>	<not present>	Blautia	<not present>	1	0.0113087038
999999	<not present>	<not present>	<not present>	<not present>	<not present>	Salmonella	<not present>	1	0.0002700256
999999	<not present>	<not present>	<not present>	<not present>	<not present>	Pasteurella	<not present>	1	0.0699084054
999999	<not present>	<not present>	<not present>	<not present>	<not present>	Bacteroides	<not present>	1	0.0140232652
999999	<not present>	<not present>	<not present>	<not present>	<not present>	Porphyromonas	<not present>	1	0.0284419013
999999	<not present>	<not present>	<not present>	<not present>	<not present>	Prevotella	<not present>	1	0.0059753977
999999	<not present>	<not present>	<not present>	<not present>	<not present>	Fusobacterium	<not present>	1	0.006140289
999999	<not present>	<not present>	<not present>	<not present>	<not present>	Enterobacteriaceae gen. [C Escherichia/Shigella]	<not present>	1	0.0153197498
